# Introduction

## A Short History of Dominions

The world of Dominions took its first insecure steps in 1997 on the road to Santiago de
Compostela. We had finished Conquest of Elysium, a simple yet addictive fantasy game with
a great deal of Nethack-ish unfairness and a multitude of monsters (a trademark of ours).
We were working on a space empire game, but decided that Master of Orion 2 had much of
what we liked in such a game, so we quit that project. Then I went to France and Spain for
the summer for a 1,000-mile walk. It took 72 days and I had a lot of thinking to do.
Several ideas came up, including a bug war with ants, wasps and other bugs armed with
cybernetics and guns. Some ideas from earlier in the spring evolved, and rudiments of
Pythium, C'tis, Man and Lareaux (a conglomerate of Ulm and Marignon) came to life.

When I returned from Santiago, we began working on the bug wars, but soon got bored and
decided to make a tactical fantasy game where you bought an army and pitted it against
your opponent's army.

Statistics, battle mechanics, and morale are from this era. The tactical engine was much
based upon board games where commanders give orders to squads. SPQR, Age of Chivalry and
Warhammer Fantasy Battle were inspirational sources. Morale loss and rout is a feature in
all of these. At first you monitored every single unit, but soon you only moved your
commanders and told them what orders to give to what squads.

WFB gave us the idea that heroes are fun, but we didn't want heroes to be as important as
they are in WFB. At that time there were no magic items, spells or monsters, apart from
the hydra.

After a while, fighting was becoming boring, and if the output is boring, you quit. At
this time we were inspired by VGA-Planets and decided that we wanted a strategic PBEM game
with tactical battles. We started to think about how to place the tactical engine in a
strategic game and still have a game that was playable by mail. Control over battles was
the solution.

The move from a purely tactical to a strategic game made the world much more important.
Some earlier ideas of an Ars Magica-like game of magical research and politics were
remade. Random content and magical sites in the provinces would increase replayability.
Mages of the Order of Hermes were replaced by competing gods. The magical and divine auras
of Ars Magica gave us the idea of a dual war of armies and dominions. Mythological and
historical paraphrases came naturally as I have a great interest in the history of
religions.

Several nations had been thought up in the process of making the tactical engine, but they
evolved and changed over time. Pythium was split into Pythium and Arcoscephale, Lareaux
into Ulm and Marignon.

Magic and research were incorporated in the game. The eight paths and several dozen spells
were there from the beginning, but research was strange and boring. The idea of the magic
schools made research an important choice, not just a matter of how rich you were. Global
enchantments were a later add-on inspired by Ars Magica and Master of Magic.

Since 1997 the game has undergone many changes, but some things are as they were in the
beginning. We still have old papers from 1997 that tells us how many resources a plate
cuirass costs, and what a mage should cost at a given skill level. Even though we
scribbled down new stats as the numbers were altered, the papers remained the same, until
work began on Dominions 3 in 2004 and we remade the armor protection mechanics. Dominions:
Priests, Prophets and Pretenders was released 2001. It got some Usenet attention and we
were glad to get some input. Bugs and imperfections were pointed out and we tried to fix
most of them. After a half year or so we decided that we wanted to make a new game instead
of making small changes to Dominions.

We started on several ideas, including a strange 3D version of Dominions. After a while we
returned to Dominions and decided to make what is now Dominions II. Our primary goal was
to remake the user interface. Much was the same, but many ideas that were difficult to
incorporate into Dominions: PPP were now possible to implement. We had as much time as we
wished, no schedule, and no expectations.

During Christmas 2001 I visited my parents and had some spare days. I accidentally made a
board game map and system inspired by Dominions, but never managed to finish it. I still
have a bunch of papers, a wooden map, and a little box filled with some hundred wood
pieces that needs painting. Johan Karlsson (the programmer and co-designer) is more of a
finisher than I am. We later scanned the map and used it as our first Dominions II map
(The Sundering).

Dominions II was released, and we started working on the first patch. The first patch
included new themes as well lots of small changes and bug fixes. The game and the
community grew and we got positive feedback and inspiration from fans all over the world.
Maps, mods and other contributions made by fans kept the community, as well as us, active.

New content was added in a number of patches. We still had many ideas regarding the world,
the game, and the future. At first, we were content with patching the game, but after a
while we decided that there were things that could not be fixed unless major changes were
made to the game engine. We decided to start on a third version of Dominions.

I had plenty of ideas regarding nations and themes. The first was Oceania, an underwater
nation similar to Pangaea. An early version of Oceania was included in one of the last
patches for Dominions II. Sauromatia, inspired by the Scythians, Amazons and Androphags of
Herodotus, and Bandar Log, a nation inspired by ancient India and Hindu myth, were two
nations I had been dreaming about. Soon, the numbers of nations increased and we decided
to divided the nations chronologically and alter the theme structure. Themes were replaced
by three ages with somewhat different characteristics. The concept of Awakening, an old
idea, was relaunched.

Then work slowed down for a while. Work, social life and other computer games ate up part
of our time. We didn't have a deadline, nor any clear direction, apart from adding fun
stuff and making the game more user-friendly. After a rather long period of random adding
of content and bug fixes, we decided that it was time to start the beta. In February 2006,
the Dominions 3 beta forum was started, and almost 7,000 posts later, Dominions 3 -- The
Awakening was finished.

That's about it, I think.

*/ Kristoffer Osterman, Sweden, Summer 2006*

## About The Creation of Dominions 4

After completing Dominions 3 we were a bit tired of making Dominions, so starting with
Dominions 4 then was out of the question. Also, Johan got a new full-time job at Sony
Ericsson then and got his programming needs fulfilled there. Many Dominions 3 patches and
a long break later we got inspiration for making a new game again, but we wanted something
different from our earlier projects. So we started with Trade & Taint.

Trade & Taint was just a preliminary name, but we never figured out a better one. It was a
real time multiplayer online game, like a MMORPG, but not massive and with no 3d
characters. The game took a lot of inspiration from Star Sonata, a great little game by
the way.

The concept was to buy a party of soldiers and donkeys and then transport goods between
villages, making money by buying cheap and selling were the demand was high. After a while
you would be rich enough to start your own colonies and create mines there if the place is
mineral-rich or maybe plant fields and sell oats. It was still an Illwinter game, so we
had magic and horrors, too. When you had a colony you could create a wizard's tower and
have your mages perform magic rituals, craft items, and enchant your surroundings. We had
global rituals too, like meteor storms that made a meteor crash down on the world every
minute or so. The meteor storms looked very apocalyptic and were devastating for everyone
but the horrors. Performing magic made the world more tainted and enough taint resulted in
horrors appearing. First came a few, then came some more, and finally there was an
apocalypse of horrors that destroyed settlements, player colonies, and eventually the
entire world.

It was, however, a bit too ambitious and it felt impossible to finish, so it got laid
aside. Instead, we decided to make something easier and that was to create a modern
Conquest of Elysium, because we have always enjoyed that little game. And now we had some
cool horrors from Trade and Taint to put into Conquest of Elysium as well.

After Conquest of Elysium 3 was finished, working on Dominions sounded like a fun idea
again, so we started to plan a Dominions 4. We had a few really major changes that we
wanted to see: one was the 3D world map from Trade and Taint. Here you would get line of
sight for armies and movement speed would be meters per day with exact distances between
cities. Also, you would have changing terrain and line-of-sight for magic rituals. Another
idea was real-time battles, with everyone moving at once and spells having different
casting times. The third idea was team play with a team consisting of one god and his
disciples.

Then we made a list of all the little changes we also wanted to make and it got very long.
So long that we thought it was enough with that list to make a new game. So we scrapped
some of the major ideas that had the potential of making Dominions 4 a worse game than its
predecessor. Thus, we decided against the 3D map and the real-time battles. We have
experienced a few games that got worse with their updates and we didn't want that with
Dominions 4. Maybe with a Dominions 5. We kept the team play idea though, because it fits
well with the current Dominions system. Also we really enjoyed the team play in the War of
the Ring board game and wanted the same feeling in Dominions. For those who haven't played
it, there are fixed teams: Sauron and his ally Saruman on one side, and all the good ones
on the other.

When development of Dominions 4 started, the GUI system from CoE3 was imported. Then the
network system, random map generation and some 3D stuff from Trade & Taint was imported
too. Sprites were imported from both games, so we got some new horrors and new item
pictures from Trade & Taint, where there are sprites for every mundane weapon and piece of
armor in the game. Some monsters like the gelatinous cube from CoE3 were also imported. In
an effort to get the sprites sorted in a more logical way as well as redrawing the ugly
ones, Kristoffer decided to rearrange all the sprites in the game. So for a long time
almost all nations had what looked like random sprites for its units, making it somewhat
difficult to play.

Our first test game took place right after we got the team play working. Many units still
looked funny and you had to tell Kristoffer that "my scout looks like an elephant with a
red cross on it," to have him prioritize that.

During development a multitude of new ideas popped up. Some were small and easy to
implement, others had more impact on the game. The Thrones of Ascension was one such later
development that we just had to add, once we came up with the idea. Some ideas were
discarded and others lie around and might be added in future patches.

Now, a bare month before release and almost 3000 posts in our beta forum, the game is
working well, random sprites are quite rare and bugs tend to be easy to fix.

We hope that you find Dominions entertaining, regardless of whether you are new to the
series or if you are a long-time player of our games.

*/ Johan & Kristoffer, August 2013*

## About the Creation of Dominions 5

After finishing Dominions 4 and making quite a few patches too we once again got a bit
tired of working on Dominions. When thinking about what kind of game we wanted to work on,
we decided it had to be something different and we began to work on a space game. It was
going to be a game where you mined and transported minerals in order to build space ships
to defeat your enemies with. It was inspired by the good old vga-planets game.

The game got random planets and some nice mineral surveys, but it never got far before we
abandoned it in favor of a new version of Conquest of Elysium. We had some good ideas for
CoE like an inferno plane that contained the demon lords and if you summoned them they
would actually be summoned from that plane. It would then be possible (just) to kill them
permanently by going down there and slaying them on their home plane. We also had ideas
for random rituals, inaccurate monster descriptions and new combat mechanics. After about
one and a half years and many additional planes, Conquest of Elysium 4 was released.

After CoE4 we started to play and develop Trade and Taint again just for the fun of it. It
is a game that we did not intend to finish, so we could play and experiment as much as we
liked.

After a while we wanted to make a game we could finish again, but we wanted it to be
something different from CoE and Dominions. We have played many roguelike games back in
the times, and recently we had played Tales of Maj'Eyal too and we had many ideas on how
to make a better roguelike. So we started to make our own roguelike game called Dungeons
of Elysium. It had the same aggressive wildlife that can be found in Elysium. It also took
advantage of the terrain drawing engine in Elysium that turned out to be really good at
drawing dungeons too.

DoE had a similar class system to TaT where you start on a random career e.g. a footpad
and then the footpad can advance to smuggler, burglar or grave robber depending on what
trainer you encounter.

We created a few stories, a fun abstract travel system, and a dungeon editor. Actually,
the dungeon editor turned out to be very useful at creating nice looking encounter maps
for our own pen and paper role playing campaigns. After canceling DoE we later made the
map editor a bit more user-friendly and released it as Illwinter's Floorplan Generator, a
tool to help pen and paper role-players.

After a few months of DoE we also started to work on our old 4x space strategy game again.
The planets and minerals were already in place, so this time we added production, space
combat and ground combat. Combat was automatic like in Dominions, but more colorful with
lasers and photon torpedoes in space.

Production was a bit different from most other games, you had to create factories for
specific spaceship models in order to produce it efficiently. So you were encouraged to
not redesign your spaceship models too frequently as you would have to build new factories
for them as well.

By now many years had passed since we released Dominions 4 and we felt inspired to do a
Dominions 5. Realtime combat was going to be the major change for the new Dominions, but
we had a quite a few other ideas too. One idea that didn't make it was The Council of
Immortals, where you got to vote for divine laws and titles and got influence from your
claimed thrones. Another idea was for mounts to have separate stats, so you could kill
either the mount or the rider. Kristoffer had ideas for a ton of new nations as usual,
some of them made it into Dominions 5 and hopefully a few more will make it in future
updates to the game.

When the development of Dominions 5 started we imported the GUI system from CoE4 that gets
rid of the fuzzy looking font and the 3D engine was updated to use the one from Trade and
Taint. After many years of incremental updates the 3D world in Trade and Taint was both
faster and better looking than the one in Dominions 4, so it would be stupid not to use
that one instead. At first we also used the particle effects on magic items that we had in
TaT and that made the items sparkle or burn with blue flames. But it didn't feel right in
Dominions and it was removed.

When writing this the 3D castles are still not finished, some units of Rus only looks like
a few red letters and many descriptions remain to be written. But the game plays well and
it feels realistic that it will be finished in a month when it is supposed to be released.

We hope you will enjoy the game!

*/ Johan & Kristoffer, October 2017*

## About the Creation of Dominions 6

After finishing Dominions 5 and patching it quite extensively we got some inspiration for
Conquest of Elysium and started creating the fifth version of that series. CoE 5 now got
two new planes, the sky and heaven, as well as much more interesting battlefields where
the terrain features had stats and could e.g. start burning if hit by a fireball. The
Cloud Lord was also added as the class that would start on the sky plane.

While working on Conquest of Elysium we collected and wrote down ideas for Dominions.
After about a year of Conquest of Elysium we felt like implementing some of our ideas for
Dominions, most notably by remaking how the mounts worked. The mounts in Dominions 5 have
always been a bit strange, sometimes they use the rider as the target and you have to kill
the rider and cannot hit the horse. Sometimes if the mount felt important you had to kill
the mount first and then maybe it transformed into a lone rider afterwards. It was not
logical, and we wanted to change this so that both rider and mount had stats and both
could be hit by attacks. And an area attack like a fireball should be able to hit both the
rider and the mount at the same time.

So we put CoE 5 on the shelf for a while and started to work on Dominions 6 instead. At
first it was only the mount system that was being changed, but pretty soon a new magic
path was added as well, the path of Glamour. With the addition of this path we could
separate the nations that are good at hurling lightning bolts from the ones that like
illusions and thus diversify the nations a bit more.

Work on Dominions 6 continued for about a year, before we decided that we wanted to finish
up CoE 5 instead. The work on CoE included even more planes, a new map system, boats and
more classes. Eventually we reached a stage where we felt it was ready enough and it was
finally released in the summer of 2021.

Somewhere in between we also continued on our game Trade & Taint. We probably mostly
played it, but some development got done as well. E.g. we fixed the invisible guard towers
that were ambushing people traveling in the forests. A limit of 50000 units of a single
type was also implemented, as the giant ants were going rampant and overwhelmed the game
occasionally.

After we had released CoE 5 and as well as a few content patches for it we returned to
Dominions 6. There was still a lot of work to be done on the reformed mount system and
several times we wondered if it was worth the amount of work it meant, but with the game
finished we are confident it was indeed worth it. There was also a lot of stuff related to
the addition of glamour magic that had to be addressed including new sites, spells and
rebalancing.

Apart from the changes to mechanics there are several new nations, and a few in the works
that will be released in some of the first content patches. One of the new nations is
Muspelheim, a nation that we have intended to make for a very long time. With some new
mechanics our vision for that nation was made possible.

Many of the improvements of CoE 5 were related to gameplay and a better UI and we probably
learned a bit in the process. Dominions 6 has more changes to QoL and UI than any previous
iteration of the game and we believe that the gaming experience in Dominions 6 is improved
compared to earlier versions.

Finally we have added a server lobby for multiplayer games. This is also a lesson learned
from the CoE5 development. Hopefully it will help people to find and start multiplier
games.

*/ Johan & Kristoffer, January 2024*

### Major Changes in Dominions 6

There are too many new changes between Dominions 5 and Dominions 6 to mention them all in
the manual. But here is a list of the most important changes to the rules and mechanics
that make up the world of Dominions. This might be useful if you are already familiar with
how the world of Dominions 5 works.

**Glamour**
: A new magic path called Glamour. Glamour deals with illusions, dreams and luck and fits
in among the sorcery paths. Blood Magic is no longer part of sorcery and is a path outside
the traditional elemental and sorcery paths.

**Mount Stats**
: Mounts now have stats of their own that are tracked separately from the rider. So in a
battle it is possible to hit rider or mount, or maybe both in the case of an area of effect
hit. If the mount is killed the rider can continue to fight on the ground. There can also
be mounts with multiple riders like elephants or the other way around, carriers with a
single rider.

**Battlefield Terrain**
: There are now bushes, rocks and other obstacles to be found on the battlefield, all with
their own stats that can be affected by e.g. area of effect attacks in the vicinity. These
terrain obstacles can easily be crushed by large monsters, but smaller ones might have to
navigate around them.

**Assassination Locations**
: Assassinations now usually take place in confined areas appropriate for the target, e.g.
a mage might be assassinated in the library and an ordinary commander might be assassinated
while visiting the local tavern. Local bystanders might be also be dragged into the
assassination if they happen to be present.

**Hidden Map**
: The map is hidden from the start and has to be explored in order to find out what kind of
provinces are available.

**Multiple Planes**
: The map can now contain multiple planes that can be discovered and conquered.

**Alterable Map Terrain**
: The terrain type of provinces on the world map can now change. This is a quite rare, but
can happen if a province is under the influence of an extreme Dominion scale for a long
time or if the province is targeted by a high level ritual that affects the terrain.

**Legendary Spells**
: Research level 9 now contains legendary spells. Legendary spells are usually very
powerful, but can only be researched one at a time. You have to choose carefully which one
to research first once you reach that level.

**Extreme Dominion Scales**
: Pretender Gods can usually only choose Dominion Scale values between -2 and 2. But some
Pretenders or Nations can add to this limit to make it possible to pick more severe scales.
Scales at values 4 and 5 are known as extreme scales and usually comes with some special
effects that are not necessarily good.

**Larger**
: The scale has increased. Dominions 6 is able to handle many more units than before, both
population and armies are now about 50% larger for more epic battles.

Of course there are also many new nations, monsters, magic items, spells, magic sites,
bless effects and random events that were not present in the world of Dominions 5.

## Authors Note

The Dominions 6 manual is based on the previous Dominions 5 manual that was written by
Bruce Geryk. It has since been updated by us at Illwinter Game Design to be suitable for
Dominions 6. We hope you will like it!

The layout of this manual was created with the help of Illwinter's PDF Typesetter, a newly
created program that might be released to the public later on. It has an easy to use
markdown-like syntax, but creates ready for printing multi-column documents with floating
pictures and tables.

*/ Johan & Kristoffer, March 2023*
