# The Basics

## Dominions Random Number (DRN)

Most Dominions game mechanisms use something called the **Dominions Random Number
(DRN)**. When a random number is called for, the number used is actually a DRN. This is
a roll of two six-sided dice (2d6) but with an additional bonus: if any individual die
roll is "6," one is subtracted, and then that die is re-rolled and added to the result.
This is referred to as an "open-ended" 2d6 roll.

> **Example:** The game calls for a DRN. Two dice are rolled and they come up 2, 6.
> Because one of the dice was a "6," one is subtracted from the total (making 7), and the
> die is rolled again. But this die is also a 6. So one is subtracted from the total (now
> up to 12) and a die is rolled again. It is a 4. The final result for this DRN is 16.

Note that if both original dice came up as 6, both would be re-rolled and added as above.
If a die keeps coming up 6, it keeps getting re-rolled and added, which can very
occasionally lead to large numbers.

Dominions has a lot of situations where something is very unlikely to happen, like a
militia soldier hitting an ethereal monster. However, in the real world of Dominions,
very few things are actually impossible. To model this fact as closely as can be, the
Dominions Random Number was created. With it, it is always possible for such an event to
occur, which would not be the case if the roll was not open-ended.

In some rare cases, there may be only one six-sided die rolled. It is still open-ended,
but in this case, the rules refer to it as a **drn**, in lower-case letters.

### Probabilities in Dominions 6

Most die rolls in Dominions 6 involve one player rolling higher than another player using
the DRN system. To give players some idea of how likely something is to happen, here is a
table that shows the difference between two values on the left, and the chance of beating
that value using two open-ended dice on the right.

| Difference | Chance |
|-----------:|-------:|
| -10 |  3% |
|  -9 |  5% |
|  -8 |  6% |
|  -7 |  8% |
|  -6 | 11% |
|  -5 | 14% |
|  -4 | 18% |
|  -3 | 24% |
|  -2 | 30% |
|  -1 | 38% |
|   0 | 46% |
|   1 | 54% |
|   2 | 62% |
|   3 | 70% |
|   4 | 76% |
|   5 | 82% |
|   6 | 86% |
|   7 | 89% |
|   8 | 92% |
|   9 | 94% |
|  10 | 95% |

What does this mean? It means that if you have a Jotun Moose Rider with attack skill 9 and
your opponent has an Abysian Infantry with defense skill 10, your chance of beating him
with two open-ended dice (and thus scoring a hit) is 38%. If the values were reversed,
your chance of success would be 54%. Why the seeming disjunction? Because the "zero-point"
is only 46%. Remember, the table shows the chance of *beating* your opponent. Thus, if you
are evenly matched, you need to roll higher than he or she does on the same type of dice,
and thus your chances of doing so are less than even. 46%, to be exact.

Sometimes the manual will state that a given effect requires a morale check (or some other
ability check) "against" some number. This is simply a way of saying that a unit's morale
(or other ability) + DRN is compared to the stated number + DRN. So if a unit has to "take
a morale check against 12," this means the unit's morale + a DRN is compared to 12 + DRN.
If the unit has a morale of 10, the chart above would indicate that the chance of this
unit passing the check is 30%.

## The Interface

### Starting a Game

Game creation and game playing in Dominions 6 are separate things. In order to start a new
game, you must create it under **Create World**. When you return to a game you have
already created after the first time you play it, you choose **Continue Old Game**.

### Creating a new game

To create a new game, click on **Create World** in the opening menu screen. You'll be
asked to choose a map, which can be a pre-made map or a randomly created one. The map will
be generated once you have made all your choices for the game. The next step is to give
the game a name. This generates a folder with this name in the "savedgames" folder so you
can find the files easily. You can access this from the Tools & Manuals menu under Other /
Open User Data Directory.

You can start playing the game immediately from the creation menu. Once a game has been
created and you have quit out of it for some reason, you can play it again by choosing
**Continue Old Game** from the same menu, and selecting the appropriate one.

### Choosing an Age

The next choice will be whether to play in the Early, Middle, or Late Ages. This
determines the nations available. In general, Early Age nations have weaker troops and
stronger mages.

### Choosing participants

Once you have selected an age, you can select the nation you and the AI player(s) will
represent. The default is "Random" which will choose from the available list of nations.
You can choose a specific nation by clicking on the word "Random" which will open a window
listing the available nations for that Age. Then click on the nation you desire. Nations
cannot be duplicated -- there can only be one of each in a given game. You can also set the
AI players to specific nations in the same way. To add another player (either AI or
human), click on "Add new player." To remove a player from the game, click on the name of
the nation (or on "Random" if you have not set a nation) and click on the word "None" at
the bottom of the list of nations.

### Disciple games

At the bottom of the Choose Participants screen is a checkbox for "Disciple Game." This is
a special type of game that will be explained below. Once you check this box, two
additional columns will appear: one for Team and one for pretender/disciple. You will not
be able to click "Ok" (the choice will be greyed out) until each team has one and only one
pretender (and any number of disciples). There is no requirement for balance among teams,
or equal numbers of disciples, or having disciples at all. You can change teams and
pretender/disciple status by clicking directly on the team number, or on the word
"pretender" or "disciple."

The disciple game is a team game which allows players to play in teams, but preserves the
true nature of the world of Dominions, which is that it is all about pretenders aspiring to
godhood. And there can only be one god in the end. So one player takes on the role of the
pretender. All other players on his team (if there are any -- there is no requirement for
all pretenders in a disciple game to have disciples) play the part of his disciples.

Disciples do not create pretenders, they create disciples. A player has 400 points (rather
than the usual 450 for pretenders) to create a disciple. Furthermore, disciples have no
dominion or scales. They only choose physical form and magic paths. They also cannot
choose whether they are awake or not from the beginning of the game. They awaken in half
the time of the pretender God, so only awake gods start with awake disciples. After all,
it is they who are heralding the entrance of the pretender god. The temples of disciple
players spread the dominion of their pretender god. The disciple unit itself does so, too,
but as a prophet (the equivalent of one temple check). Disciple units also get increases
in strength, hit points, and magic resistance when they are in their pretender god's
dominion, just like prophets. In disciple games, no one can appoint prophets, neither the
pretender player or the disciple players, since the disciples act as prophets. Prophets
can only be appointed by pretenders that have no disciples.

### Creating Pretender

After choosing which nations will participate in the game, you will be taken to the create
pretender screen for each of the human players. Here you will create the Pretender God
that will be in charge of your nation and possibly capture enough Thrones of Ascension to
acquire full godhood. Creating a pretender is an involved process that is described in the
[Pretender chapter](03-the-pretender.qmd) of the manual.

Pretenders created here can be saved by clicking `ctrl-s`. By saving it you can load it
into other games later by pressing `ctrl-l` in the pretender creation screen. In the Game
Tools menu, there is also a pretender creation tool that can be used to create and save
pretenders for future games.

### Game settings

The last issue is the game settings. These control the makeup of the world, as well as
some options for renaming commanders, showing score graphs, and various other options.

The options are straightforward and are described by tooltips that appear when mousing over
the different categories. Players can choose to make gold more or less available, change
the frequency with which magic sites will appear, adjust the strength of independents, and
many other things which will give the game a unique character. This is largely up to the
players' taste. For example, a game with a high independent strength will slow players'
expansion while they build larger armies to conquer adjacent provinces, and will prolong
the time before enemy nations come into contact. Increasing magic (either sites or
research) will hurt nations which have weak magic to begin with, because more
magic-oriented nations will be able to start using more powerful magic faster. You'll
eventually get a feel for what works for you.

#### Score graphs

Score graphs contain a lot of information, and can take over a multiplayer game as everyone
watches who has the most provinces, who has the biggest army, and thus who is seen as the
biggest threat. It makes for a very different game if players have to scout for
information, and diplomacy becomes more useful since it's not immediately obvious that you
have an army twice as big as your neighbor's. The game plays very differently in
multiplayer with score graphs on, as the prime objective becomes to not be the leader in
any of the major categories, while not falling too far behind, either. On the other hand,
in solo games, especially for newbies, the score graphs can be valuable tools for gauging
your progress and evaluating threats to your position. Use them wisely.

Units with the Spy ability give players access to score graphs, even if they are disabled.
They cannot get information on enemy players unless they are in the enemy capital, however.

#### Master password

Setting a master password allows the host to go in and set a player's position to computer
control (and thus preserve the flow of the game) if a player drops out and his pretender is
password-protected. For large multiplayer games where some attrition is likely, consider
either setting a master password, or having a third party collect all the passwords for the
game, to be used only if a player becomes unreachable. While the usefulness of the master
password is mostly the ability to give AI control to a dropped player, it does allow full
access to a player's position.

#### Limited unique artifact forging rate

This setting is on by default and limits players to forge a maximum of one unique artifact
per game turn. Unique artifacts can only be forged once you have researched level 9 in
Construction. By limiting the rate to one per turn it will also be meaningful for players
with slower research to aim for artifact construction.

#### Limited legendary spell research rate

This is on by default and makes level 9 an epic research level, where you will only get one
out of all the spells available on that level. You get to choose which spell you want to
research, and it is possible to research level 9 multiple times to get all the spells if
you want.

#### Renaming

By default it is not possible to rename commanders. This can be changed with this option.
If renaming is enabled you will be able to rename any commander except Pretender Gods,
Disciples, Prophets and famous heroes. To rename a commander, inspect his stats and then
press `r` to rename.

#### Cheat prevention

Cheat prevention will try to prevent people from cheating and send messages to all players
if anyone has been found doing something that is against the game rules. Cheat prevention
only protects against players other than the host from cheating. The host must be trusted
as he has full access to the game and can easily rewind turns without anyone noticing if he
so wishes. Make sure to password protect your Pretender God if playing in an online
multiplayer game, otherwise anyone might look at or alter your turn.

### Throne game settings

By pressing the "Thrones" tab you will be able to set up the victory conditions. Winning by
controlling enough Thrones of Ascension is the recommended and default victory condition.
This can be changed to Conquer all if you prefer a game where you have to eliminate all
other players.

#### Cataclysm

This is a way to force the game to end after a certain number of turns. The Cataclysm will
cause horrors to appear and start destroying Thrones of Ascension. (These are very powerful
horrors.) Every Throne destroyed also reduces the number of Ascension points required, so a
winner should appear shortly after the Cataclysm begins. In the unlikely event that no one
owns a Throne as the last ones are destroyed, the horrors win.

During the cataclysm the magic scale will rise in the world and the magic ether will become
corrupted. Casting rituals, forging magic items or empowering can all cause horrors to
sense the mage and attack. The more gems used, the higher the chance of a really powerful
horror appearing. The horrors that appear due to these magic activities will strike after
the activity is finished, so it is possible to sacrifice a mage in order to forge an
expensive item.

#### Throne settings

Here you can choose how many thrones of level 1-3 that will be on the map. A level 1 throne
is worth 1 ascension point and will only be marginally more well guarded than an ordinary
province. A level 3 throne is worth 3 ascension points and will be very difficult to take.

You can also set the total amount of Ascension Points required in order to become the
Pantokrator (the true god) and win the game.

### Game Tools

Dominions 6 has a number of options under this menu to create new pretenders, as well as
manage pretenders you have already created. There is also a map editor, a tool for creating
random maps with custom settings, as well as a shortcut to the directory where Dominions 6
stores your files.

## Playing a multiplayer game

The game supports many ways of playing multiplayer: hotseat play (multiple players on the
same computer), online play (either with a private server or on the official server), or
even play-by-email (PBEM). If you are the only human player in the game (all other nations
are AI) then it is a solo game and you can skip this chapter.

Because turns in Dominions 6 are resolved simultaneously, it works very well in
multiplayer. Everyone can do their turns when they want and when everyone is finished a new
turn will be generated.

### Playing a hotseat game

Starting a hotseat game is done in the same way as a single player game. Just add extra
human players when choosing the participants and you are done.

### Playing a network game

The easy way to play online is to use the official game server for Dominions 6. Choose
Network and then Enter Game Lobby from the main menu.

From the game lobby it is easy to set up a game for others to join, or to join a game
someone else has set up. It should be pretty self explanatory if you are familiar with how
to set up a solo game of Dominions 6.

> **Note:** Remember to add a password to your pretender when playing online. Without a
> password anyone will be able to peek at or alter your turns.

Setting up your own personal game server is also possible, but more complicated. The
recommended way to play multiplayer in Dominions 6 is via the game lobby. For instructions
regarding PBEM or private game servers you have to read in the old Dominions 5 manual (free
to download on www.illwinter.com).

## Playing the Game

Once you have started a game and are presented with the main game screen, you'll need to
become familiar with the interface. At first you are viewing your home province, to view a
different province you should right-click on it (this can be changed to left-click in the
preferences if desired).

- To view a different province, right click on the province.
- To select a commander, left-click on his icon and he turns white (selected).
- To give a commander order to move, you left-click the province to which you want him to
  move.

Right-clicking, in many cases, gives you further information. For example: To get
information on a unit in almost any screen, you right-click on the unit. The same applies
when you want information on magic items or spells.

### Basic Game Functions

At the top right of the map screen is a row of buttons that are used for most things. These
are divided up into five sections. The letter in parenthesis is the keyboard shortcut.

**Province buttons** (perform actions for the current province only):

- **(e) End turn** -- ends the current turn. In a single player game this initiates the
  host procedure.
- **(t) Army setup** -- assign units to commanders, change formations, and array your
  forces on the battlefield.
- **(y) Army setup at destination** -- an alternative to the regular army setup, showing
  commanders that will be present next turn instead of those currently present.
- **(u) Patrolling army setup** -- an alternative showing only patrolling commanders, most
  useful in fortified provinces.
- **(r) Recruit unit** -- opens the recruitment panel and shows the units available for
  recruitment in the selected province. Only works for provinces the player controls.
- **(b) Mercenaries** -- see which mercenaries are available for hire and bid on them.
- **(i) Read Province Chronicles** -- information about the province and its inhabitants as
  well as all past important events that have occurred there.

**Nation buttons** (not dependent on the current province):

- **(m) Read messages** -- read the beginning-of-turn messages.
- **(s) Send messages** -- send messages, items, or gold to other players.
- **(F1) Nation Overview** -- a global picture of your units and provinces. Buy province
  defense, go straight to a province, and track magic site searches.
- **(F2) Score graphs** -- a running comparison of the strengths of the various nations
  (if enabled), plus names and status of all pretenders.
- **(F3) Hall of Fame** -- commanders who have survived the most fights and killed the most
  enemies receive a Heroic Ability, which improves as long as the hero is listed.
- **(F4) Pretenders** -- a list of all pretenders in the game (unless disabled at game
  creation).

**Magic buttons:**

- **(F5) Research** -- the Research screen for spell research.
- **(F6) Global Enchantments** -- the global enchantment spells currently affecting the
  world.
- **(F7) Magic item treasury** -- the magic items stored in your treasury.
- **(F8) Magic item overview** -- all magic items in your kingdom (treasury and equipped)
  and where they are.
- **(F9) Thrones of Ascension** -- the Thrones of Ascension active in the game (if any).

**Game buttons** (change settings and end the turn):

- **(Esc) Options** -- adjusts music and video settings, and allows you to save and quit.
- **(e) End Turn** -- saves your move to a file, or uploads it to the server. You may still
  go back and adjust your move. In a solo game, hitting End Turn automatically hosts the
  current turn.

On the row underneath are buttons for all the planes. These buttons will be greyed out for
any plane that you currently have no access to. Usually the planes are these:

1. **Pantokrator's realm** -- the overland world where most of the game will take place.
2. **The realm beneath** -- the caverns underneath.
3. **The void** -- the empty space where horrors thrive. Usually you will not end up here.

You can hide all buttons and commanders by hitting the `h` key. This way only the map will
be visible. The Province buttons refer only to the province you have selected; they may do
nothing if the province you have selected is owned by the enemy.

## The Map

Maps in Dominions 6 have one characteristic feature: they are divided up into provinces.
These provinces are delineated by the greyish lines. However, the lines are really only for
your visual reference; the game engine does not use them in any way. Instead, what is
important is which province is a neighbor of which other province. You can see this by
looking at the yellow dotted lines, they go between the neighboring provinces. The yellow
lines should be seen by default, but if it is turned off, hitting the `Ctrl+8` key to
Toggle Neighbors will turn it on again.

| Shortcut | Action |
|----------|--------|
| Arrows | scroll map |
| Home | go to home province |
| Ctrl+Home | go to Pretender / Disciple |
| `g` / `#` | goto province nbr |
| End | zoom x0.5 |
| Insert | zoom to cover screen |
| Delete | zoom to fit entire map |
| Page Up / Ctrl+Up | zoom in |
| Page Down / Ctrl+Down | zoom out |
| Ctrl+f | map filter menu |
| Ctrl+1 | toggle flags/forts |
| Ctrl+2 | toggle armies |
| Ctrl+3 | toggle dominion |
| Ctrl+4 | toggle income box |
| Ctrl+5 | toggle thrones & events |
| Ctrl+6 | toggle my troops in allied provinces |
| Ctrl+7 | toggle allied troops in my provinces |
| Ctrl+8 | toggle neighbors |
| Ctrl+9 | toggle province names |
| Ctrl+0 | toggle remote rituals |

: Keyboard shortcuts to control map view

Provinces are designated by both a name and a number. The number can be used to quickly
jump to provinces with the `g` key, for goto province number. All game mechanics in
Dominions 6 are based on provinces. Movement is done from province to province. Units are
recruited on a province-by-province basis. Each province has a number of attributes that
govern its contribution to the game.

### Province attributes

When a province is selected, you can see its attributes in a box on the right side of the
screen, provided that you have some way of gaining this information (either through scouts,
dominion influence or the proximity of friendly provinces). If you don't have any way to
gather this information, all you'll get is the name and map number of the province. Most
information about a province will be unavailable unless you actually own it.

If you have dominion over a province, you will be able to see its income and scales, even
if you do not control it. Once you have scouted a province, the province name and location
is remembered and you can always see it even if you do not have friendly units in it. For
more information, see [Scouting and Scrying](#scouting-and-scrying).

#### Terrain

Terrain is shown in the top of the province info box. It is very important for determining
how valuable that province will be in terms of income, resources, supply, and magic sites.
Farmland tends to have high population (and therefore income) but low resources and few
magic sites. Highlands tend to be just the opposite.

There can be multiple terrains in the same province in which case the bonuses add up. The
River terrain indicates an abundance of freshwater in the province and applies to all lands
adjacent to the river. Terrain also allows or restricts multi-province movement (see
[Movement](05-movement.qmd)).

There is a major distinction between land and underwater provinces. Underwater provinces
cannot be entered by units without a special ability that allows it (such as amphibian,
aquatic, or water-breathing), they do not contribute resources to fortresses on land and
cannot be crossed by flying units. Units with sailing may cross water provinces, but may
not remain there at the end of a turn.

| Terrain | Population | Resources | Magic Sites |
|---------|-----------|-----------|-------------|
| Plains | -- | -- | -- |
| Mountain Ranges | -- | excellent | many |
| Forest | low | high | many |
| Highlands | low | high | -- |
| Swamp | very low | -- | many |
| Waste | extremely low | -- | abundant |
| Farm | very high | low | few |
| River | high | -- | -- |
| Sea | low | -- | -- |
| Deep Sea | very low | high | many |
| Kelp Forest | high | -- | -- |
| Gorge | low | high | abundant |
| Cave | low | -- | -- |
| Drip Cave | -- | excellent | -- |
| Crystal Cave | very low | high | abundant |
| Forest Cave | high | -- | many |

: Bonuses for different terrain types

#### Population

Population determines income, and is affected by many factors: Growth/Death scales,
patrolling, dominion, pillaging, and random events. The population in a province sets the
base income from that province: `Income base = Population / 100`. Click on the Population
line to see the growth or death rate of the province's population.

#### Income

A province contributes its income rating to the owner's treasury every turn. Income
accumulates in the treasury. The number shown is after all modifications. Income is
determined by multiple factors, including population, dominion scales, fortress
administration, and unrest.

`Modified Income = (Population / 100) * (dominion scale modifiers) * (1 + fort administration / 200)`

If the province has unrest, this number is:

`Final Income = Modified Income / (1 + (unrest * 0.02))`

If a province cannot trace an unbroken line of friendly provinces back to a friendly fort,
it does not produce income that turn. Taxation requires communication. In disciple games
income can be traced through the territories of your allies.

#### Resources

The resource value of a province, representing raw materials needed to make weapons and
armor. Resources are reduced by unrest, like income. Resources are collected by forts from
neighboring provinces. A province only produces half of its potential resources for use in
that province unless it contains a fort. The number shown is the number actually being
produced, not the potential.

Note that in the capsule screen, resources are displayed as hammers. As a province's
resources are allocated to recruitment, the hammers in the capsule screen are progressively
greyed out.

Resource availability in a province is reduced by unrest according to the formula
`Final Resources = Resources / (1 + unrest*0.01)`. Thus, an unrest level of 100 means a
province produces only one half of its normal resources. Furthermore, no units may be
recruited in a province with an unrest level of 100 or greater. Building a fort in a
province greatly increases the number of resources available there.

| Unrest | Income | Resources |
|-------:|-------:|----------:|
| 10 | 83% | 91% |
| 25 | 67% | 80% |
| 50 | 50% | 67% |
| 75 | 40% | 57% |
| 100 | 33% | 50% |
| 150 | 25% | 40% |
| 200 | 20% | 33% |

: Effect of unrest on income and resources

#### Recruitment Points

Recruitment points represent the ability of populated areas to concentrate the resources
necessary to recruit and equip forces. Recruitment points depend on the population present
in a province, as follows:

| Population | Recruitment Points |
|-----------|--------------------|
| 0 | 20 |
| 1-5,000 | pop/100 |
| 5,001-10,000 | pop/200 |
| 10,001-20,000 | pop/300 |
| 20,001-40,000 | pop/400 |
| 40,001+ | pop/500 |

Add up rows until you reach the population level in the province. *Example:* A province has
a population of 6000. It will get 20 + 5000/100 + 1000/200 recruitment points.

The recruitment bonus for forts is then applied (e.g. +50% for palisades). Order scales
also affect recruitment points by +10% per step.

#### Dominion

This represents the religious dominance being exerted into that province. Only one
pretender can have dominion in a given province. If it is positive, the dominion is yours
and is represented by a white candle. Negative dominion is someone else's dominion, and is
represented by a black candle. If you have a priest in a province with hostile dominions
you will also get to know whose dominion it is.

#### Capsule screen

The income, resources, and dominion in a province can be displayed (and toggled off) by
hitting the `Ctrl-4` key. The hammers (resources) and standards (recruitment) become
progressively greyed out as the player allocates them for production during a turn. Turning
on the capsule screen can be a good way of scanning to see if there are any provinces with
underallocated resources or production.

#### Unrest

Unrest represents turmoil in a province and reduces both income and resources there. Unrest
can be raised by random events, enemy spies, blood hunting, magic sites, certain targeted
spells, or global enchantments. Unrest can be reduced by patrolling, province defense,
order scales, magic sites or random events. Unrest will also negatively affect the chances
of capturing blood slaves, or of successfully finding stealthy units by patrolling.

Once unrest reaches 100 it will no longer be possible to recruit any units or commanders
from the province. The maximum amount of unrest is 500 or one point per 10 population, so
once the population reaches zero there can no longer be any unrest.

#### Supplies

The supply rating of a province determines how many units the province can support. If more
units occupy a province than can be supplied by the indicated supply rating, starvation
occurs. Units consume different amounts of supply based on their physical size. The supply
rating in a province is determined by multiple factors.

**Population-based supply** is calculated from the population present in a province,
modified by the Growth/Death and Heat/Cold scales. The first 15,000 population in a
province generates supplies at 1 supply point per 30 population. Additional population
generates 1 supply point per 60 population. This is modified by the Growth/Death scales
(first) and the Heat/Cold scales (second) to arrive at a Population-Based Supply number.

**Fortress-based supply** depends on the province's proximity to a fortress. If the
province in question is within four provinces of a fort, fortress-based supply is added to
the population-based supply. This depends on the fortress' Admin rating. Only the highest
fortress-based supply is used if there is more than one nearby fortress.

`Supplies from forts = (Administration * 6) / (Distance + 1)`

> **Example:** A province with 21,000 population has Growth 1 and Heat 3 dominions in it.
> It generates 500 supply points for the first 15,000 population, and 100 supply points for
> the remaining 6,000 population for a total of 600 supply. Supplies are increased by 20%
> for the Growth 1 dominion, increasing the total to 720. The Heat 3 dominion, however,
> reduces this amount by 30%, or 180 supply points, for a population-based supply of 540.
> The province is also three provinces away from a Castle (Admin 30). This generates an
> additional 30 supply points. The province has a final supply value of 540 + 30 = 570.

##### Supply Usage

The number of supplies being used by the units currently occupying a province is shown
under Supply Usage. If there are not enough supplies in a province to supply all of the
units currently occupying that province, starvation may occur.

###### Starvation

If Supply Usage exceeds Supplies, starvation will occur. When this situation occurs a
number of troops will start to starve. The supply consumption of the starving troops will
be about as large as the deficit in supplies.

Starving units will become starving the first month (-4 morale penalty) and have a 5%
chance of getting diseased. If they should be affected by starvation while they are already
starving the chance of getting diseased is increased to 50%. Diseased units will take
damage each month as usual, until they die.

Units with an appropriate survival skill have a 50% chance of being completely unaffected
by starvation and another 50% chance of not getting diseased. Starvation ends as soon as
there is no longer a lack of supplies, but diseased units will not get rid of the diseased
condition.

#### Defense

Defense indicates the level of provincial defense present in a province. Raising provincial
defense costs an amount of gold equivalent to the new level purchased. (Thus, level 2 costs
2 gold, going from level 2 to level 3 costs 3 gold, and so on.) The first level of
provincial defense is gained automatically and for free. Additional benefits are gained at
levels 10, 15 and 20.

Provincial defense costs no upkeep, and is fully restored after a battle if the owner does
not lose control of the province. Provincial defense levels can be raised by clicking on
the word Defense in the main province screen (shortcut key `d`). Provincial defense levels
cannot be voluntarily reduced. However, it takes at least 10 population to support each
point of province defense; province defense will be automatically reduced to a level which
can be supported by the population of the province.

#### Corpses

The number of unburied corpses in a province. This is important for some spells (e.g. Raven
Feast) and for raising undead. You can only see this information if you have a death mage or
an undead priest in the province. If the nation's normal priests can reanimate undead (a
special property of certain nations), they can see the number of corpses, too.

#### Dominion scales

Dominion scales are separate from dominion, although the two are related (see the
[Dominion chapter](08-dominion.qmd)). The level of dominion scales in a province is shown
by icons/text in the main province window.

Much of this information can also be seen in the Nation Overview screen `F1`, which will
also show commanders and their locations. You can set defense and give orders in this
screen, as well as use it to go directly to a province in the main map.

### National summary

Regardless of which province is selected, the national summary will be at the top of the
screen. At the top is the name of your pretender god. Below the god's name is the treasury
that lists the total amount of money your nation has. Income is the total income prior to
paying upkeep costs, which are shown in parentheses. In the upper left-hand corner is a
symbol denoting the season. If you mouse over this it will tell you the exact season and
the current turn number. Press the Treasury button to see a list of all gold you have spent
so far this turn.

All units in the game (except for most summoned units) cost upkeep each turn equal to their
gold cost divided by 15. Sacred units and slaves cost half as much upkeep (gold cost
divided by 30). Press the Income button to see a list of all income and upkeep costs.

#### Magic gem inventory

Your gem inventory's contents are displayed in the national summary, and you can go to the
gem inventory screen by clicking on any of the gem icons. The current monthly gem income is
shown in parenthesis after each gem type.

## Forts

Forts are structures which exist on the map and can be upgraded. Forts serve as collection
points for resources, supply depots for distribution to surrounding provinces, and shelter
for troops in the event of a siege. Each fortress type has different attributes.

### Fortress types

The numbers for "Build" indicate gold/months required. Because each level of fort must be
built on the previous one, the months listed are for that specific stage only. Thus, it
would take 1000 gold and five months to build a palisade, and then another 600 gold and
three months to upgrade it to a fortress. The attributes don't stack, so the admin,
recruitment, supply, and wall integrity of the previous fort are replaced by the new one.

The era of the game dictates what fort levels are available to most nations. The standard
forts are: Early Age: fortress; Middle Age: castle; Late Age: citadel. Some nations (like
Yomi) can only build primitive forts, while others (like EA Ermor) can build advanced
forts. Some nations, such as Marignon and Ulm in the middle era, have masons who are able
to construct forts one level higher than normal. The grand citadel is only available to
those nations who can construct a citadel and also have a mason.

| Name | Build Cost | Build Time | Admin | Com. Points | Rec. Points | Supply Storage | Wall Integrity |
|------|-----------:|-----------:|------:|------------:|------------:|---------------:|---------------:|
| Palisades | 1000 | 5 | 15 | +0 | +50% | 150 | 200 |
| Fortress | 600 | 3 | 30 | +1 | +75% | 750 | 500 |
| Castle | 600 | 3 | 45 | +1 | +100% | 2500 | 1000 |
| Citadel | 600 | 3 | 60 | +2 | +125% | 7500 | 1500 |
| Grand Citadel | 1000 | 5 | 70 | +2 | +150% | 10000 | 2000 |

: Fortress types

#### Admin

The admin value of a fort determines the percentage of resources from neighboring provinces
that the fortress can collect. It also propagates supply into nearby provinces. The formula
is `(Administration * 6) / (Distance + 1)`. Thus, a fortress with admin 50 contributes 150
supply to adjacent provinces. Four provinces is the maximum distance for this supply
propagation. Administration also increases the income of a province by `Admin / 2`%. Thus, a
fort with an Admin value of 30 would increase the income by 15% of any province in which it
is built.

| Distance | Supply |
|---------:|-------:|
| 0 | 400% |
| 1 | 200% |
| 2 | 133% |
| 3 | 100% |
| 4 | 80% |

: Admin supply propagation by distance

#### Defense

The defense value of a fort represents the number of points of damage that must be done to
a fort by an enemy siege before it can be attacked. Each turn a comparison is made between
the strength of the sieging and besieged forces at a fortress. The difference between these
forces determines the amount of damage done to the fortress' defense value.

#### Supply

The supply value of a fortress determines only how many units can be supplied inside that
fortress in the event of a siege. It does not affect the distribution of supply to
surrounding provinces. Each turn a fortress is under siege, its supply value is divided by
the length of the siege to determine the supply points available on that turn to the
besieged units. Thus, on the fifth turn of a siege of a fortress with a supply value of
100, the fortress provides besieged units with 20 supply.

### Castle Guards and Wall Defenders

Forts also have defense (termed Castle Guards and Wall Defenders) that will help defend the
fort when it is being stormed. The Wall Defenders will be stationed on the walls and the
Castle Guards will start behind the gate of the castle. These units will be replenished for
each fight, just like normal province defence. Castle Guards and Wall Defenders contribute
to the repair strength of the defending army (see [Sieges](06-combat.qmd)).

Wall Defenders also have the following attributes:

- never run out of ammunition.
- can be attacked from the stairs inside the walls, or by Flying or Ethereal units (or
  missiles).
- 20% increased missile range.
- some protection from missiles. The wall has the same defense as a tower shield, but it
  has a Protection value of 30. The defenders use the best of their own shield or the wall
  defense.

The number of Castle Guards and Wall Defenders depends on the fort level.

### Fortress statistics

The statistics for each fort are listed when you click on the Fortification button in the
province interface (also the `f` key). Some forts give bonuses to Commander Points and/or
Recruitment Points, as listed in the section on fortress types.

### How forts collect resources

The calculations for provincial resources can seem confusing. The most important thing to
remember is that a province's resource pool only consists of half of that province's
potential resource production as long as it has no fort. A province will only gain the
benefit of its full production when that province has a fort. Furthermore, once a province
has a fort, the fort uses its Admin value to draw resources from adjacent provinces, within
certain restrictions:

- A land fort cannot draw resources from an adjacent sea province and vice versa.
- Forts cannot draw resources from adjacent provinces that also contain forts.
- No fort can draw resources from an adjacent enemy province.

> **A worked example.** In the Early Spring of Year 5 of the Ascension Wars, Arcoscephale
> was building a fort in the province of Gaieta. Before the fort was constructed, Gaieta
> had 31 resources available for use itself, and was adjacent to six other provinces. After
> the fort (a Palisades) was constructed, Gaieta produced its full potential of 61
> resources rather than half. The Palisades' Admin value of 15 then drew 15% of the *total
> potential* resources of each adjacent province. Thus Yrik Balkor, with 92 potential
> resources, contributed 15% of 92 = 13.8. Summing all six neighbors: 62 + (54 + 32 + 80 +
> 76 + 98 + 92) * 0.15 = 125 resources at Gaieta.
>
> Later, a second Palisades was built in Yrik Balkor. Gaieta's resources dropped, because
> forts cannot draw resources from adjacent provinces that also contain forts: Gaieta lost
> the 13 it previously drew from Yrik Balkor (125 - 13 = 112). Yrik Balkor in turn drew
> from its other neighbors for a new total of 144.
>
> A fort across a river can still collect a neighbor's resources: river traffic on small
> craft is sufficient to allow resources to flow to the fort.

## Temples

Temples are the second of the three buildings you can construct in Dominions 6. Temples
help you spread your dominion, either by directly inducing dominion spread (exception:
Mictlan, Early and Late Eras) or by providing a location for blood sacrifices (only
available to certain nations). Temples also give priests a bonus when preaching.

A temple can only be built in a friendly province. If an enemy takes control of a province
with another nation's temple in it, the temple is immediately razed. Only one temple can
exist in a province at a time. Temples cost 600 gold to build, although there are
exceptions. Man and Marverni only pay half this cost. Pangaea pays half in a forest
province, while late age Gath pays double everywhere.

Clicking on the Temple button on the lower right of the screen tells you how much dominion
you spread each turn and how likely it is to be successful. Each temple can spread
dominion, as can the pretender, prophet, and nation's home province. All of this is
explained in detail in the [Dominion chapter](08-dominion.qmd).

## Laboratories

Laboratories (or labs) are the last building type available. Labs serve as magic gem
collection points and centers of research. They allow mages in that province to perform the
Research order, enable transfer of gems from the national inventory, and allow the casting
of ritual spells. Ritual spells can only be cast in a province with a laboratory.

Labs cost 600 gold to build, and some nations are able to build cheaper labs, such as
Arcoscephale, as well as Pangaea who pay half in forest provinces.

## Magic Sites

Magic sites are not buildings per se (although there are some sites which are buildings,
such as the Firbolg Fortress and Jervellan Wall) but rather locations within a province
that possess some special attribute, like magic gem production, unique unit recruitment, or
other benefits. A province may have multiple magic sites, not all of which may be visible
at once. Magic sites are more likely to be found in certain terrains like forests, wastes
and deep seas and less likely in plains and farmlands.

Magic sites do not necessarily appear when you capture a province. Instead, the sites must
be discovered by searching. There are four levels of difficulty. A mage must have skill in
the magic path of the site equal to the difficulty level of the site in order to find it
when using the Search for Magic Sites order. Thus, a level 3 Nature mage will find any
difficulty 1, 2 or 3 sites in a province, but will not find a difficulty 4 site. When
searching, level 4 in a path is the highest level ever required. There are spells which
will automatically reveal all sites of a given path in a province (for example, Haruspex
reveals all Nature magic sites), or even all magic sites, period (Acashic Knowledge).

Some sites (like the Void Gate) allow certain types of units to enter them for certain
benefits. Sites which permit the recruitment of national units (such as the Forest of
Avalon) only grant this ability to that nation. Enemy players who capture such a site will
still collect the magic gems produced by it (if any) but will not be able to recruit the
special units.

There is no guarantee that a site will be usable to a player when found. A Cave may allow a
Blood mage to recruit demons, but if the player has no Blood mages, he will not be able to
use it. A magic site may have some additional requirement before it becomes useful. For
example, the Library allows the recruitment of sages, but not until you build a laboratory.

Not all magic sites have beneficial effects. Some are sources of chaos, death, or other
negative powers. These may cause unrest or other ill effects, and will happen whether or
not the magic site causing the trouble has been discovered.

## Province Defense

Province defense (PD) is a way of protecting a province without actually stationing an army
there. Defense is purchased at a cost of whatever the new defense level will be. You will
get the first level of province defence for free, but the rest has to be purchased by
spending gold equal to the level you are purchasing. So to buy the second level costs 2
gold, while the tenth costs 10 (and to get to 10, you have to buy the intervening levels as
well, so ultimately a PD of 10 costs 2+3+4+5+6+7+8+9+10 = 54).

At defense level 1, a nation gets a commander and some troops. Each level of defense
thereafter gives you more troops. The maximum level of province defense is 100. At level 20
you get additional types of commanders and troops. Every 10 points of province defense
reduce unrest by 1 point in that province per turn.

Starting at level 15, province defense will have a chance of detecting stealthy units in
that province. Each point of province defense above 15 gains one point of patrolling
strength, so that a PD level of 25 has a patrol strength of 11. This is about the same as
an equivalent number of patrolling infantry units.

A province can only support provincial defense if it has sufficient population. For every
point of province defense, there must be 10 points of population. This is the only way in
which province defense can be reduced, other than having the province be captured (which
wipes out all existing province defense), or relinquished in disciple games (which reduces
provincial defense by 25%).

Certain undead nations (e.g. Ermor - Ashen Empire) can have province defence without having
any population to support it. In provinces without a fort they will have 1 point of PD
(usually only a single undead commander); in provinces with a fort they can have up to 100
PD (consisting of undead soldiers).

## Unrest

Unrest represents people being unhappy with the ruler of the province. This can be the
result of many different unhappiness-generating events: a difference between the nation
which controls the province and the one that exerts dominion over it will do it, since the
people worship one god but are ruled by another. Blood hunting will definitely do it. Enemy
spies and bards can do it because that is their job. Random events such as ill omens can
cause unrest to increase.

Unrest reduces the amount of income and resources a province generates. A province with
unrest of 100 or greater will not permit the recruitment of new units. Thus, you can shut
down an opponent's production by destabilizing his or her provinces.

## Mercenaries

Mercenaries are units who are willing to fight for gold. They sell their services to the
highest bidder. They are hired for a period of three months (turns). Clicking on the
Mercenaries button will display the mercenaries available for hire, as well as currently
hired mercenaries, their employer and the time of service remaining. When a mercenary
band's contract runs out, it will again become available for hire, except on that turn
only, the previous employer's bid counts double. It is only good for that turn, and if the
mercenaries are hired by someone else, the bonus is lost.

Some nations get a discount on the price for certain mercenary bands and some nations (e.g.
Ermor - Ashen Empire) must pay more for most bands.

## Scouting and Scrying

Players will not necessarily have any information about a province besides what is depicted
on the actual map. There are many ways to gather information about provinces, and these
methods differ in what information is learned.

**Scout in province**
: Reveals owner, military info, fort constructions, and the province history. Reveals
temperature of current and neighboring provinces.

**Priest in province**
: As scout + dominion strength and dominion owner.

**Spy in province**
: As scout + income, supplies, magic sites, unrest, province defense level and more
accurate military info than an ordinary scout.

**Dominion in province**
: Reveals owner, income, temperature. Reveals dominion strength of neighboring provinces.

**Scrying a province**
: Reveals owner, very accurate military info, income, supplies, magic sites, province
defense level, history, temperature, dominion strength, dominion owner, fort constructions,
unrest.

**Owning a province**
: Reveals everything about the province. Reveals location and name for provinces 1-3 steps
away. Early era only reveals names of neighboring provinces, middle era reveals name of
provinces two steps away, late era reveals the names of provinces up to three steps away.
Reveals owner, unreliable military info and temperature for neighboring provinces.

## AI Opponents

When you start a new game you get to choose how many and what level of AI controlled
opponents you want. The AI players play using the same rules as human players, except for
any possible resource bonuses depending on the level that has been selected for them. This
bonus applies to money, resources, recruitment points and magic. Note that there is no
bonus to commander recruitment rate or to holy points.

| AI Name | Bonus |
|---------|------:|
| Easy AI | -30% |
| Normal AI | 0 |
| Difficult AI | +30% |
| Mighty AI | +60% |
| Master AI | +100% |
| Impossible AI | +150% |

: AI income bonus by difficulty

Thus killing an AI army will really set them back the amount of gold it cost to create it.
Although they might get the gold back quicker than a human player if they are above Normal
difficulty level. The AI players also get an information bonus and know which countries are
owned by which players without needing scouts everywhere. This is seen as a fair shortcut
as experienced human players are very good at guessing this without the need of that many
scouts.
