# The Pretender

Dominions 6 is about the struggle between pretenders to ascend to godhood. Thus, the
pretender is the embodiment of the spirit of the nation. There are many ways to aspire to
godhood, and you have a lot of leeway to shape exactly what kind of pretender will lead
your nation. The pretender will determine how much dominion you can have in a province, how
fast your dominion spreads, what type of scales rule the land, and what bless effects your
sacred units will have. Pretenders also have the ability to research and cast spells, and
even forge magic items and fight in battle. Pretenders are the most important single aspect
of any Dominions game.

The important points to remember about pretenders are:

- A pretender is a commander unit, and moves on the strategic map and battlefield.
- The magic paths chosen for the Pretender affect which spells he will be able to use.
- Magic paths chosen also determine what Bless effects, if any, you can choose for your
  nation's Sacred units.
- The pretender's magic paths also affect what divine spells the priests of the nation can
  cast.
- The dominion scales you choose will determine what effects will be felt in provinces
  under your dominion.
- The dominion strength you choose will determine how easily your dominion spreads.
- When a pretender is killed, he or she can be brought back by priests of his nation using
  the Call God command. This may take some time. He or she will also lose some magic skill
  or a point of dominion.

## Creating a Pretender

Besides choosing a nation, creating a pretender is the most significant decision you'll
make in Dominions 6. Each nation starts out with 450 points to create a pretender god.
These points are spent on the three categories below: physical form, magic, and dominion. A
fourth category, The Awakening, is a way in which you can trade the later appearance of your
pretender for more build points at the outset.

### Physical form

A pretender must have a physical form, like a titan or giant squid, which you choose based
on the ones available to the nation you have selected. Some nations have more choices, and
some relatively fewer. Not all pretenders are available to all nations, because those
pretenders did not exist for that nation historically.

Each pretender has a different set of attributes, which can be examined by right-clicking on
the pretender in the selection screen. They all have various attributes just like regular
units, while some have special attributes that merit further explanation. These are all
attributes inherent to the physical form in question -- they cannot be conferred or
purchased separately.

Many pretenders have an inherent point cost as part of their physical form. For example,
the Phoenix, a pretender that looks like a giant heron, costs 110 points. If you choose
that one, you will have 340 points left to spend on dominion and scales.

#### Immortal Pretenders

Some pretenders (Vampire Queen, various manner of Liches, the Phoenix, and others) are
immortal. There are two kinds of immortality in Dominions 6: immortality and dominion
immortality.

**Dominion immortality** (e.g. the Phoenix) means that if a pretender is killed while in a
province with friendly dominion, it will simply re-appear in their nation's home province.
If they die in a province that does not contain friendly dominion, they are subject to Call
God just like non-immortal pretenders.

**Immortality** (e.g. the Master Lich) means that a pretender is fully immortal and can even
die outside its dominion and still re-form.

Reforming a pretender's body (whether immortal or dominion immortal) takes some time,
usually about three months, but is dependent on monster type. If the pretender is soul
slain, it will not reform and must be called back by priests just like any other dead
pretender god. Reforming the body usually gets rid of most afflictions. Immortals do not
heal afflictions more than other units otherwise. An immortal unit that dies on a remote
plane (e.g. the Void or Inferno) will not be able to utilize its immortality.

#### Immobile Pretenders

Some pretenders (Monolith, Fountain of Blood, and others) cannot move. This means they have
no inherent movement ability. But usually they can still be transported by teleportation
rituals. Some immobile pretenders (Monument, Geyser) are just too large and cannot be moved
even by teleportation. Note that some teleportation-like rituals (e.g. Wind Ride) isn't
true teleportation and requires the caster to be mobile.

Designing a good immobile pretender can be a challenge, but they have their advantages. Most
immobile pretenders have a low physical form cost.

#### Dragon Pretenders

When players select a dragon for their pretender, a wizard shows up. This is not a bug.
Research has shown again and again that dragon pretenders don't change into dragon form
until they are wounded. The pretender will be displayed as a wizard until he changes shape
either by using the change shape order or by being wounded in combat. Prior to that, he
remains in wizard form because it was easier to cast spells with hands instead of dragon
claws.

#### Trinities

Some pretenders are Trinities, one being split into three entities. The three entities share
part of their magic abilities, but lose some of their powers when not together. If two
entities in a trinity are present, they lose some magic power while a lone entity will have
severely reduced magic abilities. Different Trinities have slightly different effects on
being apart. The separate entities in a trinity have reduced research abilities, but all of
them can research at the same time. If one entity in the trinity dies it can be called back
in half the normal time (see [Call God](#call-god)).

### Magic

Some pretenders begin with skills in magical paths, others don't. This is listed in the
character screen for that physical form. For example, the Great Mother begins with Nature 2
and Earth 1. Regardless of starting abilities, magic skills can be purchased in the Magic
screen. Note that if the first skill chosen is in a new path with no magic skill yet
selected, the cost is the pretender's "New Path Cost."

| Skill | Cost |
|------:|-----:|
| 1st | 8 |
| 2nd | 16 |
| 3rd | 24 |
| 4th | 32 |
| 5th | 40 |
| 6th | 48 |
| 7th | 56 |
| 8th | 64 |
| 9th | 72 |
| 10th | 80 |

: Cost for skill point in a path

These costs are cumulative, so that increasing a magical path from 1 to 4 costs 72 points.
Note that this refers to the number of skills added *by you* in that path, not the actual
total skill. In other words, since the Great Mother begins with Nature 2, bumping her up to
Nature 3 only costs 8 points because that's the first skill increase by you in that path.
Thus, starting with a pretender who already has skills in paths you want can be a
significant cost savings.

> **Example:** The Carrion Dragon begins with Death 1 and Nature 1. You decide you want to
> increase his skill to Death 4, Nature 4, and Fire 2. That means three skills in Death (48),
> three skills in Nature (a further 48, for 96 so far), and 2 skills in Fire. However,
> because the Carrion Dragon does not start with any Fire, selecting Fire is a new path
> purchase and thus the first skill in Fire costs 80 points. To get him to Fire 2 costs
> another 16 points. The total cost of magic for this pretender is thus 192 points. Magic
> can be very expensive.

### Divine Magic

A pretender's magic paths also determine what divine spells that nation's priests can cast.
For more information on divine magic, see the [Magic chapter](07-magic.qmd).

### Bless Effects

Each nation has a number of Sacred units, most of which can only be recruited in the
nation's home province. Sacred units are specific to that nation: if another nation captures
that province and magic site, it cannot recruit those units.

The main advantage to sacred units is that they can be Blessed. Blessing is a level 1 holy
spell, and thus can be cast by any priest. It is cast only on the battlefield. A blessed
unit gains three advantages:

- +1 morale
- All the bless effects conferred by his nation's pretender, chosen upon creation
- All the bless effects conferred by any Thrones of Ascension claimed by the nation or
  disciple nations

Bless points to buy bless effects with become available when a pretender has a skill of 2 or
more in any magic path. In general, every skill level above one in a path equals one bless
point. (Thus, an Air 2, Death 4, Nature 6 pretender receives 1 + 3 + 5 bless points for
allocation.) Some nations or pretenders may receive bless bonuses which translate into
additional bless points. (For example, Marignon, Conquerors of the Sea receives 3 extra
bless points.)

Bless effects cost bless points equal to the magic skill requirements for that effect. E.g.
an effect that requires Astral 3 & Fire 1 would cost 4 bless points to buy. Sometimes a
bless effect also has a scale requirement, but this does not affect the cost. Some bless
effects are always active (e.g. unaging and larger). They are called passive blesses.

::: callout-note
In the tables below, effects marked with an asterisk (`*`) are **passive blesses**. The
manual additionally renders some effects in bold to mark them as "incarnate only" (they
apply only if the pretender is awake as well as alive); that bold styling is not preserved
in this transcription.
:::

#### Fire Bless Effects

| Requirement | Effect |
|-------------|--------|
| Fire 1 | Superior Morale (+1 Mor) |
| Fire 1 & Death 1 | Wasteland Survival * |
| Fire 2 | Attack Skill (+1 Att) |
| Fire 2 | Fire Resistance |
| Fire 4 | Inspirational Presence * |
| Fire 4 | Righteous Wrath |
| Fire 5 | Death Explosion |
| Fire 5 | Heat Aura |
| Fire 6 | Fire Shield |
| Fire 7 | Flaming Weapons |
| Fire 8 & Astral 4 | Unbearable Splendour |

#### Air Bless Effects

| Requirement | Effect |
|-------------|--------|
| Air 1 | Precision (+1 Prec) |
| Air 2 | Shock Resistance |
| Air 2 | Farshot |
| Air 3 | Awareness |
| Air 4 | Swiftness |
| Air 4 | Storm Flight |
| Air 5 | Wind Walker * |
| Air 5 & Earth 1 | Weightlessness |
| Air 6 | Air Shield |
| Air 7 | Thunder Weapons |
| Air 8 | Charged Bodies |
| Air 9 | Flight |

#### Water Bless Effects

| Requirement | Effect |
|-------------|--------|
| Water 1 & Cold Scale 1 | Winter's Gift * |
| Water 1 & Nature 1 | Swamp Survival * |
| Water 2 | Cold Resistance |
| Water 2 | Swimming * |
| Water 2 | Defense Skill (+1 Def) |
| Water 5 | Chill Aura |
| Water 5 | Slow Weapons |
| Water 6 & Fire 2 | Vitriol Weapons |
| Water 6 | Water Breathing * |
| Water 7 & Cold Scale 1 | Frost Mist Weapons |
| Water 9 & Magic Scale 1 | Quickness |

#### Earth Bless Effects

| Requirement | Effect |
|-------------|--------|
| Earth 1 | Mountain Survival * |
| Earth 2 | Reinvigoration (+1 Reinv) |
| Earth 2 | Strength of the Earth (+1 Str) |
| Earth 4 | Unbreakable |
| Earth 4 & Nature 3 | Larger * |
| Earth 5 | Reconstruction |
| Earth 5 | Resilience of the Earth |
| Earth 6 | Hard Skin |
| Earth 7 | Fortitude |

#### Astral Bless Effects

| Requirement | Effect |
|-------------|--------|
| Astral 1 | Arcane Command * |
| Astral 2 | Magic Resistance (+1 MR) |
| Astral 3 & Death 1 | Spirit Sight |
| Astral 3 & Fire 1 | Solar Weapons |
| Astral 4 | Far Caster |
| Astral 4 | Arcane Finesse |
| Astral 5 | Magic Weapons |
| Astral 6 | Twist Fate |
| Astral 7 & Misfortune Scale 1 | Fateweaving |
| Astral 8 & Magic Scale 2 | Etherealness |

#### Death Bless Effects

| Requirement | Effect |
|-------------|--------|
| Death 1 | Undying |
| Death 1 | Undead Command * |
| Death 2 & Death Scale 2 | Half Dead |
| Death 3 | Mending Bones * |
| Death 4 | Withering Weapons |
| Death 5 | Stygian Flesh |
| Death 6 | Reforming Flesh |
| Death 7 | Reanimators |
| Death 8 | Death Weapons |
| Death 8 | Fear |

#### Nature Bless Effects

| Requirement | Effect |
|-------------|--------|
| Nature 1 | Resilient (+1 HP) |
| Nature 1 | Low Light Vision |
| Nature 2 | Poison Resistance |
| Nature 2 | Forest Survival * |
| Nature 3 & Magic Scale 1 | Unaging * |
| Nature 4 & Death Scale 1 | Poison Weapons |
| Nature 5 | Recuperation * |
| Nature 5 | Berserker |
| Nature 6 | Barkskin |
| Nature 7 | Regeneration |

#### Glamour Bless Effects

| Requirement | Effect |
|-------------|--------|
| Glamour 1 | Undreaming * |
| Glamour 1 | Heroism (+50% XP) * |
| Glamour 2 | Quiet Stride * |
| Glamour 3 | True Sight * |
| Glamour 3 | Blur |
| Glamour 6 | Obfuscate * |
| Glamour 6 & Fire 2 | Awe |
| Glamour 7 | Displacement |
| Glamour 7 | Dread |
| Glamour 8 & Luck Scale 2 | Luck |

#### Blood Bless Effects

| Requirement | Effect |
|-------------|--------|
| Blood 1 | Strong Vitae (+1 HP) |
| Blood 2 | Strength of the Flesh (+1 Str) |
| Blood 3 | Strong Blood |
| Blood 4 | Enchanted Blood |
| Blood 4 | Blood Surge |
| Blood 5 | Blood Bond |
| Blood 6 | Unholy Weapons |
| Blood 7 | Blood Vengeance |
| Blood 8 & Death 4 | Vampiric Weapons |

When you are constructing your pretender, the Magic screen will list all of the bless
effects to which your selections have entitled you. The +1 morale effect is not listed
because it is common to all pretenders. Pretenders also gain Indirect Magic bonuses (see the
[Magic chapter](07-magic.qmd)). Pretenders and Disciples are Sacred units and are
automatically blessed when they are in their dominion. However, they cannot be blessed
outside their dominion.

> **Example:** Your pretender is Neter of the Sun, which starts with Fire 2 and Astral 1.
> You decide to boost the magic paths to Fire 4 and Astral 4. You are playing Machaka, so you
> get no further bonuses and thus you have six bless points to spend. You will be facing
> Ermor, so you choose Solar Weapons, which costs four, leaving you with two bless points.
> You spend these on Magic Resistance. Your blessed units gain both effects, plus +1 morale.

## Dominion

Two separate things fall under the category of dominion: maximum dominion and dominion
scales. For more information about dominion and its spread, see the
[Dominion chapter](08-dominion.qmd).

| Candle | Cost |
|-------:|-----:|
| 1st | 7 |
| 2nd | 14 |
| 3rd | 21 |
| 4th | 28 |
| 5th | 35 |
| 6th | 42 |
| 7th | 49 |
| 8th | 56 |
| 9th | 63 |

: Cost for Dominion Candles

The cost to add dominion strength is calculated for each additional candle chosen, above
the pretender's base dominion strength. Thus, a pretender who starts with dominion 3 would
use 7 design points to increase to dominion 4, and 14 more to go to dominion 5. Every
pretender starts with at least Dominion 1, and the maximum is 10, so you can only ever
choose 9 new candles.

### Scales

Dominion scales are the representation of the effect that belief in one's pretender god has
not only on the populace but on the very fabric of a province. When creating a pretender,
you choose the way in which your religious belief changes the cosmic forces in provinces
where your dominion holds sway.

Each scale has a favorable side and an unfavorable side. For example, Growth is the
favorable side of the Growth/Death scale. For each tip of the scale, bonuses or penalties
accrue to the province under the sway of that dominion. You can gain extra points for
pretender creation by choosing unfavorable scales.

- Each left-click of a scale costs 40 points.
- Each right-click of a scale gains you 40 points.

*Exception:* Each click of the Heat/Cold scale (either way) away from a race's preferred
scale gains you 40 points per click, but only for the first 3 clicks.

| Scale | Effect |
|-------|--------|
| Order | Increases income by 3%, Resources +2%, Recruitment +10%, Unrest reduction +1, 2% fewer random events |
| Turmoil | Decreases income by 3%, Resources -2%, Recruitment -10%, Unrest reduction -1, 2% more random events |
| Productivity | Increases income by 3% and resources by 15% |
| Sloth | Decreases income by 3% and resources by 15% |
| Heat/Cold | Each step of heat/cold level away from a race's ideal level decreases tax revenues by 5% and decreases supplies by 10% |
| Growth | Increases population growth by 0.2% per month, Increases supplies by 10%, Increases income by 1% |
| Death | Decreases population growth by 0.2% per month, Decreases supplies by 10%, Decreases income by 1% |
| Fortune | 5% more random events, Chance of a random event being good increased by 10% |
| Misfortune | 5% more random events, Chance of a random event being good decreased by 10% |
| Magic | Makes spells harder to resist (-0.5 MR per scale rounded down, to all units in a province), All spellcasting generates 10% less fatigue per scale, Gives all friendly mages +1 research points per scale, +50 points of starting research per scale |
| Drain | Makes spells easier to resist (+0.5 MR per scale rounded down, to all units in a province), All spellcasting generates 10% more fatigue per scale, Gives all mages -1 research points per scale, -50 points of starting research per scale |

: Effects of dominion scales (per click)

Scales range from -5 to +5, but usually they can be tipped a maximum of only two to either
side. Certain pretenders are attuned to one or two scales and can tip these scales one step
further. E.g. the Master Lich is attuned to the death scale and can raise the death scale to
3; in turn the opposite scale (growth) can only be raised to a maximum of 1. Some nations
are also attuned to certain scales. Pretender and Nation scale attunements can cancel out
each other, but they cannot stack and raise the limit above 1.

The bonus/penalty listed in the table is per click. So clicking twice in the direction of
Order gives you Order 2, and increases your income by a total of 4% while decreasing random
events by 4%. Note that extreme scale values of 4 or more are not recommended as they
usually bring certain unwanted side effects (see the [Dominion chapter](08-dominion.qmd)).

> **Example:** The Carrion Dragon begins with dominion 2. Because the dragon costs 160
> points for his physical form, and you spent 192 points on magic, that leaves you with 98
> points for dominion and scales. Increasing dominion to 5 costs 42 points, leaving you with
> 56 points for scales. Because changing your scales costs 40 points for each click, you can
> only change one scale, by one click. You can gain more points through The Awakening, or
> reassign some magic/dominion points to free up enough for scales.

Some nations prefer certain heat or cold settings. They suffer penalties when outside their
preferred environment. They only get extra points for tipping the Heat/Cold scale *away*
from their preferred scale setting.

The scales in a province under your dominion will likely not initially correspond exactly to
the scales you've chosen, because dominion scales in a province change more slowly than the
level of dominion. It may take several turns of strong dominion over a province to tip the
scales to your chosen settings. If you have low dominion over a province, your scales will
likely never ramp up to full value.

### Pretender hit points

The hit points of pretenders (and prophets) are affected by the current dominion in their
province. Pretenders and prophets in friendly dominion have increased hit points, while in
enemy dominion their hit points are reduced. The greater the dominion, the greater the
effect. They also get increased strength and magic resistance.

For each level of friendly dominion in a province a prophet and/or pretender gains:

- +1 strength,
- +1/2 magic resistance point,
- +10% hit points.

For every level of enemy dominion in a province, a prophet and/or pretender loses:

- -1 strength,
- -1/2 magic resistance point,
- -10% hit points. Hit points cannot be reduced below 10% of the total.

## The Awakening

This determines the time needed to pass before the pretender is actually summoned to this
world. If you start the game with your pretender, your initial points for pretender
construction are 450 (minus the cost of the physical form of your god). To have your
pretender appear one year (10-13 turns) into the game (**Dormant**) gives you a 150-point
bonus. If you wait three years (28-42 turns) you get an extra 350 points (**Imprisoned**).
Note that while one turn is a month, the time to the Awakening is not precise, and you may
wait a little longer than (or not as long as) other nations in the same game.

Once you have assigned a Physical Form, Magic skills, Dominion strength and Scales, and
Awakening to your pretender, you can give your pretender a name. If you leave the name blank
the game will choose an appropriate name. Disciples will awaken in about half the time of
their pretender.

## Pretender death

A pretender loses either one skill level in one path of magic or one point of dominion
strength for each death suffered (unlike the global "one loss in each path" of some of the
previous Dominions games). This does not affect bless effects, which remain what they were
at the beginning of the game. The chance of losing magic is 50% + 10% per level of Nature
magic that the pretender had when he died. If the pretender doesn't lose any magic or has no
magic skills, it will always lose one point of dominion strength instead.

The magic skill most likely to be lost will be Nature, and the least likely to be lost is
Death. In fact, there is even a small chance of *gaining* knowledge in Death magic when
dying. There is an even smaller chance of gaining skill in Astral or Blood magic after death
as well. No pretender can go below a dominion strength of 1, no matter how many times it
dies.

### Death of Immortal Pretenders

Dominion immortal pretenders who die in a friendly dominion re-appear in their home after
the reformation period, and do not suffer the magic skill or dominion strength loss. A
dominion immortal pretender who dies outside a friendly dominion is subject to all the above
rules. An immortal pretender does not lose any dominion or magic paths on death no matter
where it dies. A pretender that gets soul slain will not be able to use its immortality
ability, however.

## Call God

If a pretender dies, he or she can be brought back by his nation's priests. Each priest
level assigned to the Call God order in a turn generates 1 point. Once a nation has
accumulated around 50 points, the pretender returns to his or her home province. The total
is not exactly 50 in order to add some uncertainty to the exact reappearance. In a disciple
game the points required to call the dead god are increased by 50%.

> **Example:** The pretender of Vanarus has died. Because he had Nature 3 when he died, he
> has an 80% chance of losing one skill level in one magic path (not necessarily Nature) and
> if he does not, he will lose one point of dominion strength. On the following turn, Vanarus
> assigns three level 1 priests and a level 2 priest to Call God. If no other priests are
> assigned to this, it will take about ten turns for the pretender of Vanarus to return.
