# Units

The world of Dominions 6 is populated by all manner of creatures. These range from weak,
lightly armed militia to giant monsters of unspeakable horror and magnitude. In between
there are bards, mages, bandits, dragons, and many others.

In the game, units can be summoned by spells, recruited from the countryside, or may appear
at your gates on their own. Each province has its own recruitable units. Some units may
require a structure such as a temple or laboratory before they can be recruited. Some can
only be recruited in a province with a particular magic site.

Each nation has a unique set of units that can only be accessed in provinces with a friendly
fort. At the start of the game, this will be the starting fort in a nation's home province.
Later, as you build new fortresses, you'll be able to recruit those units in those
provinces too, although some units are recruitable only in your capital, from a magic site
located there.

There is a basic distinction between **units** and **commanders**: units are the troops that
make up your squads, while commanders are the individuals who either lead these squads or
perform other tasks like research or item crafting. Some attributes are exclusive to
commanders, like leadership and the ability to change equipment inventory or carry gems.

You can get further information about an ability simply by clicking on it. This will bring up
a window which shows how the value has been modified. For example, a unit may have a base
morale value of 12, but due to experience (+1) and friendly dominion (+1) the modified value
is 14.

## Basic attributes

**Hit Points**
: Everyone knows what this is.

**Size**
: Size determines how many units can be in a single square on the battlefield (a maximum of
10 points in a single square). It also determines how many supplies a unit needs each turn.
Units consume size minus 2 supplies each month. Small units (size 1-2) consume 1/2 supply
each month and size 0 units do not consume any supplies. Animals have their supply usage
halved. For cavalry units both the rider and the mount will consume supplies.

**Strength**
: This determines how much damage a unit does when it successfully strikes a target.
Strength is also used to break free from certain effects like entanglement.

**Attack**
: This determines the unit's chances of successfully striking a target with melee weapons.

**Defense**
: This determines the unit's chances of avoiding a strike by melee weapons.

**Protection**
: This is the unit's armor rating. It can be different on different parts of the body,
depending on equipment worn or simply the nature of the creature's hide. These separate
values will be shown when you click on Protection.

**Morale**
: This measures a unit's likelihood of not running away from battle.

**Magic Resistance**
: Think of this as Defense, only against magic. Not all spells have to penetrate Magic
Resistance, though.

**Precision**
: This is how accurate a unit is, either with missiles or with magic.

**Encumbrance**
: A unit will incur Fatigue equal to its Encumbrance on each turn it attacks. Moving (by
itself) does not incur this.

**Map Move**
: This determines how far a unit can move on the world map, subject to the movement costs
listed under [Movement](05-movement.qmd).

**Combat Speed**
: This determines how far the unit can move in combat.

**Fatigue**
: A unit's Fatigue causes it to be more susceptible to critical strikes. Once a unit reaches
100 fatigue, it becomes unconscious and is unable to attack or defend. A unit at 200 fatigue
starts taking regular hit point damage instead of fatigue damage from additional fatigue.

**Age**
: The first number is the unit's age in years. The number in parentheses is the age at which
the unit will start suffering penalties and become susceptible to afflictions due to old age
(referred to as max age). It is modified by the following (in order of priority):

- undead creatures have their max age increased by 50% per point of Death magic
- inanimate creatures have their max age increased by 50% per point of Earth magic
- demons have their max age increased by 50% per point of Blood magic
- everyone else has their max age increased by 50% per point of Nature magic
- creatures whose max age could be modified by Nature have it reduced 5% per point of Fire
  magic (burn bright, burn fast)

There are three kinds of **Leadership**, which apply to Commanders only:

**Leadership**
: The number of units a commander can lead.

**Undead Leadership**
: Like leadership, but for undead beings. Mages can lead 50 undead beings per level of Death
magic skill and 10 per level of Blood magic skill they have.

**Magical leadership**
: As above, but for magical beings. For mages this is determined by indirect magic bonuses
(not all paths confer the same benefits).

## Special abilities

Units in Dominions 6 can have a wide variety of special abilities. In fact, there are about
500 special abilities in the game. Each modifies the unit's attributes or capabilities in
some way. A mouse-over or right-click on the ability in the stats screen will give an
explanation. Some bear further explanation:

**Ambidextrous**
: Reduces the attack penalty for wielding two or more weapons by an amount equal to the
Ambidextrous level. It does not remove the 1 point of encumbrance penalty per extra weapon
wielded.

**Berserker**
: A unit with this ability goes berserk when wounded if it passes a morale check vs. 12.
Berserk units fight until dead -- they do not rout. A unit with +Berserk ability gets that
number as a bonus to its berserk attributes. A berserk unit that falls unconscious loses its
berserker state (but can go berserk again if wounded after regaining consciousness).

**Ethereal**
: Very difficult to hit with non-magical weapons. 75% of such strikes will miss. When
storming a fort ethereal units can pass through the walls and attack defenders on the other
side.

**Glamour**
: These units gain Mirror Image in combat, and are undetectable in friendly provinces.

**Recuperation**
: This unit can heal its battle afflictions over time, unless it has the Old Age icon.

**Regeneration**
: Regenerative creatures heal some of their lost HP after every combat round and have a
reduced risk of getting permanent afflictions from getting wounded in battle. Regeneration
does not affect inanimate beings like golems and longdead. There are two more varieties
called **Reconstruction** (works only on inanimate beings) and **Reforming Flesh** (works on
all undead beings, but nothing else).

**Sailing**
: Can cross (but not remain in) water provinces when moving.

**Awe**
: Units with Awe force enemies to take a morale check against 10 + Awe in order to be able to
attack them. Thus, a unit with Awe +4 would force attackers to pass a morale check against
14, or be awestruck and unable to attack on that combat round. There is a special kind called
**Sun Awe** which does not work underground, or when it is dark.

**Fear**
: Units in a monster's Fear area of effect get their morale temporarily lowered and their
entire squad must take a morale check against the monster's Fear, or rout. The basic Fear
effect requires a check against 10. Unlike Awe, the bonus to Fear indicates the additional
area of effect, not the Fear strength. So a Fear +4 monster has normal Fear that radiates to
4 additional squares. The Fear strength itself is increased for every full +5 Fear, so a
Fear +10 unit would radiate to ten additional squares, and force a morale check against 12.
The base area of effect (Fear +0) is 6 squares.

**Heat**
: Units with this ability radiate heat into adjacent squares (seen as little black smoke).
This creates level 1 or 2 heat clouds. The default size of a heat aura is 3 squares and is
increased by Heat scales and reduced by Cold scales. A huge number of units with heat aura
will cause the clouds to spread further, but the effect on a single nearby enemy unit will
still be the same.

**Chill**
: Exactly the same as Heat, except that it creates frost clouds (bluish-white smoke). The
default size is 3 squares and is increased by Cold scales and reduced by Heat scales.

**Poison cloud**
: This creates level 1 or 2 poison clouds in the vicinity (green smoke).

**Stun**
: Stun prevents a unit from taking any action for about one round.

**Invisibility**
: Units that are invisible cannot be seen. You suffer a -9 penalty to Attack when attacking a
unit you cannot see in melee. To see invisible units you must have the ability Spirit Sight.
Units that are blind anyway are not further penalized when attacking invisible enemies.

**Petrification**
: This is the Medusa's special ability. Anyone attacking her is petrified if the attacker
fails a magic resistance roll. After about 3-6 rounds, the petrification is lost. If the unit
passes a magic resistance check upon losing its petrification, it returns to normal. If it
does not, it dies.

**Standard**
: The standard ability increases the morale of the entire squad it is in. Only the best
standard for every squad will have a morale increasing effect.

**Horror Marking**
: A horror mark will result in a small chance each month that a unit will be attacked by a
horror. A unit can be horror-marked more than once which increases this chance, but there is
no way of knowing how bad the mark is. In battle Horrors always attack a horror-marked unit
first. Stronger horror marks also attract stronger horrors.

**Trample**
: A large unit runs over a smaller one. A trampling unit displaces all of the units in the
square it enters to an adjacent square. These units have to take a Defense - (fatigue / 10)
check against 3d6. If they fail, they take 7 + Size trample damage. This is an armor-piercing
attack, so Protection is halved. Ethereal tramplers have their trample damage halved. A
trampled unit always takes at least one point of damage. A unit which passes the defense
check is still displaced, but just takes one point of damage total.

**Swallow**
: Some monsters are able to swallow the target of a successful trampling attack. The
swallowed monsters are removed from the battlefield until the swallowing monster is killed.
Some monsters can digest swallowed targets (damage each turn), and some can incorporate the
swallowed target into their own bodies and gain extra hit points. Being swallowed prevents
many life-saving abilities and spells (e.g. Regeneration and Phoenix Pyre) from working and
usually means certain death unless the swallower is killed swiftly.

### Unit classes

Some special abilities divide units into classes that have different abilities associated
with them, and often leadership requirements that restrict who can lead them.

**Magic being**
: These units require a mage to lead them. They rout if left without magical leadership.

**Mindless**
: Mindless units have 50 morale and will never rout as long as there is a suitable commander
present to lead them. If left without a suitable commander they will suffer mindless
dissolution on the battlefield. Mindless units cannot be in the same squad as non-mindless
units.

**Undead**
: Undead units are subject to banishment. They require undead leadership, generally conferred
by skill in Death magic (or being an undead commander). A squad that mixes undead and
non-undead gets a -1 morale penalty. Undead are immune to affliction healing effects and
suffer no adverse effects from disease. They rout if left without undead leadership.

**Demon**
: Demons are subject to banishment. They require undead leadership, just like undead. Demons
are also immune to disease. They rout if left without undead leadership.

**Lifeless**
: Lifeless beings are immune to disease, regeneration, life drain and affliction healing
effects. They are also immune to many combat spells, but they can heal themselves with life
draining attacks like everyone else.

**Spiritform**
: Beings with spiritform cannot be affected by transformation spells like ironskin, skeletal
body and polymorph. They are also immune to both diseases and affliction healing effects.

**Animal**
: Animals can be led by normal commanders, just like humans. Animals only consume half as many
supplies as a humanoid of the same size. Animals without arms like apes are worse at both
sieging and defending forts (half strength), but most animals compensate by being stronger
than humans.

A nearly full list of abilities can be found in the Modding Manual included with the game.

## XP: Experience points

Units which survive the world of Dominions for a period of time are likely to get experience.
Units usually gain 1 XP per month, but can gain more through combat. Winning a battle gives 4
XP, retreating from a battle gives 1 XP. This battle XP will be awarded at most one time per
month. Striking enemies in melee (or trampling) also gives 1 XP per strike.

More XP gives a bonus to Prec, Att, Def, Str, Morale, Encumbrance, HP and Magic Resistance.
Commanders also get a bonus to the number of troops they can lead and Research Points if
applicable. Note that commanders with poor leadership (max 10 units) have their leadership
bonuses divided by 5.

| XP | Att | Def | Prec | Str | HP | Enc | MR | Morale | Ldr | RP |
|---:|----:|----:|-----:|----:|---:|----:|---:|-------:|----:|---:|
| 15 | +1 | +1 | +1 | -- | -- | -- | -- | +1 | +25 | +1 |
| 50 | +1 | +1 | +1 | -- | -- | -- | -- | +1 | +50 | +1 |
| 100 | +1 | +1 | +1 | +1 | +1 | -- | -- | +1 | +50 | +1 |
| 200 | +1 | +1 | +1 | -- | +1 | -1 | -- | +1 | +50 | +1 |
| 400 | +1 | +1 | +1 | +1 | +1 | -- | +1 | +1 | +50 | +1 |

: Stat bonuses from XP

Some items, sites and the Heroism bless grant additional XP.

## Heroic abilities

Non-pretender commanders who join the Hall of Fame get heroic abilities. These are denoted by
a yellow star in a red circle, and can grant increased attributes, such as strength,
leadership, magic resistance, and the like. Unique beings such as the Elemental Royalty
cannot enter the Hall of Fame.

## Afflictions

Units may suffer battle afflictions when they suffer damage. The chance is simply the
percentage of its total normal hit points a unit suffers on that strike. In other words, an
infantry unit with a healthy strength of 10 hp will have a 20% chance of suffering an
affliction upon taking 2 hp damage. The location of hits is important: loss of an arm or an
eye depends on being hit in the right place.

Afflictions are denoted by a red heart. A unit may suffer from multiple afflictions. Diseased
units may gain additional afflictions each turn. Afflictions can be healed by the following
methods:

- Units with the Recuperation special ability heal afflictions over time (unless they have
  Old Age).
- Units that are Immortal (or Dominion Immortal) may heal afflictions when they reform after
  dying.
- Units with an involuntary shapechange mechanic (such as Jaguar Warriors of Mictlan) can
  sometimes heal afflictions when they change back to their normal shape.
- Units with the Healer ability will cure a number of afflictions up to the value of the
  ability automatically in the same province every turn.
- Units with the disease healer ability will automatically cure a number of diseases equal to
  the value of the ability in the same province every turn.
- The global enchantment Gift of Health will automatically cure afflictions in the dominion
  of its owner.
- The magic artifact The Chalice will automatically cure up to 5 afflictions in the same
  province.
- The Miraculous Cure all Elixir magic item will automatically heal one diseased unit in the
  same province.
- There are a couple of magic rituals that can be cast to cure a disease from a specific unit
  in the same province.
- There are a few magic sites that can heal afflictions like a healer.
- Undead, inanimate or spiritform beings usually cannot heal afflictions unless they have
  Recuperation or Immortality.
- Afflictions caused by cursed items such as Eye of Aiming and The Black Heart cannot be
  healed unless the item is removed first.
- The corpse stitcher ability can heal corporeal undead beings (ethereal beings are immune).

Afflictions have a difficulty level that is checked against when subjected to healing. If the
healing check succeeds, the affliction is cured. Afflictions are different from Curses or
Horror Marks; the latter two cannot be removed. Horror marks may be lessened by staying dead.

## Recruiting units

Recruiting units is the main method of adding troops to your armies. Recruitment is done per
province, so as you capture provinces, you gain the ability to recruit new types of troops.
In some coastal provinces, these troops may be amphibious.

- Each province has its own pool of units.
- Some national units can only be recruited in a nation's capital.
- Building a fort in a province adds a nation's non-capital troops to that province's pool.
- Gold, resources, and Recruitment points are spent to produce units.
- Some nations can recruit additional units outside their forts, depending on terrain.

### Recruitment costs

Units have three costs: gold, resources, and recruitment points. A unit's training is
reflected in its gold cost, its equipment requires the resources, and the recruitment point
cost reflects the need to recruit more advanced unit types in more populated areas. Expect
highly skilled units to cost a lot of gold, heavily equipped units to cost a lot of
resources, and highly skilled, heavily equipped units to cost a fortune.

Sacred units also have a Holy point cost, which is usually 1 per unit (including sacred
commanders), but some large sacred units can cost more sacred points.

### Recruitment restrictions

There are some restrictions not only on how many units of a type can be recruited in one
turn, but how they can be queued as well.

- **Commanders:** You can only recruit as many commanders in a province in a turn as you have
  available commander recruitment points. Commanders can cost more than one point.
- **Gold:** Units may only be recruited up to the limit of that nation's current treasury.
  Units cannot be queued for the next turn if you don't have gold for them.
- **Resources:** Units may only be recruited in a province based on that province's current
  resources, but they may be queued for following turns. Units that cannot be built in the
  current turn, but are in the queue, are dimmed in the recruitment area.
- **Recruitment:** Units can be queued based on recruitment points just as they may be queued
  based on resources.
- **Holy:** Sacred units can only be recruited up to the home province's Holy limit, which is
  the same as the current maximum dominion. Units can be added to the queue beyond the Holy
  limit.
- **Limited:** Some units may have a recruitment limit that only allows a certain number to be
  recruited per turn (e.g. maximum of 2 Sobek Sacred Guard per turn, regardless of available
  gold or resources).

Units are recruited at the beginning of the turn resolution, so units in a province being
attacked in the same turn they are recruited will fight to defend the province. If they are
recruited in a fortress then they will stay in the fortress and become besieged.

Recruited units go into the unassigned unit pool at the top of the Army Setup screen. Holding
down `SHIFT` while selecting a unit for recruiting will choose ten of that unit. Up to 250
units may be queued in a province.

## Army Setup

The Army Setup screen is where you deploy your units for battle. When said battle occurs,
units will be placed on the map in accordance with their squad's arrangement in the Position
squad box. They will attempt to follow the battle orders given.

### Garrison units

At the top of the screen, below the province name, is a single row where all unassigned, or
garrison, units are shown. Newly recruited units get placed here, and stay there until they
are assigned to a commander (or the province is invaded and they are killed in battle). If
the province contains a fortress, these units are considered inside the walls and don't join
any patrolling units in combat. If the province has no fortress, they do participate in
combat, and form one large squad at the center of the battlefield.

### Squads

Squads are the basic organizational unit of combat. They can contain anywhere from 1 unit to
the limit of their commander's leadership value. A commander cannot lead more units than this
value, no matter how many or few squads they are split into. A commander can lead a maximum
of five squads, although depending on the commander's leadership, additional squads may
suffer a morale penalty. Thus, the maximum number of squads in an army is five times the
number of commanders. Some units require their commanders to have special abilities in order
to lead them, like undead leadership for undead and demons or magical leadership for magical
beings. Units that are both undead and magic beings require undead leadership.

To place a unit into a squad, click on the unit, and then either click on the squad box of a
currently existing squad (to add that unit to the squad), or click on the icon of the
commander himself (to create a new squad). Units can be added to a commander up to the limit
of his Leadership value.

Selection shortcuts can help you sort through the units in the Army Setup screen:

- Double-click to select all units of the same type.
- Shift-click to select multiple units.
- Hover mouse over a squad and hit `w` to select all units with afflictions.
- Hover mouse over a squad and hit `e` to select all units with 2+ experience stars.
- Hit `Enter` after clicking on a unit to deselect it.
- Press `?` to see the complete list of keyboard shortcuts.

Thus, you can more easily find all the limping units and put them elsewhere so that holes do
not open up in your squads as they advance. You can likewise make elite squads of experienced
troops that will have higher morale.

### Battle position

The green boxes to the right of each commander's icon are Position Commander and Position
Squad boxes (the "Battle Position" box). Similar boxes appear to the right of each squad.
These define where a unit will appear on the battlefield initially. Commanders are shown as
circles, and squads as boxes. The currently selected unit is highlighted in white. You can
select a single commander or squad by left-clicking, or select a group by drawing a selection
rectangle. By right-clicking you can move them around. The left side is the back of your
formation, and the right side is the front.

| Color | Meaning |
|-------|---------|
| White Circle | Currently selected commander |
| Grey Circle | Commander |
| Purple Circle | Commander with Cast order |
| Yellow Circle | Commander with Retreat order |
| White Box | Currently selected squad |
| Grey Box | Squad with default orders |
| Turquoise Box | Squad with Attack Rear order |
| Dark Blue Box | Squad with Guard Commander order |
| Light Blue | Squad with Hold and Attack order |
| Yellow | Squad with Retreat order |
| Red Box | Squad with undisciplined units |

: Battle position colors

## Battle Orders

Because players don't control units directly in combat, squads have to be issued orders which
they then attempt to follow once combat is joined. Each squad can be issued a different order,
even if it is under the leadership of the same commander. Orders indicated by an asterisk
(`*`) require target orders -- the remainder do not.

### General orders

**None**
: Turns control of this squad over to the computer. It will decide what is best.

**Attack\***
: Engage an enemy in melee.

**Fire\***
: Missile units will fire at a target until they are out of missiles.

**Guard commander**
: The unit centers on the commander and protects him from harm. If there is an assassination
attempt on the commander, these units have a chance of fighting in the assassination battle.
Ranged units with guard commander will only fire if an enemy starts getting too close.

**Hold and attack\***
: The squad will hold in place for two turns. If armed with missile weapons, it will fire at
targets in range. After two rounds, it will advance to melee combat.

**Hold and fire\***
: The squad will hold in place for two turns, then fire or advance to get into firing range.

**Fire and keep distance\***
: The squad will fire missile weapons until their target gets close, then attempt to withdraw
to a safe range and keep firing.

**Retreat**
: The squad retreats off the battlefield. This is treated exactly like a rout and the units
may scatter to adjacent provinces.

### Target orders

**None**
: Targets one random enemy and his squad.

**Archers**
: Targets a random enemy archer and its squad.

**Cavalry**
: Targets a random enemy cavalry unit or fast unit and its squad.

**Fliers**
: Targets a random enemy unit which can fly, and its squad.

**Large monsters**
: Targets one random enemy of size 7 or more and its squad. If no enemy of this size exists, a
size 6 unit will be treated as a large monster.

**Closest**
: The squad will target the closest enemy squad.

**Rearmost**
: The squad will target a random enemy at the rear of the enemy battle formation.

No matter what orders a squad is given, it may not get there if it gets stuck in the zone of
control of an enemy unit that gets in the way.

> **Question:** Can't my soldiers be ordered to just sit back and defend indefinitely?
>
> **Answer:** No. Hold and Attack will have your troops stay in place for 2 rounds, but after
> that, they attack.

### Commander orders

Commanders can be given orders just like squads. In the commander battle orders menu, the top
four orders are specific, while the bottom four are general orders. Specific orders last for
one turn, while general orders guide the commander's actions for the rest of the combat. Up
to five specific orders can be scripted for a single commander. If a commander receives no
orders, the AI will assign them.

Scripts of orders can be copied from one commander to another. Hold the mouse over the script
you wish to copy and hold down `Ctrl`, then hit a number key to store the script. Then place
the mouse over the `<set battle orders>` text of the target commander, and hit the same
number key (without holding `Ctrl`). You can store multiple scripts using the 0-9 keys.

#### Specific orders

**Hold one turn**
: Hold position for one turn.

**Hold or Fire missile weapon**
: Same as hold position, except the commander will fire a missile weapon.

**Hold or Cast a spell**
: Same as hold position, except the commander will cast a spell (chosen by the AI) if
possible. Only available for spellcasters.

**Cast a specific spell**
: Cast a spell specified by the player if the commander has sufficient gems and there is a
valid target in range. If not, the AI will choose a spell.

**Attack one turn**
: Commander will move toward a random enemy for one turn and engage it in melee if possible.

**Fly Attack one turn**
: Commander will fly toward a random enemy and try to engage it in melee. The commander must
be able to fly to use this order.

#### General orders

**Stay behind troops**
: The commander will cast spells, fire missile weapons, and attempt to place himself in the
rearmost part of the army.

**Attack**
: The commander will move towards enemies and attempt to engage them in melee.

**Cast spells**
: The commander will cast spells chosen by the AI.

**Advance and cast spells**
: The commander will advance to be close to the front and cast spells. If possible, a few
spells will be cast while advancing as well.

**Retreat**
: The commander will attempt to rout off the map.

Checking the box "conservative gem use" will ensure that the mage uses his gems as sparingly
as possible and for scripted spells only. After giving a commander an order, the same order
can be repeated by clicking `x`.

## Unit Inventories

Commanders' inventories are important places for equipment. Clicking on an empty inventory
slot takes you directly to your nation's magic item inventory (if you are in a province with
a lab), and selecting an item in this screen will equip that slot with it. Magic items can
grant the wearer all sorts of benefits, given in the [Magic Items](10-magic-items.qmd)
section. Not all units will have all inventory slots. A non-human commander may not have a
head slot, for instance. Mounted commanders have a foot slot, but it is disabled as long as
they are mounted; if they get dismounted they will be able to use their magic boots. Mounts
of commanders have a barding slot.

A unit can be upgraded with better armor and weapons simply by giving it a superior item.
However, the unit's standard items cannot be removed, and when the new item is withdrawn, the
standard item re-appears.

### Magic gem inventory

Commanders may also carry magic gems, which mages can use for a variety of purposes. Gems can
be transferred between commanders in the same province by clicking on the Magic Resource
Treasury `F7` in the main screen and then clicking the "Transfer gems to commanders" button,
or simply clicking on a commander's personal magic items inventory slot, which goes directly
to the Transfer Magic Resources screen.
