# The Origins of Nations

The world of Dominions is very much the story of certain nations over the ages. In Dominions
2, nations could have various "themes" which gave them certain characteristics. In Dominions
3, this was altered somewhat by formally separating the nations into ages, and their histories
are reflected to some extent in the progression from one age to the next. Kristoffer Osterman,
the co-designer of the Dominions series, describes the thematic inspiration and influences for
each nation in Dominions 6.

## Abysia

Abysia does not have any clear inspirational sources. Malign devil-worshiping empires of the
fantasy genre combined with some ancient Middle Eastern concepts, perhaps. Think of great
temple ziggurats adorned with ever-burning braziers fed with still-beating hearts in pompous
ceremonies, witnessed by a cowed populace of slaves and smoldering Abysian rulers. Imagine
magma-lit caverns filled with screams, roars, and fleeting shadows. With blood sacrifices
being part of the official state cult it might be considered an evil nation, but it is sprung
from elemental forces, and only under infernal influence (and ignorance) does the kingdom turn
to evil. It is a tragic nation with a proud heritage, and dilution of their magic (perhaps due
to temptation by infernal forces) leads it to embrace blood sacrifice.

## Agartha

Agartha is inspired by fantasy TTRPGs in general, and an Earth Dawn setting of my brother's
imagination, ripe with mummified ancestors entombed in ancient cavern halls, in particular.
Old ideas of a race of pale, cave-dwelling humanoids from my ideas of the game "Shepherds of
Creation" completed the conglomerate. Think of opulent halls adorned with riches of the deeper
earth in which reside ancient bloated oracles with pallid skins ruling their kin with
increasing desperation; desperation because their proud race is dying. Agartha is perhaps the
most tragic of the nations in Dominions. Surviving oracles cling to memories of a glorious past
unable to stop the unavoidable disappearance of their ancient race. I wanted a sense of loss to
permeate the nation.

## Arcoscephale

Arcoscephale is, together with Pythium, the first nation conceived in the creation of
Dominions. After having played GMT's Great Battles of Alexander and S.P.Q.R. I got fascinated
by ancient warfare, and the hoplites were among the first units to appear in Dominions. At
first the two nations were one, with a troop roster of ancient units, while Man and later on
Ulm had troop rosters with a more medieval touch. Soon, however, it became clear that Pythium
and Arcoscephale should be two distinct nations. Arcoscephale is heavily influenced by ancient
Greek city states and Hellas. The Golden Age is influenced by the mythical past and the archaic
age. Later ages boast Hellenic and Mesopotamian influences: elephants, mysteries and Chaldean
astrologers.

## Asphodel

If you have walked in a forest with trees covered in ivy and stumbled across the carcass of a
dead animal, partly covered by leaves and vines, your imagination might give life to the vines
and the roots of the nearby plants. The carrion jerks and twitches as the roots give life to
the dead animal. It opens its jaws and lets out a silent hiss.

Asphodel is a nation of the vengeful wild. Panii and halfmen of Pangaea have revolted against
their brethren and unleashed the powers of a dark and hungry god upon the living world. Vines
and roots turn into slithering and growing entities strangling the living in their sleep and
reanimating their corpses as marionettes of vines and bones. These marionettes are known as
manikin. The first carrion beasts appeared in one of my Ars Magica campaigns. There was a
manikin in the bestiary that sparked my imagination and resulted in animal carcasses
reanimated by vines.

Asphodel as a Dominions nation has a history similar to Lemuria. The nation was once a theme in
Dominions 2 that was removed and made into a global spell available primarily to late age
Pangaea. Unfortunately, this made the whole setting of the Carrion Woods rare, and that was a
pity. We decided to remake the old theme into a new Pangaean splinter nation.

## Bandar Log, Kailasa, Lanka and Patala

Bandar Log, the nation of the monkey people, is inspired by Hindu myths, ancient India and
Rudyard Kipling. The Vanara comes from the Ramayana, an epic in which the monkey people aid
prince Rama in his struggle against the demon king Ravana. The hierarchical division of the
different species of monkeys has parallels in the Hindu caste system. I wanted the Bandar to
use the alleged colors of the Indo-Aryan castes: white for priests, red for nobles and black
for commoners. Markatas are exempt from the hierarchy and society at large and might be seen as
untouchables of earlier times. Important to the development of the Bandar Log were the
semi-divine beings of Hindu myth. With a slight breath of 2001: A Space Odyssey, the Yavanas
and Devatas became lords of the monkey people. When these beings left the world the monkey
people found themselves in control, until the emergence of another divine race, the Nagas. As
Kaa hypnotized the monkeys in Kipling's Jungle Book, the Nagas mesmerized the Bandar and
Vanaras and claimed rulership over the nation.

The latest addition to the monkey business was Lanka, the mythical kingdom of Ravana. The
nation is in many ways similar to Kailasa, but rakshasas of various forms replace the yakshas
and yavanas, and blood magic and cannibalism is prevalent. I confess to having a weakness for
great ape sorcerers and necromancers in semi-civilized apparel, preferably raging and howling
with gory mouths. Hindu myth is rich and you could probably make a Dominions game based
entirely on Hindu nations, beings and gods.

## Berytos

Berytos exists only in the early era. It is the Phoenix Empire that was destroyed and reemerged
in numerous coastal city states. It is a cultural melting pot influenced by several other
nations. The nation is heavily inspired by Mediterranean seafaring peoples and the Phoenicians
in particular. The sea peoples of Canaan and Egypt, combined with Greek migrational hypotheses,
Phoenicians and their Carthaginian/Punic extension have been important sources. The
Canaanite/Phoenician cities of Byblos, Tyros, Sidon and Carthage inspired the ideas of a
seafaring nation and led to the Berytian dependency on coastal forts.

The legendary founding of Carthage by Dido/Elissa and her marriage with the high priest of
Melqart combined with the biblical concept of Canaanite Ba'al worship laid the ground for the
concept of Berytian Melqart worship. This enabled some intertwining of Hinnomite and Berytian
backstories. I also wanted a deeper mythical backstory and found that the Telchines, Dactyls
and other Greek mythological island-peoples combined with the Greek migration hypothesis fit
the role. When I remembered the slightly bizarre Ars Magica supplement "South of the Sun" by
Atlas Games, where there are Carthaginian descendants dabbling in dark magic, I figured the
great men and queens of Machaka would fit a niche as exile queens and leaders of the cult of
the Melqarts. Berytos has been one of the most fun nations to develop, probably because it
involves and expands the backstories of several other nations and concepts.

## Bogarus, Vanarus, and Rus

Imagine cold winters, princes in sable-rimmed cloaks, opulent halls where sinister old men
practice vile magics or seduce their masters' wives. Think of Rasputin. Think of orthodox
patriarchs and bizarre sect-like movements of religious fanatics living in hiding. Imagine the
monsters, heroes and bogatyrs of Russian fairy tales.

When Bogarus was added to Dominions 3, I already had some ideas about the predecessors. My
imagination was influenced by Kievan Rus' when the nation was given Vanir ancestors. I wanted
priests and an institutionalized religion that brings the Russian Orthodox Church to mind and
some sectarian movements on top of that. I did some research and was quite happy when I found
the skoptsy, the "castrated ones," and other strange religious movements.

Vanarus was partly conceived during the development of Dominions 3. It is the predecessor of
Bogarus: a nation of ruling Vanir that have subjugated and intermingled themselves with the
previous rulers of the land. Kievan Rus' is one of the sources here, but I've also used the
Chuds, a people that appears in the myths of various peoples from the eastern Baltic seaboard.
The "Pine of Skulls," shape-shifting and shamanic bear cult practices fit the nation. I never
got around to finish my ideas on Rus for Dominions 4. Instead it became the second of the new
nations for Dominions 5, with Baltic mythology, Latvian in particular, as an inspirational
source.

## Caelum

Caelum was originally a purely fictional nation of winged humanoids living atop the coldest
mountain peaks. Later development has gifted them with Zoroastrian traits. In a Dominions 4
patch, the nation's backstory was remade and more Zoroastrian traits, summons, and spells were
added. The backstory of a primordial war between Daevas and Yazatas along with concepts of the
pollution of the sacred flame merged with earlier ideas of Catharsis/Anthrax. We also added
some new guardian spirit mechanics based on Zoroastrian concepts of the soul.

## C'tis

C'tis is a nation of lizardmen under Egyptian and to some extent Mesopotamian influence. Sacred
priest kings, pyramids, swamps, and flooding rivers surrounded by deserts are all elements of
these cultures. The Desert Tombs of the late age is influenced by Egyptian concepts of the dead
and modern fiction on Egypt, and the lizard king might as well be a Pharaoh as a Lugal. The
connection between C'tis and Ermor suggests that C'tis is more Egyptian than Mesopotamian. The
sauromancers' initiation rituals are inspired by Oriental cults of the late Roman Empire, such
as that of Isis and Sarapis/Osiris.

In Dominions 4 another influence was added to C'tis: the Sobeks of Trade & Taint. They were
initially a T&T version of C'tis and Pythium, with theurgs, legionnaires and necromancers as
possible career options. Part of the Sobek lore was put into middle age C'tis.

## Eriu

With the development of Tir na n'Og it became evident that I wanted another nation of Irish
stock to accommodate human heroes such as Cu Chulainn. The legacy of Tir na n'Og was split
between Eriu and Man, and the remaining Sidhe became to Eriu what the Vanir were to Vanheim in
later ages: a blessed ruling race with human subjects.

## Ermor and its legacy

Ermor was initially a conglomerate of the Roman Empire and undead nations of general fantasy
stock. With time, it has received a history that begins as something like the early Roman
republic, with military units of that age and priests and diviners inspired by Roman religious
officials. The New Faith replaces the old state cult of the Numina, as Christianity eventually
replaced the old Roman state cult. With the turn of the age, the mistake of the Augurs becomes
apparent, and the nation is brought into darkness.

Ermor is one of the first conceived nations in the Dominions universe. When the eras were
introduced in Dominions 3, the undead empire ended up in the late age and the Dominions history
lost some of its coherency. With Dominions 4, I tried to straighten things up and once more
placed the Ashen Empire of Ermor in the middle age where its antagonists and splinter empires
can be found. The backstories of Sceleria, Pythium, Marignon and Ulm are all influenced by
Ermor.

## Hinnom, Ashdod and Gath

Hinnom, Ashdod and Gath are heavily influenced by ancient Israelite, Canaanite and Philistine
concepts. I have always been intrigued and fascinated by biblical mythology, and had long
wanted to include the Nephilim and biblical Genesis myths into the game. The Bible, the Book of
Enoch, the Dead Sea scrolls and the Ras Shamra texts of Ugarit are the main sources.

Hinnom draws more heavily on the biblical and Enochian tradition, while the veneration of the
deified dead kings of Ashdod draws inspiration from the Ras Shamra and Canaanite/Ugaritic
concepts of the dead. The rephaim/r'p'm of the Ugaritic texts are ghosts or deified dead rather
than giants, so Ashdod turned out a bit different than I first intended, with death magic
replacing blood. Gath draws more heavily from Israelite and Philistine concepts: early
Israelite religion with a centralized cult at the temple, combined with the legends of David
and Goliath of Gath. I wanted the nation to be an abomination, slowly becoming more civilized
throughout the ages. Hinnom is perhaps more than any other nation in the game an evil nation.

## Fomoria and Tir na n'Og

These nations are the predecessors of Man and Eriu. They are both heavily influenced by "The
Book of Invasions" and Celtic myths and folklore. The wars and conflicts between Fomorians,
Nemedians, Fir Bolg and Tuatha were used to create a common backstory for the nations. The
Fomorian ideas were combined with some ideas of sailing storm giants, inhuman goat-headed
giants and some concepts of Fomorians as keepers of the watery dead.

## Ind and its successors

Ind is heavily influenced by the kingdom of Prester John, a medieval idea of a hidden Christian
kingdom surrounded by heathen tribes. The idea of the hidden kingdom survived until the
seventeenth century. For inspiration on Ind I have used the first and most fantastic medieval
accounts of the marvelous kingdom, with streets of gold and dining tables of emerald. In the
descriptions of Ind's units I have paraphrased several accounts of their outstanding virtue,
like everyone being a priest and every noble being a king. Ind is probably the Dominions nation
least influenced by my own ideas. The only addition that can't be found in the medieval
accounts are the dog-headed cynocephalians, added to Ind (combined with judaeo-christian ideas
of Gog and Magog) as the worst of the cannibals serving the Prester King.

Piconye, Feminie and Andramania are successors to the magnificent kingdom of Ind. I wanted the
successors to split the virtues of the kingdom: Piconye inherits the theocratic traditions of
Ind, Feminie inherits the magic secrets, and Andramania inherits the order and discipline.
Andramania draws additional inspiration from medieval myths on the cynocephalians; after some
reimagining it became a nation of cynocephalians trying to overcome their barbaric legacy.

## Machaka

Machaka is a nation inspired by African kingdoms and the Shona in particular. The king, a
sacred figure, reigns, but does not rule. He is served by vassal chiefs, and his priests (the
Eyes, Ears and Mouth) keep constant surveillance over sub-chiefs and serve as a link between
the people and the temple. The Shilluk concept of regicide and other ideas from African
cultures have also made their way into the nation. Modern Oriental concepts and fantasy cliches
can be found in the black sorcerers of the God Mountain, and the spiders. The Machaka of the
early age is influenced by the old TTRPG Powers and Perils, with its nation of African stock
led by great men released from a great sleeping city. My first idea of clans based on body
parts (liver, heart, hand, head and leg) did not feel right and was replaced with animals, more
fitting with the spiders of the middle age. The nation evolved side by side with Berytos.

## Man

Man is one of the first nations conceived in the Dominions universe. The nation is a
conglomerate of medieval English and Arthurian concepts spiced with some fantasy elements from
Ars Magica and the books of Robert Jordan. The Irish/Northumbrian monastic tradition,
Anglo-Saxon society, and Welsh longbowmen are all inspirational sources. Later on, the nation
turns towards scholarship paired with dark tidings; the mood in the movie Sleepy Hollow is a
nice comparison. In Dominions 4 steps have been taken to accentuate the influence of invading
barbarians reminiscent of the Angles and Saxons.

## Marignon

Marignon is a late medieval nation of inquisitors and religious fanatics. Prudent (or perhaps
paranoid) priests search for vice and heresy throughout the land, putting men and women to the
pyre with fiery justice. Imagine the soldiers wearing fancy and colorful Renaissance clothing,
while religious and arcane officials wear red or black robes and severe miens. In the late era
the Spanish influence is heavier than the Albigensian. Later Gothic concepts of occultism and
devil worship are incorporated along with seafaring and missions abroad.

## Marverni

Marverni is a nation inspired by Celtic Gaul. Gutuaters, vergobrets, druid astrologers, and
blood sacrifices are all heavily influenced by the accounts of Caesar and Roman historians.
Bare-chested warriors or nobles dressed in newly invented chain mail fight side-by-side with
their chieftains to prove their worth. Bronze horns in the image of various animals are also
images to keep in mind. Further inspiration was probably found in Asterix, a remarkably good
comic by the way.

## Mekone & Phlegra

Mekone and its successors are inspired by giants of Greek myth. Described either as strong and
proud hoplites, or in later times as monstrous beings with serpent legs, the idea of a nation
of giants that doesn't follow the development of most other giant nations (with smaller and
smaller giants in the later ages) started to take form. Some research into ancient Athens and
Sparta transformed my first ideas into a nation heavily inspired by Sparta. I also wanted to
incorporate the hubris of the giants and the Gigantomachia (the war against the gods).

Phlegra in the middle age is a nation that has lost most of its proud legacy. The Gigantes of
Mekone are cursed for their hubris and are becoming physically and mentally afflicted. When I
started to think on the slaves and the Phlegran society, the idea of the oppressors and slave
mages appeared. The slave mage mechanics made for entirely new tactics not available to other
nations.

## Mictlan

Mictlan is a nation mainly inspired by the Aztecs and their practice of blood sacrifices. The
name is that of the realm of the dead in Aztec mythology. Tenochtitlan was built on a swamp,
and so is the Mictlan capital, but Mictlan, particularly in the late era, is also a nation of
the rainforest, closer in resemblance to the Maya. Quetzalcouatl, the Lawgiver, figures in most
of the Mesoamerican cultures as a returning savior figure. Mictlan is also supposed to be a
backwards nation reminding us of the arrival of the technologically (and perhaps virally)
advanced Europeans in the Americas.

## Na'Ba and Ubar

These two nations are inspired by the Arabian Nights as well as preislamic Arabia and the
Nabataeans in particular. The biblical narrative of Sheba has also made its way into the nation.
The city of Petra with its water reservoirs and cultivated lands hidden in the desert has always
fascinated me. Na'Ba had to be a nation hidden by the magic of the unseen, the jinnun. Na'Ba and
Ind were developed simultaneously and were both given the new hiding dominion mechanics.

Na'Ba would be a nation where humans, jinnun and crossbreeds coexisted, with access to jinn
summoning rituals. Out of chance I stumbled across Hud, prophet of the 'Ad people, who were
great of stature. The Avvites of Hinnom became refugee 'Adites, the giants of Na'Ba. Ubar is a
jinn nation more heavily inspired by Arabian fairy tales, the city of Brass and Iram of the
Pillars.

## Nazca

When Nazca was released in a patch for Dominions 4 it had already been on the drawing board for
a long time. I really like the necrocratic concept where mummified ancestors have a position of
influence in society: a kingdom forced to expand with every generation as previous kings and
nobles keep their conquered lands even after death, slowly going bankrupt as stipends to dead
ancestors keep piling up. When I got the idea of an Inca setting for the new nation it stuck. I
researched Andean concepts and was intrigued by mummy bundles, moieties, geoglyphs and
necrocratic practices.

## Nidavangr

Nidavangr is a nation based on three main sources. Two of them are derivatives of rpg settings
of mine. The first was a land inhabited by barbarians divided into seven clans named after
their totemic animals, at the center of which was a kettle hole where unholy rites created
Nidlogade, warriors with several lives. I reused the totemic tribes for my current pathfinder
campaign, reduced to three clans: wolf, bear and raven. The shape shifting seithberenders of
Nidavangr closely resemble the clan druids of that campaign. The third source is the mood of
the novel Midnight Tides of the Malazan Book of the Fallen. Finally Nidavangr was set in a
Dominions context with jotuns and vanir as ancestral enemies of the clans.

## Oceania, Pelagia, and Erytheia

Oceania and Pelagia are nations inspired by medieval bestiaries abundant with creatures of the
sea corresponding to beings living on land. As most of these creatures are half-men and
fish-beasts, Oceania as a nation became quite similar to Pangaea. The development of the Triton
Kings incorporated modern concepts and imagery of mermen, and in Dominions 4, Pelagia was made
a nation of its own, less Pangaean in style. Knights armed in mother-of-pearl armor, Triton
Kings on hippocampoii-drawn sea-shell chariots, and golden tridents are all part of the Pelagia
setting.

Erytheia is the late era development of Pelagia, heavily inspired by Ptolemaic Egypt. Like
Ptolemaic Egypt, it is a nation of foreign conquerors adopting local traditions, forming an
isolated kingdom desperate to keep its royal blood lines and avoid foreign influence. I wanted
the Ptolemaic practices of royal sibling marriages represented in the game, and this led to some
new mechanics developed for Erytheia.

## Pangaea

Pangaea is a nation of wild half-men of Greek myth, as they could have developed if exposed to
a vast and technologically superior humanity: Iron or skin. Adapt or die. As in most cultures
exposed to so-called civilization, some inhabitants cling to traditions while others adapt. The
loss of ancient magic and traditions over the ages is quite apparent in this nation, but in the
late era the centaurs have found new paths of magic, giving hope to the nation.

## Phaeacia

Phaeacia is an island nation inspired by its namesake in the Odyssey, the enchanted isle ruled
by Alcinous. Imagine palaces of gleaming bronze, with golden gates guarded by dogs of gold and
silver. In enchanted gardens filled with fantastic trees, fountains and marble statues, wise
men entertain their queen with song and poetry. In one of my Ars Magica TTRPG campaigns the
players were lost at sea during a storm and arrived at an enchanted island colony of surviving
Phoenician Ba'al worshipers, blessed with longevity. The Ulysses tale combined with my
campaign and previous ideas on Berytos resulted in the new island nation. The dark vessels and
the island start make the nation play differently than other nations.

## Pyrène

EA Pyrene is a nation inspired by Basque mythology and an Ars Magica rpg campaign of mine, set
in the Pyrenees. The caves of Ariege and prehistoric cave paintings combined with the Bekryde
myth were great inspirational sources. The giants of Basque myth were also incorporated. MA
Pyrene is inspired by more modern concepts of the Akelarre, the witches' sabbath, and the art
of Goya. The nation also draws inspiration from the song of Roland and the wars between
Christians and Muslims in medieval Spain.

## Pythium

Pythium is based on the eastern Roman Empire and Byzantium. Its history and military bear a
legacy of Ermor, as did Byzantium from Rome. The Theurgs and their ceremonial magic are
influenced by the lavish liturgy of the Orthodox Church. The Cathedral of the Spheres is filled
with chanting, the fragrance of incense, and processions of Theurgs robed in gold and silver.
In the late era the nation is influenced by the mystery cults and religious worshipers of
subjugated lands, much as the late Roman empire became a melting pot of imported religious
beliefs. The mystery cults of Isis/Sarapis, Mithra, Dionysos and Eleusis gave Pythium in the
late era a new and interesting flavor. I'm personally quite fond of late era Pythium, since my
thesis was about the Roman Isis/Sarapis cult.

## Ragha

Ragha was added in the Caelum patch for Dominions 4. I had played with ideas on a dual
Caelian/Abysian nation earlier on, but it wasn't until I started to remake Caelum that those
ideas bore fruit. Of the Caelian nations it is probably the one most heavily influenced by
history and myth. Since the nation was developed with Zoroastrianism in mind, the mage-priests
of the nation, dasturs and athravans, became an integral part of the nation. The heat/cold
preferences of the nation made it a bit difficult to balance, but I'm very fond of the concept
thematically.

## R'lyeh and Atlantis

These two nations are heavily influenced by H.P. Lovecraft. While R'lyeh is closer to the
Cthulhu mythos with Starspawns and strange beings from the stellar void, Atlantis is a nation
of deep ones native to the depths. The early era is more heavily Lovecraftian, while the middle
era is more influenced by fantasy concepts. Atlantis is another nation devastated at the end of
the second era; late Atlantis incorporates Inuit concepts apart from the earlier Lovecraftian
elements.

R'lyeh represents the stranger aspects and beings of the Lovecraftian universe. Starspawns,
strange openings and beings of the Void are mixed with a bit of fantasy role-playing game
cliches. The nation progresses from a D&D-ish nation of Aboleths to an insane nation of dreaming
madmen, mutated lunatics and mind-defying void beasts. F'tagn.

## Sauromatia

Sauromatia is a nation based on Herodotus' accounts of the Scythian peoples in The Histories.
Here Scythians, Amazons, Sarmatians, and Androphags are described with their strange traditions
and unsavory practices, and the book is a splendid source for any modder seeking inspiration.
Finally, Witch Kings and elements of the Pythian predecession (serpents, swamps and hydras)
were added to the Androphags to make the nation more sinister and Dominion-esque.

## Sceleria and Lemuria

Sceleria is the daughter of Ermor and sister of Pythium. In Dominions 3, the nation was the
middle era Ermor, but with the cleanup of the history, Sceleria became a splinter empire that
together with Pythium broke free from Ermor before the cataclysm. Sceleria, as Pythium, is of
course influenced by the Romans.

Lemuria is a reprise of the Dominions 2 Ermor theme "Soul Gates." With the rewriting of the
history the new nation of Lemuria followed in the wake of Sceleria. Lemuria is an undead nation
of ghosts and immaterial undead instead of skeletons and zombies. Think of grey lands of ash
and dust. Imagine spectral hordes marching forth under banners swaying in a wind you cannot
feel. At the horizon a great darkness is spreading as shadows pour forth from the Soul Gate.

## Therodos

Therodos is based on Greek legends and ideas of a golden-age kingdom swallowed by the waves as
punishment by the gods. Since I made Berytos I wanted to elaborate on the Telkhines. Previous
concepts of the Berytian Telkhine ancestry and new ideas of a spectral nation unaware of its
undead precondition were merged and Therodos started to take form. Additional ideas of
craftsmen daimones, such as Daktyls and associated Kouretes and Korybantes, found a place in
the backstory.

## T'ien Ch'i

T'ien Ch'i is obviously influenced by China. I couldn't even resist the name Spring and Autumn,
from the period of the same name in Chinese history. Daoism and its five elements, inner
alchemy, and quest for longevity inspired the Masters of the Way, as did the T'ien Shih
(celestial master) of institutional Daoism, converted into the Celestial Master of T'ien Ch'i.
Heroes come in plenty in the Chinese tales and the Seven Immortals are all interesting figures.
Sun Wukong and his friends are perhaps even more so. T'ien Ch'i has also been inspired by movies
from Hong Kong, China, and Korea.

## Ulm

Ulm is a nation that goes through major changes with the eras. In early times it is a barbarian
nation. Think Conan! Or at least, think of the first five minutes of Conan the Barbarian, when
Conan's family is slaughtered by Thulsa Doom. Think of fur-dressed shamans and warrior smiths
speaking of the Enigma of Steel. Then think of the German tribes described by Caesar in The
Gallic Wars, the Roman disaster of the Teutoburger Forest, and the pagan temple at Irminsul.
Ulm in the early era is an Ulm before the arrival of civilization.

Ulm of the later eras is inspired by, amongst others, Teutonic Knights and German Landsknechts.
Late Ulm is an intended shift of style towards central and eastern Europe, southern
Germany/Bavaria, and Transylvania. One of the classic ingredients of gothic novels is tainted
bloodlines, so making a Gothicized fantasy "Bavarian" Ulm is a natural step.

## Ur and Uruk

Ur came to be as a result of Trade & Taint, an earlier unfinished Illwinter project. I made the
first Enkidus and Sobeks for that game. In Dominions 5 the Enkidus were given a nation
influenced by Mesopotamian history. I found myself reading more on Sumerian cities and culture;
the transfer of religious and temporal importance from Eridu to other cities during Sumerian
times is an interesting process. Thus Uruk became the first new nation added in Dominions 5.

I like the concept of a single center of civilization surrounded by lands inhabited by wild men
roaming around tending goats and hunting game. This led to the development of the mechanic where
some of a nation's units are recruitable, not in their home or fortresses, but in their
surrounding lands. And of course they had to have sirrushes, the wingless dragons of the Ishtar
Gate. Ur develops into Uruk in the middle age and gets access to armaments of iron. In this new
era the Entu of the Moon, inspired by En Hedu'anna, the daughter of Sargon the Great, becomes
the unifying power of the kingdom and Uruk turns into a theocracy.

## Vanheim, Helheim, Niefelheim, Muspelheim, Jotunheim, Midgard, and Utgard

These are all nations sprung from old Norse myth. The Poetic Edda and some later tales,
combined with general conceptions of Iron Age Scandinavia, are the main sources. Vanir, Aesir
and Giants are ancient antagonists in these myths. The Aesir, being perceived as gods, have
been made pretenders in Dominions. As with most nations of supernatural origin, it seems fitting
that their magic fades with each passing age as humans become more numerous.

Niefelheim, Muspelheim, Jotunheim, and Utgard are part of the history of a single nation through
the ages. Vanheim, Helheim and Midgard also share a common ancestry. In the middle era Helheim
merges with Vanheim and disappears as an independent nation; only the valkyries remain as
reminders of its legacy. Muspelheim was added in Dominions 6. I wanted to convey the idea
presented in the norse creation myth, with the flames and heat from Muspelheim meeting the frost
and ice of Niefelheim. In Dominions 6 new mechanics were added that allow a nation to prefer
cold lands, while the capital is exempt from the effects of severe heat. Thus I could make
Muspelheim a land of ash and flames ruled by fire giants, surrounded by icy lands inhabited by
jotun giants.

## Xibalba

Xibalba is a nation inspired by Mayan mythological concepts as expressed in the Mayan texts
Popol Vuh and Chilam Balam. The Popol Vuh describes the creation of the world and tells of the
hero twins Hunahpu and Xbalanque and their travels to Xibalba, the Mayan underworld, through
which the sun travels during the night. Ever since high school, when I first came across the
TTRPG Chill and found a creature named Camazotz, I've been intrigued by bat-gods and
Mesoamerican myth. The bat-god was actually the first god made for Mictlan. When I started to
work on Xibalba it was clear from the beginning that it would be a Mayan nation of bat-people.

In the middle era Xibalba is flooded and toad people take over. Mesoamerican flood myths and
concepts of the Bacab were used in conjunction with a slightly rewritten Atlantian backstory to
fit the concept of a flooded underworld inhabited by Atlantian refugees. Xibalba was also one of
the first nations to get a national global spell based on its backstory: the Xibalban Theft of
the Sun, along with the Agarthan Unleash Imprisoned Ones, reintroduced the national global
enchantments.

## Yomi, Shinuyama and Jomon

These three nations are heavily influenced by Japanese history, folklore, and myth. The first is
an uncivilized nation of demonic brutes enslaving and eating humans and other races. They are
replaced by Bakemonos, ghostly goblins of Japanese folklore, and finally the humans take
control. The beings of Shinuyama are quite heavily influenced by the old pen-and-paper TTRPG
Bushido, although some other sources on mythological beings such as Tengus and Kitsune have been
used. Modern myth, such as the western idea of the ninja, also has a place in the late nation of
Jomon. In Dominions 5, I elaborated more on Yomi to make the nation a bit more of a swarm-nation
with demons entering this world in increasing numbers through demon gates raised by misled human
priests.

## Ys

Ys is based on Breton myths of the sunken city of Ys/Ker-Is and morgen water spirits. To expand
the nation I added some Irish/Welsh ideas of the merrow as well as the Marverni tribe of Kernou
to give the nation an opportunity to establish coastal forts with their own unique units. I
initially intended to merge the Ysian backstory with Marignon and add a Melusine morgen hero for
that nation, but never got around to finishing my ideas.
