# Battlefield Spells

These spells can only be cast in battle. Any summons gained through battle magic exist only as
long as the battle lasts; they are not permanent. Stats for summoned creatures are listed in
the **Special** column of the relevant spell.

Spells in the Divine school require no research; they are available to all nations with
priests, and the Holy level of the spell corresponds to the priest level needed to cast it. A
few national spells (such as those of Ulm and Jomon) require both Holy magic and another magic
path; in these cases the caster must meet both requirements.

Spells costing 100 fatigue or greater require one gem of the primary path. For every full 100
additional fatigue, a spell requires another gem. So for a spell costing 700 fatigue, like
Arcane Domination, 7 gems are required (plus several more are advisable just for fatigue
reduction).

## Abbreviations

| Key | Meaning |
|-----|---------|
| Path | Level in Magical Path(s) required for casting |
| F / A / W / E | Fire / Air / Water / Earth |
| S / D / N / G | aStral / Death / Nature / Glamour |
| B / H / ? | Blood / Holy / Random path |
| Fat | Fatigue |
| Rng | Range |
| AoE | Area of Effect |
| Pre | Precision |
| Dmg | Damage |
| NoE | Number of Effects |
| AN | Armor-Negating (ignores protection) |
| AP | Armor-Piercing (uses half protection) |
| NUW | Not castable underwater |
| UW | Only castable underwater |
| MR | Magic Resistance negates |
| MR- | Magic Resistance negates easily (+4 to MR) |
| BF | Entire battlefield affected |
| Mun | Mundane (attack counts as non-magical) |
| BE | Battlefield Enchantment (active as long as the caster is present) |
| UndIm | Undead are Immune |
| InanimIm | Inanimates are Immune |
| MindIm | Mindless are Immune |
| SpiIm | Spiritforms are Immune |

::: callout-note
School codes: Conj = Conjuration, Alt = Alteration, Evo = Evocation, Const = Construction,
Ench = Enchantment, Thau = Thaumaturgy, Div = Divine, Blood = Blood Magic. The number after
the code is the research level.
:::

## Fire Spells

```{=html}
<table class="table spell-table">
<thead><tr><th>School</th><th>Spell Name</th><th>Path</th><th>Fat</th><th>Rng</th><th>AoE</th><th>Pre</th><th>Dmg</th><th>NoE</th><th>Special</th></tr></thead>
<tbody>
<tr><td>Evo 0</td><td>Fire Flies</td><td>F1</td><td>20</td><td>30+</td><td>0</td><td>-1</td><td>8</td><td>6</td><td>AP, NUW</td></tr>
<tr><td>Evo 1</td><td>Burning Hands</td><td>F1</td><td>5</td><td>1</td><td>1</td><td>0</td><td>15+</td><td>1</td><td>AP, NUW</td></tr>
<tr><td>Evo 1</td><td>Fire Darts</td><td>F1</td><td>20</td><td>30+</td><td>0</td><td>1</td><td>10</td><td>4+</td><td>AP, NUW</td></tr>
<tr><td>Alt 2</td><td>Burn</td><td>F1</td><td>10</td><td>30</td><td>0</td><td>100</td><td>0</td><td>1</td><td>NUW</td></tr>
<tr><td>Alt 2</td><td>Resist Cold</td><td>F1</td><td>10</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td></td></tr>
<tr><td>Alt 4</td><td>Combustion</td><td>F1</td><td>20</td><td>30</td><td>1</td><td>100</td><td>0</td><td>1</td><td>NUW</td></tr>
<tr><td>Alt 6</td><td>Blindness</td><td>F1</td><td>20</td><td>20</td><td>0</td><td>100</td><td>0</td><td>1</td><td>MR</td></tr>
<tr><td>Conj 3</td><td>Summon Lesser Fire</td><td>F1</td><td>100</td><td>1</td><td>0</td><td>0</td><td>0</td><td>1</td><td>NUW Elemental</td></tr>
<tr class="spell-desc"><td colspan="10">Summons Fire Elemental x1: HP 25, Prot 0, MR 13, Mor 50, Str 12, Att 10, Def 8, Prec 5, Enc 0, CS 7, MM 16, Eth, Spi, Inanim, Magic, Mind, NNEat, Aff Res 99, Heat pow 1, FR +50, CR -5, PR +25, SpSi, Heat 4, Fire Shield 10 AP dmg, Wpn: Flame Strike</td></tr>
<tr><td>Conj 5</td><td>Will o&#x27; the Wisp</td><td>F1</td><td>100</td><td>0</td><td>0</td><td>0</td><td>0</td><td>2</td><td>NUW</td></tr>
<tr class="spell-desc"><td colspan="10">Summons Will o&#x27; the Wisp x2: HP 3, Prot 0, MR 12, Mor 50, Str 3, Att 20, Def 20, Prec 5, Enc 0, CS 22, MM 22, SS, Float, Eth, Spi, Magic, Mind, NNEat, FR +15, PR +15, SpSi, Wpn: Flame Burst</td></tr>
<tr><td>Ench 1</td><td>Protection from Fire</td><td>F1</td><td>5</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td></td></tr>
<tr><td>Ench 3</td><td>Fire Shield</td><td>F1</td><td>20</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>NUW</td></tr>
<tr><td>Thau 2</td><td>Bonds of Fire</td><td>F1</td><td>20</td><td>20</td><td>0</td><td>3</td><td>0</td><td>1</td><td>NUW</td></tr>
<tr><td>Evo 1</td><td>Flame Bolt</td><td>F2</td><td>20</td><td>45+</td><td>1</td><td>2</td><td>15+</td><td>1</td><td>AP, NUW</td></tr>
<tr><td>Evo 2</td><td>Fire Blast</td><td>F2</td><td>20</td><td>7+</td><td>3</td><td>0</td><td>15+</td><td>1</td><td>AP, NUW</td></tr>
<tr><td>Evo 2</td><td>Sulphur Haze</td><td>F2A1</td><td>20</td><td>30</td><td>4+</td><td>0</td><td>104+</td><td>1</td><td>AN, NUW</td></tr>
<tr><td>Evo 3</td><td>Fireball</td><td>F2</td><td>20</td><td>35+</td><td>1</td><td>1</td><td>16+</td><td>1</td><td>AP, NUW</td></tr>
<tr><td>Evo 6</td><td>Flame Eruption</td><td>F2</td><td>30</td><td>7+</td><td>15</td><td>0</td><td>13+</td><td>1</td><td>AP, NUW</td></tr>
<tr><td>Evo 8</td><td>Pillar of Fire</td><td>F2</td><td>20</td><td>100</td><td>1</td><td>0</td><td>35+</td><td>1</td><td>AP, NUW</td></tr>
<tr><td>Alt 3</td><td>Immolation</td><td>F2</td><td>20</td><td>0</td><td>7</td><td>0</td><td>12+</td><td>1</td><td>AP, NUW</td></tr>
<tr><td>Alt 3</td><td>Cold Resistance</td><td>F2</td><td>20</td><td>15</td><td>1</td><td>0</td><td>0</td><td>1</td><td></td></tr>
<tr><td>Alt 7</td><td>Phoenix Pyre</td><td>F2</td><td>20</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>NUW</td></tr>
<tr><td>Alt 8</td><td>Conflagration</td><td>F2</td><td>20</td><td>30</td><td>10</td><td>100</td><td>0</td><td>1</td><td>NUW</td></tr>
<tr><td>Conj 3</td><td>Phoenix Power</td><td>F2</td><td>20</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>NUW</td></tr>
<tr><td>Conj 4</td><td>Nest of Salamanders</td><td>F2</td><td>100</td><td>0</td><td>0</td><td>0</td><td>0</td><td>10+</td><td>NUW</td></tr>
<tr class="spell-desc"><td colspan="10">Summons Salamander Asp x10+: HP 2, Prot 1, MR 12, Mor 50, Str 2, Att 12, Def 10, Prec 5, Enc 2, CS 6, MM 10, SS, Magic, Mind, NNEat, Stealth 40, Heat pow 1, FR +25, Fire Shield 3 AP dmg, Wpn: Flame Poison Bite</td></tr>
<tr><td>Ench 2</td><td>Ignite Arrows</td><td>F2</td><td>20</td><td>10</td><td>1</td><td>0</td><td>0</td><td>1</td><td>NUW</td></tr>
<tr><td>Ench 3</td><td>Lesser Flame Ward</td><td>F2</td><td>20</td><td>15</td><td>1</td><td>0</td><td>0</td><td>1</td><td></td></tr>
<tr><td>Ench 5</td><td>Flame Ward</td><td>F2</td><td>100</td><td>15</td><td>20+</td><td>0</td><td>0</td><td>1</td><td></td></tr>
<tr><td>Thau 2</td><td>Battle Fury</td><td>F2</td><td>20</td><td>10</td><td>1</td><td>2</td><td>0</td><td>1</td><td>AnimIm, MindIm</td></tr>
<tr><td>Thau 3</td><td>Rage</td><td>F2</td><td>20</td><td>30</td><td>0</td><td>100</td><td>0</td><td>1</td><td>MR, MindIm</td></tr>
<tr><td>Thau 4</td><td>Furious Warriors</td><td>F2</td><td>40</td><td>15</td><td>3+</td><td>2</td><td>0</td><td>1</td><td>AnimIm, MindIm</td></tr>
<tr><td>Thau 8</td><td>Hydrophobia</td><td>F2</td><td>100</td><td>30</td><td>5</td><td>100</td><td>0</td><td>1</td><td>MR, UndIm, InanimIm, MindIm</td></tr>
<tr><td>Evo 2</td><td>Flare</td><td>F3</td><td>50</td><td>45+</td><td>1</td><td>1</td><td>22+</td><td>1</td><td>AP, NUW</td></tr>
<tr><td>Evo 4</td><td>Fire Cloud</td><td>F3A1</td><td>20</td><td>30</td><td>8+</td><td>1</td><td>8</td><td>1</td><td>AP, NUW</td></tr>
<tr><td>Evo 5</td><td>Falling Fires</td><td>F3</td><td>20</td><td>50</td><td>6+</td><td>-3</td><td>15</td><td>1</td><td>AP, NUW</td></tr>
<tr><td>Evo 5</td><td>Hidden Flame</td><td>F3S1</td><td>20</td><td>40+</td><td>1</td><td>0</td><td>25+</td><td>1</td><td>AN, NUW</td></tr>
<tr><td>Alt 5</td><td>Cold Resistant Warriors</td><td>F3</td><td>100</td><td>15</td><td>20+</td><td>0</td><td>0</td><td>1</td><td></td></tr>
<tr><td>Alt 5</td><td>Incinerate</td><td>F3</td><td>20</td><td>30</td><td>0</td><td>100</td><td>18+</td><td>1</td><td>AN</td></tr>
<tr><td>Alt 5</td><td>Solar Eclipse</td><td>F3S1</td><td>100</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>BE, NUW</td></tr>
<tr><td>Alt 6</td><td>Boil</td><td>F3W1</td><td>20</td><td>30</td><td>1</td><td>100</td><td>9+</td><td>1</td><td>AN, UW</td></tr>
<tr><td>Conj 5</td><td>Summon Fire Elemental</td><td>F3</td><td>100</td><td>1</td><td>0</td><td>0</td><td>0</td><td>1</td><td>NUW</td></tr>
<tr class="spell-desc"><td colspan="10">Summons Fire Elemental x1: HP 70, Prot 0, MR 16, Mor 50, Str 18, Att 10, Def 8, Prec 5, Enc 0, CS 10, MM 16, Eth, Spi, Inanim, Magic, Mind, NNEat, Aff Res 99, Heat pow 1, FR +50, CR -5, PR +25, SpSi, Heat 7, Fire Shield 13 AP dmg, Wpn: Flame Strike</td></tr>
<tr><td>Ench 5</td><td>Flaming Arrows</td><td>F3</td><td>100</td><td>15</td><td>20+</td><td>0</td><td>0</td><td>1</td><td>NUW</td></tr>
<tr><td>Thau 4</td><td>Prison of Fire</td><td>F3</td><td>30</td><td>30</td><td>3+</td><td>2</td><td>0</td><td>1</td><td>NUW</td></tr>
<tr><td>Thau 5</td><td>Gift of the Furies</td><td>F3</td><td>100</td><td>15</td><td>20+</td><td>2</td><td>0</td><td>1</td><td>AnimIm, MindIm</td></tr>
<tr><td>Alt 8</td><td>Flameflesh Army</td><td>F4</td><td>200</td><td>0</td><td>BF</td><td>0</td><td>0</td><td>1</td><td></td></tr>
<tr><td>Conj 7</td><td>Living Fire</td><td>F4</td><td>200</td><td>1</td><td>0</td><td>0</td><td>0</td><td>4+</td><td>NUW</td></tr>
<tr class="spell-desc"><td colspan="10">Summons Fire Elemental x4+: HP 53, Prot 0, MR 15, Mor 50, Str 16, Att 10, Def 8, Prec 5, Enc 0, CS 9, MM 16, Eth, Spi, Inanim, Magic, Mind, NNEat, Aff Res 99, Heat pow 1, FR +50, CR -5, PR +25, SpSi, Heat 6, Fire Shield 12 AP dmg, Wpn: Flame Strike</td></tr>
<tr><td>Ench 6</td><td>Heat from Hell</td><td>F4</td><td>200</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>BE, NUW</td></tr>
<tr><td>Ench 7</td><td>Hail of Burning Embers</td><td>F4</td><td>200</td><td>0</td><td>BF</td><td>0</td><td>0</td><td>1</td><td>NUW</td></tr>
<tr><td>Ench 8</td><td>Fire Fend</td><td>F4</td><td>100</td><td>0</td><td>BF</td><td>0</td><td>0</td><td>1</td><td></td></tr>
<tr><td>Evo 7</td><td>Fire Storm</td><td>F5</td><td>300</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>BE, NUW</td></tr>
<tr><td>Evo 9</td><td>Flame Storm</td><td>F5</td><td>100</td><td>40+</td><td>50</td><td>0</td><td>15+</td><td>1</td><td>AP, NUW</td></tr>
<tr><td>Alt 8</td><td>All-consuming Pyre</td><td>F5</td><td>100</td><td>0</td><td>40</td><td>0</td><td>20+</td><td>1</td><td>AP, NUW</td></tr>
</tbody></table>
```

## Air Spells

```{=html}
<table class="table spell-table">
<thead><tr><th>School</th><th>Spell Name</th><th>Path</th><th>Fat</th><th>Rng</th><th>AoE</th><th>Pre</th><th>Dmg</th><th>NoE</th><th>Special</th></tr></thead>
<tbody>
<tr><td>Alt 0</td><td>Air Shield</td><td>A1</td><td>10</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>NUW</td></tr>
<tr><td>Evo 1</td><td>Shocking Grasp</td><td>A1</td><td>3</td><td>1</td><td>0</td><td>0</td><td>18+</td><td>1</td><td>AN</td></tr>
<tr><td>Evo 1</td><td>Gust of Winds</td><td>A1</td><td>10</td><td>35+</td><td>2</td><td>2</td><td>15+</td><td>1</td><td>Mun, NUW</td></tr>
<tr><td>Alt 1</td><td>Charge Body</td><td>A1</td><td>5</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td></td></tr>
<tr><td>Conj 2</td><td>Summon Hawk</td><td>A1</td><td>20</td><td>5</td><td>0</td><td>0</td><td>0</td><td>1</td><td>NUW</td></tr>
<tr class="spell-desc"><td colspan="10">Summons Black Hawk x1: HP 5, Prot 0, MR 5, Mor 8, Str 5, Att 8, Def 12, Prec 8, Enc 3, CS 4, MM 22, FS, MS, Fly, Wpn: Dive attack, Talons</td></tr>
<tr><td>Conj 2</td><td>Summon Storm Power</td><td>A1</td><td>10</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>NUW</td></tr>
<tr><td>Conj 3</td><td>Summon Lesser Air</td><td>A1</td><td>100</td><td>1</td><td>0</td><td>0</td><td>0</td><td>1</td><td>NUW Elemental</td></tr>
<tr class="spell-desc"><td colspan="10">Summons Air Elemental x1: HP 15, Prot 0, MR 13, Mor 50, Str 7, Att 12, Def 12, Prec 5, Enc 0, CS 20, MM 34, Fly, Eth, Spi, Inanim, Magic, Mind, Trample, NNEat, Aff Res 99, Storm Power 2, SR +15, PR +25, SpSi, Wpn: Lightning Swarm</td></tr>
<tr><td>Ench 1</td><td>Levitate</td><td>A1</td><td>20</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>NUW</td></tr>
<tr><td>Ench 1</td><td>Trueshot</td><td>A1</td><td>5</td><td>10</td><td>1</td><td>5</td><td>0</td><td>1</td><td>NUW</td></tr>
<tr><td>Ench 1</td><td>Windrunner</td><td>A1</td><td>10</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>AN</td></tr>
<tr><td>Ench 1</td><td>Protection from Lightning</td><td>A1</td><td>5</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td></td></tr>
<tr><td>Ench 2</td><td>Personal Flight</td><td>A1</td><td>20</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>NUW</td></tr>
<tr><td>Ench 3</td><td>Farflight</td><td>A1</td><td>20</td><td>10</td><td>1</td><td>0</td><td>0</td><td>1</td><td>NUW</td></tr>
<tr><td>Thau 2</td><td>Steal Breath</td><td>A1</td><td>20</td><td>30</td><td>0</td><td>5</td><td>40+</td><td>1</td><td>AN, MR, UndIm, InanimIm, NUW</td></tr>
<tr><td>Evo 2</td><td>Lightning Bolt</td><td>A2</td><td>10</td><td>40+</td><td>0</td><td>4</td><td>14+</td><td>1</td><td>AN</td></tr>
<tr><td>Evo 2</td><td>Shock Wave</td><td>A2</td><td>10</td><td>2</td><td>6</td><td>0</td><td>9+</td><td>1</td><td>AN</td></tr>
<tr><td>Evo 3</td><td>Storm Wind</td><td>A2</td><td>10</td><td>40+</td><td>8+</td><td>3</td><td>17+</td><td>1</td><td>Mun, NUW</td></tr>
<tr><td>Evo 5</td><td>Orb Lightning</td><td>A2</td><td>20</td><td>20</td><td>0</td><td>0</td><td>5</td><td>1</td><td>AN, Chaining 7</td></tr>
<tr><td>Alt 2</td><td>Personal Mistform</td><td>A2</td><td>10</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td></td></tr>
<tr><td>Alt 3</td><td>Protective Winds</td><td>A2</td><td>40</td><td>15</td><td>3+</td><td>0</td><td>0</td><td>1</td><td>NUW</td></tr>
<tr><td>Alt 4</td><td>Lacerating Winds</td><td>A2</td><td>20</td><td>40+</td><td>5+</td><td>1</td><td>5+</td><td>1</td><td>NUW</td></tr>
<tr><td>Alt 4</td><td>Mistform</td><td>A2</td><td>20</td><td>10</td><td>1</td><td>0</td><td>0</td><td>1</td><td></td></tr>
<tr><td>Ench 3</td><td>Arrow of the Western Wind A2</td><td>20</td><td>50+</td><td>0</td><td>25</td><td>20+</td><td>1</td><td>NUW</td><td></td></tr>
<tr><td>Ench 3</td><td>Gift of Flight</td><td>A2</td><td>20</td><td>10</td><td>1</td><td>0</td><td>0</td><td>1</td><td>NUW</td></tr>
<tr><td>Ench 3</td><td>Lesser Thunder Ward</td><td>A2</td><td>20</td><td>15</td><td>1</td><td>0</td><td>0</td><td>1</td><td></td></tr>
<tr><td>Ench 4</td><td>Levitate Soldiers</td><td>A2</td><td>40</td><td>15</td><td>3+</td><td>0</td><td>0</td><td>1</td><td>AN, NUW</td></tr>
<tr><td>Ench 4</td><td>Trueshot Warriors</td><td>A2</td><td>100</td><td>15</td><td>20+</td><td>0</td><td>0</td><td>1</td><td>NUW</td></tr>
<tr><td>Ench 5</td><td>Farflight Arrows</td><td>A2</td><td>100</td><td>15</td><td>20+</td><td>0</td><td>0</td><td>1</td><td>NUW</td></tr>
<tr><td>Ench 5</td><td>Thunder Ward</td><td>A2</td><td>100</td><td>15</td><td>20+</td><td>0</td><td>0</td><td>1</td><td></td></tr>
<tr><td>Evo 4</td><td>Thunder Strike</td><td>A3</td><td>50</td><td>100</td><td>1</td><td>-2</td><td>26+</td><td>1</td><td>AN, NUW</td></tr>
<tr><td>Evo 8</td><td>Chain Lightning</td><td>A3</td><td>30</td><td>25</td><td>0</td><td>0</td><td>6+</td><td>1</td><td>AN, Chaining 20</td></tr>
<tr><td>Alt 3</td><td>Mist</td><td>A3</td><td>100</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>BE, NUW</td></tr>
<tr><td>Alt 5</td><td>Arrow Ward</td><td>A3</td><td>100</td><td>15</td><td>20+</td><td>0</td><td>0</td><td>1</td><td>NUW</td></tr>
<tr><td>Conj 5</td><td>Summon Air Elemental</td><td>A3</td><td>100</td><td>1</td><td>0</td><td>0</td><td>0</td><td>1</td><td>NUW</td></tr>
<tr class="spell-desc"><td colspan="10">Summons Air Elemental x1: HP 48, Prot 0, MR 16, Mor 50, Str 13, Att 15, Def 15, Prec 5, Enc 0, CS 26, MM 34, Fly, Eth, Spi, Inanim, Magic, Mind, Trample, NNEat, Aff Res 99, Storm Power 4, SR +15, PR +25, SpSi, Wpn: Lightning Swarm</td></tr>
<tr><td>Ench 6</td><td>Wind Guide</td><td>A3</td><td>100</td><td>0</td><td>BF</td><td>0</td><td>0</td><td>1</td><td>NUW</td></tr>
<tr><td>Alt 5</td><td>Storm</td><td>A4</td><td>100</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>BE, NUW</td></tr>
<tr><td>Alt 6</td><td>Blizzard</td><td>A4W3</td><td>100</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>BE, NUW</td></tr>
<tr><td>Alt 7</td><td>Arrow Fend</td><td>A4</td><td>100</td><td>0</td><td>BF</td><td>0</td><td>0</td><td>1</td><td>NUW</td></tr>
<tr><td>Alt 7</td><td>Fog Warriors</td><td>A4</td><td>100</td><td>15</td><td>20+</td><td>0</td><td>0</td><td>1</td><td></td></tr>
<tr><td>Conj 7</td><td>Living Clouds</td><td>A4</td><td>200</td><td>1</td><td>0</td><td>0</td><td>0</td><td>4+</td><td>NUW</td></tr>
<tr class="spell-desc"><td colspan="10">Summons Air Elemental x4+: HP 35, Prot 0, MR 15, Mor 50, Str 11, Att 14, Def 14, Prec 5, Enc 0, CS 24, MM 34, Fly, Eth, Spi, Inanim, Magic, Mind, Trample, NNEat, Aff Res 99, Storm Power 3, SR +15, PR +25, SpSi, Wpn: Lightning Swarm</td></tr>
<tr><td>Ench 6</td><td>Greater Farflight</td><td>A4</td><td>100</td><td>0</td><td>BF</td><td>0</td><td>0</td><td>1</td><td>NUW</td></tr>
<tr><td>Ench 7</td><td>Mass Flight</td><td>A4</td><td>100</td><td>15</td><td>20+</td><td>0</td><td>0</td><td>1</td><td>NUW</td></tr>
<tr><td>Ench 8</td><td>Thunder Fend</td><td>A4</td><td>100</td><td>0</td><td>BF</td><td>0</td><td>0</td><td>1</td><td></td></tr>
<tr><td>Evo 6</td><td>Wrathful Skies</td><td>A5</td><td>200</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>BE, NUW</td></tr>
<tr><td>Alt 8</td><td>Army of Mist</td><td>A5</td><td>300</td><td>0</td><td>BF</td><td>0</td><td>0</td><td>1</td><td></td></tr>
<tr><td>Ench 8</td><td>Soaring Army</td><td>A5</td><td>300</td><td>0</td><td>BF</td><td>0</td><td>0</td><td>1</td><td>NUW</td></tr>
<tr><td>Evo 9</td><td>Lightning Field</td><td>A6</td><td>100</td><td>30</td><td>100</td><td>0</td><td>1</td><td>1</td><td>AN, Chaining 8</td></tr>
</tbody></table>
```

## Water Spells

```{=html}
<table class="table spell-table">
<thead><tr><th>School</th><th>Spell Name</th><th>Path</th><th>Fat</th><th>Rng</th><th>AoE</th><th>Pre</th><th>Dmg</th><th>NoE</th><th>Special</th></tr></thead>
<tbody>
<tr><td>Evo 0</td><td>Freezing Touch</td><td>W1</td><td>10</td><td>1</td><td>0</td><td>1</td><td>9+</td><td>1</td><td>AN, NUW</td></tr>
<tr><td>Evo 1</td><td>Slime</td><td>W1</td><td>20</td><td>30+</td><td>1</td><td>2</td><td>0</td><td>1</td><td>MR, NUW</td></tr>
<tr><td>Evo 1</td><td>Water Strike</td><td>W1</td><td>20</td><td>35+</td><td>1</td><td>2</td><td>13+</td><td>1</td><td>UW</td></tr>
<tr><td>Evo 1</td><td>Geyser</td><td>W1F1</td><td>10</td><td>20+</td><td>3</td><td>3</td><td>6+</td><td>1</td><td>AP</td></tr>
<tr><td>Alt 2</td><td>Resist Fire</td><td>W1</td><td>10</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td></td></tr>
<tr><td>Alt 2</td><td>Quicken Self</td><td>W1</td><td>20</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td></td></tr>
<tr><td>Alt 2</td><td>Ice Shield</td><td>W1</td><td>20</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>UW</td></tr>
<tr><td>Alt 4</td><td>Liquid Body</td><td>W1</td><td>20</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>SpiIm</td></tr>
<tr><td>Alt 6</td><td>Frozen Heart</td><td>W1</td><td>20</td><td>25+</td><td>0</td><td>100</td><td>10+</td><td>1</td><td>AN, InanimIm</td></tr>
<tr><td>Conj 2</td><td>Summon Water Power</td><td>W1</td><td>20</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>UW</td></tr>
<tr><td>Conj 3</td><td>Summon Lesser Water</td><td>W1</td><td>100</td><td>1</td><td>0</td><td>0</td><td>0</td><td>1</td><td>Elemental</td></tr>
<tr class="spell-desc"><td colspan="10">Summons Water Elemental x1: HP 27, Prot 0, MR 13, Mor 50, Str 12, Att 10, Def 10, Prec 5, Enc 0, CS 9, MM 16, Spi, Inanim, Magic, Mind, Amph, NNEat, BlR, SlR, PiR, Aff Res 99, FR +5, PR +25, SpSi, Wpn: Crush</td></tr>
<tr><td>Ench 1</td><td>Protection from Cold</td><td>W1</td><td>5</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td></td></tr>
<tr><td>Ench 2</td><td>Water Shield</td><td>W1</td><td>20</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>UW</td></tr>
<tr><td>Ench 2</td><td>Breath of Winter</td><td>W1</td><td>20</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td></td></tr>
<tr><td>Ench 6</td><td>Water Ward</td><td>W1</td><td>100</td><td>15</td><td>25</td><td>0</td><td>0</td><td>1</td><td>UW</td></tr>
<tr><td>Thau 2</td><td>Calm Emotions</td><td>W1</td><td>20</td><td>10</td><td>0</td><td>100</td><td>0</td><td>1</td><td>MR, MindIm</td></tr>
<tr><td>Evo 1</td><td>Cold Bolt</td><td>W2</td><td>20</td><td>50+</td><td>1</td><td>3</td><td>13+</td><td>1</td><td>AP, NUW</td></tr>
<tr><td>Evo 1</td><td>Acid Spray</td><td>W2F1</td><td>20</td><td>2</td><td>5</td><td>0</td><td>10</td><td>1</td><td>AP, NUW</td></tr>
<tr><td>Evo 2</td><td>Cold Blast</td><td>W2</td><td>20</td><td>7+</td><td>3</td><td>0</td><td>12+</td><td>1</td><td>AP, NUW</td></tr>
<tr><td>Evo 3</td><td>Acid Bolt</td><td>W2F1</td><td>30</td><td>35+</td><td>1</td><td>3</td><td>16+</td><td>1</td><td>AP, NUW</td></tr>
<tr><td>Evo 6</td><td>Cleansing Water</td><td>W2</td><td>20</td><td>30+</td><td>5+</td><td>0</td><td>5+</td><td>1</td><td>AN, NUW</td></tr>
<tr><td>Evo 7</td><td>Ice Strike</td><td>W2</td><td>20</td><td>30</td><td>24+</td><td>1</td><td>18</td><td>1</td><td>NUW</td></tr>
<tr><td>Alt 2</td><td>Gooey Water</td><td>W2</td><td>20</td><td>35+</td><td>5+</td><td>2</td><td>0</td><td>1</td><td>MR, UW</td></tr>
<tr><td>Alt 3</td><td>Fire Resistance</td><td>W2</td><td>20</td><td>15</td><td>1</td><td>0</td><td>0</td><td>1</td><td></td></tr>
<tr><td>Alt 3</td><td>Freeze</td><td>W2</td><td>20</td><td>25</td><td>1</td><td>100</td><td>0</td><td>1</td><td></td></tr>
<tr><td>Alt 4</td><td>Quickness</td><td>W2</td><td>20</td><td>15</td><td>1</td><td>1</td><td>0</td><td>1</td><td></td></tr>
<tr><td>Alt 4</td><td>Slow</td><td>W2</td><td>20</td><td>30</td><td>1</td><td>100</td><td>0</td><td>1</td><td>MR</td></tr>
<tr><td>Alt 4</td><td>Encase in Ice</td><td>W2</td><td>20</td><td>25</td><td>1</td><td>100</td><td>0</td><td>1</td><td>UW</td></tr>
<tr><td>Alt 5</td><td>Gift of Formlessness</td><td>W2</td><td>40</td><td>10</td><td>1</td><td>0</td><td>0</td><td>1</td><td>SpiIm</td></tr>
<tr><td>Alt 8</td><td>Quickening</td><td>W2</td><td>100</td><td>20</td><td>9+</td><td>0</td><td>0</td><td>1</td><td></td></tr>
<tr><td>Conj 4</td><td>School of Sharks</td><td>W2</td><td>100</td><td>0</td><td>0</td><td>0</td><td>0</td><td>10+</td><td>UW</td></tr>
<tr class="spell-desc"><td colspan="10">Summons Small Shark x10+: HP 2, Prot 0, MR 4, Mor 30, Str 1, Att 13, Def 12, Prec 5, Enc 3, CS 14, MM 18, Aqua, NNEat, Stealth 40, Wpn: Bite</td></tr>
<tr><td>Ench 3</td><td>Lesser Winter Ward</td><td>W2</td><td>20</td><td>15</td><td>1</td><td>0</td><td>0</td><td>1</td><td></td></tr>
<tr><td>Ench 5</td><td>Winter Ward</td><td>W2</td><td>100</td><td>15</td><td>20+</td><td>0</td><td>0</td><td>1</td><td></td></tr>
<tr><td>Thau 1</td><td>Desiccation</td><td>W2</td><td>20</td><td>30</td><td>1</td><td>100</td><td>0</td><td>1</td><td>AN, MR, UndIm, InanimIm, NUW</td></tr>
<tr><td>Evo 3</td><td>Rain</td><td>W3</td><td>100</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>BE, NUW</td></tr>
<tr><td>Evo 3</td><td>Freezing Mist</td><td>W3A1</td><td>20</td><td>30</td><td>10+</td><td>1</td><td>1</td><td>1</td><td>AN, NUW</td></tr>
<tr><td>Evo 4</td><td>Acid Rain</td><td>W3F1</td><td>30</td><td>30</td><td>6+</td><td>-1</td><td>12</td><td>1</td><td>AP, NUW</td></tr>
<tr><td>Evo 5</td><td>Falling Frost</td><td>W3</td><td>20</td><td>50</td><td>10+</td><td>-2</td><td>10+</td><td>1</td><td>AP, NUW</td></tr>
<tr><td>Alt 5</td><td>Winter&#x27;s Chill</td><td>W3</td><td>20</td><td>25</td><td>5+</td><td>100</td><td>0</td><td>1</td><td></td></tr>
<tr><td>Alt 5</td><td>Fire Resistant Warriors</td><td>W3</td><td>100</td><td>15</td><td>20+</td><td>0</td><td>0</td><td>1</td><td></td></tr>
<tr><td>Alt 5</td><td>Bone Melter</td><td>W3N2</td><td>20</td><td>25</td><td>1</td><td>3</td><td>Death</td><td>1</td><td>Mun, MR, SpiIm</td></tr>
<tr><td>Alt 7</td><td>Prison of Sedna</td><td>W3</td><td>100</td><td>25</td><td>6+</td><td>100</td><td>0</td><td>1</td><td>UW</td></tr>
<tr><td>Alt 7</td><td>Crawl</td><td>W3</td><td>100</td><td>30</td><td>6+</td><td>100</td><td>0</td><td>1</td><td>MR</td></tr>
<tr><td>Alt 7</td><td>Wave Warriors</td><td>W3</td><td>100</td><td>15</td><td>20+</td><td>0</td><td>0</td><td>1</td><td></td></tr>
<tr><td>Conj 5</td><td>Summon Water Elemental W3</td><td>100</td><td>1</td><td>0</td><td>0</td><td>0</td><td>1</td><td></td><td></td></tr>
<tr class="spell-desc"><td colspan="10">Summons Water Elemental x1: HP 81, Prot 0, MR 16, Mor 50, Str 18, Att 13, Def 13, Prec 5, Enc 0, CS 12, MM 16, Spi, Inanim, Magic, Mind, Amph, NNEat, BlR, SlR, PiR, Aff Res 99, FR +10, PR +25, SpSi, Wpn: Crush, Crush, Crush, Crush</td></tr>
<tr><td>Conj 6</td><td>Shark Attack</td><td>W3</td><td>300</td><td>1</td><td>0</td><td>0</td><td>0</td><td>1</td><td>BE, UW</td></tr>
<tr><td>Ench 5</td><td>Friendly Currents</td><td>W3</td><td>100</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>BE, UW</td></tr>
<tr><td>Thau 3</td><td>Sailors&#x27; Death</td><td>W3</td><td>20</td><td>30</td><td>1</td><td>1</td><td>14+</td><td>1</td><td>AN, MR, UndIm, InanimIm, NUW</td></tr>
<tr><td>Thau 4</td><td>Curse of the Desert</td><td>W3</td><td>30</td><td>30</td><td>5</td><td>100</td><td>0</td><td>1</td><td>AN, MR, UndIm, InanimIm, NUW</td></tr>
<tr><td>Thau 5</td><td>Serenity</td><td>W3</td><td>20</td><td>15</td><td>3+</td><td>100</td><td>0</td><td>1</td><td>MR, MindIm</td></tr>
<tr><td>Evo 7</td><td>Acid Storm</td><td>W4F1</td><td>300</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>BE, NUW</td></tr>
<tr><td>Alt 8</td><td>Liquify</td><td>W4</td><td>20</td><td>30</td><td>3</td><td>100</td><td>Death</td><td>1</td><td>MR-, SpiIm</td></tr>
<tr><td>Alt 8</td><td>Frostflesh Army</td><td>W4</td><td>200</td><td>0</td><td>BF</td><td>0</td><td>0</td><td>1</td><td></td></tr>
<tr><td>Conj 7</td><td>Living Water</td><td>W4</td><td>200</td><td>1</td><td>0</td><td>0</td><td>0</td><td>4+</td><td></td></tr>
<tr class="spell-desc"><td colspan="10">Summons Water Elemental x4+: HP 60, Prot 0, MR 15, Mor 50, Str 16, Att 12, Def 12, Prec 5, Enc 0, CS 11, MM 16, Spi, Inanim, Magic, Mind, Amph, NNEat, BlR, SlR, PiR, Aff Res 99, FR +10, PR +25, SpSi, Wpn: Crush, Crush, Crush</td></tr>
<tr><td>Ench 5</td><td>Quagmire</td><td>W4</td><td>100</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>BE, NUW</td></tr>
<tr><td>Ench 6</td><td>Grip of Winter</td><td>W4</td><td>200</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>BE</td></tr>
<tr><td>Ench 8</td><td>Frost Fend</td><td>W4</td><td>100</td><td>0</td><td>BF</td><td>0</td><td>0</td><td>1</td><td></td></tr>
<tr><td>Evo 9</td><td>Niefel Flames</td><td>W5</td><td>100</td><td>40+</td><td>75+</td><td>0</td><td>12+</td><td>1</td><td>AP, NUW</td></tr>
<tr><td>Ench 9</td><td>Demon Cleansing</td><td>W5</td><td>100</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>BE</td></tr>
</tbody></table>
```

## Earth Spells

```{=html}
<table class="table spell-table">
<thead><tr><th>School</th><th>Spell Name</th><th>Path</th><th>Fat</th><th>Rng</th><th>AoE</th><th>Pre</th><th>Dmg</th><th>NoE</th><th>Special</th></tr></thead>
<tbody>
<tr><td>Evo 0</td><td>Flying Shards</td><td>E1</td><td>30</td><td>30+</td><td>0</td><td>0</td><td>7+</td><td>4+</td><td>Mun, NUW</td></tr>
<tr><td>Evo 3</td><td>Magma Bolts</td><td>E1F1</td><td>20</td><td>30+</td><td>0</td><td>2</td><td>25+</td><td>5</td><td>NUW</td></tr>
<tr><td>Alt 1</td><td>Fists of Iron</td><td>E1</td><td>20</td><td>1</td><td>0</td><td>100</td><td>15</td><td>1+</td><td></td></tr>
<tr><td>Alt 1</td><td>Earth Grip</td><td>E1</td><td>10</td><td>20</td><td>0</td><td>5</td><td>0</td><td>1</td><td></td></tr>
<tr><td>Alt 2</td><td>Resist Lightning</td><td>E1</td><td>10</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td></td></tr>
<tr><td>Alt 2</td><td>Personal Stoneskin</td><td>E1</td><td>10</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>SpiIm</td></tr>
<tr><td>Alt 2</td><td>Armor of Achilles</td><td>E1</td><td>40</td><td>15</td><td>1</td><td>3</td><td>10</td><td>1</td><td>AN</td></tr>
<tr><td>Alt 3</td><td>Personal Ironskin</td><td>E1</td><td>20</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>SpiIm</td></tr>
<tr><td>Alt 4</td><td>Temper Flesh</td><td>E1</td><td>20</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>SpiIm</td></tr>
<tr><td>Conj 3</td><td>Summon Lesser Earth</td><td>E1</td><td>100</td><td>1</td><td>0</td><td>0</td><td>0</td><td>1</td><td>Elemental</td></tr>
<tr class="spell-desc"><td colspan="10">Summons Earth Elemental x1: HP 33, Prot 12, MR 13, Mor 50, Str 13, Att 10, Def 10, Prec 3, Enc 0, CS 9, MM 16, Inanim, Magic, Mind, Trample, Amph, NNEat, Aff Res 4, Reconstruction 10%, PR +25, SpSi, Wpn: Crystal Fist</td></tr>
<tr><td>Ench 2</td><td>Flying Shield</td><td>E1A1</td><td>20</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>NUW</td></tr>
<tr><td>Thau 3</td><td>Iron Will</td><td>E1</td><td>20</td><td>25</td><td>1</td><td>100</td><td>0</td><td>1</td><td>MindIm</td></tr>
<tr><td>Evo 2</td><td>Rust Mist</td><td>E2W1</td><td>30</td><td>30</td><td>9+</td><td>0</td><td>0</td><td>1</td><td>NUW</td></tr>
<tr><td>Evo 6</td><td>Magma Eruption</td><td>E2F2</td><td>50</td><td>30</td><td>6+</td><td>0</td><td>22+</td><td>1</td><td></td></tr>
<tr><td>Alt 3</td><td>Lightning Resistance</td><td>E2</td><td>20</td><td>15</td><td>1</td><td>0</td><td>0</td><td>1</td><td></td></tr>
<tr><td>Alt 3</td><td>Earth Meld</td><td>E2</td><td>60</td><td>25</td><td>5</td><td>3</td><td>0</td><td>1</td><td></td></tr>
<tr><td>Alt 4</td><td>Stoneskin</td><td>E2</td><td>20</td><td>15</td><td>1</td><td>0</td><td>0</td><td>1</td><td>SpiIm</td></tr>
<tr><td>Alt 5</td><td>Ironskin</td><td>E2</td><td>40</td><td>10</td><td>1</td><td>2</td><td>0</td><td>1</td><td>SpiIm</td></tr>
<tr><td>Conj 3</td><td>Summon Earthpower</td><td>E2</td><td>20</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td></td></tr>
<tr><td>Ench 1</td><td>Strength of Giants</td><td>E2</td><td>20</td><td>5</td><td>1</td><td>0</td><td>0</td><td>1</td><td></td></tr>
<tr><td>Ench 3</td><td>Gift of Giant Strength</td><td>E2</td><td>40</td><td>15</td><td>3+</td><td>0</td><td>0</td><td>1</td><td></td></tr>
<tr><td>Ench 4</td><td>Earth Shatter Hammers</td><td>E2</td><td>40</td><td>15</td><td>1</td><td>0</td><td>0</td><td>1</td><td></td></tr>
<tr><td>Ench 4</td><td>Shroud of Flying Shards</td><td>E2A1</td><td>20</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>NUW</td></tr>
<tr><td>Thau 1</td><td>Farstrike</td><td>E2S1</td><td>5</td><td>50</td><td>0</td><td>5</td><td>17+</td><td>1</td><td></td></tr>
<tr><td>Evo 4</td><td>Blade Wind</td><td>E3</td><td>80</td><td>35+</td><td>0</td><td>0</td><td>14</td><td>50+</td><td>Mun, NUW</td></tr>
<tr><td>Evo 5</td><td>Gifts from Heaven</td><td>E3S1</td><td>50</td><td>100</td><td>1</td><td>-3</td><td>150</td><td>3</td><td>NUW</td></tr>
<tr><td>Evo 7</td><td>Rain of Stones</td><td>E3A1</td><td>100</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>Mun, BE, NUW</td></tr>
<tr><td>Alt 4</td><td>Destruction</td><td>E3</td><td>40</td><td>30</td><td>6</td><td>3</td><td>5</td><td>1</td><td>AN</td></tr>
<tr><td>Alt 4</td><td>Curse of Stones</td><td>E3</td><td>300</td><td>0</td><td>BF</td><td>0</td><td>0</td><td>1</td><td>MR-</td></tr>
<tr><td>Alt 5</td><td>Group Stoneskin</td><td>E3</td><td>40</td><td>15</td><td>3+</td><td>0</td><td>0</td><td>1</td><td>SpiIm</td></tr>
<tr><td>Alt 5</td><td>Lightning Resistant</td><td>E3</td><td>100</td><td>15</td><td>20+</td><td>0</td><td>0</td><td>1</td><td>Warriors</td></tr>
<tr><td>Alt 5</td><td>Maws of the Earth</td><td>E3</td><td>100</td><td>30+</td><td>7+</td><td>3</td><td>15+</td><td>1</td><td>AP</td></tr>
<tr><td>Alt 5</td><td>Shatter</td><td>E3</td><td>20</td><td>15</td><td>0</td><td>100</td><td>35+</td><td>1</td><td>AN</td></tr>
<tr><td>Alt 6</td><td>Group Ironskin</td><td>E3</td><td>60</td><td>15</td><td>3+</td><td>2</td><td>0</td><td>1</td><td>SpiIm</td></tr>
<tr><td>Alt 6</td><td>Iron Bane</td><td>E3</td><td>100</td><td>0</td><td>BF</td><td>0</td><td>0</td><td>1</td><td></td></tr>
<tr><td>Alt 7</td><td>Marble Warriors</td><td>E3</td><td>100</td><td>15</td><td>20+</td><td>0</td><td>0</td><td>1</td><td>SpiIm</td></tr>
<tr><td>Conj 5</td><td>Summon Earth Elemental</td><td>E3</td><td>100</td><td>1</td><td>0</td><td>0</td><td>0</td><td>1</td><td></td></tr>
<tr class="spell-desc"><td colspan="10">Summons Earth Elemental x1: HP 93, Prot 14, MR 16, Mor 50, Str 22, Att 10, Def 10, Prec 3, Enc 0, CS 12, MM 16, Inanim, Magic, Mind, Trample, Amph, NNEat, Aff Res 4, Reconstruction 7%, PR +25, SpSi, Wpn: Crystal Fist, Crystal Fist</td></tr>
<tr><td>Ench 5</td><td>Giant Strength Warriors</td><td>E3</td><td>100</td><td>15</td><td>20+</td><td>0</td><td>0</td><td>1</td><td></td></tr>
<tr><td>Ench 5</td><td>Weapons of Sharpness</td><td>E3</td><td>40</td><td>15</td><td>1</td><td>0</td><td>0</td><td>1</td><td></td></tr>
<tr><td>Evo 5</td><td>Earthquake</td><td>E4</td><td>300</td><td>0</td><td>BF</td><td>0</td><td>8</td><td>1</td><td>Mun, AP, NUW</td></tr>
<tr><td>Alt 8</td><td>Iron Warriors</td><td>E4</td><td>200</td><td>15</td><td>20+</td><td>2</td><td>0</td><td>1</td><td>SpiIm</td></tr>
<tr><td>Alt 8</td><td>Marble Army</td><td>E4</td><td>300</td><td>0</td><td>BF</td><td>0</td><td>0</td><td>1</td><td>SpiIm</td></tr>
<tr><td>Alt 8</td><td>Ground Army</td><td>E4</td><td>200</td><td>0</td><td>BF</td><td>0</td><td>0</td><td>1</td><td></td></tr>
<tr><td>Conj 7</td><td>Living Earth</td><td>E4</td><td>200</td><td>1</td><td>0</td><td>0</td><td>0</td><td>4+</td><td></td></tr>
<tr class="spell-desc"><td colspan="10">Summons Earth Elemental x4+: HP 70, Prot 13, MR 16, Mor 50, Str 19, Att 10, Def 10, Prec 3, Enc 0, CS 11, MM 16, Inanim, Magic, Mind, Trample, Amph, NNEat, Aff Res 4, Reconstruction 8%, PR +25, SpSi, Wpn: Crystal Fist</td></tr>
<tr><td>Ench 6</td><td>Earthquake Warriors</td><td>E4</td><td>100</td><td>15</td><td>20+</td><td>0</td><td>0</td><td>1</td><td></td></tr>
<tr><td>Ench 7</td><td>Steel Slice Warriors</td><td>E4</td><td>100</td><td>15</td><td>20+</td><td>0</td><td>0</td><td>1</td><td></td></tr>
<tr><td>Evo 8</td><td>Meteor Shower</td><td>E5S4</td><td>300</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>BE, NUW</td></tr>
<tr><td>Alt 6</td><td>Petrify</td><td>E5</td><td>40</td><td>30</td><td>1</td><td>100</td><td>Death</td><td>1</td><td>AN, SpiIm</td></tr>
<tr><td>Alt 9</td><td>Army of Gold</td><td>E5F1</td><td>300</td><td>0</td><td>BF</td><td>0</td><td>0</td><td>1</td><td>SpiIm</td></tr>
<tr><td>Alt 9</td><td>Army of Lead</td><td>E5S1</td><td>300</td><td>0</td><td>BF</td><td>0</td><td>0</td><td>1</td><td>SpiIm</td></tr>
<tr><td>Ench 9</td><td>Earth Shatter Army</td><td>E5</td><td>200</td><td>0</td><td>BF</td><td>0</td><td>0</td><td>1</td><td></td></tr>
<tr><td>Alt 9</td><td>Army of Bronze</td><td>E6</td><td>300</td><td>0</td><td>BF</td><td>0</td><td>0</td><td>1</td><td>SpiIm</td></tr>
</tbody></table>
```

## Astral Spells

```{=html}
<table class="table spell-table">
<thead><tr><th>School</th><th>Spell Name</th><th>Path</th><th>Fat</th><th>Rng</th><th>AoE</th><th>Pre</th><th>Dmg</th><th>NoE</th><th>Special</th></tr></thead>
<tbody>
<tr><td>Alt 0</td><td>Twist Fate</td><td>S1</td><td>10</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td></td></tr>
<tr><td>Evo 1</td><td>Star Fires</td><td>S1</td><td>20</td><td>35</td><td>0</td><td>2</td><td>5+</td><td>3</td><td>AN, NUW</td></tr>
<tr><td>Evo 3</td><td>Magic Duel</td><td>S1</td><td>100</td><td>100</td><td>0</td><td>100</td><td>Death</td><td>1</td><td>AN, MindIm</td></tr>
<tr><td>Evo 3</td><td>Healing Light</td><td>S1N1</td><td>20</td><td>30+</td><td>1</td><td>100</td><td>15</td><td>1</td><td>AN, UndIm, InanimIm,</td></tr>
<tr class="spell-desc"><td colspan="10">MindIm, NUW</td></tr>
<tr><td>Evo 4</td><td>Nether Bolt</td><td>S1D1</td><td>15</td><td>35+</td><td>1</td><td>2</td><td>20+</td><td>1</td><td>AP, MR+</td></tr>
<tr><td>Evo 7</td><td>Nether Darts</td><td>S1D1</td><td>15</td><td>30+</td><td>0</td><td>0</td><td>15+</td><td>15+</td><td>AP, MR+</td></tr>
<tr><td>Alt 2</td><td>Gift of Cheated Fate</td><td>S1</td><td>20</td><td>10</td><td>1</td><td>0</td><td>0</td><td>1</td><td></td></tr>
<tr><td>Alt 3</td><td>Body Ethereal</td><td>S1</td><td>30</td><td>10</td><td>1</td><td>0</td><td>0</td><td>1</td><td></td></tr>
<tr><td>Conj 3</td><td>Power of the Spheres</td><td>S1</td><td>100</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td></td></tr>
<tr><td>Ench 1</td><td>Resist Magic</td><td>S1</td><td>20</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td></td></tr>
<tr><td>Ench 3</td><td>Astral Shield</td><td>S1</td><td>20</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td></td></tr>
<tr><td>Ench 3</td><td>Second Sight</td><td>S1D1</td><td>20</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td></td></tr>
<tr><td>Thau 1</td><td>Blink</td><td>S1</td><td>10</td><td>0</td><td>0</td><td>0</td><td>30</td><td>1</td><td></td></tr>
<tr><td>Thau 1</td><td>Communion Master</td><td>S1</td><td>20</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td></td></tr>
<tr><td>Thau 1</td><td>Communion Slave</td><td>S1</td><td>20</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td></td></tr>
<tr><td>Evo 1</td><td>Arcane Bolt</td><td>S2</td><td>20</td><td>40+</td><td>1</td><td>3</td><td>10+</td><td>1</td><td>AN</td></tr>
<tr><td>Evo 2</td><td>Solar Rays</td><td>S2</td><td>20</td><td>40+</td><td>1</td><td>100</td><td>14+</td><td>1</td><td>AP, NUW</td></tr>
<tr><td>Evo 5</td><td>Stellar Cascades</td><td>S2</td><td>20</td><td>35</td><td>7</td><td>100</td><td>25</td><td>1</td><td>AP, NUW</td></tr>
<tr><td>Ench 4</td><td>Spell Ward</td><td>S2</td><td>100</td><td>15</td><td>20+</td><td>0</td><td>0</td><td>1</td><td></td></tr>
<tr><td>Thau 1</td><td>Horror Mark</td><td>S2</td><td>20</td><td>50</td><td>0</td><td>100</td><td>0</td><td>1</td><td>MindIm</td></tr>
<tr><td>Thau 2</td><td>Returning</td><td>S2</td><td>200</td><td>0</td><td>0</td><td>0</td><td>1</td><td>1</td><td>AN</td></tr>
<tr><td>Thau 2</td><td>Mind Burn</td><td>S2</td><td>20</td><td>100</td><td>0</td><td>100</td><td>12+</td><td>1</td><td>AN, MR, MindIm</td></tr>
<tr><td>Thau 4</td><td>Paralyze</td><td>S2</td><td>20</td><td>100</td><td>0</td><td>100</td><td>60+</td><td>1</td><td>AN, MR, MindIm</td></tr>
<tr><td>Evo 5</td><td>Astral Geyser</td><td>S3</td><td>20</td><td>50+</td><td>1</td><td>0</td><td>0</td><td>1</td><td>AN, MindIm</td></tr>
<tr><td>Alt 6</td><td>Control</td><td>S3</td><td>100</td><td>25</td><td>0</td><td>100</td><td>0</td><td>1</td><td>AN, MR</td></tr>
<tr><td>Conj 4</td><td>Light of the Northern Star</td><td>S3</td><td>200</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>BE</td></tr>
<tr><td>Ench 4</td><td>Astral Healing</td><td>S3</td><td>100</td><td>0</td><td>BF</td><td>0</td><td>2</td><td>1</td><td>AN, InanimIm, MindIm</td></tr>
<tr><td>Ench 5</td><td>Gift of Spirit Sight</td><td>S3D1</td><td>20</td><td>15</td><td>1</td><td>0</td><td>0</td><td>1</td><td></td></tr>
<tr><td>Ench 6</td><td>Opposition</td><td>S3</td><td>20</td><td>25</td><td>0</td><td>100</td><td>Death</td><td>1</td><td>MR</td></tr>
<tr><td>Ench 7</td><td>Antimagic</td><td>S3</td><td>200</td><td>0</td><td>BF</td><td>0</td><td>0</td><td>1</td><td></td></tr>
<tr><td>Thau 5</td><td>Soul Slay</td><td>S3</td><td>20</td><td>100</td><td>0</td><td>100</td><td>Death</td><td>1</td><td>AN, MR, MindIm</td></tr>
<tr><td>Evo 6</td><td>Astral Fires</td><td>S4F1</td><td>20</td><td>45+</td><td>1</td><td>100</td><td>10</td><td>1</td><td>AN, MR+</td></tr>
<tr><td>Alt 6</td><td>Rewrite Fate</td><td>S4</td><td>100</td><td>15</td><td>20+</td><td>5</td><td>0</td><td>1</td><td></td></tr>
<tr><td>Alt 7</td><td>Doom</td><td>S4</td><td>100</td><td>0</td><td>BF</td><td>0</td><td>0</td><td>1</td><td></td></tr>
<tr><td>Thau 6</td><td>Enslave Mind</td><td>S4</td><td>20</td><td>100</td><td>0</td><td>100</td><td>0</td><td>1</td><td>AN, MR, MindIm</td></tr>
<tr><td>Thau 7</td><td>Vortex of Returning</td><td>S4</td><td>300</td><td>0</td><td>BF</td><td>0</td><td>1</td><td>1</td><td>AN</td></tr>
<tr><td>Evo 8</td><td>Astral Tempest</td><td>S5</td><td>200</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>BE</td></tr>
<tr><td>Alt 7</td><td>Will of the Fates</td><td>S5</td><td>200</td><td>0</td><td>BF</td><td>0</td><td>0</td><td>1</td><td></td></tr>
<tr><td>Ench 7</td><td>Solar Brilliance</td><td>S5</td><td>300</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>BE, NUW</td></tr>
<tr><td>Thau 8</td><td>Soul Drain</td><td>S5D5</td><td>500</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>MindIm, BE</td></tr>
<tr><td>Alt 9</td><td>Time Stop</td><td>S6</td><td>100</td><td>0</td><td>0</td><td>0</td><td>104</td><td>1</td><td>MR</td></tr>
<tr><td>Ench 8</td><td>Unraveling</td><td>S6</td><td>600</td><td>0</td><td>BF</td><td>0</td><td>0</td><td>1</td><td>MR</td></tr>
<tr><td>Alt 8</td><td>Arcane Domination</td><td>S7</td><td>700</td><td>0</td><td>BF</td><td>0</td><td>0</td><td>1</td><td>AN, MR-</td></tr>
<tr><td>Thau 9</td><td>Master Enslave</td><td>S8</td><td>800</td><td>0</td><td>BF</td><td>0</td><td>0</td><td>1</td><td>AN, MR-, MindIm</td></tr>
</tbody></table>
```

## Death Spells

```{=html}
<table class="table spell-table">
<thead><tr><th>School</th><th>Spell Name</th><th>Path</th><th>Fat</th><th>Rng</th><th>AoE</th><th>Pre</th><th>Dmg</th><th>NoE</th><th>Special</th></tr></thead>
<tbody>
<tr><td>Alt 0</td><td>Hand of Dust</td><td>D1</td><td>10</td><td>1</td><td>0</td><td>0</td><td>6+</td><td>1</td><td>AN</td></tr>
<tr><td>Evo 4</td><td>Bane Fire Dart</td><td>D1F1</td><td>20</td><td>30+</td><td>0</td><td>4</td><td>15+</td><td>1</td><td>AP, NUW</td></tr>
<tr><td>Alt 1</td><td>Skeletal Body</td><td>D1</td><td>20</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>SpiIm</td></tr>
<tr><td>Alt 2</td><td>Weakness</td><td>D1</td><td>20</td><td>25</td><td>0</td><td>3</td><td>3</td><td>1</td><td>AN, MR</td></tr>
<tr><td>Alt 4</td><td>Stygian Skin</td><td>D1W1</td><td>20</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>InanimIm, SpiIm</td></tr>
<tr><td>Conj 1</td><td>Spirit Curse</td><td>D1</td><td>100</td><td>50</td><td>0</td><td>100</td><td>0</td><td>1</td><td></td></tr>
<tr><td>Conj 5</td><td>Ghost Grip</td><td>D1</td><td>10</td><td>25</td><td>0</td><td>3</td><td>25+</td><td>5</td><td></td></tr>
<tr><td>Conj 5</td><td>Corpse Candle</td><td>D1F1</td><td>100</td><td>0</td><td>0</td><td>0</td><td>0</td><td>3</td><td>NUW</td></tr>
<tr class="spell-desc"><td colspan="10">Summons Corpse Candle x3: HP 4, Prot 0, MR 13, Mor 50, Str 4, Att 19, Def 19, Prec 5, Enc 0, CS 20, MM 22, SS, Float, Eth, Spi, Magic, Mind, NNEat, PR +15, SpSi, Wpn: Bane Burst</td></tr>
<tr><td>Ench 1</td><td>Animate Skeleton</td><td>D1</td><td>30</td><td>5</td><td>0</td><td>-2</td><td>0</td><td>1</td><td></td></tr>
<tr class="spell-desc"><td colspan="10">Summons Longdead x1: HP 5, Prot 8, MR 9, Mor 50, Str 10, Att 11, Def 11, Prec 10, Enc 0, CS 8, MM 20, Inanim, Und, Mind, PAmph, NNEat, PiR, CR +15, PR +25, SpSi, Wpn: Spear</td></tr>
<tr><td>Ench 1</td><td>Animate Dead</td><td>D1</td><td>20</td><td>5</td><td>0</td><td>-2</td><td>0</td><td>1</td><td></td></tr>
<tr><td>Thau 1</td><td>Dust to Dust</td><td>D1</td><td>20</td><td>30</td><td>1</td><td>0</td><td>22+</td><td>1</td><td>AN</td></tr>
<tr><td>Thau 1</td><td>Decay</td><td>D1</td><td>20</td><td>25</td><td>0</td><td>3</td><td>0</td><td>1</td><td>MR</td></tr>
<tr><td>Thau 1</td><td>Frighten</td><td>D1</td><td>5</td><td>50</td><td>1</td><td>5</td><td>5</td><td>1</td><td>AN</td></tr>
<tr><td>Evo 3</td><td>Shadow Bolt</td><td>D2</td><td>20</td><td>35+</td><td>1</td><td>3</td><td>7+</td><td>1</td><td>AN, UndIm</td></tr>
<tr><td>Evo 4</td><td>Bolt of Unlife</td><td>D2</td><td>20</td><td>30+</td><td>1</td><td>1</td><td>15+</td><td>1</td><td>AN, MR, UndIm, MindIm</td></tr>
<tr><td>Evo 5</td><td>Shadow Blast</td><td>D2</td><td>100</td><td>35+</td><td>9+</td><td>0</td><td>8+</td><td>1</td><td>AN, UndIm</td></tr>
<tr><td>Alt 1</td><td>Hand of Death</td><td>D2</td><td>5</td><td>1</td><td>0</td><td>0</td><td>40+</td><td>1</td><td>AN</td></tr>
<tr><td>Alt 5</td><td>Enfeeble</td><td>D2</td><td>100</td><td>25</td><td>6+</td><td>3</td><td>2</td><td>1</td><td>AN, MR</td></tr>
<tr><td>Alt 8</td><td>Disintegrate</td><td>D2</td><td>10</td><td>30</td><td>0</td><td>100</td><td>Death</td><td>1</td><td>AN, MR</td></tr>
<tr><td>Conj 4</td><td>Summon Lammashtas</td><td>D2</td><td>100</td><td>0</td><td>0</td><td>0</td><td>0</td><td>2</td><td></td></tr>
<tr class="spell-desc"><td colspan="10">Summons Lammashta x2: HP 15, Prot 0, MR 15, Mor 30, Str 13, Att 13, Def 16, Prec 13, Enc 0, CS 12, MM 22, Fly, Eth, Und, Amph, CR +15, PR +25, Fear +5, SpSi, Invulnerability 20, Wpn: Wraith Sword</td></tr>
<tr><td>Ench 3</td><td>Raise Skeletons</td><td>D2</td><td>40</td><td>5</td><td>0</td><td>-2</td><td>0</td><td>3</td><td></td></tr>
<tr class="spell-desc"><td colspan="10">Summons Longdead x3: HP 5, Prot 0, MR 9, Mor 50, Str 10, Att 11, Def 9, Prec 10, Enc 0, CS 11, MM 22, Inanim, Und, Mind, PAmph, NNEat, PiR, CR +15, PR +25, SpSi, Wpn: Spear</td></tr>
<tr><td>Ench 4</td><td>Raise Dead</td><td>D2</td><td>40</td><td>5</td><td>0</td><td>-2</td><td>0</td><td>10+</td><td></td></tr>
<tr><td>Ench 5</td><td>Horde of Skeletons</td><td>D2</td><td>40</td><td>5</td><td>0</td><td>-2</td><td>0</td><td>5+</td><td></td></tr>
<tr class="spell-desc"><td colspan="10">Summons Longdead x5+: HP 5, Prot 8, MR 9, Mor 50, Str 10, Att 11, Def 12, Prec 10, Enc 0, CS 8, MM 20, Inanim, Und, Mind, PAmph, NNEat, PiR, CR +15, PR +25, SpSi, Wpn: Broad Sword</td></tr>
<tr><td>Thau 5</td><td>Control the Dead</td><td>D2</td><td>20</td><td>25</td><td>1</td><td>0</td><td>0</td><td>1</td><td>AN, MR</td></tr>
<tr><td>Evo 6</td><td>Blast of Unlife</td><td>D3</td><td>20</td><td>30+</td><td>2</td><td>0</td><td>20+</td><td>1</td><td>AN, MR, UndIm, MindIm</td></tr>
<tr><td>Evo 6</td><td>Bane Fire</td><td>D3F1</td><td>20</td><td>45+</td><td>1</td><td>1</td><td>55+</td><td>1</td><td>AP</td></tr>
<tr><td>Evo 7</td><td>Stygian Rains</td><td>D3W2</td><td>200</td><td>0</td><td>BF</td><td>0</td><td>0</td><td>1</td><td>InanimIm, NUW</td></tr>
<tr><td>Alt 5</td><td>Invulnerability</td><td>D3</td><td>20</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td></td></tr>
<tr><td>Alt 6</td><td>Soul Vortex</td><td>D3</td><td>40</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td></td></tr>
<tr><td>Thau 4</td><td>Terror</td><td>D3</td><td>20</td><td>30</td><td>5+</td><td>1</td><td>0</td><td>1</td><td>AN</td></tr>
<tr><td>Thau 5</td><td>Leeching Darkness</td><td>D3</td><td>20</td><td>30</td><td>3+</td><td>1</td><td>0</td><td>1</td><td>AP, MR, NUW</td></tr>
<tr><td>Thau 6</td><td>Wither Bones</td><td>D3</td><td>50</td><td>30</td><td>6+</td><td>-1</td><td>16+</td><td>1</td><td>AN</td></tr>
<tr><td>Evo 7</td><td>Cloud of Death</td><td>D4A1</td><td>20</td><td>30</td><td>15+</td><td>-3</td><td>1192+</td><td>1</td><td>AN, MR, UndIm, NUW</td></tr>
<tr><td>Evo 7</td><td>Wind of Death</td><td>D4A1</td><td>100</td><td>0</td><td>BF</td><td>0</td><td>0</td><td>1</td><td>MR-, NUW</td></tr>
<tr><td>Alt 5</td><td>Drain Life</td><td>D4</td><td>10</td><td>30</td><td>0</td><td>100</td><td>14+</td><td>1</td><td>AN, InanimIm</td></tr>
<tr><td>Alt 6</td><td>Skeletal Legion</td><td>D4</td><td>100</td><td>0</td><td>BF</td><td>0</td><td>0</td><td>1</td><td></td></tr>
<tr><td>Alt 6</td><td>Darkness</td><td>D4</td><td>400</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>BE, NUW</td></tr>
<tr><td>Ench 6</td><td>Rigor Mortis</td><td>D4</td><td>300</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>AN, MR+, UndIm, InanimIm, BE</td></tr>
<tr><td>Ench 7</td><td>Life after Death</td><td>D4</td><td>400</td><td>0</td><td>BF</td><td>0</td><td>0</td><td>1</td><td>MindIm</td></tr>
<tr><td>Thau 7</td><td>Plague</td><td>D4</td><td>100</td><td>25</td><td>1</td><td>0</td><td>0</td><td>1</td><td>MR, UndIm, InanimIm</td></tr>
<tr><td>Evo 8</td><td>Vortex of Unlife</td><td>D5</td><td>20</td><td>30+</td><td>8+</td><td>0</td><td>16+</td><td>1</td><td>AN, MR, UndIm, MindIm</td></tr>
<tr><td>Ench 8</td><td>Fields of the Dead</td><td>D5E2</td><td>200</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>BE</td></tr>
<tr><td>Alt 7</td><td>Bone Grinding</td><td>D7</td><td>100</td><td>0</td><td>BF</td><td>0</td><td>3</td><td>1</td><td>Mun, AN</td></tr>
<tr><td>Thau 8</td><td>Undead Mastery</td><td>D7</td><td>700</td><td>0</td><td>BF</td><td>0</td><td>0</td><td>1</td><td>AN, MR-</td></tr>
</tbody></table>
```

## Nature Spells

```{=html}
<table class="table spell-table">
<thead><tr><th>School</th><th>Spell Name</th><th>Path</th><th>Fat</th><th>Rng</th><th>AoE</th><th>Pre</th><th>Dmg</th><th>NoE</th><th>Special</th></tr></thead>
<tbody>
<tr><td>Alt 0</td><td>Poison Touch</td><td>N1</td><td>5</td><td>1</td><td>0</td><td>0</td><td>10+</td><td>1</td><td>AN</td></tr>
<tr><td>Evo 1</td><td>Vine Arrow</td><td>N1</td><td>20</td><td>30+</td><td>0</td><td>0</td><td>14+</td><td>1</td><td>NUW</td></tr>
<tr><td>Evo 2</td><td>Web</td><td>N1</td><td>20</td><td>25+</td><td>3</td><td>2</td><td>0</td><td>1</td><td>Mun</td></tr>
<tr><td>Evo 3</td><td>Poison Darts</td><td>N1</td><td>20</td><td>30+</td><td>0</td><td>3</td><td>9</td><td>5+</td><td>AP, NUW</td></tr>
<tr><td>Alt 1</td><td>Eagle Eyes</td><td>N1</td><td>5</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td></td></tr>
<tr><td>Alt 1</td><td>Cat Eyes</td><td>N1</td><td>5</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td></td></tr>
<tr><td>Alt 1</td><td>Personal Poison Resistance N1</td><td>5</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td></td><td></td></tr>
<tr><td>Alt 1</td><td>Personal Barkskin</td><td>N1</td><td>5</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>SpiIm</td></tr>
<tr><td>Alt 3</td><td>Gift of Cat Eyes</td><td>N1</td><td>20</td><td>15</td><td>2+</td><td>0</td><td>0</td><td>1</td><td></td></tr>
<tr><td>Alt 3</td><td>Barkskin</td><td>N1</td><td>20</td><td>10</td><td>1</td><td>100</td><td>0</td><td>1</td><td>SpiIm</td></tr>
<tr><td>Alt 3</td><td>Animate Tree</td><td>N1</td><td>20</td><td>10</td><td>1</td><td>100</td><td>0</td><td>1</td><td>InanimIm, NUW</td></tr>
<tr><td>Alt 3</td><td>Mossbody</td><td>N1W1</td><td>20</td><td>10</td><td>1</td><td>0</td><td>0</td><td>1</td><td>SpiIm</td></tr>
<tr><td>Alt 4</td><td>Elemental Fortitude</td><td>N1</td><td>10</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td></td></tr>
<tr><td>Conj 1</td><td>Tangle Vines</td><td>N1</td><td>20</td><td>20</td><td>1</td><td>2</td><td>0</td><td>1</td><td></td></tr>
<tr><td>Conj 4</td><td>Maggots</td><td>N1</td><td>100</td><td>25</td><td>0</td><td>100</td><td>50</td><td>1</td><td>Mun, AN</td></tr>
<tr><td>Ench 1</td><td>Protection from Poison</td><td>N1</td><td>5</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td></td></tr>
<tr><td>Ench 1</td><td>Healing Touch</td><td>N1</td><td>20</td><td>1</td><td>1</td><td>1</td><td>30+</td><td>1</td><td>AN, InanimIm</td></tr>
<tr><td>Ench 2</td><td>Proud Steed</td><td>N1</td><td>20</td><td>10</td><td>1</td><td>2</td><td>0</td><td>1</td><td>Anim, Mount, MindIm</td></tr>
<tr><td>Ench 2</td><td>Gift of the Hare</td><td>N1</td><td>20</td><td>15</td><td>1+</td><td>0</td><td>0</td><td>1</td><td>AN</td></tr>
<tr><td>Ench 2</td><td>Envenom Arrows</td><td>N1</td><td>20</td><td>10</td><td>1</td><td>0</td><td>0</td><td>1</td><td>NUW</td></tr>
<tr><td>Ench 2</td><td>Gift of the Serpent</td><td>N1</td><td>20</td><td>15</td><td>1</td><td>0</td><td>0</td><td>1</td><td></td></tr>
<tr><td>Ench 3</td><td>Heal</td><td>N1</td><td>20</td><td>15</td><td>1</td><td>5</td><td>30+</td><td>1</td><td>AN, InanimIm</td></tr>
<tr><td>Thau 1</td><td>Seven Year Fever</td><td>N1F1</td><td>30</td><td>25</td><td>1</td><td>2</td><td>0</td><td>1</td><td>MR, UndIm, InanimIm</td></tr>
<tr><td>Thau 2</td><td>Beast Fury</td><td>N1</td><td>20</td><td>10</td><td>1</td><td>2</td><td>0</td><td>1</td><td>Anim, MindIm</td></tr>
<tr><td>Thau 4</td><td>Touch of Madness</td><td>N1</td><td>30</td><td>20</td><td>1</td><td>0</td><td>0</td><td>1</td><td>AN, InanimIm, MindIm</td></tr>
<tr><td>Evo 4</td><td>Breath of the Dragon</td><td>N2</td><td>20</td><td>20+</td><td>4+</td><td>-1</td><td>7+</td><td>1</td><td>AN, NUW</td></tr>
<tr><td>Evo 5</td><td>Poison Arrows</td><td>N2</td><td>20</td><td>35+</td><td>0</td><td>3</td><td>15+</td><td>4+</td><td>NUW</td></tr>
<tr><td>Evo 7</td><td>Storm of Thorns</td><td>N2</td><td>20</td><td>35+</td><td>0</td><td>0</td><td>15+</td><td>10+</td><td>NUW</td></tr>
<tr><td>Alt 2</td><td>Enlarge</td><td>N2</td><td>20</td><td>10</td><td>1</td><td>0</td><td>0</td><td>1</td><td>SpiIm</td></tr>
<tr><td>Alt 3</td><td>Torpor</td><td>N2</td><td>20</td><td>35</td><td>1</td><td>100</td><td>20+</td><td>1</td><td>AN, MR, UndIm, InanimIm, MindIm</td></tr>
<tr><td>Alt 4</td><td>Group Barkskin</td><td>N2</td><td>40</td><td>15</td><td>3+</td><td>100</td><td>0</td><td>1</td><td>SpiIm</td></tr>
<tr><td>Alt 4</td><td>Swarm</td><td>N2</td><td>100</td><td>0</td><td>0</td><td>0</td><td>0</td><td>20+</td><td></td></tr>
<tr class="spell-desc"><td colspan="10">Summons Large Beetle x20+: HP 1, Prot 1, MR 3, Mor 50, Str 1, Att 14, Def 12, Prec 10, Enc 5, CS 6, MM 20, FS, Fly, Magic, Mind, NNEat, Stealth 40, Wpn: Tiny Sting</td></tr>
<tr><td>Alt 4</td><td>Shrink</td><td>N2</td><td>20</td><td>20+</td><td>1</td><td>0</td><td>0</td><td>1</td><td>MR, SpiIm</td></tr>
<tr><td>Alt 5</td><td>Blood Poisoning</td><td>N2</td><td>20</td><td>30</td><td>0</td><td>100</td><td>15+</td><td>1</td><td>AN</td></tr>
<tr><td>Alt 6</td><td>Venomous Death</td><td>N2D1</td><td>20</td><td>30</td><td>0</td><td>100</td><td>25+</td><td>1</td><td>AN</td></tr>
<tr><td>Alt 7</td><td>Curse of the Frog Prince</td><td>N2</td><td>20</td><td>25</td><td>0</td><td>100</td><td>0</td><td>1</td><td>MR, UndIm, InanimIm,</td></tr>
<tr class="spell-desc"><td colspan="10">SpiIm, MindIm</td></tr>
<tr><td>Conj 4</td><td>Nest of Asps</td><td>N2D1</td><td>100</td><td>0</td><td>0</td><td>0</td><td>0</td><td>10+</td><td>NUW</td></tr>
<tr class="spell-desc"><td colspan="10">Summons Asp x10+: HP 2, Prot 1, MR 4, Mor 50, Str 2, Att 12, Def 10, Prec 5, Enc 2, CS 6, MM 10, SS, Magic, Mind, NNEat, Stealth 40, Wpn: Asp Bite</td></tr>
<tr><td>Ench 2</td><td>Personal Regeneration</td><td>N2</td><td>20</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>InanimIm</td></tr>
<tr><td>Ench 4</td><td>Immaculate Mounts</td><td>N2</td><td>20</td><td>10</td><td>3+</td><td>2</td><td>0</td><td>1</td><td>Anim, Mount, MindIm</td></tr>
<tr><td>Ench 4</td><td>Poison Ward</td><td>N2</td><td>100</td><td>15</td><td>20+</td><td>0</td><td>0</td><td>1</td><td></td></tr>
<tr><td>Thau 3</td><td>Panic</td><td>N2</td><td>20</td><td>30</td><td>5+</td><td>1</td><td>1</td><td>1</td><td>AN</td></tr>
<tr><td>Thau 4</td><td>Ferocity</td><td>N2</td><td>20</td><td>15</td><td>3+</td><td>2</td><td>0</td><td>1</td><td>Anim, MindIm</td></tr>
<tr><td>Thau 4</td><td>Rage of the Cornered Rat</td><td>N2</td><td>20</td><td>20</td><td>3+</td><td>0</td><td>0</td><td>1</td><td>AN, Anim</td></tr>
<tr><td>Thau 5</td><td>Charm Animal</td><td>N2</td><td>20</td><td>20</td><td>0</td><td>100</td><td>0</td><td>1</td><td>MR-, Anim</td></tr>
<tr><td>Thau 5</td><td>Pack Ferocity</td><td>N2</td><td>100</td><td>15</td><td>20+</td><td>2</td><td>0</td><td>1</td><td>Anim, MindIm</td></tr>
<tr><td>Conj 4</td><td>Tangle Thicket</td><td>N2</td><td>30</td><td>20</td><td>3+</td><td>2</td><td>0</td><td>1</td><td></td></tr>
<tr><td>Evo 5</td><td>Poison Cloud</td><td>N3A1</td><td>20</td><td>30</td><td>6+</td><td>-1</td><td>64</td><td>1</td><td>AN</td></tr>
<tr><td>Evo 6</td><td>Stream of Life</td><td>N3</td><td>20</td><td>40+</td><td>1</td><td>2</td><td>40+</td><td>1</td><td>AN, MR, UndIm, InanimIm</td></tr>
<tr><td>Evo 7</td><td>Poison Mist</td><td>N3A1</td><td>40</td><td>30</td><td>15+</td><td>-1</td><td>64</td><td>1</td><td>AN</td></tr>
<tr><td>Alt 6</td><td>Eagle-eyed Warriors</td><td>N3</td><td>100</td><td>15</td><td>20+</td><td>0</td><td>0</td><td>1</td><td></td></tr>
<tr><td>Alt 5</td><td>Cat-eyed Warriors</td><td>N3</td><td>100</td><td>15</td><td>20+</td><td>0</td><td>0</td><td>1</td><td></td></tr>
<tr><td>Alt 6</td><td>Wooden Warriors</td><td>N3</td><td>100</td><td>15</td><td>20+</td><td>0</td><td>0</td><td>1</td><td>SpiIm</td></tr>
<tr><td>Alt 6</td><td>Giant Warriors</td><td>N3</td><td>100</td><td>10</td><td>10</td><td>0</td><td>0</td><td>1</td><td>SpiIm</td></tr>
<tr><td>Alt 7</td><td>Creeping Doom</td><td>N3</td><td>100</td><td>0</td><td>0</td><td>0</td><td>0</td><td>70+</td><td>NUW</td></tr>
<tr class="spell-desc"><td colspan="10">Summons Large Spider x70+: HP 1, Prot 1, MR 3, Mor 50, Str 1, Att 8, Def 10, Prec 4, Enc 2, CS 4, MM 10, FS, Magic, Mind, NNEat, Stealth 40, PR +15, Wpn: Sting</td></tr>
<tr><td>Alt 8</td><td>Polymorph</td><td>N3</td><td>200</td><td>25</td><td>10+</td><td>5</td><td>0</td><td>1</td><td>MR, UndIm, InanimIm,</td></tr>
<tr class="spell-desc"><td colspan="10">SpiIm, MindIm</td></tr>
<tr><td>Conj 4</td><td>Strength of Gaia</td><td>N3E1</td><td>20</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td></td></tr>
<tr><td>Conj 5</td><td>Howl</td><td>N3</td><td>300</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>BE, NUW</td></tr>
<tr><td>Ench 3</td><td>Regeneration</td><td>N3</td><td>40</td><td>15</td><td>1</td><td>0</td><td>0</td><td>1</td><td>InanimIm</td></tr>
<tr><td>Ench 4</td><td>Haste</td><td>N3</td><td>100</td><td>15</td><td>20+</td><td>0</td><td>0</td><td>1</td><td>AN, InanimIm</td></tr>
<tr><td>Ench 4</td><td>Serpent Fang Arrows</td><td>N3</td><td>100</td><td>15</td><td>20+</td><td>0</td><td>0</td><td>1</td><td>NUW</td></tr>
<tr><td>Ench 5</td><td>Group Regeneration</td><td>N3</td><td>60</td><td>15</td><td>3+</td><td>0</td><td>0</td><td>1</td><td>InanimIm</td></tr>
<tr><td>Thau 4</td><td>Wildness</td><td>N3</td><td>20</td><td>30</td><td>1</td><td>3</td><td>0</td><td>1</td><td>MR, Anim</td></tr>
<tr><td>Thau 5</td><td>The Ravenous Swarm</td><td>N3</td><td>100</td><td>1</td><td>0</td><td>0</td><td>0</td><td>1</td><td>BE, NUW</td></tr>
<tr><td>Alt 7</td><td>Oaken Army</td><td>N4</td><td>300</td><td>0</td><td>BF</td><td>0</td><td>0</td><td>1</td><td>SpiIm</td></tr>
<tr><td>Conj 8</td><td>Wild Growth</td><td>N4</td><td>40</td><td>20</td><td>10+</td><td>0</td><td>0</td><td>1</td><td></td></tr>
<tr><td>Ench 6</td><td>Hail of Serpent Fangs</td><td>N4</td><td>200</td><td>0</td><td>BF</td><td>0</td><td>0</td><td>1</td><td>NUW</td></tr>
<tr><td>Ench 6</td><td>Foul Vapors</td><td>N4W1</td><td>200</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>BE</td></tr>
<tr><td>Ench 7</td><td>Mass Regeneration</td><td>N4</td><td>100</td><td>15</td><td>20+</td><td>0</td><td>0</td><td>1</td><td>InanimIm</td></tr>
<tr><td>Ench 7</td><td>Serpent&#x27;s Blessing</td><td>N4</td><td>200</td><td>0</td><td>BF</td><td>0</td><td>0</td><td>1</td><td></td></tr>
<tr><td>Thau 6</td><td>Growing Fury</td><td>N4</td><td>100</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>BE</td></tr>
<tr><td>Thau 7</td><td>Fury of the Wild</td><td>N4</td><td>200</td><td>0</td><td>BF</td><td>0</td><td>0</td><td>1</td><td>Anim, MindIm</td></tr>
<tr><td>Alt 8</td><td>Army of Giants</td><td>N5</td><td>300</td><td>0</td><td>BF</td><td>0</td><td>0</td><td>1</td><td>SpiIm</td></tr>
<tr><td>Alt 9</td><td>Army of Rats</td><td>N5</td><td>400</td><td>0</td><td>BF</td><td>0</td><td>0</td><td>1</td><td>MR+, SpiIm</td></tr>
<tr><td>Alt 9</td><td>Awaken Forest</td><td>N5</td><td>200</td><td>0</td><td>BF</td><td>100</td><td>0</td><td>1</td><td>InanimIm, NUW</td></tr>
<tr><td>Ench 6</td><td>Relief</td><td>N5</td><td>100</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>BE</td></tr>
<tr><td>Ench 8</td><td>Army Regeneration</td><td>N5</td><td>300</td><td>0</td><td>BF</td><td>0</td><td>0</td><td>1</td><td>InanimIm</td></tr>
<tr><td>Ench 9</td><td>Gaia&#x27;s Blessing</td><td>N5E2</td><td>300</td><td>0</td><td>BF</td><td>0</td><td>0</td><td>1</td><td></td></tr>
<tr><td>Thau 9</td><td>Beast Mastery</td><td>N6</td><td>400</td><td>0</td><td>BF</td><td>0</td><td>0</td><td>1</td><td>AN, MR-, Anim</td></tr>
</tbody></table>
```

## Glamour Spells

```{=html}
<table class="table spell-table">
<thead><tr><th>School</th><th>Spell Name</th><th>Path</th><th>Fat</th><th>Rng</th><th>AoE</th><th>Pre</th><th>Dmg</th><th>NoE</th><th>Special</th></tr></thead>
<tbody>
<tr><td>Thau 0</td><td>Sleep Ray</td><td>G1</td><td>20</td><td>1</td><td>1</td><td>0</td><td>0</td><td>1</td><td>AN, MR, UndIm, InanimIm, MindIm</td></tr>
<tr><td>Evo 1</td><td>Bewitching Lights</td><td>G1</td><td>20</td><td>30</td><td>3</td><td>1</td><td>100</td><td>1</td><td>AN, MR-, MindIm, NUW</td></tr>
<tr><td>Evo 2</td><td>Warrior Illusion</td><td>G1</td><td>10</td><td>5</td><td>0</td><td>0</td><td>0</td><td>1</td><td></td></tr>
<tr class="spell-desc"><td colspan="10">Summons Warrior Illusion x1: HP 1, Prot 0, MR 10, Mor 50, Str 10, Att 10, Def 10, Prec 10, Enc 0, CS 12, MM 22, Eth, Illu, Inanim, Mind, Amph, NNEat, PR +25, SpSi, Wpn: Phantasmal Weapon</td></tr>
<tr><td>Evo 3</td><td>False Fire</td><td>G1F1</td><td>20</td><td>30+</td><td>1</td><td>1</td><td>14+</td><td>1</td><td>AP, MR, NUW</td></tr>
<tr><td>Evo 3</td><td>Elf Shot</td><td>G1N1</td><td>20</td><td>30+</td><td>0</td><td>4</td><td>100</td><td>1</td><td>AN, MR, NUW</td></tr>
<tr><td>Alt 1</td><td>Blurred Body</td><td>G1</td><td>10</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>AN</td></tr>
<tr><td>Alt 2</td><td>Mirror Image</td><td>G1</td><td>10</td><td>0</td><td>0</td><td>0</td><td>2+</td><td>1</td><td>AN</td></tr>
<tr><td>Alt 2</td><td>Blur</td><td>G1</td><td>20</td><td>20</td><td>1</td><td>0</td><td>0</td><td>1</td><td>AN</td></tr>
<tr><td>Conj 3</td><td>Conjure Phantasmal</td><td>G1</td><td>100</td><td>5</td><td>0</td><td>0</td><td>0</td><td>2</td><td>Wolves</td></tr>
<tr class="spell-desc"><td colspan="10">Summons Phantasmal Wolf x2: HP 11, Prot 0, MR 12, Mor 14, Str 11, Att 14, Def 12, Prec 5, Enc 2, CS 26, MM 26, FS, MS, Eth, Magic, NNEat, TrSi, Wpn: Phantasmal Bite</td></tr>
<tr><td>Conj 6</td><td>Summon Sprites</td><td>G1N1</td><td>100</td><td>1</td><td>0</td><td>0</td><td>0</td><td>6</td><td>NUW</td></tr>
<tr class="spell-desc"><td colspan="10">Summons Sprite x6: HP 2, Prot 0, MR 14, Mor 7, Str 3, Att 14, Def 19, Prec 14, Enc 1, CS 10, MM 22, FS, SS, Fly, Glamour, Magic, NNEat, Stealth 65, TrSi, Wpn: Fist, Elf Shot</td></tr>
<tr><td>Ench 1</td><td>True Sight</td><td>G1</td><td>5</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td></td></tr>
<tr><td>Ench 2</td><td>Shroud of Splendor</td><td>G1F1</td><td>10</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>AN</td></tr>
<tr><td>Ench 3</td><td>Gift of True Sight</td><td>G1</td><td>20</td><td>10</td><td>1</td><td>0</td><td>0</td><td>1</td><td>NUW</td></tr>
<tr><td>Ench 6</td><td>Steal Sight</td><td>G1</td><td>20</td><td>20</td><td>0</td><td>100</td><td>0</td><td>1</td><td>MR</td></tr>
<tr><td>Thau 1</td><td>Fascination</td><td>G1</td><td>20</td><td>15</td><td>0</td><td>100</td><td>100</td><td>1</td><td>AN, MR, MindIm</td></tr>
<tr><td>Thau 1</td><td>Personal Luck</td><td>G1</td><td>20</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>UndIm, InanimIm</td></tr>
<tr><td>Thau 1</td><td>Curse</td><td>G1S1</td><td>30</td><td>50</td><td>0</td><td>100</td><td>0</td><td>1</td><td></td></tr>
<tr><td>Thau 3</td><td>Luck</td><td>G1</td><td>20</td><td>10</td><td>1</td><td>2</td><td>0</td><td>1</td><td>UndIm, InanimIm</td></tr>
<tr><td>Thau 4</td><td>Mind Blank</td><td>G1S1</td><td>20</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td></td></tr>
<tr><td>Evo 2</td><td>Ephemeral Bolt</td><td>G2</td><td>10</td><td>35+</td><td>1</td><td>2</td><td>4+</td><td>1</td><td>AN, MR</td></tr>
<tr><td>Evo 3</td><td>Dance of Ephemeral</td><td>G2</td><td>10</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>AN Swords</td></tr>
<tr><td>Evo 3</td><td>Cloud of Dreamless</td><td>G2A1</td><td>20</td><td>30</td><td>3+</td><td>3</td><td>4346+</td><td>1</td><td>AN, MR, UndIm, InanimIm,</td></tr>
<tr class="spell-desc"><td colspan="10">Slumber                                                                                        MindIm</td></tr>
<tr><td>Alt 3</td><td>Displace Body</td><td>G2</td><td>10</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>AN</td></tr>
<tr><td>Alt 3</td><td>Group Blur</td><td>G2</td><td>40</td><td>20</td><td>3+</td><td>0</td><td>0</td><td>1</td><td>AN</td></tr>
<tr><td>Alt 6</td><td>Gift of Displacement</td><td>G2</td><td>20</td><td>10</td><td>1</td><td>0</td><td>0</td><td>1</td><td>AN</td></tr>
<tr><td>Conj 4</td><td>Conjure Phantasmal</td><td>G2</td><td>100</td><td>5</td><td>0</td><td>0</td><td>0</td><td>2</td><td>Warriors</td></tr>
<tr class="spell-desc"><td colspan="10">Summons Phantasmal Warrior x2: HP 14, Prot 9, MR 14, Mor 13, Str 12, Att 13, Def 17, Prec 13, Enc 3, CS 11, MM 20, Eth, Magic, NNEat, TrSi, Wpn: Phantasmal Weapon</td></tr>
<tr><td>Conj 7</td><td>Conjure Phantasmal Knight G2</td><td>100</td><td>5</td><td>0</td><td>0</td><td>0</td><td>1</td><td></td><td></td></tr>
<tr class="spell-desc"><td colspan="10">Summons Phantasmal Knight x1: HP 15, Prot 17, MR 14, Mor 14, Str 12, Att 14, Def 20, Prec 13, Enc 3, CS 12, MM 20, Eth, Magic, NNEat, TrSi, Rider 3, Wpn: Phantasmal Lance, Phantasmal Weapon, Mount: Phantasmal Steed</td></tr>
<tr><td>Ench 1</td><td>False Fetters</td><td>G2</td><td>10</td><td>15</td><td>2+</td><td>0</td><td>0</td><td>1</td><td>MR</td></tr>
<tr><td>Ench 3</td><td>Shroud of Bewilderment</td><td>G2</td><td>20</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>AN</td></tr>
<tr><td>Ench 3</td><td>Horrible Visage</td><td>G2D1</td><td>10</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>AN</td></tr>
<tr><td>Ench 4</td><td>Gift of Splendor</td><td>G2F1</td><td>20</td><td>10</td><td>1</td><td>0</td><td>0</td><td>1</td><td>AN</td></tr>
<tr><td>Thau 2</td><td>Sleep</td><td>G2</td><td>20</td><td>35</td><td>0</td><td>100</td><td>0</td><td>1</td><td>AN, MR, UndIm, InanimIm, MindIm</td></tr>
<tr><td>Thau 3</td><td>Despair</td><td>G2</td><td>10</td><td>30</td><td>5+</td><td>1</td><td>4</td><td>1</td><td>AN, MR</td></tr>
<tr><td>Thau 4</td><td>Slumber</td><td>G2</td><td>20</td><td>35</td><td>3+</td><td>100</td><td>0</td><td>1</td><td>AN, MR, UndIm, InanimIm, MindIm</td></tr>
<tr><td>Thau 5</td><td>Confusion</td><td>G2</td><td>10</td><td>30</td><td>1</td><td>3</td><td>0</td><td>1</td><td>MR, MindIm</td></tr>
<tr><td>Thau 5</td><td>Group Luck</td><td>G2</td><td>40</td><td>15</td><td>3+</td><td>2</td><td>0</td><td>1</td><td>UndIm, InanimIm</td></tr>
<tr><td>Thau 6</td><td>Mirror Mind</td><td>G2S1</td><td>20</td><td>15</td><td>3+</td><td>0</td><td>0</td><td>1</td><td></td></tr>
<tr><td>Evo 4</td><td>Ephemeral Blast</td><td>G3</td><td>10</td><td>40+</td><td>4+</td><td>2</td><td>7+</td><td>1</td><td>AN, MR</td></tr>
<tr><td>Evo 4</td><td>Ghost Wolves</td><td>G3</td><td>10</td><td>5</td><td>0</td><td>0</td><td>0</td><td>2</td><td></td></tr>
<tr class="spell-desc"><td colspan="10">Summons Wolf Illusion x2: HP 1, Prot 0, MR 10, Mor 50, Str 9, Att 10, Def 10, Prec 10, Enc 0, CS 26, MM 22, Eth, Illu, Inanim, Mind, Amph, NNEat, PR +25, SpSi, Wpn: Phantasmal Bite</td></tr>
<tr><td>Evo 5</td><td>Illusory Army</td><td>G3</td><td>100</td><td>3+</td><td>0</td><td>0</td><td>0</td><td>20+</td><td></td></tr>
<tr class="spell-desc"><td colspan="10">Summons Warrior Illusion x20+: HP 1, Prot 0, MR 10, Mor 50, Str 10, Att 10, Def 10, Prec 10, Enc 0, CS 12, MM 22, Eth, Illu, Inanim, Mind, Amph, NNEat, PR +25, SpSi, Wpn: Phantasmal Weapon</td></tr>
<tr><td>Evo 6</td><td>False Horror</td><td>G3</td><td>10</td><td>5</td><td>0</td><td>0</td><td>0</td><td>1</td><td></td></tr>
<tr class="spell-desc"><td colspan="10">Summons False Horror x1: HP 1, Prot 0, MR 10, Mor 50, Str 10, Att 10, Def 13, Prec 10, Enc 0, CS 4, MM 22, Float, Eth, Illu, Inanim, Mind, Amph, NNEat, PR +25, Fear +5, SpSi, Wpn: Phantasmal Claw, Phantasmal Claw</td></tr>
<tr><td>Alt 4</td><td>Twilight</td><td>G3</td><td>100</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>BE, NUW</td></tr>
<tr><td>Alt 5</td><td>Nightfall</td><td>G3</td><td>100</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>BE, NUW</td></tr>
<tr><td>Alt 5</td><td>Shadow Warriors</td><td>G3</td><td>100</td><td>20</td><td>20+</td><td>0</td><td>0</td><td>1</td><td>AN</td></tr>
<tr><td>Alt 6</td><td>Invisibility</td><td>G3</td><td>10</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>AN</td></tr>
<tr><td>Ench 6</td><td>Fay-eyed Warriors</td><td>G3</td><td>100</td><td>15</td><td>20+</td><td>0</td><td>0</td><td>1</td><td>NUW</td></tr>
<tr><td>Conj 5</td><td>Conjure Phantasmal Beast G3</td><td>100</td><td>5</td><td>0</td><td>0</td><td>0</td><td>1</td><td></td><td></td></tr>
<tr class="spell-desc"><td colspan="10">Summons Phantasmal Beast x1: HP 62, Prot 6, MR 15, Mor 15, Str 19, Att 14, Def 12, Prec 10, Enc 2, CS 18, MM 20, Eth, Magic, Amph, NNEat, TrSi, Wpn: Phantasmal Claw, Phantasmal Claw, Phantasmal Claw, Phantasmal Claw, Phantasmal Bite</td></tr>
<tr><td>Ench 6</td><td>Aura of Splendor</td><td>G3F1</td><td>40</td><td>15</td><td>5+</td><td>0</td><td>0</td><td>1</td><td>AN</td></tr>
<tr><td>Thau 4</td><td>Visions of Death</td><td>G3</td><td>20</td><td>35+</td><td>0</td><td>100</td><td>25+</td><td>1</td><td>AN, MR</td></tr>
<tr><td>Thau 6</td><td>Unending Nightmare</td><td>G3D1</td><td>20</td><td>35</td><td>3+</td><td>100</td><td>0</td><td>1</td><td>AN, MR, UndIm, InanimIm, MindIm</td></tr>
<tr><td>Thau 7</td><td>Charm</td><td>G3</td><td>30</td><td>25</td><td>0</td><td>100</td><td>0</td><td>1</td><td>AN, MR, MindIm</td></tr>
<tr><td>Thau 7</td><td>Mass Confusion</td><td>G3</td><td>10</td><td>30</td><td>5+</td><td>3</td><td>0</td><td>1</td><td>MR, MindIm</td></tr>
<tr><td>Evo 7</td><td>Wailing Winds</td><td>G4A1</td><td>200</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>BE, NUW</td></tr>
<tr><td>Alt 7</td><td>Army of Shades</td><td>G4</td><td>200</td><td>0</td><td>BF</td><td>0</td><td>0</td><td>1</td><td>AN</td></tr>
<tr><td>Alt 8</td><td>Displaced Warriors</td><td>G4</td><td>100</td><td>15</td><td>20+</td><td>0</td><td>0</td><td>1</td><td>AN</td></tr>
<tr><td>Ench 7</td><td>Aura of Bewilderment</td><td>G4</td><td>100</td><td>15</td><td>5+</td><td>0</td><td>0</td><td>1</td><td>AN</td></tr>
<tr><td>Ench 7</td><td>Nightmare Masks</td><td>G4D1</td><td>100</td><td>15</td><td>5+</td><td>0</td><td>0</td><td>1</td><td>AN</td></tr>
<tr><td>Ench 7</td><td>Warriors of the Dawn</td><td>G4F1</td><td>100</td><td>20</td><td>20+</td><td>0</td><td>0</td><td>1</td><td>AN</td></tr>
<tr><td>Thau 8</td><td>Battle Fortune</td><td>G4</td><td>200</td><td>15</td><td>20+</td><td>5</td><td>0</td><td>1</td><td>UndIm, InanimIm</td></tr>
<tr><td>Evo 7</td><td>Shimmering Fields</td><td>G5</td><td>200</td><td>25</td><td>50</td><td>0</td><td>9+</td><td>1</td><td>AN, MR</td></tr>
<tr><td>Evo 8</td><td>Aurora Borealis</td><td>G5S1</td><td>200</td><td>1</td><td>1</td><td>-1</td><td>0</td><td>1</td><td>BE, NUW</td></tr>
<tr><td>Ench 8</td><td>Mists of Deception</td><td>G5A1</td><td>200</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>BE, NUW</td></tr>
<tr><td>Thau 6</td><td>Sandman&#x27;s Blessing</td><td>G5</td><td>20</td><td>30</td><td>25</td><td>0</td><td>0</td><td>1</td><td>AN, MR, UndIm, InanimIm, MindIm</td></tr>
<tr><td>Thau 9</td><td>Dreamwild Legion</td><td>G5</td><td>400</td><td>0</td><td>BF</td><td>0</td><td>0</td><td>1</td><td>UndIm, InanimIm</td></tr>
<tr><td>Thau 9</td><td>Legion&#x27;s Demise</td><td>G7</td><td>400</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>AN, MR-, BE</td></tr>
</tbody></table>
```

## Blood Spells

```{=html}
<table class="table spell-table">
<thead><tr><th>School</th><th>Spell Name</th><th>Path</th><th>Fat</th><th>Rng</th><th>AoE</th><th>Pre</th><th>Dmg</th><th>NoE</th><th>Special</th></tr></thead>
<tbody>
<tr><td>Blood 0</td><td>Bleed</td><td>B1</td><td>100</td><td>30+</td><td>0</td><td>0</td><td>0</td><td>1</td><td>AN, MR, UndIm, InanimIm, NUW</td></tr>
<tr><td>Blood 1</td><td>Blood Burst</td><td>B1</td><td>200</td><td>35</td><td>1</td><td>5</td><td>11+</td><td>1</td><td>AN, UndIm, InanimIm, NUW</td></tr>
<tr><td>Blood 1</td><td>Blood Heal</td><td>B1</td><td>100</td><td>0</td><td>0</td><td>3</td><td>50</td><td>1</td><td>AN, UndIm, InanimIm, NUW</td></tr>
<tr><td>Blood 1</td><td>Sabbath Master</td><td>B1</td><td>100</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>NUW</td></tr>
<tr><td>Blood 1</td><td>Sabbath Slave</td><td>B1</td><td>100</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>NUW</td></tr>
<tr><td>Blood 1</td><td>Reinvigoration</td><td>B1</td><td>100</td><td>0</td><td>0</td><td>0</td><td>200</td><td>1</td><td>AN, NUW</td></tr>
<tr><td>Blood 1</td><td>Summon Imps</td><td>B1</td><td>100</td><td>1</td><td>0</td><td>0</td><td>0</td><td>5</td><td>NUW</td></tr>
<tr class="spell-desc"><td colspan="10">Summons Imp x5: HP 8, Prot 6, MR 13, Mor 9, Str 9, Att 11, Def 15, Prec 10, Enc 1, CS 7, MM 22, Fly, Demon, NNEat, FR +15, CR -5, Wpn: Claws</td></tr>
<tr><td>Blood 1</td><td>Blood Boil</td><td>B1F1</td><td>50</td><td>25</td><td>0</td><td>100</td><td>11+</td><td>1</td><td>AN, MR, UndIm, InanimIm</td></tr>
<tr><td>Blood 2</td><td>Banish Demon</td><td>B1</td><td>100</td><td>30</td><td>0</td><td>100</td><td>Death</td><td>1</td><td>MR, UndIm, NUW</td></tr>
<tr><td>Blood 3</td><td>Leeching Touch</td><td>B1</td><td>20</td><td>1</td><td>0</td><td>0</td><td>15+</td><td>1</td><td>AN, InanimIm</td></tr>
<tr><td>Blood 4</td><td>Hellfire</td><td>B1F2</td><td>100</td><td>25+</td><td>3</td><td>0</td><td>9+</td><td>2</td><td>AP, NUW</td></tr>
<tr><td>Blood 7</td><td>Leech</td><td>B1</td><td>100</td><td>30</td><td>1</td><td>25</td><td>25+</td><td>1</td><td>AN, InanimIm, NUW</td></tr>
<tr><td>Blood 8</td><td>Damage Reversal</td><td>B1</td><td>100</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>NUW</td></tr>
<tr><td>Blood 6</td><td>Soul Transaction</td><td>B1G1</td><td>100</td><td>20</td><td>0</td><td>100</td><td>0</td><td>1</td><td>AN, MR+, MindIm, NUW</td></tr>
<tr><td>Blood 2</td><td>Agony</td><td>B2</td><td>100</td><td>40</td><td>4+</td><td>2</td><td>1</td><td>1</td><td>AN, MR, UndIm, InanimIm, NUW</td></tr>
<tr><td>Blood 3</td><td>Pain Transfer</td><td>B2</td><td>20</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>NUW</td></tr>
<tr><td>Blood 4</td><td>Blood Lust</td><td>B2</td><td>100</td><td>0</td><td>BF</td><td>0</td><td>0</td><td>1</td><td>UndIm, NUW</td></tr>
<tr><td>Blood 4</td><td>Call Lesser Horror</td><td>B2S2</td><td>200</td><td>5</td><td>0</td><td>-2</td><td>0</td><td>1</td><td>NUW</td></tr>
<tr class="spell-desc"><td colspan="10">Summons Tainted Soul x1: HP 5, Prot 0, MR 15, Mor 50, Str 10, Att 18, Def 18, Prec 5, Enc 0, CS 20, MM 22, SS, Float, Eth, Spi, Magic, Mind, Amph, NNEat, Magic Power 1, PR +15, SpSi, Void Sanity 20, Wpn: Life Draining Flare</td></tr>
<tr><td>Blood 5</td><td>Hellbind Heart</td><td>B2</td><td>100</td><td>30</td><td>0</td><td>100</td><td>0</td><td>1</td><td>AN, MR, MindIm, NUW</td></tr>
<tr><td>Blood 5</td><td>Summon Illearth</td><td>B2E2</td><td>200</td><td>1</td><td>0</td><td>0</td><td>0</td><td>1</td><td>NUW</td></tr>
<tr class="spell-desc"><td colspan="10">Summons Illearth x1: HP 93, Prot 12, MR 16, Mor 50, Str 22, Att 10, Def 10, Prec 0, Enc 0, CS 12, MM 16, Inanim, Magic, Mind, Trample, Amph, NNEat, Reconstruction 9%, PR +25, SpSi, Wpn: Crystal Fist, Crystal Fist</td></tr>
<tr><td>Blood 6</td><td>Harm</td><td>B2</td><td>100</td><td>50</td><td>4+</td><td>5</td><td>2+</td><td>1</td><td>AN, MR, InanimIm, NUW</td></tr>
<tr><td>Blood 2</td><td>Hell Power</td><td>B3</td><td>300</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>NUW</td></tr>
<tr><td>Blood 6</td><td>Blood Rain</td><td>B3</td><td>300</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>BE, NUW</td></tr>
<tr><td>Blood 6</td><td>Call Horror</td><td>B3S3</td><td>300</td><td>5</td><td>0</td><td>-2</td><td>0</td><td>1</td><td>NUW</td></tr>
<tr class="spell-desc"><td colspan="10">Summons Mind Slime Horror x1: HP 28, Prot 10, MR 20, Mor 30, Str 14, Att 18, Def 16, Prec 10, Enc 0, CS 6, MM 22, Float, Eth, Spi, Magic, Amph, NNEat, Reinvig 2, Magic Power 1, SR +15, PR +15, Fear +10, SpSi, Damage Reversal 2 vs MR, Void Sanity 20, Invisibility, Mag: S5, Wpn: Weakness Tentacle, Weakness Tentacle, Weakness Tentacle, Weakness Tentacle, Weakness Tentacle</td></tr>
<tr><td>Blood 8</td><td>Rush of Strength</td><td>B3</td><td>100</td><td>0</td><td>BF</td><td>0</td><td>0</td><td>1</td><td>NUW</td></tr>
<tr><td>Blood 8</td><td>Life for a Life</td><td>B3</td><td>199</td><td>100</td><td>0</td><td>100</td><td>40+</td><td>1</td><td>AN, InanimIm, NUW</td></tr>
<tr><td>Blood 8</td><td>Infernal Prison</td><td>B3F1</td><td>200</td><td>35</td><td>0</td><td>100</td><td>0</td><td>1</td><td>AN, NUW</td></tr>
<tr><td>Blood 8</td><td>Claws of Kokytos</td><td>B3W1</td><td>200</td><td>35</td><td>0</td><td>100</td><td>0</td><td>1</td><td>AN, NUW</td></tr>
<tr><td>Blood 5</td><td>Bloodletting</td><td>B4</td><td>400</td><td>0</td><td>BF</td><td>0</td><td>1</td><td>1</td><td>AN, MR, UndIm, InanimIm, NUW</td></tr>
<tr><td>Blood 7</td><td>Purify Blood</td><td>B4N1</td><td>300</td><td>0</td><td>BF</td><td>0</td><td>0</td><td>1</td><td>NUW</td></tr>
</tbody></table>
```

## Priest Spells

```{=html}
<table class="table spell-table">
<thead><tr><th>School</th><th>Spell Name</th><th>Path</th><th>Fat</th><th>Rng</th><th>AoE</th><th>Pre</th><th>Dmg</th><th>NoE</th><th>Special</th></tr></thead>
<tbody>
<tr><td>Div 0</td><td>Blessing</td><td>H1</td><td>0</td><td>15+</td><td>5+</td><td>100</td><td>0</td><td>1</td><td></td></tr>
<tr><td>Div 0</td><td>Banishment</td><td>H1</td><td>0</td><td>25+</td><td>4+</td><td>0</td><td>4+</td><td>1</td><td>AN, MR, Restriction Non-specialized God</td></tr>
<tr><td>Div 0</td><td>Ashes to Ashes</td><td>H1</td><td>0</td><td>25+</td><td>4+</td><td>0</td><td>4+</td><td>1</td><td>AN, MR</td></tr>
<tr><td>Div 0</td><td>Purifying Water</td><td>H1</td><td>0</td><td>25+</td><td>6+</td><td>0</td><td>2+</td><td>1</td><td>AN, MR, Restriction Water God</td></tr>
<tr><td>Div 0</td><td>Pull from the Grave</td><td>H1</td><td>0</td><td>25+</td><td>4+</td><td>0</td><td>4+</td><td>1</td><td>AN, MR, Restriction Earth God</td></tr>
<tr><td>Div 0</td><td>Sacred Wind</td><td>H1</td><td>0</td><td>30+</td><td>15+</td><td>0</td><td>1</td><td>1</td><td>AN, MR, Restriction Air God</td></tr>
<tr><td>Div 0</td><td>Final Rest</td><td>H1</td><td>0</td><td>25+</td><td>2+</td><td>0</td><td>Death</td><td>1</td><td>AN, MR-, Restriction Nature God</td></tr>
<tr><td>Div 0</td><td>Decree of the Underworld H1</td><td>0</td><td>25+</td><td>4+</td><td>0</td><td>4+</td><td>1</td><td>AN, MR, Restriction Death</td><td>God</td></tr>
<tr><td>Div 0</td><td>Stellar Decree</td><td>H1</td><td>0</td><td>35+</td><td>8+</td><td>0</td><td>2+</td><td>1</td><td>AN, MR, Restriction Astral God</td></tr>
<tr><td>Div 0</td><td>Return of the Past</td><td>H1</td><td>0</td><td>30+</td><td>8+</td><td>0</td><td>2+</td><td>1</td><td>AN, MR, Restriction Glamour God</td></tr>
<tr><td>Div 0</td><td>Sermon of Courage</td><td>H2</td><td>0</td><td>25+</td><td>10+</td><td>100</td><td>1</td><td>1</td><td>AN</td></tr>
<tr><td>Div 0</td><td>Smite Demon</td><td>H2</td><td>0</td><td>30+</td><td>0</td><td>100</td><td>15+</td><td>1</td><td>AN, MR, UndIm</td></tr>
<tr><td>Div 0</td><td>Holy Word</td><td>H2</td><td>0</td><td>25</td><td>0</td><td>100</td><td>100</td><td>1</td><td>MR</td></tr>
<tr><td>Div 0</td><td>Holy Avenger</td><td>H2</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td></td></tr>
<tr><td>Div 0</td><td>Divine Blessing</td><td>H3</td><td>0</td><td>0</td><td>BF</td><td>100</td><td>0</td><td>1</td><td></td></tr>
<tr><td>Div 0</td><td>Smite</td><td>H3</td><td>0</td><td>30</td><td>0</td><td>100</td><td>10</td><td>1</td><td>AN, MR, Restriction Non-specialized God</td></tr>
<tr><td>Div 0</td><td>Heavenly Fire</td><td>H3</td><td>0</td><td>30</td><td>0</td><td>100</td><td>10</td><td>1</td><td>AN, MR</td></tr>
<tr><td>Div 0</td><td>Watery Death</td><td>H3</td><td>0</td><td>25</td><td>0</td><td>100</td><td>10</td><td>1</td><td>AN, MR, Restriction Water God</td></tr>
<tr><td>Div 0</td><td>Word of Stone</td><td>H3</td><td>0</td><td>25</td><td>0</td><td>100</td><td>10</td><td>1</td><td>AN, MR, Restriction Earth God</td></tr>
<tr><td>Div 0</td><td>Heavenly Strike</td><td>H3</td><td>0</td><td>50</td><td>0</td><td>100</td><td>10</td><td>1</td><td>AN, MR, Restriction Air God</td></tr>
<tr><td>Div 0</td><td>Word of Power</td><td>H3</td><td>0</td><td>100</td><td>0</td><td>100</td><td>10</td><td>1</td><td>AN, MR, Restriction Astral God</td></tr>
<tr><td>Div 0</td><td>Syllable of Death</td><td>H3</td><td>0</td><td>25</td><td>0</td><td>100</td><td>10</td><td>1</td><td>AN, MR, Restriction Death God</td></tr>
<tr><td>Div 0</td><td>Word of Thorns</td><td>H3</td><td>0</td><td>30</td><td>0</td><td>100</td><td>5</td><td>1</td><td>AN, MR, Restriction Nature God</td></tr>
<tr><td>Div 0</td><td>Word of Bewilderment</td><td>H3</td><td>0</td><td>30</td><td>0</td><td>100</td><td>10</td><td>1</td><td>AN, MR, UndIm, InanimIm,</td></tr>
<tr class="spell-desc"><td colspan="10">Restriction Glamour God</td></tr>
<tr><td>Div 0</td><td>Claim Life</td><td>H3</td><td>0</td><td>30</td><td>0</td><td>100</td><td>20</td><td>1</td><td>AN, MR, UndIm, InanimIm, Restriction Blood God</td></tr>
<tr><td>Div 0</td><td>Fanaticism</td><td>H4</td><td>0</td><td>0</td><td>BF</td><td>0</td><td>1</td><td>1</td><td>AN</td></tr>
<tr><td>Div 0</td><td>Divine Channeling</td><td>H5</td><td>90</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>BE</td></tr>
</tbody></table>
```

## National Spells: Arcoscephale (age 1)

```{=html}
<table class="table spell-table">
<thead><tr><th>School</th><th>Spell Name</th><th>Path</th><th>Fat</th><th>Rng</th><th>AoE</th><th>Pre</th><th>Dmg</th><th>NoE</th><th>Special</th></tr></thead>
<tbody>
<tr><td>Ench 6</td><td>Sow Dragon Teeth</td><td>E2</td><td>100</td><td>1</td><td>0</td><td>0</td><td>0</td><td>10</td><td>NUW</td></tr>
<tr class="spell-desc"><td colspan="10">Summons Spartae x10: HP 8, Prot 19, MR 13, Mor 18, Str 11, Att 12, Def 12, Prec 10, Enc 0, CS 7, MM 19, Inanim, Magic, PAmph, NNEat, PiR, CR +15, PR +25, SpSi, Wpn: Golden Spear</td></tr>
</tbody></table>
```

## National Spells: Mekone (age 1)

```{=html}
<table class="table spell-table">
<thead><tr><th>School</th><th>Spell Name</th><th>Path</th><th>Fat</th><th>Rng</th><th>AoE</th><th>Pre</th><th>Dmg</th><th>NoE</th><th>Special</th></tr></thead>
<tbody>
<tr><td>Ench 6</td><td>Sow Dragon Teeth</td><td>E2</td><td>100</td><td>1</td><td>0</td><td>0</td><td>0</td><td>10</td><td>NUW</td></tr>
<tr class="spell-desc"><td colspan="10">Summons Spartae x10: HP 8, Prot 19, MR 13, Mor 18, Str 11, Att 12, Def 12, Prec 10, Enc 0, CS 7, MM 19, Inanim, Magic, PAmph, NNEat, PiR, CR +15, PR +25, SpSi, Wpn: Golden Spear</td></tr>
</tbody></table>
```

## National Spells: Pangaea (age 1)

```{=html}
<table class="table spell-table">
<thead><tr><th>School</th><th>Spell Name</th><th>Path</th><th>Fat</th><th>Rng</th><th>AoE</th><th>Pre</th><th>Dmg</th><th>NoE</th><th>Special</th></tr></thead>
<tbody>
<tr><td>Ench 0</td><td>Tune of Fear</td><td>N1</td><td>5</td><td>0</td><td>25</td><td>0</td><td>0</td><td>1</td><td>AN, MindIm, NUW</td></tr>
<tr><td>Ench 0</td><td>Tune of Growth</td><td>N1</td><td>5</td><td>0</td><td>25</td><td>0</td><td>0</td><td>1</td><td>NUW</td></tr>
<tr><td>Ench 0</td><td>Tune of Dancing Death</td><td>N1</td><td>5</td><td>0</td><td>25</td><td>0</td><td>31+</td><td>1</td><td>AN, MR, MindIm, NUW</td></tr>
</tbody></table>
```

## National Spells: Sauromatia (age 1)

```{=html}
<table class="table spell-table">
<thead><tr><th>School</th><th>Spell Name</th><th>Path</th><th>Fat</th><th>Rng</th><th>AoE</th><th>Pre</th><th>Dmg</th><th>NoE</th><th>Special</th></tr></thead>
<tbody>
<tr><td>Conj 1</td><td>Call Ancestor</td><td>D1</td><td>20</td><td>1</td><td>0</td><td>0</td><td>0</td><td>1</td><td></td></tr>
<tr class="spell-desc"><td colspan="10">Summons Ancestral Spirit x1: HP 1, Prot 0, MR 11, Mor 30, Str 1, Att 8, Def 8, Prec 10, Enc 0, CS 12, MM 18, Float, Eth, Spi, Sacr, Und, PAmph, NNEat, Stealth 40, CR +15, PR +25, SpSi, Wpn: Paralyze</td></tr>
<tr><td>Conj 7</td><td>Wrath of the Ancestors</td><td>D1</td><td>100</td><td>1</td><td>0</td><td>0</td><td>0</td><td>20+</td><td></td></tr>
<tr class="spell-desc"><td colspan="10">Summons Ancestral Spirit x20+: HP 1, Prot 0, MR 11, Mor 30, Str 1, Att 8, Def 8, Prec 10, Enc 0, CS 12, MM 18, Float, Eth, Spi, Sacr, Und, PAmph, NNEat, Stealth 40, CR +15, PR +25, SpSi, Wpn: Paralyze</td></tr>
<tr><td>Ench 3</td><td>Awaken Tattoos</td><td>N1H1</td><td>20</td><td>20+</td><td>5+</td><td>100</td><td>0</td><td>1</td><td></td></tr>
</tbody></table>
```

## National Spells: Fomoria (age 1)

```{=html}
<table class="table spell-table">
<thead><tr><th>School</th><th>Spell Name</th><th>Path</th><th>Fat</th><th>Rng</th><th>AoE</th><th>Pre</th><th>Dmg</th><th>NoE</th><th>Special</th></tr></thead>
<tbody>
<tr><td>Conj 8</td><td>Dance of the Morrigans</td><td>D5A2</td><td>400</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>BE, NUW</td></tr>
<tr><td>Thau 3</td><td>Geas</td><td>G2</td><td>20</td><td>25</td><td>0</td><td>100</td><td>0</td><td>1</td><td>MR+, MindIm</td></tr>
<tr><td>Ench 7</td><td>Curse of Balor</td><td>G3D1</td><td>100</td><td>20</td><td>11+</td><td>100</td><td>0</td><td>1</td><td>MR</td></tr>
</tbody></table>
```

## National Spells: Tir na n'Og (age 1)

```{=html}
<table class="table spell-table">
<thead><tr><th>School</th><th>Spell Name</th><th>Path</th><th>Fat</th><th>Rng</th><th>AoE</th><th>Pre</th><th>Dmg</th><th>NoE</th><th>Special</th></tr></thead>
<tbody>
<tr><td>Thau 3</td><td>Geas</td><td>G2</td><td>20</td><td>25</td><td>0</td><td>100</td><td>0</td><td>1</td><td>MR+, MindIm</td></tr>
</tbody></table>
```

## National Spells: Marverni (age 1)

```{=html}
<table class="table spell-table">
<thead><tr><th>School</th><th>Spell Name</th><th>Path</th><th>Fat</th><th>Rng</th><th>AoE</th><th>Pre</th><th>Dmg</th><th>NoE</th><th>Special</th></tr></thead>
<tbody>
<tr><td>Ench 3</td><td>Awaken Tattoos</td><td>N1H1</td><td>20</td><td>20+</td><td>5+</td><td>100</td><td>0</td><td>1</td><td></td></tr>
</tbody></table>
```

## National Spells: Agartha (age 1)

```{=html}
<table class="table spell-table">
<thead><tr><th>School</th><th>Spell Name</th><th>Path</th><th>Fat</th><th>Rng</th><th>AoE</th><th>Pre</th><th>Dmg</th><th>NoE</th><th>Special</th></tr></thead>
<tbody>
<tr><td>Evo 5</td><td>Liquid Flames of Rhuax</td><td>F3E1</td><td>20</td><td>30+</td><td>1</td><td>0</td><td>24+</td><td>1</td><td>AP, NUW</td></tr>
</tbody></table>
```

## National Spells: Abysia (age 1)

```{=html}
<table class="table spell-table">
<thead><tr><th>School</th><th>Spell Name</th><th>Path</th><th>Fat</th><th>Rng</th><th>AoE</th><th>Pre</th><th>Dmg</th><th>NoE</th><th>Special</th></tr></thead>
<tbody>
<tr><td>Ench 5</td><td>Inner Furnace</td><td>F3</td><td>100</td><td>0</td><td>BF</td><td>0</td><td>0</td><td>1</td><td>MindIm, NUW</td></tr>
<tr><td>Evo 5</td><td>Liquid Flames of Rhuax</td><td>F3E1</td><td>20</td><td>30+</td><td>1</td><td>0</td><td>24+</td><td>1</td><td>AP, NUW</td></tr>
</tbody></table>
```

## National Spells: Ubar (age 1)

```{=html}
<table class="table spell-table">
<thead><tr><th>School</th><th>Spell Name</th><th>Path</th><th>Fat</th><th>Rng</th><th>AoE</th><th>Pre</th><th>Dmg</th><th>NoE</th><th>Special</th></tr></thead>
<tbody>
<tr><td>Evo 6</td><td>Smokeless Flame</td><td>F3A1</td><td>30</td><td>35+</td><td>1</td><td>1</td><td>45+</td><td>1</td><td>AP, NUW</td></tr>
<tr><td>Evo 4</td><td>Scorching Wind</td><td>A2F1</td><td>30</td><td>40</td><td>6+</td><td>0</td><td>0</td><td>1</td><td>AN, MR, UndIm, InanimIm, NUW</td></tr>
</tbody></table>
```

## National Spells: Kailasa (age 1)

```{=html}
<table class="table spell-table">
<thead><tr><th>School</th><th>Spell Name</th><th>Path</th><th>Fat</th><th>Rng</th><th>AoE</th><th>Pre</th><th>Dmg</th><th>NoE</th><th>Special</th></tr></thead>
<tbody>
<tr><td>Thau 6</td><td>Celestial Music</td><td>S3</td><td>100</td><td>1</td><td>BF</td><td>0</td><td>0</td><td>1</td><td>NUW</td></tr>
</tbody></table>
```

## National Spells: T'ien Ch'i (age 1)

```{=html}
<table class="table spell-table">
<thead><tr><th>School</th><th>Spell Name</th><th>Path</th><th>Fat</th><th>Rng</th><th>AoE</th><th>Pre</th><th>Dmg</th><th>NoE</th><th>Special</th></tr></thead>
<tbody>
<tr><td>Evo 5</td><td>Celestial Chastisement</td><td>S3</td><td>20</td><td>20</td><td>0</td><td>100</td><td>8+</td><td>1</td><td>AN</td></tr>
<tr><td>Conj 1</td><td>Call Ancestor</td><td>D1</td><td>20</td><td>1</td><td>0</td><td>0</td><td>0</td><td>1</td><td></td></tr>
<tr class="spell-desc"><td colspan="10">Summons Ancestral Spirit x1: HP 1, Prot 0, MR 11, Mor 30, Str 1, Att 8, Def 8, Prec 10, Enc 0, CS 12, MM 18, Float, Eth, Spi, Sacr, Und, PAmph, NNEat, Stealth 40, CR +15, PR +25, SpSi, Wpn: Paralyze</td></tr>
<tr><td>Conj 7</td><td>Wrath of the Ancestors</td><td>D1</td><td>100</td><td>1</td><td>0</td><td>0</td><td>0</td><td>20+</td><td></td></tr>
<tr class="spell-desc"><td colspan="10">Summons Ancestral Spirit x20+: HP 1, Prot 0, MR 11, Mor 30, Str 1, Att 8, Def 8, Prec 10, Enc 0, CS 12, MM 18, Float, Eth, Spi, Sacr, Und, PAmph, NNEat, Stealth 40, CR +15, PR +25, SpSi, Wpn: Paralyze</td></tr>
</tbody></table>
```

## National Spells: Yomi (age 1)

```{=html}
<table class="table spell-table">
<thead><tr><th>School</th><th>Spell Name</th><th>Path</th><th>Fat</th><th>Rng</th><th>AoE</th><th>Pre</th><th>Dmg</th><th>NoE</th><th>Special</th></tr></thead>
<tbody>
<tr><td>Alt 6</td><td>End of Weakness</td><td>E2</td><td>100</td><td>0</td><td>BF</td><td>0</td><td>0</td><td>1</td><td>UndIm, NUW</td></tr>
</tbody></table>
```

## National Spells: Caelum (age 1)

```{=html}
<table class="table spell-table">
<thead><tr><th>School</th><th>Spell Name</th><th>Path</th><th>Fat</th><th>Rng</th><th>AoE</th><th>Pre</th><th>Dmg</th><th>NoE</th><th>Special</th></tr></thead>
<tbody>
<tr><td>Thau 6</td><td>Parting of the Soul</td><td>D1A1</td><td>40</td><td>30</td><td>0</td><td>100</td><td>15+</td><td>1</td><td>AN, MR, MindIm</td></tr>
</tbody></table>
```

## National Spells: Xibalba (age 1)

```{=html}
<table class="table spell-table">
<thead><tr><th>School</th><th>Spell Name</th><th>Path</th><th>Fat</th><th>Rng</th><th>AoE</th><th>Pre</th><th>Dmg</th><th>NoE</th><th>Special</th></tr></thead>
<tbody>
<tr><td>Thau 2</td><td>Break the Third Soul</td><td>A1</td><td>20</td><td>30</td><td>0</td><td>5</td><td>20+</td><td>1</td><td>AN, UndIm, InanimIm, NUW</td></tr>
<tr><td>Thau 3</td><td>Gift of the Third Soul</td><td>A1</td><td>20</td><td>20</td><td>0</td><td>0</td><td>0</td><td>1</td><td>UndIm, InanimIm</td></tr>
<tr><td>Thau 2</td><td>Break the Second Soul</td><td>E1</td><td>20</td><td>30</td><td>0</td><td>5</td><td>0</td><td>1</td><td>Mun, AN, NUW</td></tr>
<tr><td>Thau 3</td><td>Gift of the Second Soul</td><td>E1</td><td>20</td><td>20</td><td>0</td><td>0</td><td>0</td><td>1</td><td>Mun</td></tr>
<tr><td>Thau 2</td><td>Break the Fourth Soul</td><td>D1</td><td>20</td><td>30</td><td>0</td><td>5</td><td>0</td><td>1</td><td>Mun, AN, NUW</td></tr>
<tr><td>Thau 3</td><td>Gift of the Fourth Soul</td><td>D1</td><td>20</td><td>20</td><td>0</td><td>2</td><td>0</td><td>1</td><td>Mun</td></tr>
<tr><td>Blood 2</td><td>Break the First Soul</td><td>B1</td><td>20</td><td>30</td><td>0</td><td>5</td><td>0</td><td>1</td><td>AN, UndIm, InanimIm, NUW</td></tr>
<tr><td>Blood 3</td><td>Gift of the First Soul</td><td>B1</td><td>20</td><td>20</td><td>0</td><td>0</td><td>0</td><td>1</td><td>UndIm, InanimIm</td></tr>
</tbody></table>
```

## National Spells: Vanheim (age 1)

```{=html}
<table class="table spell-table">
<thead><tr><th>School</th><th>Spell Name</th><th>Path</th><th>Fat</th><th>Rng</th><th>AoE</th><th>Pre</th><th>Dmg</th><th>NoE</th><th>Special</th></tr></thead>
<tbody>
<tr><td>Conj 6</td><td>Summon Valkyries</td><td>A3D1</td><td>100</td><td>1</td><td>0</td><td>0</td><td>0</td><td>7</td><td>NUW</td></tr>
<tr class="spell-desc"><td colspan="10">Summons Valkyrie x7: HP 12, Prot 13, MR 14, Mor 12, Str 11, Att 13, Def 16, Prec 13, Enc 5, CS 11, MM 20, Fly, Glamour, Sacr, Stealth 65, SpSi, Wpn: Light Lance</td></tr>
</tbody></table>
```

## National Spells: Helheim (age 1)

```{=html}
<table class="table spell-table">
<thead><tr><th>School</th><th>Spell Name</th><th>Path</th><th>Fat</th><th>Rng</th><th>AoE</th><th>Pre</th><th>Dmg</th><th>NoE</th><th>Special</th></tr></thead>
<tbody>
<tr><td>Conj 6</td><td>Summon Valkyries</td><td>A3D1</td><td>100</td><td>1</td><td>0</td><td>0</td><td>0</td><td>7</td><td>NUW</td></tr>
<tr class="spell-desc"><td colspan="10">Summons Valkyrie x7: HP 12, Prot 13, MR 14, Mor 12, Str 11, Att 13, Def 16, Prec 13, Enc 5, CS 11, MM 20, Fly, Glamour, Sacr, Stealth 65, SpSi, Wpn: Light Lance</td></tr>
</tbody></table>
```

## National Spells: Therodos (age 1)

```{=html}
<table class="table spell-table">
<thead><tr><th>School</th><th>Spell Name</th><th>Path</th><th>Fat</th><th>Rng</th><th>AoE</th><th>Pre</th><th>Dmg</th><th>NoE</th><th>Special</th></tr></thead>
<tbody>
<tr><td>Ench 6</td><td>Sow Dragon Teeth</td><td>E2</td><td>100</td><td>1</td><td>0</td><td>0</td><td>0</td><td>10</td><td>NUW</td></tr>
<tr class="spell-desc"><td colspan="10">Summons Spartae x10: HP 8, Prot 19, MR 13, Mor 18, Str 11, Att 12, Def 12, Prec 10, Enc 0, CS 7, MM 19, Inanim, Magic, PAmph, NNEat, PiR, CR +15, PR +25, SpSi, Wpn: Golden Spear</td></tr>
</tbody></table>
```

## National Spells: Arcoscephale (age 2)

```{=html}
<table class="table spell-table">
<thead><tr><th>School</th><th>Spell Name</th><th>Path</th><th>Fat</th><th>Rng</th><th>AoE</th><th>Pre</th><th>Dmg</th><th>NoE</th><th>Special</th></tr></thead>
<tbody>
<tr><td>Ench 6</td><td>Sow Dragon Teeth</td><td>E2</td><td>100</td><td>1</td><td>0</td><td>0</td><td>0</td><td>10</td><td>NUW</td></tr>
<tr class="spell-desc"><td colspan="10">Summons Spartae x10: HP 8, Prot 19, MR 13, Mor 18, Str 11, Att 12, Def 12, Prec 10, Enc 0, CS 7, MM 19, Inanim, Magic, PAmph, NNEat, PiR, CR +15, PR +25, SpSi, Wpn: Golden Spear</td></tr>
</tbody></table>
```

## National Spells: Phlegra (age 2)

```{=html}
<table class="table spell-table">
<thead><tr><th>School</th><th>Spell Name</th><th>Path</th><th>Fat</th><th>Rng</th><th>AoE</th><th>Pre</th><th>Dmg</th><th>NoE</th><th>Special</th></tr></thead>
<tbody>
<tr><td>Ench 6</td><td>Sow Dragon Teeth</td><td>E2</td><td>100</td><td>1</td><td>0</td><td>0</td><td>0</td><td>10</td><td>NUW</td></tr>
<tr class="spell-desc"><td colspan="10">Summons Spartae x10: HP 8, Prot 19, MR 13, Mor 18, Str 11, Att 12, Def 12, Prec 10, Enc 0, CS 7, MM 19, Inanim, Magic, PAmph, NNEat, PiR, CR +15, PR +25, SpSi, Wpn: Golden Spear</td></tr>
</tbody></table>
```

## National Spells: Pangaea (age 2)

```{=html}
<table class="table spell-table">
<thead><tr><th>School</th><th>Spell Name</th><th>Path</th><th>Fat</th><th>Rng</th><th>AoE</th><th>Pre</th><th>Dmg</th><th>NoE</th><th>Special</th></tr></thead>
<tbody>
<tr><td>Ench 0</td><td>Tune of Fear</td><td>N1</td><td>5</td><td>0</td><td>25</td><td>0</td><td>0</td><td>1</td><td>AN, MindIm, NUW</td></tr>
<tr><td>Ench 0</td><td>Tune of Growth</td><td>N1</td><td>5</td><td>0</td><td>25</td><td>0</td><td>0</td><td>1</td><td>NUW</td></tr>
<tr><td>Ench 0</td><td>Tune of Dancing Death</td><td>N1</td><td>5</td><td>0</td><td>25</td><td>0</td><td>31+</td><td>1</td><td>AN, MR, MindIm, NUW</td></tr>
</tbody></table>
```

## National Spells: Asphodel (age 2)

```{=html}
<table class="table spell-table">
<thead><tr><th>School</th><th>Spell Name</th><th>Path</th><th>Fat</th><th>Rng</th><th>AoE</th><th>Pre</th><th>Dmg</th><th>NoE</th><th>Special</th></tr></thead>
<tbody>
<tr><td>Conj 3</td><td>Sleep Vines</td><td>N1G1</td><td>20</td><td>20</td><td>1</td><td>2</td><td>0</td><td>1</td><td></td></tr>
<tr><td>Conj 4</td><td>Vengeful Vines</td><td>N1D1</td><td>20</td><td>20</td><td>1</td><td>2</td><td>0</td><td>1</td><td></td></tr>
<tr><td>Ench 0</td><td>Quick Roots</td><td>H1</td><td>0</td><td>30+</td><td>1+</td><td>100</td><td>0</td><td>1</td><td>AN</td></tr>
<tr><td>Ench 0</td><td>Regrowth</td><td>H2</td><td>0</td><td>30+</td><td>2+</td><td>100</td><td>0</td><td>1</td><td>AN</td></tr>
<tr><td>Ench 0</td><td>Mend the Dead</td><td>H2</td><td>0</td><td>25+</td><td>0</td><td>100</td><td>40+</td><td>1</td><td>AN</td></tr>
<tr><td>Ench 0</td><td>Puppet Mastery</td><td>H3</td><td>0</td><td>0</td><td>BF</td><td>100</td><td>0</td><td>1</td><td>AN, MR</td></tr>
<tr><td>Ench 0</td><td>Carrion Growth</td><td>H4</td><td>0</td><td>0</td><td>BF</td><td>100</td><td>0</td><td>1</td><td>AN, MR-</td></tr>
</tbody></table>
```

## National Spells: Ermor (age 2)

```{=html}
<table class="table spell-table">
<thead><tr><th>School</th><th>Spell Name</th><th>Path</th><th>Fat</th><th>Rng</th><th>AoE</th><th>Pre</th><th>Dmg</th><th>NoE</th><th>Special</th></tr></thead>
<tbody>
<tr><td>Div 0</td><td>Unholy Command</td><td>H1</td><td>0</td><td>10</td><td>0</td><td>0</td><td>0</td><td>1</td><td>AN, MR-</td></tr>
<tr><td>Div 0</td><td>Unholy Protection</td><td>H1</td><td>0</td><td>20</td><td>1</td><td>100</td><td>0</td><td>1</td><td></td></tr>
<tr><td>Div 0</td><td>Unholy Blessing</td><td>H1</td><td>0</td><td>20</td><td>1</td><td>100</td><td>0</td><td>1</td><td></td></tr>
<tr><td>Div 0</td><td>Unholy Power</td><td>H1</td><td>0</td><td>20</td><td>1</td><td>100</td><td>0</td><td>1</td><td></td></tr>
<tr><td>Div 0</td><td>Unholy Protection</td><td>H2</td><td>0</td><td>10</td><td>10</td><td>100</td><td>0</td><td>1</td><td></td></tr>
<tr><td>Div 0</td><td>Unholy Blessing</td><td>H2</td><td>0</td><td>10</td><td>10</td><td>100</td><td>0</td><td>1</td><td></td></tr>
<tr><td>Div 0</td><td>Unholy Power</td><td>H3</td><td>0</td><td>10</td><td>5</td><td>100</td><td>0</td><td>1</td><td></td></tr>
<tr><td>Div 0</td><td>Unholy Blessing</td><td>H3</td><td>0</td><td>0</td><td>BF</td><td>100</td><td>0</td><td>1</td><td></td></tr>
<tr><td>Div 0</td><td>Protection of the Sepulchre H3</td><td>0</td><td>0</td><td>BF</td><td>100</td><td>0</td><td>1</td><td>MR-</td><td></td></tr>
<tr><td>Div 0</td><td>Power of the Sepulchre</td><td>H4</td><td>0</td><td>0</td><td>BF</td><td>0</td><td>0</td><td>1</td><td></td></tr>
</tbody></table>
```

## National Spells: Sceleria (age 2)

```{=html}
<table class="table spell-table">
<thead><tr><th>School</th><th>Spell Name</th><th>Path</th><th>Fat</th><th>Rng</th><th>AoE</th><th>Pre</th><th>Dmg</th><th>NoE</th><th>Special</th></tr></thead>
<tbody>
<tr><td>Div 0</td><td>Unholy Command</td><td>H1</td><td>0</td><td>10</td><td>0</td><td>0</td><td>0</td><td>1</td><td>AN, MR-</td></tr>
<tr><td>Div 0</td><td>Unholy Protection</td><td>H1</td><td>0</td><td>20</td><td>1</td><td>100</td><td>0</td><td>1</td><td></td></tr>
<tr><td>Div 0</td><td>Unholy Blessing</td><td>H1</td><td>0</td><td>20</td><td>1</td><td>100</td><td>0</td><td>1</td><td></td></tr>
<tr><td>Div 0</td><td>Unholy Power</td><td>H1</td><td>0</td><td>20</td><td>1</td><td>100</td><td>0</td><td>1</td><td></td></tr>
<tr><td>Div 0</td><td>Unholy Protection</td><td>H2</td><td>0</td><td>10</td><td>10</td><td>100</td><td>0</td><td>1</td><td></td></tr>
<tr><td>Div 0</td><td>Unholy Blessing</td><td>H2</td><td>0</td><td>10</td><td>10</td><td>100</td><td>0</td><td>1</td><td></td></tr>
<tr><td>Div 0</td><td>Apostasy</td><td>H3</td><td>0</td><td>50</td><td>0</td><td>100</td><td>0</td><td>1</td><td>MR-</td></tr>
<tr><td>Div 0</td><td>Unholy Power</td><td>H3</td><td>0</td><td>10</td><td>5</td><td>100</td><td>0</td><td>1</td><td></td></tr>
<tr><td>Div 0</td><td>Unholy Blessing</td><td>H3</td><td>0</td><td>0</td><td>BF</td><td>100</td><td>0</td><td>1</td><td></td></tr>
<tr><td>Div 0</td><td>Protection of the Sepulchre H3</td><td>0</td><td>0</td><td>BF</td><td>100</td><td>0</td><td>1</td><td>MR-</td><td></td></tr>
<tr><td>Div 0</td><td>Power of the Sepulchre</td><td>H4</td><td>0</td><td>0</td><td>BF</td><td>0</td><td>0</td><td>1</td><td></td></tr>
</tbody></table>
```

## National Spells: Man (age 2)

```{=html}
<table class="table spell-table">
<thead><tr><th>School</th><th>Spell Name</th><th>Path</th><th>Fat</th><th>Rng</th><th>AoE</th><th>Pre</th><th>Dmg</th><th>NoE</th><th>Special</th></tr></thead>
<tbody>
<tr><td>Thau 1</td><td>Chorus Master</td><td>G1</td><td>20</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td></td></tr>
<tr><td>Thau 1</td><td>Chorus Slave</td><td>G1</td><td>20</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td></td></tr>
<tr><td>Thau 3</td><td>Geas</td><td>G2</td><td>20</td><td>25</td><td>0</td><td>100</td><td>0</td><td>1</td><td>MR+, MindIm</td></tr>
</tbody></table>
```

## National Spells: Eriu (age 2)

```{=html}
<table class="table spell-table">
<thead><tr><th>School</th><th>Spell Name</th><th>Path</th><th>Fat</th><th>Rng</th><th>AoE</th><th>Pre</th><th>Dmg</th><th>NoE</th><th>Special</th></tr></thead>
<tbody>
<tr><td>Thau 3</td><td>Geas</td><td>G2</td><td>20</td><td>25</td><td>0</td><td>100</td><td>0</td><td>1</td><td>MR+, MindIm</td></tr>
</tbody></table>
```

## National Spells: Ulm (age 2)

```{=html}
<table class="table spell-table">
<thead><tr><th>School</th><th>Spell Name</th><th>Path</th><th>Fat</th><th>Rng</th><th>AoE</th><th>Pre</th><th>Dmg</th><th>NoE</th><th>Special</th></tr></thead>
<tbody>
<tr><td>Evo 3</td><td>Iron Darts</td><td>E1H1</td><td>10</td><td>40</td><td>0</td><td>5</td><td>13</td><td>3+</td><td>AP, NUW</td></tr>
<tr><td>Evo 6</td><td>Iron Blizzard</td><td>E1H1</td><td>50</td><td>30</td><td>0</td><td>3</td><td>10</td><td>20+</td><td>AP, NUW</td></tr>
<tr><td>Thau 5</td><td>Tempering the Will</td><td>E3</td><td>20</td><td>0</td><td>BF</td><td>100</td><td>0</td><td>1</td><td>MR-, MindIm</td></tr>
</tbody></table>
```

## National Spells: Marignon (age 2)

```{=html}
<table class="table spell-table">
<thead><tr><th>School</th><th>Spell Name</th><th>Path</th><th>Fat</th><th>Rng</th><th>AoE</th><th>Pre</th><th>Dmg</th><th>NoE</th><th>Special</th></tr></thead>
<tbody>
<tr><td>Evo 4</td><td>Holy Pyre</td><td>F2</td><td>20</td><td>40+</td><td>23+</td><td>1</td><td>7+</td><td>1</td><td>AP, NUW</td></tr>
</tbody></table>
```

## National Spells: Abysia (age 2)

```{=html}
<table class="table spell-table">
<thead><tr><th>School</th><th>Spell Name</th><th>Path</th><th>Fat</th><th>Rng</th><th>AoE</th><th>Pre</th><th>Dmg</th><th>NoE</th><th>Special</th></tr></thead>
<tbody>
<tr><td>Ench 5</td><td>Inner Furnace</td><td>F3</td><td>100</td><td>0</td><td>BF</td><td>0</td><td>0</td><td>1</td><td>MindIm, NUW</td></tr>
<tr><td>Evo 5</td><td>Liquid Flames of Rhuax</td><td>F3E1</td><td>20</td><td>30+</td><td>1</td><td>0</td><td>24+</td><td>1</td><td>AP, NUW</td></tr>
</tbody></table>
```

## National Spells: Ashdod (age 2)

```{=html}
<table class="table spell-table">
<thead><tr><th>School</th><th>Spell Name</th><th>Path</th><th>Fat</th><th>Rng</th><th>AoE</th><th>Pre</th><th>Dmg</th><th>NoE</th><th>Special</th></tr></thead>
<tbody>
<tr><td>Evo 4</td><td>Strange Fire</td><td>S2F1</td><td>20</td><td>40+</td><td>3</td><td>1</td><td>8+</td><td>1</td><td>AP, NUW</td></tr>
</tbody></table>
```

## National Spells: Na'Ba (age 2)

```{=html}
<table class="table spell-table">
<thead><tr><th>School</th><th>Spell Name</th><th>Path</th><th>Fat</th><th>Rng</th><th>AoE</th><th>Pre</th><th>Dmg</th><th>NoE</th><th>Special</th></tr></thead>
<tbody>
<tr><td>Evo 6</td><td>Smokeless Flame</td><td>F3A1</td><td>30</td><td>35+</td><td>1</td><td>1</td><td>45+</td><td>1</td><td>AP, NUW</td></tr>
<tr><td>Evo 4</td><td>Scorching Wind</td><td>A2F1</td><td>30</td><td>40</td><td>6+</td><td>0</td><td>0</td><td>1</td><td>AN, MR, UndIm, InanimIm, NUW</td></tr>
</tbody></table>
```

## National Spells: Bandar Log (age 2)

```{=html}
<table class="table spell-table">
<thead><tr><th>School</th><th>Spell Name</th><th>Path</th><th>Fat</th><th>Rng</th><th>AoE</th><th>Pre</th><th>Dmg</th><th>NoE</th><th>Special</th></tr></thead>
<tbody>
<tr><td>Thau 6</td><td>Celestial Music</td><td>S3</td><td>100</td><td>1</td><td>BF</td><td>0</td><td>0</td><td>1</td><td>NUW</td></tr>
</tbody></table>
```

## National Spells: T'ien Ch'i (age 2)

```{=html}
<table class="table spell-table">
<thead><tr><th>School</th><th>Spell Name</th><th>Path</th><th>Fat</th><th>Rng</th><th>AoE</th><th>Pre</th><th>Dmg</th><th>NoE</th><th>Special</th></tr></thead>
<tbody>
<tr><td>Evo 5</td><td>Celestial Chastisement</td><td>S3</td><td>20</td><td>20</td><td>0</td><td>100</td><td>8+</td><td>1</td><td>AN</td></tr>
</tbody></table>
```

## National Spells: Caelum (age 2)

```{=html}
<table class="table spell-table">
<thead><tr><th>School</th><th>Spell Name</th><th>Path</th><th>Fat</th><th>Rng</th><th>AoE</th><th>Pre</th><th>Dmg</th><th>NoE</th><th>Special</th></tr></thead>
<tbody>
<tr><td>Thau 6</td><td>Parting of the Soul</td><td>D1A1</td><td>40</td><td>30</td><td>0</td><td>100</td><td>15+</td><td>1</td><td>AN, MR, MindIm</td></tr>
</tbody></table>
```

## National Spells: Xibalba (age 2)

```{=html}
<table class="table spell-table">
<thead><tr><th>School</th><th>Spell Name</th><th>Path</th><th>Fat</th><th>Rng</th><th>AoE</th><th>Pre</th><th>Dmg</th><th>NoE</th><th>Special</th></tr></thead>
<tbody>
<tr><td>Thau 2</td><td>Break the Third Soul</td><td>A1</td><td>20</td><td>30</td><td>0</td><td>5</td><td>20+</td><td>1</td><td>AN, UndIm, InanimIm, NUW</td></tr>
<tr><td>Thau 3</td><td>Gift of the Third Soul</td><td>A1</td><td>20</td><td>20</td><td>0</td><td>0</td><td>0</td><td>1</td><td>UndIm, InanimIm</td></tr>
<tr><td>Thau 2</td><td>Break the Second Soul</td><td>E1</td><td>20</td><td>30</td><td>0</td><td>5</td><td>0</td><td>1</td><td>Mun, AN, NUW</td></tr>
<tr><td>Thau 3</td><td>Gift of the Second Soul</td><td>E1</td><td>20</td><td>20</td><td>0</td><td>0</td><td>0</td><td>1</td><td>Mun</td></tr>
<tr><td>Thau 2</td><td>Break the Fourth Soul</td><td>D1</td><td>20</td><td>30</td><td>0</td><td>5</td><td>0</td><td>1</td><td>Mun, AN, NUW</td></tr>
<tr><td>Thau 3</td><td>Gift of the Fourth Soul</td><td>D1</td><td>20</td><td>20</td><td>0</td><td>2</td><td>0</td><td>1</td><td>Mun</td></tr>
<tr><td>Blood 2</td><td>Break the First Soul</td><td>B1</td><td>20</td><td>30</td><td>0</td><td>5</td><td>0</td><td>1</td><td>AN, UndIm, InanimIm, NUW</td></tr>
<tr><td>Blood 3</td><td>Gift of the First Soul</td><td>B1</td><td>20</td><td>20</td><td>0</td><td>0</td><td>0</td><td>1</td><td>UndIm, InanimIm</td></tr>
</tbody></table>
```

## National Spells: Phaeacia (age 2)

```{=html}
<table class="table spell-table">
<thead><tr><th>School</th><th>Spell Name</th><th>Path</th><th>Fat</th><th>Rng</th><th>AoE</th><th>Pre</th><th>Dmg</th><th>NoE</th><th>Special</th></tr></thead>
<tbody>
<tr><td>Ench 6</td><td>Sow Dragon Teeth</td><td>E2</td><td>100</td><td>1</td><td>0</td><td>0</td><td>0</td><td>10</td><td>NUW</td></tr>
<tr class="spell-desc"><td colspan="10">Summons Spartae x10: HP 8, Prot 19, MR 13, Mor 18, Str 11, Att 12, Def 12, Prec 10, Enc 0, CS 7, MM 19, Inanim, Magic, PAmph, NNEat, PiR, CR +15, PR +25, SpSi, Wpn: Golden Spear</td></tr>
</tbody></table>
```

## National Spells: Vanheim (age 2)

```{=html}
<table class="table spell-table">
<thead><tr><th>School</th><th>Spell Name</th><th>Path</th><th>Fat</th><th>Rng</th><th>AoE</th><th>Pre</th><th>Dmg</th><th>NoE</th><th>Special</th></tr></thead>
<tbody>
<tr><td>Conj 6</td><td>Summon Valkyries</td><td>A3D1</td><td>100</td><td>1</td><td>0</td><td>0</td><td>0</td><td>7</td><td>NUW</td></tr>
<tr class="spell-desc"><td colspan="10">Summons Valkyrie x7: HP 12, Prot 13, MR 14, Mor 12, Str 11, Att 13, Def 16, Prec 13, Enc 5, CS 11, MM 20, Fly, Glamour, Sacr, Stealth 65, SpSi, Wpn: Light Lance</td></tr>
</tbody></table>
```

## National Spells: Ys (age 2)

```{=html}
<table class="table spell-table">
<thead><tr><th>School</th><th>Spell Name</th><th>Path</th><th>Fat</th><th>Rng</th><th>AoE</th><th>Pre</th><th>Dmg</th><th>NoE</th><th>Special</th></tr></thead>
<tbody>
<tr><td>Thau 3</td><td>Geas</td><td>G2</td><td>20</td><td>25</td><td>0</td><td>100</td><td>0</td><td>1</td><td>MR+, MindIm</td></tr>
</tbody></table>
```

## National Spells: Arcoscephale (age 3)

```{=html}
<table class="table spell-table">
<thead><tr><th>School</th><th>Spell Name</th><th>Path</th><th>Fat</th><th>Rng</th><th>AoE</th><th>Pre</th><th>Dmg</th><th>NoE</th><th>Special</th></tr></thead>
<tbody>
<tr><td>Ench 6</td><td>Sow Dragon Teeth</td><td>E2</td><td>100</td><td>1</td><td>0</td><td>0</td><td>0</td><td>10</td><td>NUW</td></tr>
<tr class="spell-desc"><td colspan="10">Summons Spartae x10: HP 8, Prot 19, MR 13, Mor 18, Str 11, Att 12, Def 12, Prec 10, Enc 0, CS 7, MM 19, Inanim, Magic, PAmph, NNEat, PiR, CR +15, PR +25, SpSi, Wpn: Golden Spear</td></tr>
<tr><td>Thau 3</td><td>Rhapsody of the Dead</td><td>D1</td><td>20</td><td>15+</td><td>4+</td><td>0</td><td>4+</td><td>1</td><td>AN, MR, MindIm, NUW</td></tr>
<tr><td>Thau 3</td><td>Rhapsody of Life</td><td>N1</td><td>20</td><td>15+</td><td>0</td><td>5</td><td>10+</td><td>1</td><td>AN, InanimIm, MindIm, NUW</td></tr>
</tbody></table>
```

## National Spells: Phlegra (age 3)

```{=html}
<table class="table spell-table">
<thead><tr><th>School</th><th>Spell Name</th><th>Path</th><th>Fat</th><th>Rng</th><th>AoE</th><th>Pre</th><th>Dmg</th><th>NoE</th><th>Special</th></tr></thead>
<tbody>
<tr><td>Ench 6</td><td>Sow Dragon Teeth</td><td>E2</td><td>100</td><td>1</td><td>0</td><td>0</td><td>0</td><td>10</td><td>NUW</td></tr>
<tr class="spell-desc"><td colspan="10">Summons Spartae x10: HP 8, Prot 19, MR 13, Mor 18, Str 11, Att 12, Def 12, Prec 10, Enc 0, CS 7, MM 19, Inanim, Magic, PAmph, NNEat, PiR, CR +15, PR +25, SpSi, Wpn: Golden Spear</td></tr>
</tbody></table>
```

## National Spells: Pangaea (age 3)

```{=html}
<table class="table spell-table">
<thead><tr><th>School</th><th>Spell Name</th><th>Path</th><th>Fat</th><th>Rng</th><th>AoE</th><th>Pre</th><th>Dmg</th><th>NoE</th><th>Special</th></tr></thead>
<tbody>
<tr><td>Ench 0</td><td>Tune of Fear</td><td>N1</td><td>5</td><td>0</td><td>25</td><td>0</td><td>0</td><td>1</td><td>AN, MindIm, NUW</td></tr>
<tr><td>Ench 0</td><td>Tune of Growth</td><td>N1</td><td>5</td><td>0</td><td>25</td><td>0</td><td>0</td><td>1</td><td>NUW</td></tr>
<tr><td>Ench 0</td><td>Tune of Dancing Death</td><td>N1</td><td>5</td><td>0</td><td>25</td><td>0</td><td>31+</td><td>1</td><td>AN, MR, MindIm, NUW</td></tr>
</tbody></table>
```

## National Spells: Pythium (age 3)

```{=html}
<table class="table spell-table">
<thead><tr><th>School</th><th>Spell Name</th><th>Path</th><th>Fat</th><th>Rng</th><th>AoE</th><th>Pre</th><th>Dmg</th><th>NoE</th><th>Special</th></tr></thead>
<tbody>
<tr><td>Ench 2</td><td>Gift of the Sacred Swamp</td><td>N1H1</td><td>20</td><td>15</td><td>5+</td><td>0</td><td>0</td><td>1</td><td></td></tr>
</tbody></table>
```

## National Spells: Lemuria (age 3)

```{=html}
<table class="table spell-table">
<thead><tr><th>School</th><th>Spell Name</th><th>Path</th><th>Fat</th><th>Rng</th><th>AoE</th><th>Pre</th><th>Dmg</th><th>NoE</th><th>Special</th></tr></thead>
<tbody>
<tr><td>Div 0</td><td>Unholy Command</td><td>H1</td><td>0</td><td>10</td><td>0</td><td>0</td><td>0</td><td>1</td><td>AN, MR-</td></tr>
<tr><td>Div 0</td><td>Unholy Protection</td><td>H1</td><td>0</td><td>20</td><td>1</td><td>100</td><td>0</td><td>1</td><td></td></tr>
<tr><td>Div 0</td><td>Unholy Blessing</td><td>H1</td><td>0</td><td>20</td><td>1</td><td>100</td><td>0</td><td>1</td><td></td></tr>
<tr><td>Div 0</td><td>Unholy Power</td><td>H1</td><td>0</td><td>20</td><td>1</td><td>100</td><td>0</td><td>1</td><td></td></tr>
<tr><td>Div 0</td><td>Anathema</td><td>H2</td><td>0</td><td>50</td><td>1</td><td>100</td><td>0</td><td>1</td><td></td></tr>
<tr><td>Div 0</td><td>Unholy Protection</td><td>H2</td><td>0</td><td>10</td><td>10</td><td>100</td><td>0</td><td>1</td><td></td></tr>
<tr><td>Div 0</td><td>Unholy Blessing</td><td>H2</td><td>0</td><td>10</td><td>10</td><td>100</td><td>0</td><td>1</td><td></td></tr>
<tr><td>Div 0</td><td>Apostasy</td><td>H3</td><td>0</td><td>50</td><td>0</td><td>100</td><td>0</td><td>1</td><td>MR-</td></tr>
<tr><td>Div 0</td><td>Unholy Power</td><td>H3</td><td>0</td><td>10</td><td>5</td><td>100</td><td>0</td><td>1</td><td></td></tr>
<tr><td>Div 0</td><td>Unholy Blessing</td><td>H3</td><td>0</td><td>0</td><td>BF</td><td>100</td><td>0</td><td>1</td><td></td></tr>
<tr><td>Div 0</td><td>Protection of the</td><td>H3</td><td>0</td><td>0</td><td>BF</td><td>100</td><td>0</td><td>1</td><td>MR- Shadelands</td></tr>
<tr><td>Div 0</td><td>Power of the Shadelands</td><td>H4</td><td>0</td><td>0</td><td>BF</td><td>0</td><td>0</td><td>1</td><td></td></tr>
</tbody></table>
```

## National Spells: Ulm (age 3)

```{=html}
<table class="table spell-table">
<thead><tr><th>School</th><th>Spell Name</th><th>Path</th><th>Fat</th><th>Rng</th><th>AoE</th><th>Pre</th><th>Dmg</th><th>NoE</th><th>Special</th></tr></thead>
<tbody>
<tr><td>Evo 3</td><td>Iron Darts</td><td>E1H1</td><td>10</td><td>40</td><td>0</td><td>5</td><td>13</td><td>3+</td><td>AP, NUW</td></tr>
<tr><td>Evo 6</td><td>Iron Blizzard</td><td>E1H1</td><td>50</td><td>30</td><td>0</td><td>3</td><td>10</td><td>20+</td><td>AP, NUW</td></tr>
<tr><td>Thau 5</td><td>Tempering the Will</td><td>E3</td><td>20</td><td>0</td><td>BF</td><td>100</td><td>0</td><td>1</td><td>MR-, MindIm</td></tr>
<tr><td>Ench 4</td><td>Gift of the Moon</td><td>S1</td><td>20</td><td>30+</td><td>1</td><td>100</td><td>0</td><td>1</td><td>Anim</td></tr>
</tbody></table>
```

## National Spells: Agartha (age 3)

```{=html}
<table class="table spell-table">
<thead><tr><th>School</th><th>Spell Name</th><th>Path</th><th>Fat</th><th>Rng</th><th>AoE</th><th>Pre</th><th>Dmg</th><th>NoE</th><th>Special</th></tr></thead>
<tbody>
<tr><td>Alt 5</td><td>Iron Marionettes</td><td>E3</td><td>100</td><td>30</td><td>25</td><td>100</td><td>0</td><td>1</td><td></td></tr>
</tbody></table>
```

## National Spells: Marignon (age 3)

```{=html}
<table class="table spell-table">
<thead><tr><th>School</th><th>Spell Name</th><th>Path</th><th>Fat</th><th>Rng</th><th>AoE</th><th>Pre</th><th>Dmg</th><th>NoE</th><th>Special</th></tr></thead>
<tbody>
<tr><td>Evo 4</td><td>Holy Pyre</td><td>F2</td><td>20</td><td>40+</td><td>23+</td><td>1</td><td>7+</td><td>1</td><td>AP, NUW</td></tr>
</tbody></table>
```

## National Spells: Abysia (age 3)

```{=html}
<table class="table spell-table">
<thead><tr><th>School</th><th>Spell Name</th><th>Path</th><th>Fat</th><th>Rng</th><th>AoE</th><th>Pre</th><th>Dmg</th><th>NoE</th><th>Special</th></tr></thead>
<tbody>
<tr><td>Ench 5</td><td>Inner Furnace</td><td>F3</td><td>100</td><td>0</td><td>BF</td><td>0</td><td>0</td><td>1</td><td>MindIm, NUW</td></tr>
<tr><td>Evo 5</td><td>Liquid Flames of Rhuax</td><td>F3E1</td><td>20</td><td>30+</td><td>1</td><td>0</td><td>24+</td><td>1</td><td>AP, NUW</td></tr>
</tbody></table>
```

## National Spells: Ragha (age 3)

```{=html}
<table class="table spell-table">
<thead><tr><th>School</th><th>Spell Name</th><th>Path</th><th>Fat</th><th>Rng</th><th>AoE</th><th>Pre</th><th>Dmg</th><th>NoE</th><th>Special</th></tr></thead>
<tbody>
<tr><td>Thau 6</td><td>Parting of the Soul</td><td>D1A1</td><td>40</td><td>30</td><td>0</td><td>100</td><td>15+</td><td>1</td><td>AN, MR, MindIm</td></tr>
</tbody></table>
```

## National Spells: Caelum (age 3)

```{=html}
<table class="table spell-table">
<thead><tr><th>School</th><th>Spell Name</th><th>Path</th><th>Fat</th><th>Rng</th><th>AoE</th><th>Pre</th><th>Dmg</th><th>NoE</th><th>Special</th></tr></thead>
<tbody>
<tr><td>Thau 6</td><td>Parting of the Soul</td><td>D1A1</td><td>40</td><td>30</td><td>0</td><td>100</td><td>15+</td><td>1</td><td>AN, MR, MindIm</td></tr>
</tbody></table>
```

## National Spells: Gath (age 3)

```{=html}
<table class="table spell-table">
<thead><tr><th>School</th><th>Spell Name</th><th>Path</th><th>Fat</th><th>Rng</th><th>AoE</th><th>Pre</th><th>Dmg</th><th>NoE</th><th>Special</th></tr></thead>
<tbody>
<tr><td>Evo 4</td><td>Strange Fire</td><td>S2F1</td><td>20</td><td>40+</td><td>3</td><td>1</td><td>8+</td><td>1</td><td>AP, NUW</td></tr>
</tbody></table>
```

## National Spells: T'ien Ch'i (age 3)

```{=html}
<table class="table spell-table">
<thead><tr><th>School</th><th>Spell Name</th><th>Path</th><th>Fat</th><th>Rng</th><th>AoE</th><th>Pre</th><th>Dmg</th><th>NoE</th><th>Special</th></tr></thead>
<tbody>
<tr><td>Evo 5</td><td>Celestial Chastisement</td><td>S3</td><td>20</td><td>20</td><td>0</td><td>100</td><td>8+</td><td>1</td><td>AN</td></tr>
<tr><td>Conj 1</td><td>Call Ancestor</td><td>D1</td><td>20</td><td>1</td><td>0</td><td>0</td><td>0</td><td>1</td><td></td></tr>
<tr class="spell-desc"><td colspan="10">Summons Ancestral Spirit x1: HP 1, Prot 0, MR 11, Mor 30, Str 1, Att 8, Def 8, Prec 10, Enc 0, CS 12, MM 18, Float, Eth, Spi, Sacr, Und, PAmph, NNEat, Stealth 40, CR +15, PR +25, SpSi, Wpn: Paralyze</td></tr>
<tr><td>Conj 7</td><td>Wrath of the Ancestors</td><td>D1</td><td>100</td><td>1</td><td>0</td><td>0</td><td>0</td><td>20+</td><td></td></tr>
<tr class="spell-desc"><td colspan="10">Summons Ancestral Spirit x20+: HP 1, Prot 0, MR 11, Mor 30, Str 1, Att 8, Def 8, Prec 10, Enc 0, CS 12, MM 18, Float, Eth, Spi, Sacr, Und, PAmph, NNEat, Stealth 40, CR +15, PR +25, SpSi, Wpn: Paralyze</td></tr>
</tbody></table>
```

## National Spells: Jomon (age 3)

```{=html}
<table class="table spell-table">
<thead><tr><th>School</th><th>Spell Name</th><th>Path</th><th>Fat</th><th>Rng</th><th>AoE</th><th>Pre</th><th>Dmg</th><th>NoE</th><th>Special</th></tr></thead>
<tbody>
<tr><td>Div 0</td><td>Teaching Sign</td><td>H1N1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td></td></tr>
<tr><td>Div 0</td><td>Fear-not Sign</td><td>H1A1</td><td>0</td><td>15</td><td>2+</td><td>100</td><td>0</td><td>1</td><td></td></tr>
<tr><td>Div 0</td><td>Welcome Sign</td><td>H1F1</td><td>0</td><td>5</td><td>0</td><td>100</td><td>0</td><td>1</td><td>MR-</td></tr>
<tr><td>Div 0</td><td>Earth-touching Sign</td><td>H1E1</td><td>0</td><td>20</td><td>0</td><td>100</td><td>Death</td><td>1</td><td>AN, MR-, UndIm</td></tr>
<tr><td>Div 0</td><td>Meditation Sign</td><td>H1W1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>15</td><td>1</td><td></td></tr>
</tbody></table>
```

## National Spells: Xibalba (age 3)

```{=html}
<table class="table spell-table">
<thead><tr><th>School</th><th>Spell Name</th><th>Path</th><th>Fat</th><th>Rng</th><th>AoE</th><th>Pre</th><th>Dmg</th><th>NoE</th><th>Special</th></tr></thead>
<tbody>
<tr><td>Thau 2</td><td>Break the Third Soul</td><td>A1</td><td>20</td><td>30</td><td>0</td><td>5</td><td>20+</td><td>1</td><td>AN, UndIm, InanimIm, NUW</td></tr>
<tr><td>Thau 3</td><td>Gift of the Third Soul</td><td>A1</td><td>20</td><td>20</td><td>0</td><td>0</td><td>0</td><td>1</td><td>UndIm, InanimIm</td></tr>
<tr><td>Thau 2</td><td>Break the Second Soul</td><td>E1</td><td>20</td><td>30</td><td>0</td><td>5</td><td>0</td><td>1</td><td>Mun, AN, NUW</td></tr>
<tr><td>Thau 3</td><td>Gift of the Second Soul</td><td>E1</td><td>20</td><td>20</td><td>0</td><td>0</td><td>0</td><td>1</td><td>Mun</td></tr>
<tr><td>Thau 2</td><td>Break the Fourth Soul</td><td>D1</td><td>20</td><td>30</td><td>0</td><td>5</td><td>0</td><td>1</td><td>Mun, AN, NUW</td></tr>
<tr><td>Thau 3</td><td>Gift of the Fourth Soul</td><td>D1</td><td>20</td><td>20</td><td>0</td><td>2</td><td>0</td><td>1</td><td>Mun</td></tr>
<tr><td>Blood 2</td><td>Break the First Soul</td><td>B1</td><td>20</td><td>30</td><td>0</td><td>5</td><td>0</td><td>1</td><td>AN, UndIm, InanimIm, NUW</td></tr>
<tr><td>Blood 3</td><td>Gift of the First Soul</td><td>B1</td><td>20</td><td>20</td><td>0</td><td>0</td><td>0</td><td>1</td><td>UndIm, InanimIm</td></tr>
</tbody></table>
```

## National Spells: C'tis (age 3)

```{=html}
<table class="table spell-table">
<thead><tr><th>School</th><th>Spell Name</th><th>Path</th><th>Fat</th><th>Rng</th><th>AoE</th><th>Pre</th><th>Dmg</th><th>NoE</th><th>Special</th></tr></thead>
<tbody>
<tr><td>Div 0</td><td>Protection of the Grave</td><td>H1</td><td>0</td><td>20</td><td>1</td><td>100</td><td>0</td><td>1</td><td></td></tr>
<tr><td>Div 0</td><td>Power of the Grave</td><td>H1</td><td>0</td><td>20</td><td>1</td><td>100</td><td>0</td><td>1</td><td></td></tr>
<tr><td>Div 0</td><td>Protection of the Grave</td><td>H2</td><td>0</td><td>10</td><td>10</td><td>100</td><td>0</td><td>1</td><td></td></tr>
<tr><td>Div 0</td><td>Royal Power</td><td>H3</td><td>0</td><td>10</td><td>5</td><td>100</td><td>0</td><td>1</td><td></td></tr>
<tr><td>Div 0</td><td>Royal Protection</td><td>H3</td><td>0</td><td>0</td><td>BF</td><td>100</td><td>0</td><td>1</td><td>MR-</td></tr>
<tr><td>Div 0</td><td>Power of the Reborn King</td><td>H4</td><td>0</td><td>0</td><td>BF</td><td>0</td><td>0</td><td>1</td><td></td></tr>
</tbody></table>
```

## National Spells: Midgård (age 3)

```{=html}
<table class="table spell-table">
<thead><tr><th>School</th><th>Spell Name</th><th>Path</th><th>Fat</th><th>Rng</th><th>AoE</th><th>Pre</th><th>Dmg</th><th>NoE</th><th>Special</th></tr></thead>
<tbody>
<tr><td>Conj 6</td><td>Summon Valkyries</td><td>A3D1</td><td>100</td><td>1</td><td>0</td><td>0</td><td>0</td><td>7</td><td>NUW</td></tr>
<tr class="spell-desc"><td colspan="10">Summons Valkyrie x7: HP 12, Prot 13, MR 14, Mor 12, Str 11, Att 13, Def 16, Prec 13, Enc 5, CS 11, MM 20, Fly, Glamour, Sacr, Stealth 65, SpSi, Wpn: Light Lance</td></tr>
</tbody></table>
```

## National Spells: Erytheia (age 3)

```{=html}
<table class="table spell-table">
<thead><tr><th>School</th><th>Spell Name</th><th>Path</th><th>Fat</th><th>Rng</th><th>AoE</th><th>Pre</th><th>Dmg</th><th>NoE</th><th>Special</th></tr></thead>
<tbody>
<tr><td>Ench 6</td><td>Sow Dragon Teeth</td><td>E2</td><td>100</td><td>1</td><td>0</td><td>0</td><td>0</td><td>10</td><td>NUW</td></tr>
<tr class="spell-desc"><td colspan="10">Summons Spartae x10: HP 8, Prot 19, MR 13, Mor 18, Str 11, Att 12, Def 12, Prec 10, Enc 0, CS 7, MM 19, Inanim, Magic, PAmph, NNEat, PiR, CR +15, PR +25, SpSi, Wpn: Golden Spear</td></tr>
</tbody></table>
```

