# Global Enchantments

The following spells are global enchantments, and thus are classified as rituals. The gem
requirements listed are minimums; players can choose to use more gems when casting, making the
enchantment harder to dispel. Most global enchantments last until their caster dies or they are
dispelled. Spells with the **NUW** special cannot be cast underwater.

The **Special** column holds each enchantment's full effect description (any flags such as NUW
or AP appear first).

## Fire Rituals

```{=html}
<table class="table spell-table">
<thead><tr><th>School</th><th>Ritual Name</th><th>Path</th><th>Cost</th><th>Rng</th><th>Dmg</th><th>Special</th></tr></thead>
<tbody>
<tr><td>Conj 8</td><td>The Kindly Ones</td><td>F6N4</td><td>40</td><td>-</td><td>-</td><td></td></tr>
<tr class="spell-desc"><td colspan="7">The caster unleashes the Erinyes upon the world. The Erinyes are three horrible spirits of vengeance that punish those who slay innocent women. In elder times, they upheld the ban against Blood magic, but they have since returned to the darkness whence they came. They are sometimes called the Eumenides, the Kindly Ones, but their true names are Avenger of Murder, Grudging Anger and The Unrelenting One. Sinners will hear the horrible baying of the sisters and madness will strike them unless they are found and most gruesomely slain by the sisters. The first sister kills those who have killed, the second one hunts those who use blood magic and the third one hunts the enemies of he who summoned her and her sisters. The Kindly Ones remain in the world until the enchantment is dispelled or the three of them are slain.</td></tr>
<tr><td>Ench 6</td><td>Eternal Pyre</td><td>F6</td><td>80</td><td>-</td><td>-</td><td>NUW</td></tr>
<tr class="spell-desc"><td colspan="7">A huge blazing pyre lights up the landscape. It never burns out and the embers of the pyre will absorb the heat and can be harvested as magical gems imbued with the fiery power of the pyre. The Eternal Pyre causes the temperature to rise to unbearable levels in the province where it is cast. Once the eternal pyre has started burning, it will be impossible to extinguish without the use of magic. Even putting it underwater would only reduce its heat a little. Generates 20 Fire gems each month. Increases temperature and dispels all darkness in the province where it is cast.</td></tr>
<tr><td>Thau 7</td><td>Purgatory</td><td>F6</td><td>60</td><td>-</td><td>18</td><td>AP, NUW</td></tr>
<tr class="spell-desc"><td colspan="7">Holy fire will strike undead enemy creatures in the God&#x27;s Dominion. The more powerful the Dominion, the more undead will be killed. All hostile undead beings have Dominion * 10% chance of being hit by 18 AP fire Dmg</td></tr>
<tr><td>Thau 8</td><td>Ordeal by Fire</td><td>F6S6</td><td>70</td><td>-</td><td>-</td><td></td></tr>
<tr class="spell-desc"><td colspan="7">This enchantment sets the magical ether ablaze by utilizing a huge amount of magic fire gems. As long as the ether is ablaze it will be difficult to manipulate any kind of magic without also taking fire damage from the heat. It is still possible to perform rituals and forge magic items, but if not properly protected the chance of burning to death is high. Performing simple spells in combat is possible without risk as long as they don&#x27;t require any magic gems. Blood magic is unaffected by this ritual. Performing rituals, forging and empowerment results in two d(gems spent / 2) AN fire attacks. Damage underwater is halved. Using magic gems in combat results in catching fire.</td></tr>
<tr><td>Evo 8</td><td>Second Sun</td><td>F8</td><td>80</td><td>-</td><td>-</td><td></td></tr>
<tr class="spell-desc"><td colspan="7">The caster creates a huge ball of fire in the sky. This Second Sun will always shine, day and night, resulting in severe effects across the entire world. Provinces will become hotter and drier every turn until the Second Sun is destroyed. Each turn increases heat scales throughout the world. Cave provinces will only get up to 1 step hotter.</td></tr>
</tbody></table>
```

## Air Rituals

```{=html}
<table class="table spell-table">
<thead><tr><th>School</th><th>Ritual Name</th><th>Path</th><th>Cost</th><th>Rng</th><th>Dmg</th><th>Special</th></tr></thead>
<tbody>
<tr><td>Evo 6</td><td>Perpetual Storm</td><td>A5</td><td>70</td><td>-</td><td>-</td><td></td></tr>
<tr class="spell-desc"><td colspan="7">An enormous storm will rage constantly over the entire world. This will reduce the income of all land provinces. Supplies are scarce, as transportation is difficult and sailing and flying is impossible. All mountain passes are unusable during the perpetual storm and shooting in battle is very difficult. Evocations cast upon distant provinces might fail as the magical gale pushes the projectiles out of their trajectory. All battles are affected by storm. Income -20%. Map movement costs are increased by 2. Far-attack spells such as Fires from Afar have a 25% chance of missing their targets. Seeking Arrow has a 75% chance of missing its target. Underwater and cave provinces are not affected.</td></tr>
<tr><td>Thau 7</td><td>Dark Skies</td><td>A5</td><td>50</td><td>-</td><td>-</td><td>NUW</td></tr>
<tr class="spell-desc"><td colspan="7">Black clouds billow forth and cover the lands of your Dominion. All enemies under your Dominion will perceive the heavens as dark and oppressing. The stronger the Dominion is, the more fearful the skies. The dark skies severely lower the morale of those affected. The darkness also gives slightly lowered attack and defense skills to units without darkvision. Enemy morale lowered by 1 for each point of dominion. Slight darkness in battles. Cave and deep sea provinces are not affected.</td></tr>
<tr><td>Thau 8</td><td>Gale Gate</td><td>A5</td><td>60</td><td>-</td><td>-</td><td>NUW</td></tr>
<tr class="spell-desc"><td colspan="7">The caster opens a rift in space creating a gate into a realm of storms. Huge amounts of aerial magic are effectively channeled through this gate, producing twenty Air gems each turn. Also air elementals summoned anywhere in the world will be extra powerful while the gale gate is open. Not all of the powers of the Gale Gate can be harnessed though. Hurricanes and storms will be randomly unleashed and hit a province somewhere in the world. The caster will be able to direct hurricanes and have them strike provinces that are controlled by the enemies. A high skill in air magic makes it more likely to successfully steer the hurricanes away. Generates 20 Air gems each month. Air Elemental size +1 Creates a random amount of hurricanes. Caster has air magic skill*10% chance of directing each hurricane to a safe province.</td></tr>
<tr><td>Thau 9</td><td>Winds of Arcane Drought</td><td>A7S6</td><td>90</td><td>-</td><td>-</td><td>NUW</td></tr>
<tr class="spell-desc"><td colspan="7">The caster creates an enormous whirlwind that originates in the province where the ritual is performed. With the help of astral magic the whirlwind will be sucked dry of any magical energies and then when it sweeps out over the world it will absorb elemental magic to replenish itself. The absorbed magic is then distilled into pure air gems at the origin. All elemental gem producing sites within range will have their output severely reduced as their magic is absorbed by the wind instead. Air being light is most affected, leaving nothing left and earth being heavy is least affected. Sites and rituals that extend the range of air rituals from a province will help the winds reach further. All sites within a range of 6 provinces have their elemental gem output reduced (air -100%, water/fire -50%, earth -25%). The stolen gems will be gained as air gems (1/2 conversion ratio, except for air). Affects non yet found magic sites as well. Underwater and cave provinces are not affected. Worldwide +1 drain, in range +3 drain, origin +5 drain scale.</td></tr>
</tbody></table>
```

## Water Rituals

```{=html}
<table class="table spell-table">
<thead><tr><th>School</th><th>Ritual Name</th><th>Path</th><th>Cost</th><th>Rng</th><th>Dmg</th><th>Special</th></tr></thead>
<tbody>
<tr><td>Ench 7</td><td>Thetis&#x27; Blessing</td><td>W5</td><td>50</td><td>-</td><td>-</td><td></td></tr>
<tr class="spell-desc"><td colspan="7">Allows all troops in the world to enter the sea and breathe under water. Fighting below the surface will still be a little awkward for those not used to it, but at least it will be doable. Poor Amphibian penalty: CS -half, Att -1, Def -2, Enc +1</td></tr>
<tr><td>Ench 7</td><td>Ghost Ship Armada</td><td>W5D3</td><td>60</td><td>-</td><td>-</td><td></td></tr>
<tr class="spell-desc"><td colspan="7">This spell will awaken the dead Admiral Torgrin and make him fight for your cause. The Admiral will attack random coastal provinces controlled by your enemies and plunder it. The gold will be returned to the caster of the enchantment and the dead will be used to build up the armada. Once enough people have been killed the Admiral will create a new ghost armada. If the main armada with Admiral Torgrin is defeated no new armadas will be created. Once all armadas are defeated the enchantment will dissipate.</td></tr>
<tr><td>Ench 8</td><td>Wrath of the Sea</td><td>W5</td><td>70</td><td>-</td><td>-</td><td></td></tr>
<tr class="spell-desc"><td colspan="7">The sea will rise and flood all coastal provinces within just a few months. Provinces that are struck by the flood will have their income and population growth reduced. Once the enchantment is gone the flooded provinces will slowly start to return to normal. Coastal provinces and provinces with lakes will get income -30% and population growth -0.4%.</td></tr>
<tr><td>Evo 8</td><td>Maelstrom</td><td>W6</td><td>80</td><td>-</td><td>-</td><td>UW</td></tr>
<tr class="spell-desc"><td colspan="7">A huge magical maelstrom is created in a sea. The maelstrom constantly sucks in huge amounts of water and filters out its magical essence. This results in a huge amount of magic gems for the caster. Grants 15 Water, 5 astral, 3 air and 1 of each other gem type each month.</td></tr>
<tr><td>Alt 7</td><td>Sea of Ice</td><td>W6</td><td>80</td><td>-</td><td>-</td><td></td></tr>
<tr class="spell-desc"><td colspan="7">All lakes, seas and rivers in the world are frozen by this powerful enchantment. This makes travel between land and sea impossible, except by magical means such as teleportation. The frozen seas also stop Vanheim and other seafaring nations from sailing.</td></tr>
<tr><td>Conj 8</td><td>Guardians of the Deep</td><td>W6</td><td>60</td><td>-</td><td>-</td><td>UW</td></tr>
<tr class="spell-desc"><td colspan="7">Sea monsters will help the local militia defend underwater provinces for as long as this spell is in effect. The defending monsters are dependent on the terrain and type of sea. The monsters require some small degree of leadership and guidance, so a small local defence is required for the enchantment to have any effect, but sometimes a group of monsters can emerge and attack enemy provinces under your dominion. The global enchantment will last until it is dispelled or the caster dies.</td></tr>
<tr><td>Thau 7</td><td>Vengeful Water</td><td>W7</td><td>70</td><td>-</td><td>-</td><td></td></tr>
<tr class="spell-desc"><td colspan="7">The caster chains the seven pillars of water to his god&#x27;s command. Wherever the pretender god has influence water will rise up and strike down any heathens that plot against him. Water in friendly dominion will animate and try to kill enemy commanders whenever possible. The elemental is stronger in provinces with a rich water supply than in dry provinces. A waste with no access to water will never get any attacks. Chance of elemental attacking: 5% + dominion * 2%.</td></tr>
</tbody></table>
```

## Earth Rituals

```{=html}
<table class="table spell-table">
<thead><tr><th>School</th><th>Ritual Name</th><th>Path</th><th>Cost</th><th>Rng</th><th>Dmg</th><th>Special</th></tr></thead>
<tbody>
<tr><td>Ench 6</td><td>Riches from Beneath</td><td>E5</td><td>70</td><td>-</td><td>-</td><td></td></tr>
<tr class="spell-desc"><td colspan="7">This enchantment transforms mining from something harsh and dangerous to a really uplifting experience. The miners can carve out gold and iron with their knives and the stone is extra soft where the valuable ore veins are as if the mountain is trying to guide them. The enchantment only works within friendly dominion and a higher dominion score will make it more effective. The enchantment gives a major boost to resource production and a minor boost to gold production, both increases depend on the resource value of the province. Also all magic sites that are income yielding mines will have their income up to doubled. Resources: +20% * dominion (max +100%). Province Income: +4% * resource value * dominion (max 5). Income from mines: +20% * dominion (max +100%).</td></tr>
<tr><td>Ench 7</td><td>Earth Blood Deep Well</td><td>E6</td><td>80</td><td>-</td><td>-</td><td>NUW</td></tr>
<tr class="spell-desc"><td colspan="7">A well, deeper than any other, is created. This well does not bring water, but rather blood from the Earth itself. This Earth Blood is then made into magical Earth gems that can be used for magic rituals. The well will work more effectively if it is created in a cave that is already deep down and thus closer to the earth blood. Generates 17 Earth gems each month (+5 if in a cave).</td></tr>
<tr><td>Thau 9</td><td>Elemental Dampening</td><td>E7S3</td><td>60</td><td>-</td><td>-</td><td></td></tr>
<tr class="spell-desc"><td colspan="7">This ritual dampens any attempt at manipulating the elemental powers. All combat spells of primarily the elemental paths will be much slower to cast. Any elemental beings summoned will be slightly weaker than usual. This dampening will also make it more difficult to perform elemental rituals and forging magic items that are mainly elemental in nature, additional gems are required when performing these activities. Elemental combat spells +100% casting time, Elemental size -1, Elemental rituals &amp; magic items +20% gem cost.</td></tr>
</tbody></table>
```

## Astral Rituals

```{=html}
<table class="table spell-table">
<thead><tr><th>School</th><th>Ritual Name</th><th>Path</th><th>Cost</th><th>Rng</th><th>Dmg</th><th>Special</th></tr></thead>
<tbody>
<tr><td>Evo 6</td><td>The Wrath of God</td><td>S5A3</td><td>70</td><td>-</td><td>9</td><td>AN</td></tr>
<tr class="spell-desc"><td colspan="7">With this enchantment, lighting will strike the enemies of the God, no matter where they are. However, the lightning bolts strike most powerfully in provinces where the God has a strong Dominion. In provinces with a high turmoil scale more thunderbolts strike. Enemies under water or inside caves are not affected. Hit chance per month: 2% + 2% * dominion + turmoil (minimum 1% chance). Damage: 9 AN</td></tr>
<tr><td>Ench 5</td><td>The Eyes of God</td><td>S5</td><td>50</td><td>-</td><td>-</td><td></td></tr>
<tr class="spell-desc"><td colspan="7">This enchantment enables the mage to see all provinces in the world. Dominions can be seen in great detail and so can discovered magic sites, but income cannot be determined exactly. Inside the God&#x27;s own Dominion income as well as any troop movements and battles can be seen in great detail. This includes the detection of any glamoured or invisible troops that are not stealthing. Patrolling units inside friendly dominion will find it much easier to detect enemy scouts and to quell unrest. The historic records for all nations can be accessed and everyone on the Hall of Fame can be inspected.</td></tr>
<tr><td>Ench 7</td><td>Stellar Focus</td><td>S5</td><td>60</td><td>-</td><td>-</td><td>NUW</td></tr>
<tr class="spell-desc"><td colspan="7">This spell focuses the light of the night sky into a crystal sphere, depriving the entire world of some of its splendor. The entire world is drained of arcana while magic flows freely in the province where the ritual was cast. The light of the sphere can be distilled into pearls of arcane power. Grants 10 Astral pearls each month. Increases Drain by +1 world wide. Increases Magic by +3 in the province where the ritual was cast.</td></tr>
<tr><td>Alt 9</td><td>Arcane Decree</td><td>S6</td><td>60</td><td>-</td><td>-</td><td></td></tr>
<tr class="spell-desc"><td colspan="7">This decree forbids anyone but the rightful Pretender God from manipulating the global enchantments. Any hostile mage trying to cast or dispel a global enchantment must first overcome the arcane decree, which will weaken the manipulation attempt even if it should manage to get through. This also applies to any dispel attempt against the arcane decree. New hostile global enchantments and dispels have their might reduced by half of the arcane decree&#x27;s might.</td></tr>
<tr><td>Evo 9</td><td>Strands of Arcane Power</td><td>S7</td><td>70</td><td>-</td><td>-</td><td></td></tr>
<tr class="spell-desc"><td colspan="7">This mighty enchantment enables the caster to project his mind to many distant places at once, via strands of arcane power. While projected, the caster will only be able to sense and affect magic, but this still makes it possible to search for magic sites and enemy mages. The caster will be able to project himself into all provinces that have a friendly Dominion. Mind Burn: 10 AN dmg (MR negates), penetration bonuses makes the MR test harder.</td></tr>
<tr><td>Ench 9</td><td>Arcane Nexus</td><td>S8</td><td>150</td><td>-</td><td>-</td><td></td></tr>
<tr class="spell-desc"><td colspan="7">This mighty enchantment absorbs magical energies worldwide to replenish the caster&#x27;s magical resources. Half of all magic gems used to cast spells and to create magic items will be absorbed into the Arcane Nexus and converted into astral pearls at a two to one ratio. The purity of Astral and Blood magic makes it impossible for the Nexus to absorb any magic when these types of spells are cast, but all other types of magic will have some of their power absorbed by the Nexus. Even when no spells are cast or no items are forged, the Nexus will absorb some ambient magic energy from the world. Gathers Astral pearls equal to a quarter of all magic gems used for rituals, forging and empowerment. Power from astral pearls and blood slaves are not gathered.</td></tr>
</tbody></table>
```

## Death Rituals

```{=html}
<table class="table spell-table">
<thead><tr><th>School</th><th>Ritual Name</th><th>Path</th><th>Cost</th><th>Rng</th><th>Dmg</th><th>Special</th></tr></thead>
<tbody>
<tr><td>Thau 6</td><td>Foul Air</td><td>D5A1</td><td>75</td><td>-</td><td>-</td><td>NUW</td></tr>
<tr class="spell-desc"><td colspan="7">The air will become polluted by a deadly disease when this enchantment is cast. Anyone who is wounded will instantly become diseased due to the foul air. This enchantment affects all land provinces in the entire world and will last until dispelled or the caster dies. Unrest will increase worldwide while the enchantment is active. Worldwide Unrest +d4.</td></tr>
<tr><td>Conj 8</td><td>Well of Misery</td><td>D6</td><td>80</td><td>-</td><td>-</td><td></td></tr>
<tr class="spell-desc"><td colspan="7">This mighty ritual is a blessing to units across the world. Diseases, old age, suffering and pains are all drained of some of their essence. All malign energies are siphoned from the world and concentrated in the Well of Misery, effectively giving the caster a huge income of magical gems of Death. Each month a large amount of death gems are generated and the growth scale is increased in all provinces of the world. Generates 21 Death gems each month. Increases growth worldwide by +2 Growth scale is increased by +5 in the province where the spell was cast. The spell is broken if the province where it was cast is lost.</td></tr>
<tr><td>Thau 9</td><td>Remnants in the Depths</td><td>D6W4</td><td>90</td><td>-</td><td>-</td><td>UW</td></tr>
<tr class="spell-desc"><td colspan="7">Massive amounts of death and disease have always been safely locked away at the bottom of the oceans. Maybe the world once had too much disease and the old pantokrator stashed away most of it there as a gesture of generosity. No one knows for sure, but many wise old people seem to remember tales of a god saving the world from a horrible plague. With this enchantment the lock will be opened, just a little, to let the death and disease out into the oceans. All seas will start to get increased death scales until they reach the maximum, at which point everyone will start to get diseased and population will die completely in just a few years time. Increases death in seas by +1/month. Increases death in coastal provinces by +1/month, but max +2. Sea provinces with +5 death spreads disease to units and kill 4% population/month.</td></tr>
<tr><td>Thau 7</td><td>Burden of Time</td><td>D7</td><td>70</td><td>-</td><td>-</td><td></td></tr>
<tr class="spell-desc"><td colspan="7">This evil enchantment will make everyone in the world age at a highly accelerated rate. Unrest will increase in the entire world and soldiers will soon become crippled and useless. While this enchantment is active, the world will become more and more desolate until everyone dies. Worldwide Population loss about -2%, worldwide Unrest +d4, death scale +2, aging for all units greatly increased.</td></tr>
<tr><td>Alt 9</td><td>Utterdark</td><td>D9</td><td>100</td><td>-</td><td>-</td><td></td></tr>
<tr class="spell-desc"><td colspan="7">The world is covered by a blanket of utter darkness. All living beings must use torches to see even a few feet in front of themselves. During the perpetual night, forces of darkness and roaming shades will attack enemy provinces. Worldwide Income and Resources -90%. Caves and deep seas are exempt from the income reduction. All battles are fought under Darkness -6. Demons, blind beings and beings with spirit sight or perfect darkvision are unaffected by this spell.</td></tr>
</tbody></table>
```

## Nature Rituals

```{=html}
<table class="table spell-table">
<thead><tr><th>School</th><th>Ritual Name</th><th>Path</th><th>Cost</th><th>Rng</th><th>Dmg</th><th>Special</th></tr></thead>
<tbody>
<tr><td>Alt 5</td><td>Mother Oak</td><td>N5</td><td>50</td><td>-</td><td>-</td><td>NUW</td></tr>
<tr class="spell-desc"><td colspan="7">The oldest and mightiest of all oaks in the realm is enchanted to become the greatest oak there ever was. The Mother Oak produces magical acorns that can be harvested and made into Nature gems. Grants 10 Nature gems each month. The Oak increases Growth by +2 in the province where it is cast.</td></tr>
<tr><td>Ench 8</td><td>Haunted Forest</td><td>N5D1</td><td>60</td><td>-</td><td>-</td><td>NUW</td></tr>
<tr class="spell-desc"><td colspan="7">Vines will merge with anyone killed in the God&#x27;s Dominion, creating an undead Manikin. The Manikin will fight any enemies of the God for a short while before it is totally dissolved by the vines. Undead or inanimate beings are not affected by the spell.</td></tr>
<tr><td>Ench 7</td><td>Gift of Health</td><td>N6</td><td>50</td><td>-</td><td>-</td><td></td></tr>
<tr class="spell-desc"><td colspan="7">This gift grants excellent health to all loyal subjects inside the God&#x27;s Dominion. The gifted ones receive extra hit points, grow old more slowly and may even heal permanent afflictions. Just like most healing effects, lifeless, undead and spiritform beings are not affected. HP +10% per dominion. Chance of healing afflictions: about 10% * dominion. Aging reduced by half.</td></tr>
<tr><td>Conj 9</td><td>Enchanted Forests</td><td>N7</td><td>90</td><td>-</td><td>-</td><td>NUW</td></tr>
<tr class="spell-desc"><td colspan="7">All forests will start to whisper the hymns to the pretender that controls this enchantment. This will spread dominion to the places where false pretenders were worshiped. When a forest has the right dominion it will start to attack instead of whispering hymns. Enemies in that province or neighboring provinces will be attacked by creatures of the awakening forest. All forests (including cave forests) under neutral or enemy dominion spread dominion as if they were temples of the caster&#x27;s pretender. Forests with friendly dominion will spontaneously spawn attacks in the province or enemy controlled neighboring provinces. A strong dominion and high Growth scale helps the effectiveness of the attacks. Wastelands are never attacked.</td></tr>
<tr><td>Ench 9</td><td>Gift of Nature&#x27;s Bounty</td><td>N7</td><td>70</td><td>-</td><td>-</td><td></td></tr>
<tr class="spell-desc"><td colspan="7">All life in the God&#x27;s Dominion is blessed. Grain grows more quickly, the mustard tastes better, the ducks are fatter and all living creatures mate and give birth to young. The income of lands under the God&#x27;s Dominion is greatly increased. Income: +15% per dominion, growth scale +1 per dominion.</td></tr>
</tbody></table>
```

## Glamour Rituals

```{=html}
<table class="table spell-table">
<thead><tr><th>School</th><th>Ritual Name</th><th>Path</th><th>Cost</th><th>Rng</th><th>Dmg</th><th>Special</th></tr></thead>
<tbody>
<tr><td>Conj 7</td><td>Wild Hunt</td><td>G5N3</td><td>50</td><td>-</td><td>-</td><td></td></tr>
<tr class="spell-desc"><td colspan="7">The caster unleashes the Wild Hunt upon the world. The Hunt is led by Herne the Lord of the Hunt, an ancient deity of the wild roaming the woodlands in search of those who have offended the wild and its inhabitants. When the Hunt has been called, powerful priests of enemy faiths will be hunted down for as long as the Lord is not slain. Apart from the main hunt led by Herne the Lord of the Hunt, there are also up to four lesser hunts that helps him hunt down less important enemy sacred commanders. Sneaking commanders might fool the lesser hunts, but Herne is extremely skilled and will find anyone eventually. Herne targets powerful enemy priests in forest provinces (including cave forests). Up to 4 lesser hunts will target any enemy sacred commanders located in forest provinces. Sneaking reduces chance of being targeted by the lesser hunts.</td></tr>
<tr><td>Thau 7</td><td>Gates of Horn and Ivory</td><td>G5</td><td>60</td><td>-</td><td>-</td><td>NUW</td></tr>
<tr class="spell-desc"><td colspan="7">The caster erects two gates into the Dreamwild. Through the first comes fulfillment and true dreams that tell of the future, from the other comes dreams of deception or despair. Rituals cast at the Gates of Horn and Ivory will have their reach extended greatly. Also a huge amount of Glamour gems can be harvested from the gates each month. Generates 15 Glamour gems each month. Increases range for glamour rituals cast in the province by +3.</td></tr>
<tr><td>Thau 8</td><td>Lure of the Deep</td><td>G5W2</td><td>70</td><td>-</td><td>-</td><td>UW</td></tr>
<tr class="spell-desc"><td colspan="7">Sirens will start to emerge from the deeps when this powerful enchantment is cast. The Sirens will sing to enemy troops and lure them down to certain death in the deeps. The lure is most persuasive in coastal and sea provinces with strong friendly Dominion. Inland provinces are not affected at all. Nations that can recruit Sirens will find that this is cheaper while this enchantment is in effect. This global enchantment can only be cast in an underwater laboratory. Lure chance: 20% + dominion * 20%. Enemy dominion prevents the Lure. Easy MR check to avoid drowning.</td></tr>
<tr><td>Evo 9</td><td>Celestial Rainbow</td><td>G7W5</td><td>80</td><td>-</td><td>-</td><td>NUW</td></tr>
<tr class="spell-desc"><td colspan="7">This ritual creates a rainbow large enough to be seen from everywhere in the world. The mage can direct where he wants the rainbow to appear and by doing this huge amounts of gold can easily be collected at the base of the rainbow. While the rainbow is in place luck will increase in all the caster&#x27;s provinces. Once the luck is positive in a province the luck of the rainbow will protect it from hostile spells. The more luck in a province, the greater chance of hostile spells failing. Gold: about 500 each month. Luck scale +2. Dome Protection: 10% per luck scale level.</td></tr>
<tr><td>Ench 8</td><td>Fata Morgana</td><td>G7</td><td>90</td><td>-</td><td>-</td><td></td></tr>
<tr class="spell-desc"><td colspan="7">Under the fata morgana life seems much easier and everyone is happy. Phantasmal Warriors will assist the local defence in defending the province against invaders. If the entire province should not be hidden from the enemy, enemy scouts will still be tricked by the illusions and likely give incorrect reports about armies present. All provinces in friendly dominion will be affected by the fata morgana. Province Defense 1+: +2 Warrior Illusions, +1 Archer Illusion. Province Defense 20+: +1 Knight Illusion. Unrest -10 per turn. False scout reports.</td></tr>
<tr><td>Alt 8</td><td>Eternal Twilight</td><td>G8</td><td>90</td><td>-</td><td>-</td><td></td></tr>
<tr class="spell-desc"><td colspan="7">The entire world is stuck in between the day and the night, an eternal twilight. Vision is hampered and it is difficult to discern details. That which is small seems large and that which is close seems far away. Appearances are deceiving and it is difficult to separate dreams from reality. The caster&#x27;s dominion will protect friendly provinces from any adverse effects, but outside people will struggle in their daily labor. Hostile units must be constantly suspicious of what they see, or they will wander off a cliff or maybe into the sea. This enchantment requires the presence of a single sun in order to function properly. All provinces get +1 magic scale and all battles have the Twilight effect. Lands that are hostile or outside dominion get -10% income and -20% resources. Hostile units risk getting tricked and die (morale + MR check), this risk is lower in densely populated provinces.</td></tr>
<tr><td>Thau 9</td><td>Dreams of the Awakening</td><td>G8</td><td>90</td><td>-</td><td>-</td><td>God</td></tr>
<tr class="spell-desc"><td colspan="7">Everywhere where it is not yet worshiped, people will start dreaming of the rightful Pretender God. Maybe just a glimpse of its wonderful promises, maybe an excruciating nightmare showing what can befall its enemies. All provinces without friendly dominion have an 85% chance of gaining one dominion spread.</td></tr>
</tbody></table>
```

## Blood Rituals

```{=html}
<table class="table spell-table">
<thead><tr><th>School</th><th>Ritual Name</th><th>Path</th><th>Cost</th><th>Rng</th><th>Dmg</th><th>Special</th></tr></thead>
<tbody>
<tr><td>Blood 9</td><td>Astral Corruption</td><td>B6S6</td><td>166</td><td>-</td><td>-</td><td>NUW</td></tr>
<tr class="spell-desc"><td colspan="7">This horrible ritual is the cause of Blood magic being banned in ancient times. With an awesome sacrifice, the fabric of astral space becomes tainted with blood. All spell casting uses the tainted Arcana and attracts the attention of Horrors. Every time a non-Blood magic ritual is cast, a magic item is forged or a mage is empowering himself, there is a chance that a Horror will follow the arcane flow and attack the mage. The more gems spent the greater the chance of attracting a horror.</td></tr>
<tr><td>Blood 7</td><td>Blood Moon</td><td>B7S5</td><td>90</td><td>-</td><td>-</td><td>NUW</td></tr>
<tr class="spell-desc"><td colspan="7">By making an enormous blood sacrifice when both the stars and the moon are right, it is possible to imbue the moon with the power of the blood. The moon will turn red as blood and as long as it is visible in the night sky, performing blood magic during the night will be much easier. The moon turning red is a powerful sign of misfortune and that will be felt in the entire world. All blood mages will start to perform their rituals under the moon at night and have their power increased for rituals and blood hunting. The moon will not have any effect in caves, underwater or if there is no night, e.g. in the presence of two suns. Blood magic level +1 for rituals and blood searching. Misfortune +2 worldwide.</td></tr>
<tr><td>Blood 8</td><td>Blood Vortex</td><td>B7</td><td>166</td><td>-</td><td>-</td><td>NUW</td></tr>
<tr class="spell-desc"><td colspan="7">This horrifying ritual creates the blood vortex. A churning pool of polluted blood that roars horrible yet terribly alluring songs. The song of the vortex is heard by all mortals in the world, whispering sweet melodies of death and carnage, beckoning all people to come bask in its crimson presence. Its song is especially strongly felt by those whose blood is suitable for blood rituals, summoning them to the site of the ritual. The mortals that enter its presence stare dumbfounded on the waves and swirls in the vortex, or throw themselves heedlessly to drown in the bloody swirls. The master of the ritual then collects suitable victims to use in other rituals. Eventually, when no life is left in the world around the vortex, it dries out and dies. Provinces with strong influences of order will be less affected by the beckoning and those with strong turmoil influences will be more drawn to the vortex.</td></tr>
<tr><td>Blood 9</td><td>The Looming Hell</td><td>B8</td><td>150</td><td>-</td><td>-</td><td>NUW</td></tr>
<tr class="spell-desc"><td colspan="7">Devils will appear in the dreams of some unfortunate enemies whenever they try to sleep. These Devils, through various threats, will try to persuade their victims to sell their souls and join in the killing of their own commander. The strength of the threats depends on the strength of the God&#x27;s Dominion, but extreme courage is always required to defy the Devils. The Devils are totally powerless if they are unable to persuade any victims, which may well happen should the enemy commander be more feared than they are. Up to 5 random enemy units inside the dominion will be offered to sell their souls. Morale save vs 10 + dominion to refuse (4 easier to refuse if the commander has fear).</td></tr>
</tbody></table>
```

## National Rituals: Mekone (age 1)

```{=html}
<table class="table spell-table">
<thead><tr><th>School</th><th>Ritual Name</th><th>Path</th><th>Cost</th><th>Rng</th><th>Dmg</th><th>Special</th></tr></thead>
<tbody>
<tr><td>Thau 7</td><td>Gigantomachia</td><td>E4F4</td><td>60</td><td>-</td><td>-</td><td></td></tr>
<tr class="spell-desc"><td colspan="7">The war upon the gods is declared. Trembling and cowering in fear, false gods sense the rattling of spears forged for the armies of the giants. The will of false pretenders withdraw from the might of the giants who gather in ever greater numbers. Recruitment limit in friendly dominion +1, dominion gains a +3 conflict bonus, Mekone and Phlegran giants recruitment cost -10</td></tr>
</tbody></table>
```

## National Rituals: Yomi (age 1)

```{=html}
<table class="table spell-table">
<thead><tr><th>School</th><th>Ritual Name</th><th>Path</th><th>Cost</th><th>Rng</th><th>Dmg</th><th>Special</th></tr></thead>
<tbody>
<tr><td>Thau 6</td><td>End of Culture</td><td>F5</td><td>60</td><td>-</td><td>-</td><td></td></tr>
<tr class="spell-desc"><td colspan="7">This is the End of Culture for the entire world as chaos will increase worldwide. Spawn rate of Oni, both from temples under friendly dominion and from Oni generals will be greatly increased.</td></tr>
</tbody></table>
```

## National Rituals: Xibalba (age 1)

```{=html}
<table class="table spell-table">
<thead><tr><th>School</th><th>Ritual Name</th><th>Path</th><th>Cost</th><th>Rng</th><th>Dmg</th><th>Special</th></tr></thead>
<tbody>
<tr><td>Ench 8</td><td>Theft of the Sun</td><td>D6F3</td><td>70</td><td>-</td><td>-</td><td>NUW</td></tr>
<tr class="spell-desc"><td colspan="7">Since the disappearance of the Sun, the Zotz have longed for the warmth and reputed splendor of the celestial entity. With this spell the sorcerer lures the Sun from its heavenly abode to once more travel through Xibalba during the night. But the intent is a malicious one, for once the Sun has entered the labyrinthine caverns of Xibalba it is led astray and trapped in the Cavern of the Sun, giving its splendor to the Sun Guides and its fiery magic to the Ah K&#x27;in. With only the moon and the stars lighting the sky, the world is plunged into darkness. Grants 10 fire gems and 5 astral pearls each month. Worldwide darkness, income -30%, resources -30% (does not affect caves and deep seas).</td></tr>
</tbody></table>
```

## National Rituals: Niefelheim (age 1)

```{=html}
<table class="table spell-table">
<thead><tr><th>School</th><th>Ritual Name</th><th>Path</th><th>Cost</th><th>Rng</th><th>Dmg</th><th>Special</th></tr></thead>
<tbody>
<tr><td>Blood 6</td><td>Illwinter</td><td>B5W3</td><td>120</td><td>-</td><td>-</td><td>NUW</td></tr>
<tr class="spell-desc"><td colspan="7">The caster sacrifices the blood of innocent virgins in an attempt to revive the old Rimtursar, ancient giants of terrible might and the ancestors of the Jotun. The giants are slow to awaken but their presence will cause blizzards, wolf attacks and severe cold all over the world. The Illwinter is the most feared of all omens and unrest will increase worldwide. Affects entire world. 50% chance of unrest +d4, Cold +1 for every 4 months, random attacks in cold provinces. Allows recruitment of one Niefel Giant in every fort for Jotun nations.</td></tr>
</tbody></table>
```

## National Rituals: Phlegra (age 2)

```{=html}
<table class="table spell-table">
<thead><tr><th>School</th><th>Ritual Name</th><th>Path</th><th>Cost</th><th>Rng</th><th>Dmg</th><th>Special</th></tr></thead>
<tbody>
<tr><td>Thau 7</td><td>Gigantomachia</td><td>E4F4</td><td>60</td><td>-</td><td>-</td><td></td></tr>
<tr class="spell-desc"><td colspan="7">The war upon the gods is declared. Trembling and cowering in fear, false gods sense the rattling of spears forged for the armies of the giants. The will of false pretenders withdraw from the might of the giants who gather in ever greater numbers. Recruitment limit in friendly dominion +1, dominion gains a +3 conflict bonus, Mekone and Phlegran giants recruitment cost -10</td></tr>
</tbody></table>
```

## National Rituals: Jotunheim (age 2)

```{=html}
<table class="table spell-table">
<thead><tr><th>School</th><th>Ritual Name</th><th>Path</th><th>Cost</th><th>Rng</th><th>Dmg</th><th>Special</th></tr></thead>
<tbody>
<tr><td>Blood 6</td><td>Illwinter</td><td>B5W3</td><td>120</td><td>-</td><td>-</td><td>NUW</td></tr>
<tr class="spell-desc"><td colspan="7">The caster sacrifices the blood of innocent virgins in an attempt to revive the old Rimtursar, ancient giants of terrible might and the ancestors of the Jotun. The giants are slow to awaken but their presence will cause blizzards, wolf attacks and severe cold all over the world. The Illwinter is the most feared of all omens and unrest will increase worldwide. Affects entire world. 50% chance of unrest +d4, Cold +1 for every 4 months, random attacks in cold provinces. Allows recruitment of one Niefel Giant in every fort for Jotun nations.</td></tr>
</tbody></table>
```

## National Rituals: Phlegra (age 3)

```{=html}
<table class="table spell-table">
<thead><tr><th>School</th><th>Ritual Name</th><th>Path</th><th>Cost</th><th>Rng</th><th>Dmg</th><th>Special</th></tr></thead>
<tbody>
<tr><td>Thau 7</td><td>Gigantomachia</td><td>E4F4</td><td>60</td><td>-</td><td>-</td><td></td></tr>
<tr class="spell-desc"><td colspan="7">The war upon the gods is declared. Trembling and cowering in fear, false gods sense the rattling of spears forged for the armies of the giants. The will of false pretenders withdraw from the might of the giants who gather in ever greater numbers. Recruitment limit in friendly dominion +1, dominion gains a +3 conflict bonus, Mekone and Phlegran giants recruitment cost -10</td></tr>
</tbody></table>
```

## National Rituals: Utgård (age 3)

```{=html}
<table class="table spell-table">
<thead><tr><th>School</th><th>Ritual Name</th><th>Path</th><th>Cost</th><th>Rng</th><th>Dmg</th><th>Special</th></tr></thead>
<tbody>
<tr><td>Blood 6</td><td>Illwinter</td><td>B5W3</td><td>120</td><td>-</td><td>-</td><td>NUW</td></tr>
<tr class="spell-desc"><td colspan="7">The caster sacrifices the blood of innocent virgins in an attempt to revive the old Rimtursar, ancient giants of terrible might and the ancestors of the Jotun. The giants are slow to awaken but their presence will cause blizzards, wolf attacks and severe cold all over the world. The Illwinter is the most feared of all omens and unrest will increase worldwide. Affects entire world. 50% chance of unrest +d4, Cold +1 for every 4 months, random attacks in cold provinces. Allows recruitment of one Niefel Giant in every fort for Jotun nations.</td></tr>
</tbody></table>
```

## National Rituals: Vaettiheim (age 3)

```{=html}
<table class="table spell-table">
<thead><tr><th>School</th><th>Ritual Name</th><th>Path</th><th>Cost</th><th>Rng</th><th>Dmg</th><th>Special</th></tr></thead>
<tbody>
<tr><td>Blood 6</td><td>Illwinter</td><td>B5W3</td><td>120</td><td>-</td><td>-</td><td>NUW</td></tr>
<tr class="spell-desc"><td colspan="7">The caster sacrifices the blood of innocent virgins in an attempt to revive the old Rimtursar, ancient giants of terrible might and the ancestors of the Jotun. The giants are slow to awaken but their presence will cause blizzards, wolf attacks and severe cold all over the world. The Illwinter is the most feared of all omens and unrest will increase worldwide. Affects entire world. 50% chance of unrest +d4, Cold +1 for every 4 months, random attacks in cold provinces. Allows recruitment of one Niefel Giant in every fort for Jotun nations.</td></tr>
</tbody></table>
```

