# Other Rituals

The spells listed here are rituals which do not summon creatures and are not global
enchantments. This is an artificial distinction for the purposes of the manual only; for game
purposes, all rituals are subject to the rules for rituals and are treated as such.

Rituals marked **anonymous** can target the enemy without them knowing who cast the ritual or
where it originated from. For some rituals the enemy might not even be sure if it was a random
event or a hostile ritual. The **Special** column holds each ritual's effect description (with
any flags such as NUW or AP first).

## Fire Rituals

```{=html}
<table class="table spell-table">
<thead><tr><th>School</th><th>Ritual Name</th><th>Path</th><th>Cost</th><th>Rng</th><th>Dmg</th><th>Special</th></tr></thead>
<tbody>
<tr><td>Alt 1</td><td>Distill Gold</td><td>F1</td><td>10</td><td>-</td><td>-</td><td>+250 gold</td></tr>
<tr class="spell-desc"><td colspan="7">The alchemist distills gold from minerals. The process is time consuming and requires the alchemist to use fire gems.</td></tr>
<tr><td>Alt 3</td><td>Inner Sun</td><td>F1S1</td><td>1</td><td>-</td><td>-</td><td>UndIm</td></tr>
<tr class="spell-desc"><td colspan="7">This spell provides the mage with a way to retaliate when attacked by undead warriors. When the mage is slain, a shower of light will shoot forth from the body and burn all undead beings in the vicinity. The Inner Sun spell is a ritual and will last until the mage is killed. Explosion: 15 AN MR dmg (undeads and demons only), 35 AoE</td></tr>
<tr><td>Alt 5</td><td>Transmute Fire</td><td>F2</td><td>10</td><td>-</td><td>-</td><td>+350 gold</td></tr>
<tr class="spell-desc"><td colspan="7">The alchemist transmutes fire gems into gold. Every gem spent gives the alchemist several pounds of gold.</td></tr>
<tr><td>Thau 3</td><td>Augury</td><td>F2</td><td>2</td><td>5</td><td>-</td><td>NUW</td></tr>
<tr class="spell-desc"><td colspan="7">The caster pours oil on a pile of soil from a distant province and sets it ablaze. The flickering flames will reveal all hidden sites of fiery power in the province.</td></tr>
<tr><td>Evo 4</td><td>Breath of the Desert</td><td>F3A1</td><td>5</td><td>5</td><td>-</td><td>NUW, Anon, Lim</td></tr>
<tr class="spell-desc"><td colspan="7">The caster curses a distant province with a dramatic rise in temperature. The mage can target any province of his choice and those affected will not know who has cast this spell upon them. Heat scale +3, Population -5%.</td></tr>
<tr><td>Thau 5</td><td>Pyre of Catharsis</td><td>F3</td><td>4</td><td>-</td><td>-</td><td>InanimIm, NUW</td></tr>
<tr class="spell-desc"><td colspan="7">Catharsis was once the spirit of the Purifying Flames. He would cleanse bodily sicknesses of those who exposed themselves to his flames. Since his corruption by the Daevas and the wicked Mainyus he no longer controls the Purifying Flames and any powerful fire mage can wield his flames. With this ritual the caster sets himself ablaze on a pyre of Purifying Flames. The flames burns away any diseases he carries, but the caster is likely to suffer terribly from the flames unless properly protected.</td></tr>
<tr><td>Evo 4</td><td>Fate of Oedipus</td><td>F4</td><td>75</td><td>-</td><td>-</td><td></td></tr>
<tr class="spell-desc"><td colspan="7">The caster punishes a mage for having claimed the Eyes of God. The mage&#x27;s eyes are blasted by brilliance, his eye sockets emptied forever, and the Eyes of God no longer observe the world. This spell can only be cast if the Eyes of God enchantment is active.</td></tr>
<tr><td>Evo 5</td><td>Fires from Afar</td><td>F4</td><td>10</td><td>3</td><td>20+</td><td>AP, NUW, Anon</td></tr>
<tr class="spell-desc"><td colspan="7">The mage fires a row of flame bolts towards an enemy army camp located in a province far away. The more units present in the camp, the greater the chance of hitting a target. The spell can also be used to harass a besieging force or the defenders of a castle. A scout or a scrying spell will be required to see whether the spell was successful or not.</td></tr>
<tr><td>Evo 9</td><td>Volcanic Eruption</td><td>F4E3</td><td>25</td><td>6</td><td>-</td><td>NUW, Anon</td></tr>
<tr class="spell-desc"><td colspan="7">The caster unleashes a volcanic eruption upon a distant province, destroying the lands and killing one third of the population. Population -30%, Unrest +30.</td></tr>
<tr><td>Ench 7</td><td>Dome of Flaming Death</td><td>F4</td><td>8</td><td>-</td><td>-</td><td>NUW</td></tr>
<tr class="spell-desc"><td colspan="7">An invisible web of Fire magic is created over the entire province where this spell is cast. Any enemy spells cast into the protected province will trigger the deadly trap. A powerful blast of fire will find its way to the casting mage and burn him and possibly also the laboratory to cinders. The more magic gems put into the spell, the longer the dome lasts. If the mage who cast the dome dies, the dome dissolves instantly. The dome does not stop spells that pass through it, but it may stop the offending mage from ever casting spells again. Dome Trap: 2d20 AP fire dmg. Luck scale reduces the chance of the laboratory burning down. Friendly casters will also be affected.</td></tr>
<tr><td>Thau 5</td><td>Raging Hearts</td><td>F4</td><td>10</td><td>5</td><td>-</td><td>Anon</td></tr>
<tr class="spell-desc"><td colspan="7">Fury will start to grow in the hearts of all people in an entire province. Those affected will soon start to plunder and kill their fellow citizens. A mage can target any province of his choice and those affected will not know who has cast this spell on them. Population -5%, Unrest +60.</td></tr>
<tr><td>Evo 7</td><td>Elemental Opposition of</td><td>F5</td><td>60</td><td>-</td><td>-</td><td>Water</td></tr>
<tr class="spell-desc"><td colspan="7">The caster channels vast amounts of Fire Arcana against all active Global Water Enchantments to simultaneously dispel them. The gems spent, in excess of the cost to cast the spell, is compared to the gems used to overcast each of the Global Enchantments. If the Opposition matches any of the Globals, that Global is dispelled.</td></tr>
<tr><td>Evo 9</td><td>Flames from the Sky</td><td>F5</td><td>30</td><td>4</td><td>20+</td><td>AP, NUW, Anon</td></tr>
<tr class="spell-desc"><td colspan="7">With this spell, the mage hurls a maelstrom of flaming spheres towards an enemy province. The flame storm will strike an enemy army camp within the province with enormous force. Most likely, the majority of the units present will die from this powerful attack, but units resistant to fire or more sturdy than ordinary humans have a good chance of surviving. Through this ritual, the fire mage will also be able to see exactly what is happening as the flaming spheres strike the enemy.</td></tr>
<tr><td>Ench 6</td><td>Vafur Flames</td><td>F5</td><td>10</td><td>-</td><td>-</td><td>NUW, Fort only</td></tr>
<tr class="spell-desc"><td colspan="7">This spell recreates the legendary enchantment of Asgård. The fortress is surrounded by a ring wall of enchanted flames. The flames are able to read the intentions of those who approach and will let friends pass safely through. Flying beings that pass over the flames will still be put on fire, but the damage will be less severe than for those walking through. Enemies walking through: 10 AP fire dmg. Enemies flying through: 5 AP fire dmg. Enchantments lasts 1 turn + 3 turns / extra gem.</td></tr>
<tr><td>Thau 6</td><td>Choleria</td><td>F5</td><td>20</td><td>5</td><td>-</td><td></td></tr>
<tr class="spell-desc"><td colspan="7">The caster affects a friendly province with the humor of fire, choleria. The populace becomes energetic and productive, but also easy to anger. Production and income are increased, but quarrels are common and unrest will gradually increase. Scale of Production is increased by 2. Unrest increases by 1d6 each month. The enchantment lasts longer if more gems are used in the casting.</td></tr>
</tbody></table>
```

## Air Rituals

```{=html}
<table class="table spell-table">
<thead><tr><th>School</th><th>Ritual Name</th><th>Path</th><th>Cost</th><th>Rng</th><th>Dmg</th><th>Special</th></tr></thead>
<tbody>
<tr><td>Ench 4</td><td>Cloud Trapeze</td><td>A2</td><td>3</td><td>5</td><td>-</td><td>NUW</td></tr>
<tr class="spell-desc"><td colspan="7">The caster swings himself up and away with incredible speed, landing in a province far away. Although much faster than normal flying, the caster does not really teleport and can have the path blocked by impassable mountains ranges or the Sea of Ice global enchantment.</td></tr>
<tr><td>Thau 3</td><td>Carrier Birds</td><td>A2</td><td>2</td><td>4</td><td>-</td><td>NUW</td></tr>
<tr class="spell-desc"><td colspan="7">This ritual summons a large flock of birds that will quickly transport the mage&#x27;s magic gems to a commander in another province. A maximum of 15 magic gems can be transported and blood slaves are too heavy to be carried at all. The commander who receives the gems cannot belong to another nation.</td></tr>
<tr><td>Thau 3</td><td>Carrier Eagle</td><td>A2</td><td>3</td><td>4</td><td>-</td><td>NUW</td></tr>
<tr class="spell-desc"><td colspan="7">This ritual summons a large eagle that will quickly transport a magic item to a commander in another province. Heavy items cannot be transported by this ritual. The commander who receives the magic item cannot belong to another nation.</td></tr>
<tr><td>Thau 4</td><td>Auspex</td><td>A2</td><td>2</td><td>2</td><td>-</td><td>NUW</td></tr>
<tr class="spell-desc"><td colspan="7">The caster listens to the winds and observes the flight of birds. The winds will carry legends of magical places and ancient storms. If the winds are correctly interpreted, the caster gains knowledge of sites of Air power in a distant province. This spell cannot be cast at an enemy province.</td></tr>
<tr><td>Evo 4</td><td>Hurricane</td><td>A3</td><td>5</td><td>5</td><td>-</td><td>NUW, Anon, Lim</td></tr>
<tr class="spell-desc"><td colspan="7">The caster unleashes a violent hurricane upon a province, devastating the countryside. The hurricane will appear as a natural event. Unrest will increase and part of the population will die.</td></tr>
<tr><td>Ench 3</td><td>Seeking Arrow</td><td>A3</td><td>4</td><td>3</td><td>8</td><td>AN, Anon</td></tr>
<tr class="spell-desc"><td colspan="7">The caster sends an enchanted arrow across the world to find a suitable heart to penetrate. The arrow will target one leader in a province of the caster&#x27;s choice. 8 AN magic dmg that always hits the chest.</td></tr>
<tr><td>Evo 7</td><td>Thunderstorm</td><td>A4</td><td>30</td><td>3</td><td>28+</td><td>AN, NUW, Anon</td></tr>
<tr class="spell-desc"><td colspan="7">The caster unleashes a devastating thunderstorm upon an enemy army. Lightning strikes randomly hit the army, killing and maiming many. The storm is localized and doesn&#x27;t affect the civilian population of the province.</td></tr>
<tr><td>Conj 5</td><td>Raven Feast</td><td>A4</td><td>3</td><td>5</td><td>-</td><td>NUW</td></tr>
<tr class="spell-desc"><td colspan="7">The caster summons an unkindness of ravens and sends them into a distant province to feast upon the newly dead. The ravens consume the rotting corpses and return to be slaughtered for the raw death essence they then contain. Provinces struck by plagues or containing recent battlefields can give the caster large amounts of Death gems. All unburied dead in a province are consumed. Enemy provinces can be targeted. Death gems gained from a province with about 100 unburied corpses: 5. Death gems gained from a province with about 400 unburied corpses: 10.</td></tr>
<tr><td>Conj 5</td><td>Messenger Crows</td><td>A4</td><td>6</td><td>4</td><td>-</td><td></td></tr>
<tr class="spell-desc"><td colspan="7">The caster sends out a vast murder of crows to scout a distant province. The birds will continue to scout the province until the spell ends or until the province is lost. Enemy scouts and sneaking armies will become aware that crows are present everywhere, glaring suspiciously. Patrol strength +50 patrol vs enemy units. Duration: 1 month + 3 months per extra gems.</td></tr>
<tr><td>Ench 5</td><td>Trade Wind</td><td>A4</td><td>10</td><td>-</td><td>-</td><td>NUW</td></tr>
<tr class="spell-desc"><td colspan="7">The caster creates a perpetual stable wind in a coastal province that enables merchants to quickly sail to and from the province. The trade wind will greatly increase the income from the province. The spell lasts longer for every gem spent on the ritual. The enchantment will dissipate if the province is lost. Coastal province income +25%.</td></tr>
<tr><td>Evo 7</td><td>Elemental Opposition of</td><td>A5</td><td>60</td><td>-</td><td>-</td><td>Earth</td></tr>
<tr class="spell-desc"><td colspan="7">The caster channels vast amounts of Air Arcana against all active Global Earth Enchantments to simultaneously dispel them. The gems spent, in excess of the cost to cast the spell, is compared to the gems used to overcast each of the Global Enchantments. If the Opposition matches any of the Globals, that Global is dispelled.</td></tr>
<tr><td>Conj 5</td><td>Wind Ride</td><td>A5</td><td>10</td><td>3</td><td>-</td><td>NUW</td></tr>
<tr class="spell-desc"><td colspan="7">The Air mage summons a whirlwind in a province of his choice. The whirlwind will try to find a commander in the province and transport him to where the Air mage is located. This spell is an effective way to rescue cornered commanders, but it can also be a very effective way to get enemy commanders out of the way. Large beings are difficult or impossible to lift and might fall to the ground somewhere along the way, possibly dying upon impact. Powerful Earth mages are likewise difficult to transport. Size 8+ targets, earth 4+ mages and ethereal beings are impossible to lift. Skilled air mages will take less damage from falling.</td></tr>
<tr><td>Ench 6</td><td>Dome of Solid Air</td><td>A5</td><td>20</td><td>-</td><td>-</td><td>NUW</td></tr>
<tr class="spell-desc"><td colspan="7">A dome made out of air is created over the entire province the mage is in. The dome will protect the province from many spells that originate outside the warded province. While undisturbed, the spell will last indefinitely, but if a spell passes through the dome, or if the mage who cast the dome dies, it will shatter instantly. Dome Protection 80%. Destroyed if it fails to block a spell. Friendly spells will also be blocked.</td></tr>
<tr><td>Thau 6</td><td>Sanguinia</td><td>A5</td><td>20</td><td>5</td><td>-</td><td></td></tr>
<tr class="spell-desc"><td colspan="7">The caster affects a friendly province with the humor of air, sanguinia. Sanguine people are enthusiastic, social and active. The province will become a place of merriment, festivities and good spirits. Unrest will continuously decrease in the province. Unrest is reduced by 1d6 each month. The enchantment lasts longer if more gems are used in the casting.</td></tr>
</tbody></table>
```

## Water Rituals

```{=html}
<table class="table spell-table">
<thead><tr><th>School</th><th>Ritual Name</th><th>Path</th><th>Cost</th><th>Rng</th><th>Dmg</th><th>Special</th></tr></thead>
<tbody>
<tr><td>Thau 2</td><td>Scrying Pool</td><td>W1G1</td><td>2</td><td>5</td><td>-</td><td>NUW</td></tr>
<tr class="spell-desc"><td colspan="7">The mage will enchant a pool of water to provide images of a province far away. The more magic gems spent on the scrying pool, the longer it will last. The information gained by scrying is much more accurate than a normal scout can provide.</td></tr>
<tr><td>Conj 4</td><td>Voice of Apsu</td><td>W2</td><td>2</td><td>3</td><td>-</td><td></td></tr>
<tr class="spell-desc"><td colspan="7">The caster conjures the dreams of Apsu, the Fresh Water Underneath. He has knowledge of all sweet water. The voice of his dreams, when rightly interpreted, reveals sites of Water power located above the surface. The dreams will find their way to everyone living in the targeted province and the magical sites will no longer be hidden.</td></tr>
<tr><td>Conj 5</td><td>Voice of Tiamat</td><td>W2</td><td>8</td><td>4</td><td>-</td><td>UW</td></tr>
<tr class="spell-desc"><td colspan="7">The caster conjures up the dreams of Tiamat, the Raging Sea. She has knowledge of all that lies underneath the sea. The voice of her dreams, when rightly interpreted, reveals all sites of Elemental power in a sea. The dreams will find their way to everyone living in that province and the magical sites will no longer be secret. This spell can only be cast under water.</td></tr>
<tr><td>Alt 4</td><td>Wolven Winter</td><td>W3</td><td>5</td><td>5</td><td>-</td><td>Anon, Lim</td></tr>
<tr class="spell-desc"><td colspan="7">The caster curses a distant province with a dramatic fall in temperature. The mage can target any province of his choice and those affected will not know who has cast this spell upon them. Cold scale +3, Population -5%.</td></tr>
<tr><td>Evo 7</td><td>Murdering Winter</td><td>W5</td><td>40</td><td>4</td><td>8</td><td>AN, Anon, Lim</td></tr>
<tr class="spell-desc"><td colspan="7">A sudden, furious blizzard will strike an enemy army camp in a province of the mage&#x27;s choice. The blizzard is very powerful and will kill most normal men unless they are located in a hot province. The spell will be extremely powerful if it is cast in a very cold province and almost useless if cast in a very hot province. The spell has a very large area of effect and most of the enemy army is likely to be affected. Commanders have access to the good tents and will take reduced damage from the cold. The ritual can target cave provinces, but the effect will be much reduced there.</td></tr>
<tr><td>Evo 7</td><td>Elemental Opposition of</td><td>W5</td><td>60</td><td>-</td><td>-</td><td>Fire</td></tr>
<tr class="spell-desc"><td colspan="7">The caster channels vast amounts of Water Arcana against all active Global Fire Enchantments to simultaneously dispel them. The gems spent, in excess of the cost to cast the spell, is compared to the gems used to overcast each of the Global Enchantments. If the Opposition matches any of the Globals, that Global is dispelled.</td></tr>
<tr><td>Evo 8</td><td>Tidal Wave</td><td>W5</td><td>15</td><td>6</td><td>-</td><td>Anon</td></tr>
<tr class="spell-desc"><td colspan="7">The caster unleashes a huge tidal wave upon a distant province, destroying the lands and killing the people. Population -30%, Unrest +50.</td></tr>
<tr><td>Alt 7</td><td>Ice Walls</td><td>W5</td><td>15</td><td>-</td><td>-</td><td>NUW, Fort only</td></tr>
<tr class="spell-desc"><td colspan="7">The caster strengthens the walls of a castle by covering them in ice, making the walls very difficult to breach. The ice walls get thicker the colder the province is and will disappear if the province should become non-cold. The alteration lasts as long as the caster remains alive, the province is cold and the fort is not conquered. The enchantment will not help an already breached wall. Wall integrity increase: 500*cold scale points Walls are magic and ethereal units cannot pass through</td></tr>
<tr><td>Ench 6</td><td>Frost Dome</td><td>W5</td><td>15</td><td>-</td><td>-</td><td></td></tr>
<tr class="spell-desc"><td colspan="7">A frost dome is created over the entire province where the spell is cast. Any spells cast into this dome will trigger the deadly trap. A powerful frost blast will find its way to the enemy mage and freeze him to death. Every spell cast into the dome has a 30 percent chance of being destroyed by the frost dome. The more magic gems put into the spell, the longer it will last. If the mage who cast the dome dies, it will dissolve instantly. Dome Protection: 30%. Dome Trap: d15 AN cold dmg. Friendly spells will also be blocked.</td></tr>
<tr><td>Thau 6</td><td>Phlegmatia</td><td>W5</td><td>20</td><td>5</td><td>-</td><td></td></tr>
<tr class="spell-desc"><td colspan="7">The caster curses a province with the humor of water, phlegmatia. The population becomes passive, quiet and unproductive. Work as well as religious duties are ignored and soldiers in the province are likely to desert. Scale of sloth is increased by 3. Dominion is reduced by 1-2. All units in the province must make a MR check vs 10 and a morale check vs 10. If they fail both they desert.</td></tr>
</tbody></table>
```

## Earth Rituals

```{=html}
<table class="table spell-table">
<thead><tr><th>School</th><th>Ritual Name</th><th>Path</th><th>Cost</th><th>Rng</th><th>Dmg</th><th>Special</th></tr></thead>
<tbody>
<tr><td>Alt 2</td><td>Alchemical Transmutation E1</td><td>10</td><td>-</td><td>-</td><td>+200 gold</td><td></td></tr>
<tr class="spell-desc"><td colspan="7">The alchemist transmutes base metals into precious ones. The process is time consuming and requires the alchemist to use earth gems.</td></tr>
<tr><td>Alt 4</td><td>Blight</td><td>E2D1</td><td>5</td><td>5</td><td>-</td><td>Anon, Lim</td></tr>
<tr class="spell-desc"><td colspan="7">The caster unleashes a blight upon a distant province. Five percent of the population will die, unrest increases and one hundred and twenty pounds of gold must be used to feed the starving. Population -5%, Unrest +15, Gold -120</td></tr>
<tr><td>Alt 6</td><td>Earth Gem Alchemy</td><td>E2</td><td>10</td><td>-</td><td>-</td><td>+300 gold</td></tr>
<tr class="spell-desc"><td colspan="7">The alchemist transmutes earth gems into precious metals. Every gem spent gives the alchemist several pounds of gold.</td></tr>
<tr><td>Thau 4</td><td>Gnome Lore</td><td>E2</td><td>3</td><td>3</td><td>-</td><td></td></tr>
<tr class="spell-desc"><td colspan="7">The caster bestows the knowledge of the gnomes upon himself and uses it to find places of Earth power. The spell will find all magic Earth sites in a friendly province of the caster&#x27;s choice.</td></tr>
<tr><td>Alt 8</td><td>Wizard&#x27;s Tower</td><td>E4</td><td>50</td><td>4</td><td>-</td><td></td></tr>
<tr class="spell-desc"><td colspan="7">The caster raises a tall impregnable stone tower from the ground in any friendly province within range. It is very difficult to break down the walls of this tower, but the administrative facilities are not to the same high standard.</td></tr>
<tr><td>Thau 5</td><td>Earth Sense</td><td>E4</td><td>6</td><td>-</td><td>-</td><td></td></tr>
<tr class="spell-desc"><td colspan="7">The caster attunes himself with the earth itself to sense who treads upon it. Enemies trying to sneak around in the province will be detected and traced, even if invisible. The spell is broken if the caster leaves the province. Patrol strength +100 vs enemy units. Able to detect invisible units as well. Duration: 1 month + 3 months per extra gems.</td></tr>
<tr><td>Evo 7</td><td>Elemental Opposition of Air E5</td><td>60</td><td>-</td><td>-</td><td></td><td></td></tr>
<tr class="spell-desc"><td colspan="7">The caster channels vast amounts of Earth arcana against all active Global Air Enchantments to simultaneously dispel them. The gems spent, in excess of the cost to cast the spell, is compared to the gems used to overcast each of the Global Enchantments. If the Opposition matches any of the Globals, that Global is dispelled.</td></tr>
<tr><td>Alt 7</td><td>Iron Walls</td><td>E5</td><td>10</td><td>-</td><td>-</td><td>Fort only</td></tr>
<tr class="spell-desc"><td colspan="7">The caster transforms the stone walls of a castle into iron walls, making it almost impregnable. The alteration lasts longer if additional gems are used in the ritual, but will end prematurely if the caster should be killed. The enchantment will not help an already breached wall. Wall integrity increase: 2000 points Walls are magic and ethereal units cannot pass through</td></tr>
<tr><td>Alt 6</td><td>Crumble</td><td>E5</td><td>20</td><td>4</td><td>-</td><td></td></tr>
<tr class="spell-desc"><td colspan="7">The caster unleashes great power upon a besieged castle. The walls of the castle will fall apart and debris will crash down upon the unwary defenders. Wall Damage: 300 +25 points for each additional Earth skill level 50% of the defenders must roll for defence or get 3 AP blunt damage.</td></tr>
<tr><td>Conj 8</td><td>Earth Attack</td><td>E5</td><td>5</td><td>4</td><td>-</td><td>Anon</td></tr>
<tr class="spell-desc"><td colspan="7">A huge Earth Elemental will appear in a province of the caster&#x27;s choice. Here, it will travel under the ground and search for enemy commanders. When it finds one, it will rise out of the ground and strike it down. The Earth Elemental disappears when it has completed this task or if it can&#x27;t find an enemy commander. The elemental can only find targets that are grounded, thus floating beings will never be attacked by the elemental.</td></tr>
<tr><td>Ench 7</td><td>Lion Sentinels</td><td>E5</td><td>30</td><td>-</td><td>-</td><td>Fort only</td></tr>
<tr class="spell-desc"><td colspan="7">The caster sculpts eleven statues of lions and enchants them with powerful magic. Ten of them are placed outside the castle walls and the eleventh on the courtyard. Order and prosperity flowers as the lions sentinels protect the inhabitants and guard them from harm. Should the castle be attacked the lions will come to life and attack the besieging army. The lions are magical beings and require magical leadership. Should the lion in the courtyard be destroyed the lions will crumble, unless a mage can take command over the remaining lions. Eleven Marble Lions guard the fortress if the castle is stormed. The enchantment also increases the order scale by +1.</td></tr>
<tr><td>Thau 6</td><td>Melancholia</td><td>E5</td><td>20</td><td>5</td><td>-</td><td></td></tr>
<tr class="spell-desc"><td colspan="7">The caster curses a province with the humor of earth, melancholia. The populace becomes depressed, cynical and listless. Peasants don&#x27;t care about harvesting and let their livestock wander. Craftsmen only work when they feel like it and soldiers tend to desert unless whipped into obedience. Even the temples are left untended. The Dominion of the local god will decrease. Scale of Sloth is increased by 2. Dominion is reduced by 2-3. All units in the province must make a MR check vs 10 and a morale check vs 10. If they fail both they desert.</td></tr>
<tr><td>Evo 9</td><td>Lost Land</td><td>E6W5</td><td>100</td><td>3</td><td>-</td><td>NUW, Anon</td></tr>
<tr class="spell-desc"><td colspan="7">This most powerful ritual will cause an entire province to slowly sink until it has become lost far under the surface of the sea. While the land sinks slowly it will still be difficult for the population to escape and those who live too far away from safety are likely to drown. Military units in the land are likely to escape if they are fast moving. If they can fly or float they are guaranteed to make it away safely if possible. One coastal province is drowned. 50% of the population dies. Units have a chance to escape depending on map move (50% at map move 10).</td></tr>
</tbody></table>
```

## Astral Rituals

```{=html}
<table class="table spell-table">
<thead><tr><th>School</th><th>Ritual Name</th><th>Path</th><th>Cost</th><th>Rng</th><th>Dmg</th><th>Special</th></tr></thead>
<tbody>
<tr><td>Evo 1</td><td>Astral Projection</td><td>S1</td><td>2</td><td>7</td><td>-</td><td></td></tr>
<tr class="spell-desc"><td colspan="7">The caster&#x27;s mind is separated from his body and travels the Astral Planes in search of military information. His mind and body are connected with a silvery cord, which can be detected by unfriendly Astral mages. Once detected, the cord of the mage can be severed - a traumatic experience indeed. Each casting of this ritual allows the mage to scry on one province. The use of extra astral pearls increases the duration of the ritual. Duration: 1 month + 1 / extra astral pearl. Astral cord detection chance = 40% * enemy mage&#x27;s astral level.</td></tr>
<tr><td>Evo 3</td><td>Arcane Probing</td><td>S1</td><td>3</td><td>4</td><td>-</td><td></td></tr>
<tr class="spell-desc"><td colspan="7">The caster projects his astral self in an attempt to locate sites of Astral power. This spell can only be used to search for magic in friendly provinces.</td></tr>
<tr><td>Conj 5</td><td>Acashic Record</td><td>S2</td><td>10</td><td>10</td><td>-</td><td></td></tr>
<tr class="spell-desc"><td colspan="7">This spell lets the caster access the acashic records to find out the history for one nation. The spell must be targeted on a capital to give any useful information.</td></tr>
<tr><td>Ench 5</td><td>Ritual of Returning</td><td>S2</td><td>3</td><td>-</td><td>-</td><td></td></tr>
<tr class="spell-desc"><td colspan="7">The mage will return to the home citadel at once if he is wounded. The spell lasts until the mage actually has been wounded and returned home. This ritual will result in swift death for a mage if the home citadel has been conquered by the enemy.</td></tr>
<tr><td>Thau 4</td><td>Astral Window</td><td>S2</td><td>3</td><td>6</td><td>-</td><td></td></tr>
<tr class="spell-desc"><td colspan="7">The caster opens an arcane rift through which he can observe distant lands. The rift closes after a while, but the duration can be prolonged if extra magic gems are used in the casting. Each casting of this ritual allows the mage to scry on one province. The information gained by this spell is much more accurate than a normal scout can provide. Duration: 1 month + 1 month per extra magic pearl</td></tr>
<tr><td>Thau 5</td><td>Teleport Item</td><td>S2</td><td>3</td><td>6</td><td>-</td><td></td></tr>
<tr class="spell-desc"><td colspan="7">This ritual can be used by an astral mage to teleport a single magic item to a commander in a province far away. Heavy items cannot be transported by this ritual. The commander who receives the magic item cannot belong to another nation.</td></tr>
<tr><td>Alt 5</td><td>Baleful Star</td><td>S3</td><td>7</td><td>7</td><td>-</td><td>NUW, Anon, Lim</td></tr>
<tr class="spell-desc"><td colspan="7">The caster invokes the great Maleficent and forces the evil star to take a conjunctive position in the heavens above one province, causing unfortunate events and evil deeds to occur. Anyone exposed to the evil star risks getting cursed for the rest of his life.</td></tr>
<tr><td>Conj 6</td><td>Acashic Knowledge</td><td>S3</td><td>25</td><td>10</td><td>-</td><td></td></tr>
<tr class="spell-desc"><td colspan="7">This spell lets the caster tap information from the memory of the Spheres to reveal the presence of all magical sites in a given province. The spell cannot be used to find magic sites in enemy provinces.</td></tr>
<tr><td>Ench 5</td><td>Dispel</td><td>S3</td><td>30</td><td>-</td><td>-</td><td></td></tr>
<tr class="spell-desc"><td colspan="7">This enchantment enables a mage to destroy an active global enchantment. The power of global enchantments is often boosted with the use of additional gems. This number of gems must be matched in order for the dispel to work.</td></tr>
<tr><td>Thau 3</td><td>Teleport Gems</td><td>S3</td><td>2</td><td>6</td><td>-</td><td></td></tr>
<tr class="spell-desc"><td colspan="7">This ritual can be used by an astral mage to teleport all his magic gems to a commander in a province far away. A maximum of 10 magic gems can be transported and blood slaves are not affected by this ritual. The commander who receives the gems cannot belong to another nation.</td></tr>
<tr><td>Thau 4</td><td>Teleport</td><td>S3</td><td>2</td><td>6</td><td>-</td><td></td></tr>
<tr class="spell-desc"><td colspan="7">With this spell, the mage can transport himself to almost any province in the world, only those very very far away are out of range for this ritual.</td></tr>
<tr><td>Evo 6</td><td>Mind Hunt</td><td>S4</td><td>2</td><td>6</td><td>-</td><td>AN, Detect, Anon</td></tr>
<tr class="spell-desc"><td colspan="7">The caster&#x27;s mind is separated from his body and travels the astral planes in search of enemy commanders&#x27; minds. His mind and body are connected with a silvery cord, which can be detected by unfriendly Astral mages. Once detected, the cord of the mage can be severed - a traumatic experience indeed. Each casting of this ritual allows the mage to find and attack one enemy commander in a specific province. The attack will be either a Mind Burn or Soul Slay spell, depending on which spell the caster knows. There will be no attack if he doesn&#x27;t know either of those spells. Astral cord detection chance = 40% * enemy mage&#x27;s astral level.</td></tr>
<tr><td>Conj 6</td><td>Ether Gate</td><td>S4D1</td><td>90</td><td>-</td><td>-</td><td></td></tr>
<tr class="spell-desc"><td colspan="7">This ritual opens a gate to the Astral Plane and summons a clan of Ether Warriors led by an Ether Lord. The Ether Warriors were banished from this world in ancient times. Their wars drained the world of Arcana and they were forced to enter other realms of existence in order to continue their clan wars. The lesser races and their gods sealed the Astral Gates to rid the world of the plague. Ether Warriors are, naturally, ethereal and thus very difficult to harm with non-magical weapons. They use Moon Blades, magical swords that cause additional damage to magical beings. When the gate opens, vast powers are released and the magic level is increased in the province. If cast with additional gems the gate will last for several months and further rituals that summons Ether Warriors will have increased effect. The Gate increases the magic scale by +2. The gate increases the number of Ether Warriors summoned from other rituals by +2.</td></tr>
<tr><td>Ench 6</td><td>Dome of Arcane Warding</td><td>S4</td><td>10</td><td>-</td><td>-</td><td></td></tr>
<tr class="spell-desc"><td colspan="7">An astral dome is created over the entire province that the mage is located in. The dome will protect the province from many spells that originate from outside the warded province. The more magic gems put into the spell, the longer it will last. If the mage dies, the dome dissolves instantly. The dome has a 50 percent chance of stopping each spell that tries to pass through it. Horror Protection: 60% (halved against doom horrors).</td></tr>
<tr><td>Ench 8</td><td>Void Pattern Labyrinth</td><td>S4G3</td><td>10</td><td>-</td><td>-</td><td></td></tr>
<tr class="spell-desc"><td colspan="7">A void pattern dome is created over the province that the mage is located in. This pattern is invisible to human perception, but horrors will see the strange pattern and get confused and led astray when trying to pass. The dome will protect the province from any horrors trying to attack from the outside, including against those drawn to horror marks. The more magic gems put into the spell, the longer it will last. If the mage dies, the void pattern labyrinth dissolves instantly. The chance of warding off a Doom Horror is lower than for normal horrors.</td></tr>
<tr><td>Ench 9</td><td>Dome of Seven Seals</td><td>S4E4</td><td>14</td><td>-</td><td>-</td><td></td></tr>
<tr class="spell-desc"><td colspan="7">A magic dome is created over the entire province. The dome offers perfect protection against hostile magic targeted at the province, while allowing friendly mages to temporarily deactivate the seals and have their spells pass through. All friendly astral mages will know how to get through the seals safely. Each time a spell is stopped by the dome, one of the seven seals will crack. Once all seals are cracked or the caster dies the dome will dissolve.</td></tr>
<tr><td>Thau 6</td><td>Imprint Souls</td><td>S4</td><td>15</td><td>5</td><td>-</td><td></td></tr>
<tr class="spell-desc"><td colspan="7">The people of a small village in a remote province will have their minds gradually broken down. When they are entirely lobotomized, their minds will be imprinted with religious zeal towards the rightful Pretender God. When the conversion is complete, they will attack the province in an attempt to conquer it and serve their God to the best of their abilities. This is a very dangerous process, many people die and most of the survivors are not fully restored with the proper religious zeal. A skillful mage and extra penetration skill from magic items will help in successful conversion of the villagers. Souls imprinted = 120 + extra level * 4. Success imprint chance: 12% + penetration strength * 6%, Death chance: 50%</td></tr>
<tr><td>Thau 6</td><td>Gateway</td><td>S4</td><td>10</td><td>6</td><td>-</td><td></td></tr>
<tr class="spell-desc"><td colspan="7">The caster creates a rift in the fabric of space, allowing him to step through with all troops under his command and enter a distant laboratory that has been prepared for the gateway. The gateway can only lead to a lab controlled by the same nation, and it closes as soon as the troops have passed through.</td></tr>
<tr><td>Thau 9</td><td>Arcane Analysis</td><td>S4</td><td>25</td><td>-</td><td>-</td><td></td></tr>
<tr class="spell-desc"><td colspan="7">With this ritual a skillful astral mage can send a thaumaturgical probe into the ether in order to examine the strength and weaknesses of a global enchantment. The mage chooses a single global enchantment to examine and he will get a fairly accurate measure of the number of astral pearls worth of overcast that would be required to dispel it.</td></tr>
<tr><td>Evo 9</td><td>Stellar Strike</td><td>S5E3</td><td>20</td><td>5</td><td>150</td><td>Anon</td></tr>
<tr class="spell-desc"><td colspan="7">By reading the stars carefully the astral mage will be able to foresee the perfect opportunity to inflict maximum damage on the enemy. When it is time a large swarm of meteors will be coaxed to fall down from the sky just as they pass above an enemy army camp in a faraway province. The astral mage will be able to observe the event as the meteors hit.</td></tr>
<tr><td>Alt 7</td><td>Enchanted Walls</td><td>S5</td><td>10</td><td>-</td><td>-</td><td>Fort only</td></tr>
<tr class="spell-desc"><td colspan="7">By enchanting the walls of a castle they will become slightly more difficult to breach, but more importantly ethereal beings will not be able to pass through the walls. Wall integrity increase: 100 Walls are magic and ethereal units cannot pass through</td></tr>
<tr><td>Ench 7</td><td>Disenchantment</td><td>S5</td><td>50</td><td>-</td><td>-</td><td></td></tr>
<tr class="spell-desc"><td colspan="7">This ritual is a more powerful Dispel. If cast at sufficient power it will destroy an active global enchantment, but if it fails it will still reduce the power of the targeted enchantment. Destroys a global enchantment if cast with enough power. Lowers the overcast level of a global enchantment by half the overcast level of Disenchantment.</td></tr>
<tr><td>Thau 7</td><td>Divine Name</td><td>S5</td><td>25</td><td>-</td><td>-</td><td></td></tr>
<tr class="spell-desc"><td colspan="7">The caster inscribes a divine name on a piece of paper and places it in the head of a mindless being. The being is gifted with an artificial mind and commanding abilities. The caster can also inscribe the name on the forehead of a willing target, increasing his mental faculties and making him a commander.</td></tr>
<tr><td>Thau 8</td><td>Astral Travel</td><td>S5</td><td>25</td><td>5</td><td>-</td><td></td></tr>
<tr class="spell-desc"><td colspan="7">The caster creates a rift in the fabric of space, allowing him to step through with all troops under his command and enter a distant province.</td></tr>
<tr><td>Thau 9</td><td>Nexus Gate</td><td>S5E3</td><td>40</td><td>-</td><td>-</td><td></td></tr>
<tr class="spell-desc"><td colspan="7">The caster enscribes and enchants a great stone archway, creating an arcane portal to Nexus, a place between places. Armies may hereafter use the portal to enter Nexus. Nexus is connected to all active Nexus Gates and individuals and armies in Nexus may leave through any gate, even those created by other Pretenders. The Nexus Gate is permanent and once created it cannot be dispelled. Dwelling in Nexus for longer than necessary is not recommended, as it is located in the Void where horrors thrive. Creates a permanent gate between the current province and Nexus.</td></tr>
<tr><td>Thau 9</td><td>Astral Disruption</td><td>S6</td><td>60</td><td>-</td><td>-</td><td></td></tr>
<tr class="spell-desc"><td colspan="7">The mage manipulates the astral plane, creating ripples that overload the world with magic. This magic overload will dispel all enchantments in the entire world if done with enough strength. However manipulating the astral world in such a great way always comes with a certain risk, both to the world and the mage performing the ritual. Destroys all global enchantments if cast with enough power. Destroys all local enchantments. Increases magic and horror marks in entire world. Might increase maximum number of global enchantment slots if cast with much power.</td></tr>
<tr><td>Alt 9</td><td>Wish</td><td>S9</td><td>100</td><td>-</td><td>-</td><td></td></tr>
<tr class="spell-desc"><td colspan="7">This ritual taps the primal powers from beyond the Spheres. By projection of his own will upon the Principle of Beginning, the caster can affect the very processes of creation and receive an answer to his wish. There are many things to wish for, but the outcome is not always good. If you want something good and safe, you can try wishing for an artifact or magic gems.</td></tr>
</tbody></table>
```

## Death Rituals

```{=html}
<table class="table spell-table">
<thead><tr><th>School</th><th>Ritual Name</th><th>Path</th><th>Cost</th><th>Rng</th><th>Dmg</th><th>Special</th></tr></thead>
<tbody>
<tr><td>Conj 3</td><td>Dark Knowledge</td><td>D1</td><td>4</td><td>3</td><td>-</td><td></td></tr>
<tr class="spell-desc"><td colspan="7">The caster summons a spirit of the Underworld and coerces it to reveal knowledge of sites of Death in a distant province. The spell can not be used to find magic in enemy provinces.</td></tr>
<tr><td>Ench 4</td><td>Twiceborn</td><td>D2</td><td>10</td><td>-</td><td>-</td><td>UndIm, InanimIm, SpiIm</td></tr>
<tr class="spell-desc"><td colspan="7">With this ritual, the necromancer enchants his own body to protect himself from death. If the necromancer is slain, he is revived as a Wight Mage in the province where the ritual was cast, possibly gaining dark insights in the process. For the ritual to work, the province it was cast in must be in friendly hands when the necromancer dies. This spell requires more power to affect large beings and the cost of casting the ritual is increased with the caster&#x27;s size. Undead, demons, plants, inanimates, pretender gods as well as most monsters that aren&#x27;t even remotely humanoid (e.g. hydras and sea serpents) cannot be twiceborned.</td></tr>
<tr><td>Ench 7</td><td>Ritual of Rebirth</td><td>D4</td><td>15</td><td>-</td><td>-</td><td>NUW</td></tr>
<tr class="spell-desc"><td colspan="7">The caster of this spell revives a previously slain hero via the ancient Ritual of Rebirth. The ritual mummifies the dead hero before bringing him or her back to life. Only great heroes from the Hall of Fame can be resurrected by this ritual. The ritual can be performed multiple times on a single hero. Inanimate or undead beings are not affected by this spell</td></tr>
<tr><td>Conj 8</td><td>Manifestation</td><td>D5</td><td>4</td><td>4</td><td>-</td><td>NUW</td></tr>
<tr class="spell-desc"><td colspan="7">With this spell, an Ashen Angel is summoned with the promise of an opportunity to kill a commander in this realm and to bring his soul back to the Lord of the Netherworld. The Ashen Angel will appear in a province of the mage&#x27;s choice and search for a suitable commander. If no suitable commander is found, the Angel will return to the mage and kill him instead. A commander who is horror marked runs a greater risk of being chosen by the Angel.</td></tr>
<tr><td>Ench 9</td><td>Lichcraft</td><td>D5</td><td>25</td><td>-</td><td>-</td><td>UndIm, InanimIm, SpiIm</td></tr>
<tr class="spell-desc"><td colspan="7">With knowledge of this ritual, the Death mage has discovered the means to remove his own viscera and place it in a jar, killing himself, only to return as an immortal undead being of great power. By dying and returning from the dead the Lich gains insights and powers in the path of death magic. Furthermore, the body of the Lich becomes almost impossible to harm with mundane weapons. Should the body of the Lich be physically destroyed, a new one is formed from the dust of the dead. The caster dies and returns as an undead, immortal Lich. The Lich is empowered in death magic. Pretenders can&#x27;t use this ritual.</td></tr>
<tr><td>Thau 6</td><td>Leprosy</td><td>D5</td><td>10</td><td>4</td><td>-</td><td>MR, UndIm, InanimIm</td></tr>
<tr class="spell-desc"><td colspan="7">The mage conjures forth a wasting disease upon an enemy army in a distant province. Diseased targets will never regain any lost hit points and will take damage every season they are alive. Undead, demons and inanimate beings are not affected by this spell. 50% of the units in the targeted province must make a MR check or get diseased.</td></tr>
<tr><td>Thau 8</td><td>Stygian Paths</td><td>D5</td><td>15</td><td>10</td><td>-</td><td></td></tr>
<tr class="spell-desc"><td colspan="7">All lands are connected to the Underworld and every location in the Underworld corresponds to a location in the lands of the living, but time passes differently in the Underworld. By traveling in the Underworld, great distances can be covered in a short period of time. When this ritual is cast, a gateway into the realm of the dead is opened. The necromancer then leads his followers on dark paths through the Underworld to emerge in a faraway province. The journey, however, is not free from risk: no one is allowed to leave the lands of the dead. Everyone using the Stygian paths risks injury or even death by poisoning, spirit attacks or fates even worse. Stealthy units are less likely to be detected by the guardians of the Underworld. Spirit attacks: 1 AN dmg + death MR attack. Stealthy units have only 20% chance of being attacked. Caster can not take advantage of stealth.</td></tr>
<tr><td>Thau 8</td><td>Black Death</td><td>D5</td><td>15</td><td>5</td><td>-</td><td>Anon</td></tr>
<tr class="spell-desc"><td colspan="7">The necromancer curses a province with the Black Death. This plague will kill thousands upon thousands of people. The spell is targeted at the general population and will probably not affect the military units in the province. Population -50%, Unrest +10</td></tr>
<tr><td>Conj 9</td><td>Tartarian Gate</td><td>D7</td><td>7</td><td>-</td><td>-</td><td>NUW</td></tr>
<tr class="spell-desc"><td colspan="7">The caster opens a gate to Tartarus and releases a dead Titan or Monstrum imprisoned in that horrible place. The Titans were gods in ancient times, but were defeated and imprisoned in Tartarus aeons ago. The dead Titan once had tremendous powers, but the imprisonment in the realm of perpetual pain might have destroyed the mind of the ancient god.</td></tr>
</tbody></table>
```

## Nature Rituals

```{=html}
<table class="table spell-table">
<thead><tr><th>School</th><th>Ritual Name</th><th>Path</th><th>Cost</th><th>Rng</th><th>Dmg</th><th>Special</th></tr></thead>
<tbody>
<tr><td>Alt 6</td><td>Transformation</td><td>N2</td><td>8</td><td>-</td><td>-</td><td>UndIm, InanimIm, SpiIm</td></tr>
<tr class="spell-desc"><td colspan="7">The caster is transformed into a random monster or animal. Some monsters, such as fire drakes, are closely attuned to an element or other magical path. If the caster successfully transforms into such a being he might gain magic power. Also the caster&#x27;s new body is young and healthy. The transformation is not without risk, however, as the caster&#x27;s mind and body may be damaged in the process. Sometimes a failed transformation can result in the form of a mindless being and usually mind and magic abilities are lost as a result. But sometimes a being with powerful magic can retain his magic ability as the magic is too strong to let the absence of a mind stop it. The caster transforms into a young monster, but lost limbs are still lost after the transformation. The chance of failure is 20% reduced or increased by the Luck/Misfortune scale value. If cast under water the transformation results in a water being.</td></tr>
<tr><td>Thau 3</td><td>Haruspex</td><td>N2</td><td>2</td><td>3</td><td>-</td><td></td></tr>
<tr class="spell-desc"><td colspan="7">The caster opens the bellies of newly slaughtered animals and observes their livers. The state of the livers reveals distant locations of Nature power.</td></tr>
<tr><td>Thau 3</td><td>Whispers of the Wild</td><td>N2</td><td>3</td><td>4</td><td>-</td><td></td></tr>
<tr class="spell-desc"><td colspan="7">The caster taps into the minds and perceptions of the animals of a distant forest province to gain insight into what transpires in the province. Scrying on a forest province The ritual last an additional month for each extra gem used.</td></tr>
<tr><td>Conj 5</td><td>Winged Monkeys</td><td>N3S2</td><td>10</td><td>5</td><td>-</td><td>NUW</td></tr>
<tr class="spell-desc"><td colspan="7">The caster summons a troop of winged monkeys and sends them away to fetch a commander from a distant land. The monkeys will try to grab and fly away with the helpless commander, but will attack if the target is too heavy. The monkeys are afraid of mages and will never try to snatch a mage from the ground. The monkeys leave after they have accomplished their mission.</td></tr>
<tr><td>Conj 6</td><td>Locust Swarms</td><td>N3</td><td>8</td><td>5</td><td>-</td><td>NUW, Anon</td></tr>
<tr class="spell-desc"><td colspan="7">The caster unleashes swarms of locusts upon a province. The locusts will cause panic, consume crops and cause the loss of taxes. The swarms will appear as a natural event. Unrest +20, Income -50%.</td></tr>
<tr><td>Evo 7</td><td>Miasma</td><td>N4</td><td>25</td><td>4</td><td>5+</td><td>AN, Anon</td></tr>
<tr class="spell-desc"><td colspan="7">With this ritual a nature mage will try to poison an entire enemy army camp by releasing the poisonous gases that are trapped under the ground. This ritual will only work against armies that are located in swamps or drip caves as only these terrains have these gases trapped beneath them. The nature mage will be able to view the release of the gases through the ritual and observe the effects on the enemy army.</td></tr>
<tr><td>Conj 5</td><td>Vermin Feast</td><td>N4</td><td>6</td><td>4</td><td>-</td><td></td></tr>
<tr class="spell-desc"><td colspan="7">The caster makes vermin like rats and cockroaches (or shrimps and crabs) attracted to the supply stores of a besieged castle. The vermin will make sure that the supplies do not last very long. The more gems spent in this ritual the longer it will last. Having more than one Vermin Feast ritual active on the same province will not add to the effect and the ritual has no effect on an unbesieged castle. Doubles the supply loss in a besieged castle.</td></tr>
<tr><td>Conj 7</td><td>Living Castle</td><td>N4W1</td><td>40</td><td>4</td><td>-</td><td>UW</td></tr>
<tr class="spell-desc"><td colspan="7">The caster conjures a castle of living kelp and algae. The castle can only be created in a friendly sea. This spell cannot be cast above the waves.</td></tr>
<tr><td>Ench 5</td><td>Faery Trod</td><td>N4G1</td><td>20</td><td>10</td><td>-</td><td></td></tr>
<tr class="spell-desc"><td colspan="7">The mage leads his army into a magic forest to find a Faery Trod. The army follows this strange path through faerie lands and will finally arrive in a distant forest. Both the source and destination provinces must be forests for this spell to work. Navigating on the faerie paths is a tricky adventure and it might be that you won&#x27;t emerge exactly where you planned. Chance of ending up in a neighboring forest province: 50% if completely surrounded by forests, 0% if no neighboring forest provinces.</td></tr>
<tr><td>Thau 4</td><td>Cure Disease</td><td>N4</td><td>5</td><td>-</td><td>-</td><td>InanimIm</td></tr>
<tr class="spell-desc"><td colspan="7">This ritual cures a unit from disease, an affliction that otherwise is certain to result in a quick and early death. The target unit must be in the same province as the caster.</td></tr>
<tr><td>Thau 5</td><td>Gift of Reason</td><td>N4</td><td>20</td><td>-</td><td>-</td><td>MindIm</td></tr>
<tr class="spell-desc"><td colspan="7">This gift grants commander status and a sharp intellect to any one being. The target unit must be in the same province as the caster. Mindless units cannot be affected by the spell.</td></tr>
<tr><td>Ench 6</td><td>Forest Dome</td><td>N5</td><td>10</td><td>-</td><td>-</td><td></td></tr>
<tr class="spell-desc"><td colspan="7">Vegetation will grow into a dome that covers the entire province where the spell is cast. The dome will protect the province from many spells that originate outside the warded province. If left undisturbed, the forest dome will last forever. However, if a Fire spell is absorbed by the dome, it may catch fire and be destroyed. If the caster dies, the dome will wither and die. Dome Protection 30%. Destroyed by Fire Spells. Friendly spells will also be blocked.</td></tr>
</tbody></table>
```

## Glamour Rituals

```{=html}
<table class="table spell-table">
<thead><tr><th>School</th><th>Ritual Name</th><th>Path</th><th>Cost</th><th>Rng</th><th>Dmg</th><th>Special</th></tr></thead>
<tbody>
<tr><td>Conj 2</td><td>Tapestry of Dreams</td><td>G2</td><td>4</td><td>4</td><td>-</td><td></td></tr>
<tr class="spell-desc"><td colspan="7">The caster conjures the dreams and memories of a distant land and weaves them into a tapestry that reveals what transpires in the province. The tapestry will dissolve over a month, but can be made to last longer if additional gems are used in the casting.</td></tr>
<tr><td>Conj 4</td><td>At the End of the Rainbow</td><td>G2</td><td>3</td><td>3</td><td>-</td><td>NUW</td></tr>
<tr class="spell-desc"><td colspan="7">The caster conjures dreams from beyond the Gate of Horn to find what lies hidden at the End of the Rainbow. All sites of glamour in the targeted province are revealed.</td></tr>
<tr><td>Evo 5</td><td>Project Self</td><td>G3S1</td><td>5</td><td>5</td><td>-</td><td></td></tr>
<tr class="spell-desc"><td colspan="7">The caster sends a projection of himself to a distant land. The projection is an ethereal replica of the caster with the same magical skills as the caster. Items are not projected, gems and blood slaves cannot be used, but any path boosting magic items will still have effect. The projection is shortlived and will only last enough for one battle. It can only be used against hostile provinces as the projection won&#x27;t last long enough to wait for any enemies to arrive in still friendly provinces. It cannot be used on your own forts when they are under siege.</td></tr>
<tr><td>Ench 8</td><td>Dragon Master</td><td>G3</td><td>30</td><td>-</td><td>-</td><td></td></tr>
<tr class="spell-desc"><td colspan="7">The caster claims lordship over all serpentkin. Every time the caster summons a Drake, Wyvern or Sea Serpent, two additional beasts will heed the call. Grants Dragon Mastery +2.</td></tr>
<tr><td>Ench 4</td><td>Simulacrum</td><td>G3</td><td>20</td><td>-</td><td>-</td><td></td></tr>
<tr class="spell-desc"><td colspan="7">The caster creates a replica of himself and enchants it with glamour magic to give it false life. The simulacrum will be controlled by the original owner&#x27;s soul and the simulacrum also inherits all the magic powers of its creator. In turn the creator&#x27;s body is placed in a state of deep torpor that only ends when the simulacrum dies. However, there is a chance that the caster&#x27;s soul will fail to return and become trapped and lost in the dreamwild, possibly until his soul withers away and dies. The Simulacrum is an almost perfect copy of the caster and will be in play instead of the caster. If the Simulacrum dies the caster will reappear where the ritual was cast. There is a 80% chance that the caster reappears a month after the simulacrum&#x27;s death. Each month thereafter the chance is reduced by half. The soul withers away after one year.</td></tr>
<tr><td>Thau 4</td><td>Vengeance of the Dead</td><td>G3D1</td><td>3</td><td>5</td><td>-</td><td>MR, UndIm, MindIm, Detect</td></tr>
<tr class="spell-desc"><td colspan="7">The mage will contact the dead souls of all the people or creatures that the target has slain. These dead souls will then be guided to the dreams of the target, where they can attack him in a horrible nightmare. The mage will ensure that the target is pulled strongly into the nightmare, so that he stays dead if the dead souls are successful in killing him. This spell does not work on mindless or undead beings and the target must have slain units in combat for the spell to work. One province is chosen for the spell and the greatest butcher of all enemy commanders in that province will be targeted for the nightmare.</td></tr>
<tr><td>Alt 6</td><td>Mirage</td><td>G4</td><td>20</td><td>4</td><td>-</td><td>NUW</td></tr>
<tr class="spell-desc"><td colspan="7">The mage creates an illusory castle in a distant province to fool neighboring nations. Only upon besieging the castle will the truth be revealed to an advancing army. The enchantment lasts longer the more gems the caster invests. Enchantments lasts 1 turn + 3 turns / extra gem.</td></tr>
<tr><td>Conj 7</td><td>Lore of Legends</td><td>G4</td><td>20</td><td>-</td><td>-</td><td>NUW</td></tr>
<tr class="spell-desc"><td colspan="7">The caster taps into the legends of the dreamwild to unearth long forgotten lore. For one month the caster&#x27;s magic skills become legendary and his skills in all magic paths are increased. After a month has passed the powers fade and the caster is once more bound by the restrictions of this world. The caster gains +1 in all his magic paths for one month.</td></tr>
<tr><td>Thau 6</td><td>Beckoning</td><td>G4N2</td><td>20</td><td>4</td><td>-</td><td>MR</td></tr>
<tr class="spell-desc"><td colspan="7">The caster awakens the forces of the wild, which call out to lure the unwary. Those who fall prey vanish into the woodlands, never to be seen again. The Beckoning will only work in forests and forest beings are immune to the call. Those who are strong of mind or duty will resist the call. 75+ enemy units will be killed (MR and difficult morale negates). Units with forest survival ignore the spell.</td></tr>
<tr><td>Alt 7</td><td>Immaculate Fort</td><td>G5</td><td>10</td><td>-</td><td>-</td><td>Fort only</td></tr>
<tr class="spell-desc"><td colspan="7">With the help of glamour a fortification and everything in it is made perfect, at least that is how it seems. The air is cleaner, the food tastes better, the streets are always clean and all the buildings are in better shape than when they were just built. The fortification also looks perfectly fine, no matter how much damage it sustains. This makes it very difficult to figure out how to breach the walls, but when they are finally breached the opening will be seen. Unrest Reduction: 5 / month Wall breakdown resistance: 50% Walls are magic and ethereal units cannot pass through</td></tr>
<tr><td>Ench 5</td><td>Dreamwild Demesne</td><td>G5</td><td>10</td><td>-</td><td>-</td><td>NUW</td></tr>
<tr class="spell-desc"><td colspan="7">The caster enchants an entire province with the magic of the Dreamwild, creating a land of hope and peace free from misery and woe. As long as the enchantment is active unrest will decrease and few bad events will disturb the peace. The enchantment is broken if the land is conquered by hostile forces. Unrest -2d5, prevents 50% of bad events.</td></tr>
<tr><td>Ench 6</td><td>Dome of Misdirection</td><td>G5</td><td>20</td><td>-</td><td>-</td><td>NUW</td></tr>
<tr class="spell-desc"><td colspan="7">The entire province the mage is in is protected by a dome of glamour and illusions. The dome will fool enemy mages and protect the warded province from spells that originate outside the dome and make them target a neighboring province instead. The more magic gems put into the spell, the longer it will last. Dome misdirection chance 70%. Friendly spells will also be misdirected.</td></tr>
<tr><td>Ench 7</td><td>Veil of Perpetual Mists</td><td>G5</td><td>30</td><td>-</td><td>-</td><td>NUW</td></tr>
<tr class="spell-desc"><td colspan="7">The caster shrouds an entire province in mists alive with whispers, screams and harrowing shapes. Anyone trying to enter the province without the consent of the caster will find themselves led astray and leave the province from whence they came. Troops with strong morale will follow their commander, but if he is weak of mind and succumbs to the enchantment they will follow him when he leaves the province. The more magic gems put into the spell, the longer it will last.</td></tr>
<tr><td>Ench 7</td><td>Land of the Ever Young</td><td>G5N1</td><td>10</td><td>-</td><td>-</td><td>NUW</td></tr>
<tr class="spell-desc"><td colspan="7">With this enchantment in place everyone in the province will grow old much much slower than usual, only aging one year in four winters. It is a very sought after enchantment for old mages who have much magic research left to do, but not enough time to do it.</td></tr>
<tr><td>Thau 6</td><td>Forgotten Palace</td><td>G5</td><td>15</td><td>3</td><td>-</td><td>NUW</td></tr>
<tr class="spell-desc"><td colspan="7">The caster casts a spell on a fortress in a nearby province and makes it disappear from everyone&#x27;s memories. People are able to see and interact with the fortification, but once they leave they will forget about it. Scouts will forget to report about the palace and neighboring provinces will not know about it. Mages who scry upon the province will be able to see the fortification however. The spell is broken if the fortification is besieged. The ritual can also be used to hide the construction of the fortification.</td></tr>
</tbody></table>
```

## Blood Rituals

```{=html}
<table class="table spell-table">
<thead><tr><th>School</th><th>Ritual Name</th><th>Path</th><th>Cost</th><th>Rng</th><th>Dmg</th><th>Special</th></tr></thead>
<tbody>
<tr><td>Blood 2</td><td>Bowl of Blood</td><td>B1</td><td>5</td><td>5</td><td>-</td><td>NUW</td></tr>
<tr class="spell-desc"><td colspan="7">The caster fills a bowl with blood, mixes it with soil from a distant land and observes the five signs. The signs will reveal all sites of blood power in that province.</td></tr>
<tr><td>Blood 3</td><td>Cross Breeding</td><td>B1N1</td><td>15</td><td>-</td><td>-</td><td>NUW</td></tr>
<tr class="spell-desc"><td colspan="7">Hundreds of different creatures from mice to humans are magically cross-bred and grown in an effort to produce a powerful monster. Most offspring die early, but some survive and are bound to serve their creator. Luck is required to breed the more powerful creatures.</td></tr>
<tr><td>Blood 5</td><td>Wrath of Pazuzu</td><td>B1A3</td><td>15</td><td>5</td><td>-</td><td>NUW, Anon</td></tr>
<tr class="spell-desc"><td colspan="7">The caster unleashes an infernal tempest from the realm of Pazuzu upon a province. The storm is anything but natural and Shedim, servants of Pazuzu, can be heard bellowing in the gale. The storm causes unrest and devastation upon a province. Unrest +35, population -4%.</td></tr>
<tr><td>Blood 6</td><td>Rejuvenate</td><td>B1</td><td>10</td><td>-</td><td>-</td><td>UndIm, InanimIm, NUW</td></tr>
<tr class="spell-desc"><td colspan="7">The mage drenches himself in the blood of ten young girls in an attempt to become younger. Each offered girl will make the caster one year younger.</td></tr>
<tr><td>Blood 3</td><td>Blood Feast</td><td>B2</td><td>5</td><td>-</td><td>-</td><td>InanimIm, NUW</td></tr>
<tr class="spell-desc"><td colspan="7">The caster has learned the recuperative secrets of cannibalism. In a gruesome ritual lasting a month he consumes the blood and feast of ritually purified sacrifices. The blood feast requires copious amounts of flesh and blood of unpurified victims as well however, so the populace in the province where the caster resides is slaughtered in great quantities. The flesh and blood of the victims rejuvenates the caster, healing him of all or at least most afflictions. Bloodmages who partake too often in blood feasts often develop uncontrollable cravings for human flesh. The ritual does not work on inanimate beings. Removes up to 10 afflictions, kills up to 750 population, 25% chance to develop cravings</td></tr>
<tr><td>Blood 4</td><td>Blood Fecundity</td><td>B2N2</td><td>10</td><td>-</td><td>-</td><td>NUW</td></tr>
<tr class="spell-desc"><td colspan="7">The mage performs a great blood ceremony in order to increase the fertility of the land. The growth scale of the province will be increased for as long as the ritual lasts. The spell lasts longer if more slaves are sacrificed. Growth +2. Duration: 1 month +1 1 month per extra blood slave</td></tr>
<tr><td>Blood 8</td><td>Improved Cross Breeding</td><td>B2N2</td><td>20</td><td>-</td><td>-</td><td>NUW</td></tr>
<tr class="spell-desc"><td colspan="7">Hundreds of different creatures from mice to humans are magically cross-bred and grown in an effort to produce a powerful monster. Most offspring die early, but some survive and are bound to serve their creator. Luck is required to breed the more powerful creatures.</td></tr>
<tr><td>Blood 4</td><td>Hell Ride</td><td>B3</td><td>10</td><td>3</td><td>-</td><td>NUW</td></tr>
<tr class="spell-desc"><td colspan="7">The caster summons a swarm of imps and commands them to carry him to a distant province with haste. Although supernaturally fast the imps are not very strong and can&#x27;t lift anything heavier than a human. While the imps are faster than normal fliers they cannot teleport and can have the path blocked by impassable mountains, cave walls or the Sea of Ice global enchantment.</td></tr>
<tr><td>Blood 5</td><td>Rain of Toads</td><td>B3N1</td><td>20</td><td>5</td><td>-</td><td>NUW, Anon, Lim</td></tr>
<tr class="spell-desc"><td colspan="7">The caster creates a horrible omen, turning the falling rain in a target province into toads. The target province will suffer from unrest and misfortune. Soldiers stationed in the province will risk becoming diseased when dead toads fester in the wells. Unrest +40, misfortune +3, disease chance 4%.</td></tr>
<tr><td>Blood 7</td><td>Send Dream Horror</td><td>B3S4</td><td>15</td><td>6</td><td>-</td><td>NUW, Anon</td></tr>
<tr class="spell-desc"><td colspan="7">The caster sends a Defiler of Dreams to attack a distant province. The Dream Horror will project nightmares and feed on the emotional distress of its victims. Unrest will increase in the province until the Horror is found and slain. Dealing with horrors is not without risk however and the caster of this ritual might attract some unwanted attention. Unrest +30, Dream Horror summoned.</td></tr>
<tr><td>Blood 8</td><td>Horror Seed</td><td>B3S4</td><td>25</td><td>6</td><td>-</td><td>NUW</td></tr>
<tr class="spell-desc"><td colspan="7">A Horror is sent to possess a far away enemy. The Horror hides its true self and spreads its evil ways, marking and cursing soldiers in the province. The most horrible ability of the possessing Horror is to infect living soldiers with Parasitic Horrors. These Parasitic Horrors sooner or later break the mind and body of their host, transforming them into full fledged Horrors. Should the host of the Master Horror be slain, the true Horror will manifest and attack everything alive.</td></tr>
<tr><td>Blood 7</td><td>Dome of Corruption</td><td>B4S4</td><td>20</td><td>-</td><td>-</td><td>NUW</td></tr>
<tr class="spell-desc"><td colspan="7">The caster seals a pact with Horrors. The Horrors create a dome that protects the province from most spells that originate from outside the warded province. Trying to cast a spell through this dome is very dangerous and might drive the casting mage insane. A good side effect of the dome is that it exudes magic and will raise the magic scales of the province considerably, making it easy for mages to do their research. The pact has a downside too, which will become apparent to mages living under the dome. The creators of the dome will occasionally attack and consume a mage. The dome will dissolve instantly if the caster of this ritual dies.</td></tr>
<tr><td>Blood 9</td><td>Infernal Fumes</td><td>B4E3</td><td>40</td><td>4</td><td>10+</td><td>AP, NUW, Anon</td></tr>
<tr class="spell-desc"><td colspan="7">This ritual opens up a way for the hot infernal gases trapped under the depths, to make their way into the sea. The blood and earth mage casting the ritual will guide the fumes to just where the enemy forces are camping. The gases are blisteringly hot and deadly poisonous to most living beings. The mage will also get a vision of the effect taking place.</td></tr>
<tr><td>Blood 3</td><td>Infernal Circle</td><td>B5</td><td>5</td><td>-</td><td>-</td><td>NUW</td></tr>
<tr class="spell-desc"><td colspan="7">The caster creates a circle with infernal symbols drawn in the blood of virgins. Blood rituals cast from the circle with have their range increased. The circle will dissipate eventually, but the more blood slaves used for the circle, the longer it will last. Blood ritual range +1 province. Duration: 1 month + 1 month per extra blood slave</td></tr>
<tr><td>Blood 6</td><td>Infernal Disease</td><td>B5</td><td>5</td><td>5</td><td>-</td><td>NUW, Anon</td></tr>
<tr class="spell-desc"><td colspan="7">This ritual starts with a month of scribing complex magic symbols and eventually culminates with the sacrifice of five young girls. When the ritual is finished, a Disease Demon is bound and ordered to attack an enemy commander wherever in the world the caster chooses. The demon is very deadly and should be a sure way to kill an enemy.</td></tr>
<tr><td>Blood 8</td><td>Three Red Seconds</td><td>B5</td><td>120</td><td>4</td><td>-</td><td>NUW</td></tr>
<tr class="spell-desc"><td colspan="7">The caster summons a horde of Imps and commands them to raise a fortress. In three red seconds, a mighty citadel is built in a province of the caster&#x27;s choice.</td></tr>
</tbody></table>
```

## National Rituals: Arcoscephale (age 1)

```{=html}
<table class="table spell-table">
<thead><tr><th>School</th><th>Ritual Name</th><th>Path</th><th>Cost</th><th>Rng</th><th>Dmg</th><th>Special</th></tr></thead>
<tbody>
<tr><td>Conj 5</td><td>Monster Boar</td><td>N3</td><td>10</td><td>5</td><td>-</td><td>NUW, Anon</td></tr>
<tr class="spell-desc"><td colspan="7">The caster summons a monster boar and sends it to a distant province to ravage the land. The boar is a descendant of the monster boars sent by the Lady of the Hunt to ravage the farmlands of obnoxious peasants. The boar will cause unrest in the province until it is found and slain.</td></tr>
</tbody></table>
```

## National Rituals: Mekone (age 1)

```{=html}
<table class="table spell-table">
<thead><tr><th>School</th><th>Ritual Name</th><th>Path</th><th>Cost</th><th>Rng</th><th>Dmg</th><th>Special</th></tr></thead>
<tbody>
<tr><td>Ench 0</td><td>Blessing of the God-slayer</td><td>W1H1</td><td>5</td><td>-</td><td>-</td><td>NUW</td></tr>
<tr class="spell-desc"><td colspan="7">At a grand ceremony witnessed by all, the Basileus inaugurates a Polemarch as champion of the God-slayer. Endowed with unequaled battle prowess and charisma the Polemarch is expected to slay a false god within the upcoming year. Only one champion can be blessed at the same time. Grants att +5, def +5, always blessed, halt heretic +7, inspirational +1</td></tr>
</tbody></table>
```

## National Rituals: Pangaea (age 1)

```{=html}
<table class="table spell-table">
<thead><tr><th>School</th><th>Ritual Name</th><th>Path</th><th>Cost</th><th>Rng</th><th>Dmg</th><th>Special</th></tr></thead>
<tbody>
<tr><td>Conj 5</td><td>Monster Boar</td><td>N3</td><td>10</td><td>5</td><td>-</td><td>NUW, Anon</td></tr>
<tr class="spell-desc"><td colspan="7">The caster summons a monster boar and sends it to a distant province to ravage the land. The boar is a descendant of the monster boars sent by the Lady of the Hunt to ravage the farmlands of obnoxious peasants. The boar will cause unrest in the province until it is found and slain.</td></tr>
<tr><td>Alt 0</td><td>Grow Fortress</td><td>N4</td><td>35</td><td>-</td><td>-</td><td></td></tr>
<tr class="spell-desc"><td colspan="7">This ritual forces nature to form a complete fortress in a matter of weeks, sturdy enough to rival stone walls. Defenders can stand on the walls and fire missiles from the parapets. This ritual can only be cast in forests or shallow seas, where nature has plenty of material to build from.</td></tr>
</tbody></table>
```

## National Rituals: Marverni (age 1)

```{=html}
<table class="table spell-table">
<thead><tr><th>School</th><th>Ritual Name</th><th>Path</th><th>Cost</th><th>Rng</th><th>Dmg</th><th>Special</th></tr></thead>
<tbody>
<tr><td>Conj 5</td><td>Monster Boar</td><td>N3</td><td>10</td><td>5</td><td>-</td><td>NUW, Anon</td></tr>
<tr class="spell-desc"><td colspan="7">The caster summons a monster boar and sends it to a distant province to ravage the land. The boar is a descendant of the monster boars sent by the Lady of the Hunt to ravage the farmlands of obnoxious peasants. The boar will cause unrest in the province until it is found and slain.</td></tr>
</tbody></table>
```

## National Rituals: Pyrène (age 1)

```{=html}
<table class="table spell-table">
<thead><tr><th>School</th><th>Ritual Name</th><th>Path</th><th>Cost</th><th>Rng</th><th>Dmg</th><th>Special</th></tr></thead>
<tbody>
<tr><td>Conj 6</td><td>Send Aatxe</td><td>A3</td><td>6</td><td>4</td><td>-</td><td>NUW, Anon</td></tr>
<tr class="spell-desc"><td colspan="7">The Aatxe is a flaming bull spirit and servant of the Mother of Storms. It emerges from its cave abode during storms and bad weather to punish those who have angered their mistress. In ancient times the Sorginak were granted the means to call the Aatxe and send it against those who have wronged them or their mistress.</td></tr>
</tbody></table>
```

## National Rituals: Agartha (age 1)

```{=html}
<table class="table spell-table">
<thead><tr><th>School</th><th>Ritual Name</th><th>Path</th><th>Cost</th><th>Rng</th><th>Dmg</th><th>Special</th></tr></thead>
<tbody>
<tr><td>Thau 4</td><td>Mirror of Earth&#x27;s Memories W2E2</td><td>5</td><td>10</td><td>-</td><td></td><td></td></tr>
<tr class="spell-desc"><td colspan="7">An Agarthan Oracle ventures down to the Womb of the Earth and gazes into the reflections of the First Pool to gain knowledge of subterranean sources of magic. The spell reveals all magic sites of earth, fire, water and death in a distant cave province.</td></tr>
<tr><td>Alt 8</td><td>Unleash Imprisoned Ones</td><td>E6D4</td><td>100</td><td>-</td><td>-</td><td></td></tr>
<tr class="spell-desc"><td colspan="7">Since before the founding of Agartha there has been a forbidden chamber under the Roots of the Earth. Agarthan legends tell of three dark gods of an earlier age imprisoned with the help of the first Pale Ones. The Seal was strengthened with the souls of thousands of Pale Ones who gave their lives to protect the world from the Imprisoned Ones. Now the Seal seems to be weakening and there are rumors of a crack in the Seal. Some Oracles of the Dead have heard silent whispers in their dreams. Whispers of promise. A promise to spare the Agarthan people if the Imprisoned Ones are released. The oldest and most influential of the Oracles of the Dead has spoken against it, but desperate times need desperate measures, and the whispered promise has not been forgotten.</td></tr>
</tbody></table>
```

## National Rituals: Abysia (age 1)

```{=html}
<table class="table spell-table">
<thead><tr><th>School</th><th>Ritual Name</th><th>Path</th><th>Cost</th><th>Rng</th><th>Dmg</th><th>Special</th></tr></thead>
<tbody>
<tr><td>Alt 6</td><td>Hellscape</td><td>F4</td><td>10</td><td>5</td><td>-</td><td>NUW, Anon</td></tr>
<tr class="spell-desc"><td colspan="7">The caster calls on the fires of Rhuax to curse a distant province with blistering heat. Smoke and wildfires will erupt as the very ground will burn with unnatural heat. The Hellscape will appear as an unnatural event, but those affected will not know who has cast the curse upon them. Heat Scale +3, Death Scale +1, Population -10%, Unrest +20.</td></tr>
<tr><td>Blood 3</td><td>Infernal Breeding</td><td>B2</td><td>25</td><td>-</td><td>-</td><td>NUW</td></tr>
<tr class="spell-desc"><td colspan="7">The Warlocks of Abysia have experimented with crossbreeding since they first discovered blood magic. Under the influence of infernal magic Abysians, humans and giants are crossbred with demons, salamanders and other beasts. In the early days most of the experiments were conducted on Abysians, but the wars with Hinnom made the blood of giants occasionally available. In later times humans and humanbreds have dominated the breeding stock and abysian crossbreds are rarer. Due to the creation process many Hell Spawn suffer from various afflictions and early aging.</td></tr>
</tbody></table>
```

## National Rituals: T'ien Ch'i (age 1)

```{=html}
<table class="table spell-table">
<thead><tr><th>School</th><th>Ritual Name</th><th>Path</th><th>Cost</th><th>Rng</th><th>Dmg</th><th>Special</th></tr></thead>
<tbody>
<tr><td>Alt 5</td><td>Internal Alchemy</td><td>W2S1</td><td>5</td><td>-</td><td>-</td><td>UndIm, InanimIm</td></tr>
<tr class="spell-desc"><td colspan="7">The mystics and hermits of T&#x27;ien Ch&#x27;i have always been obsessed with longevity. Internal Alchemy is a method to transmute the inner self instead of external substances. Meditation, severe asceticism and breathing techniques are used to access the inner cinnabar fields in an attempt to alter them. Often the alchemist feeds on cinnabar, transmuted quicksilver, the most highly regarded alchemical substance, during the process. The transformative nature of the cinnabar might also transmute the mind of the hermit. Age -15 years</td></tr>
</tbody></table>
```

## National Rituals: Yomi (age 1)

```{=html}
<table class="table spell-table">
<thead><tr><th>School</th><th>Ritual Name</th><th>Path</th><th>Cost</th><th>Rng</th><th>Dmg</th><th>Special</th></tr></thead>
<tbody>
<tr><td>Conj 0</td><td>Hannya Pact</td><td>D1</td><td>6</td><td>-</td><td>-</td><td>UndIm, InanimIm</td></tr>
<tr class="spell-desc"><td colspan="7">The Namanari seals a pact with the Oni Kings, giving up her humanity to become a Chunari. The Chunari gains powers in death and fire magic and a demonic nature. Jealous and greedy for power a Chunari will sooner or later strengthen her pact with her masters losing her humanity altogether.</td></tr>
<tr><td>Conj 0</td><td>Greater Hannya Pact</td><td>D2</td><td>12</td><td>-</td><td>-</td><td>UndIm, InanimIm</td></tr>
<tr class="spell-desc"><td colspan="7">The Chunari seals a second and final pact with the Oni Kings, giving up the last shreds of humanity to become a true Hannya. The Hannya gains further powers in death and fire magic. A fiery aura and a serpent tail are also given to her to remind her of who her true masters are.</td></tr>
</tbody></table>
```

## National Rituals: Caelum (age 1)

```{=html}
<table class="table spell-table">
<thead><tr><th>School</th><th>Ritual Name</th><th>Path</th><th>Cost</th><th>Rng</th><th>Dmg</th><th>Special</th></tr></thead>
<tbody>
<tr><td>Thau 7</td><td>Call of the Drugvant</td><td>D4F1</td><td>15</td><td>4</td><td>-</td><td>NUW, Anon</td></tr>
<tr class="spell-desc"><td colspan="7">The Drugvant are the People of the Lie, those under the influence of evil intentions. With this ritual the caster lets loose the will of the Destructive Spirit upon a remote land. Falsehood, wickedness and violence will spread in the province and in its wake Daevas will come. Unrest is greatly increased and the province is attacked by bandits and a host of Daevas.</td></tr>
</tbody></table>
```

## National Rituals: Machaka (age 1)

```{=html}
<table class="table spell-table">
<thead><tr><th>School</th><th>Ritual Name</th><th>Path</th><th>Cost</th><th>Rng</th><th>Dmg</th><th>Special</th></tr></thead>
<tbody>
<tr><td>Ench 5</td><td>Weavers of the Wood</td><td>N4</td><td>6</td><td>-</td><td>-</td><td>NUW</td></tr>
<tr class="spell-desc"><td colspan="7">The caster makes spiders large and small weave a giant web covering an entire forest province. Anyone trying to sneak through the forest is highly likely to be detected as the caster monitors the webs. The caster of the ritual will be able to direct both the local patrolling forces and spiders from the woods in order to attack any trespassers. The ritual will break if the caster leaves the province. Patrol strength +100 vs enemy units. Able to detect invisible beings as well. Spiders will aid patrolling forces in combat. Duration: 1 month + 3 months per extra gems.</td></tr>
</tbody></table>
```

## National Rituals: Rus (age 1)

```{=html}
<table class="table spell-table">
<thead><tr><th>School</th><th>Ritual Name</th><th>Path</th><th>Cost</th><th>Rng</th><th>Dmg</th><th>Special</th></tr></thead>
<tbody>
<tr><td>Conj 5</td><td>Send Lady Midday</td><td>A3D1</td><td>5</td><td>5</td><td>-</td><td>NUW, Anon</td></tr>
<tr class="spell-desc"><td colspan="7">The Lady Midday is a malign spirit of the noon. She appears as a young girl surrounded by whirling dust and armed with a scythe that stinks of disease. Sometimes she will stop people and ask them a question. Failure to answer results in her displeasure and she will use her scythe to disease or chop off the head of the victim. The caster of this ritual will contact the spirit and force it to appear in a suitable province where it will attack and try to slay a commander.</td></tr>
</tbody></table>
```

## National Rituals: Niefelheim (age 1)

```{=html}
<table class="table spell-table">
<thead><tr><th>School</th><th>Ritual Name</th><th>Path</th><th>Cost</th><th>Rng</th><th>Dmg</th><th>Special</th></tr></thead>
<tbody>
<tr><td>Thau 5</td><td>Seith Curse</td><td>D1S1</td><td>3</td><td>5</td><td>-</td><td>MR+, Detect, NUW, Anon</td></tr>
<tr class="spell-desc"><td colspan="7">Seith is an ancient form of sorcery, reputedly invented by Angerboda. It has been practiced by females of the nation through the ages. Gygjor, vaetti hags and human Seithkonur all have some knowledge of the Seith, but it is the Seithkonur of Utgård that have mastered the art. Seith can be used to spell doom upon a distant target. When cast, a single enemy commander in a faraway province is cursed for the rest of his life. However, the price is high, and the Fates will keep the balance. Someone close to the caster will also suffer a curse.</td></tr>
</tbody></table>
```

## National Rituals: Muspelheim (age 1)

```{=html}
<table class="table spell-table">
<thead><tr><th>School</th><th>Ritual Name</th><th>Path</th><th>Cost</th><th>Rng</th><th>Dmg</th><th>Special</th></tr></thead>
<tbody>
<tr><td>Thau 5</td><td>Seith Curse</td><td>D1S1</td><td>3</td><td>5</td><td>-</td><td>MR+, Detect, NUW, Anon</td></tr>
<tr class="spell-desc"><td colspan="7">Seith is an ancient form of sorcery, reputedly invented by Angerboda. It has been practiced by females of the nation through the ages. Gygjor, vaetti hags and human Seithkonur all have some knowledge of the Seith, but it is the Seithkonur of Utgård that have mastered the art. Seith can be used to spell doom upon a distant target. When cast, a single enemy commander in a faraway province is cursed for the rest of his life. However, the price is high, and the Fates will keep the balance. Someone close to the caster will also suffer a curse.</td></tr>
</tbody></table>
```

## National Rituals: Oceania (age 1)

```{=html}
<table class="table spell-table">
<thead><tr><th>School</th><th>Ritual Name</th><th>Path</th><th>Cost</th><th>Rng</th><th>Dmg</th><th>Special</th></tr></thead>
<tbody>
<tr><td>Alt 0</td><td>Grow Fortress</td><td>N4</td><td>35</td><td>-</td><td>-</td><td></td></tr>
<tr class="spell-desc"><td colspan="7">This ritual forces nature to form a complete fortress in a matter of weeks, sturdy enough to rival stone walls. Defenders can stand on the walls and fire missiles from the parapets. This ritual can only be cast in forests or shallow seas, where nature has plenty of material to build from.</td></tr>
</tbody></table>
```

## National Rituals: R'lyeh (age 1)

```{=html}
<table class="table spell-table">
<thead><tr><th>School</th><th>Ritual Name</th><th>Path</th><th>Cost</th><th>Rng</th><th>Dmg</th><th>Special</th></tr></thead>
<tbody>
<tr><td>Thau 3</td><td>Mind Vessel</td><td>S3</td><td>15</td><td>2</td><td>-</td><td></td></tr>
<tr class="spell-desc"><td colspan="7">This ritual puts a part of the Aboleth&#x27;s mind in the humanlike vessel that has been bred for this purpose. After the ritual the vessel will have little left of its own mind and the Aboleth part will have to guide it along. After the merging of minds the vessel will be able to use its old magic knowledge as well as the astral knowledge of the Aboleth. The state of the Aboleth is constantly influencing its vessel and should the Aboleth die the vessel will not survive for more than a few days at the most. An Aboleth can not share his mind with more than one vessel at a time. Vessel gets astral power of the Aboleth (levels over 5 are halved). Vessel dies if Aboleth dies.</td></tr>
</tbody></table>
```

## National Rituals: Arcoscephale (age 2)

```{=html}
<table class="table spell-table">
<thead><tr><th>School</th><th>Ritual Name</th><th>Path</th><th>Cost</th><th>Rng</th><th>Dmg</th><th>Special</th></tr></thead>
<tbody>
<tr><td>Conj 5</td><td>Monster Boar</td><td>N3</td><td>10</td><td>5</td><td>-</td><td>NUW, Anon</td></tr>
<tr class="spell-desc"><td colspan="7">The caster summons a monster boar and sends it to a distant province to ravage the land. The boar is a descendant of the monster boars sent by the Lady of the Hunt to ravage the farmlands of obnoxious peasants. The boar will cause unrest in the province until it is found and slain.</td></tr>
</tbody></table>
```

## National Rituals: Pangaea (age 2)

```{=html}
<table class="table spell-table">
<thead><tr><th>School</th><th>Ritual Name</th><th>Path</th><th>Cost</th><th>Rng</th><th>Dmg</th><th>Special</th></tr></thead>
<tbody>
<tr><td>Conj 5</td><td>Monster Boar</td><td>N3</td><td>10</td><td>5</td><td>-</td><td>NUW, Anon</td></tr>
<tr class="spell-desc"><td colspan="7">The caster summons a monster boar and sends it to a distant province to ravage the land. The boar is a descendant of the monster boars sent by the Lady of the Hunt to ravage the farmlands of obnoxious peasants. The boar will cause unrest in the province until it is found and slain.</td></tr>
<tr><td>Alt 5</td><td>Fort of the Ancients</td><td>N4</td><td>35</td><td>-</td><td>-</td><td></td></tr>
<tr class="spell-desc"><td colspan="7">In ancient times, Pangaea made its forts not from mud and mortar but bramble and birch. This ritual forces nature to form a complete fortress in a matter of weeks, sturdy enough to rival stone walls. The ritual can only be cast in forests or shallow seas, where an appropriate amount of vegetation can be found.</td></tr>
</tbody></table>
```

## National Rituals: Asphodel (age 2)

```{=html}
<table class="table spell-table">
<thead><tr><th>School</th><th>Ritual Name</th><th>Path</th><th>Cost</th><th>Rng</th><th>Dmg</th><th>Special</th></tr></thead>
<tbody>
<tr><td>Alt 0</td><td>Carrion Fortress</td><td>N3D2</td><td>35</td><td>-</td><td>-</td><td></td></tr>
<tr class="spell-desc"><td colspan="7">This ritual forms a fortress of brambles, roots and bones in a matter of weeks, sturdy enough to rival stone walls. Defenders can stand on the walls and fire missiles from the parapets. This ritual can only be cast in forests or shallow seas, where nature has plenty of material to build from.</td></tr>
<tr><td>Ench 4</td><td>Dark Slumber</td><td>N4D2</td><td>15</td><td>5</td><td>-</td><td>NUW, Anon</td></tr>
<tr class="spell-desc"><td colspan="7">The Caster calls on the wrath of the forest to engulf a village in a distant province. The villagers succumb to an enchanted sleep and walk into the woods to die a dreamless death. Vines and roots begin to grow and reanimate the corpses. Within days an army of manikin emerges from the woods to claim the province from the living.</td></tr>
</tbody></table>
```

## National Rituals: Pyrène (age 2)

```{=html}
<table class="table spell-table">
<thead><tr><th>School</th><th>Ritual Name</th><th>Path</th><th>Cost</th><th>Rng</th><th>Dmg</th><th>Special</th></tr></thead>
<tbody>
<tr><td>Conj 6</td><td>Send Aatxe</td><td>A3</td><td>6</td><td>4</td><td>-</td><td>NUW, Anon</td></tr>
<tr class="spell-desc"><td colspan="7">The Aatxe is a flaming bull spirit and servant of the Mother of Storms. It emerges from its cave abode during storms and bad weather to punish those who have angered their mistress. In ancient times the Sorginak were granted the means to call the Aatxe and send it against those who have wronged them or their mistress.</td></tr>
</tbody></table>
```

## National Rituals: Abysia (age 2)

```{=html}
<table class="table spell-table">
<thead><tr><th>School</th><th>Ritual Name</th><th>Path</th><th>Cost</th><th>Rng</th><th>Dmg</th><th>Special</th></tr></thead>
<tbody>
<tr><td>Alt 6</td><td>Hellscape</td><td>F4</td><td>10</td><td>5</td><td>-</td><td>NUW, Anon</td></tr>
<tr class="spell-desc"><td colspan="7">The caster calls on the fires of Rhuax to curse a distant province with blistering heat. Smoke and wildfires will erupt as the very ground will burn with unnatural heat. The Hellscape will appear as an unnatural event, but those affected will not know who has cast the curse upon them. Heat Scale +3, Death Scale +1, Population -10%, Unrest +20.</td></tr>
<tr><td>Blood 3</td><td>Infernal Breeding</td><td>B2</td><td>25</td><td>-</td><td>-</td><td>NUW</td></tr>
<tr class="spell-desc"><td colspan="7">The Warlocks of Abysia have experimented with crossbreeding since they first discovered blood magic. Under the influence of infernal magic Abysians, humans and giants are crossbred with demons, salamanders and other beasts. In the early days most of the experiments were conducted on Abysians, but the wars with Hinnom made the blood of giants occasionally available. In later times humans and humanbreds have dominated the breeding stock and abysian crossbreds are rarer. Due to the creation process many Hell Spawn suffer from various afflictions and early aging.</td></tr>
</tbody></table>
```

## National Rituals: T'ien Ch'i (age 2)

```{=html}
<table class="table spell-table">
<thead><tr><th>School</th><th>Ritual Name</th><th>Path</th><th>Cost</th><th>Rng</th><th>Dmg</th><th>Special</th></tr></thead>
<tbody>
<tr><td>Alt 5</td><td>Internal Alchemy</td><td>W2S1</td><td>5</td><td>-</td><td>-</td><td>UndIm, InanimIm</td></tr>
<tr class="spell-desc"><td colspan="7">The mystics and hermits of T&#x27;ien Ch&#x27;i have always been obsessed with longevity. Internal Alchemy is a method to transmute the inner self instead of external substances. Meditation, severe asceticism and breathing techniques are used to access the inner cinnabar fields in an attempt to alter them. Often the alchemist feeds on cinnabar, transmuted quicksilver, the most highly regarded alchemical substance, during the process. The transformative nature of the cinnabar might also transmute the mind of the hermit. Age -15 years The mystics and hermits of T&#x27;ien Ch&#x27;i have always been obsessed with longevity. During the Time of the Bureaucracy and the prevalence of herbal medicine, one means to this end was found. The Thousand Year Ginseng will give the imbiber longevity and good health and is the closest to immortality one can come without practicing Internal Alchemy. Age -5 years</td></tr>
</tbody></table>
```

## National Rituals: Caelum (age 2)

```{=html}
<table class="table spell-table">
<thead><tr><th>School</th><th>Ritual Name</th><th>Path</th><th>Cost</th><th>Rng</th><th>Dmg</th><th>Special</th></tr></thead>
<tbody>
<tr><td>Thau 7</td><td>Call of the Drugvant</td><td>D4F1</td><td>15</td><td>4</td><td>-</td><td>NUW, Anon</td></tr>
<tr class="spell-desc"><td colspan="7">The Drugvant are the People of the Lie, those under the influence of evil intentions. With this ritual the caster lets loose the will of the Destructive Spirit upon a remote land. Falsehood, wickedness and violence will spread in the province and in its wake Daevas will come. Unrest is greatly increased and the province is attacked by bandits and a host of Daevas.</td></tr>
</tbody></table>
```

## National Rituals: Nazca (age 2)

```{=html}
<table class="table spell-table">
<thead><tr><th>School</th><th>Ritual Name</th><th>Path</th><th>Cost</th><th>Rng</th><th>Dmg</th><th>Special</th></tr></thead>
<tbody>
<tr><td>Ench 2</td><td>Eyes of the Condors</td><td>A2</td><td>1</td><td>4</td><td>-</td><td>NUW</td></tr>
<tr class="spell-desc"><td colspan="7">The Condor is sacred to the people of Nazca. It is considered a messenger of the sun and herald of storms. No other bird can soar at such heights, thus Condor scouts are rarely seen and almost impossible to catch. With this ritual the caster borrows the all perceiving eyes of the Condors and send the sacred birds to a distant province to scry.</td></tr>
<tr><td>Ench 5</td><td>Geoglyphs</td><td>S3E2</td><td>18</td><td>-</td><td>-</td><td>NUW</td></tr>
<tr class="spell-desc"><td colspan="7">The Coyas of Nazca, daughters of the Moon, are accomplished students of the stellar bodies and their connection with the earth. They have discovered means to amplify the influence of the planets on the terrestrial sphere through vast geoglyphs inscribed on the bare ground. As long as the enchantment of the geoglyph is active magic in the province is increased as are the ranges of rituals. Enemies fighting in a province with an active geoglyph are more easily affected by magic and have their magic resistance reduced. It is only possible to cast the ritual if you can see the land from above. Thus only flying mages can cast the spell. For the enchantment to be effective the geoglyphs must be exposed to stellar lights, so it is only castable in barren lands. Magic scale +2, MR for enemies in province -2, ritual range +1</td></tr>
</tbody></table>
```

## National Rituals: Machaka (age 2)

```{=html}
<table class="table spell-table">
<thead><tr><th>School</th><th>Ritual Name</th><th>Path</th><th>Cost</th><th>Rng</th><th>Dmg</th><th>Special</th></tr></thead>
<tbody>
<tr><td>Ench 5</td><td>Weavers of the Wood</td><td>N4</td><td>6</td><td>-</td><td>-</td><td>NUW</td></tr>
<tr class="spell-desc"><td colspan="7">The caster makes spiders large and small weave a giant web covering an entire forest province. Anyone trying to sneak through the forest is highly likely to be detected as the caster monitors the webs. The caster of the ritual will be able to direct both the local patrolling forces and spiders from the woods in order to attack any trespassers. The ritual will break if the caster leaves the province. Patrol strength +100 vs enemy units. Able to detect invisible beings as well. Spiders will aid patrolling forces in combat. Duration: 1 month + 3 months per extra gems.</td></tr>
</tbody></table>
```

## National Rituals: Vanarus (age 2)

```{=html}
<table class="table spell-table">
<thead><tr><th>School</th><th>Ritual Name</th><th>Path</th><th>Cost</th><th>Rng</th><th>Dmg</th><th>Special</th></tr></thead>
<tbody>
<tr><td>Conj 5</td><td>Send Lady Midday</td><td>A3D1</td><td>5</td><td>5</td><td>-</td><td>NUW, Anon</td></tr>
<tr class="spell-desc"><td colspan="7">The Lady Midday is a malign spirit of the noon. She appears as a young girl surrounded by whirling dust and armed with a scythe that stinks of disease. Sometimes she will stop people and ask them a question. Failure to answer results in her displeasure and she will use her scythe to disease or chop off the head of the victim. The caster of this ritual will contact the spirit and force it to appear in a suitable province where it will attack and try to slay a commander.</td></tr>
</tbody></table>
```

## National Rituals: Jotunheim (age 2)

```{=html}
<table class="table spell-table">
<thead><tr><th>School</th><th>Ritual Name</th><th>Path</th><th>Cost</th><th>Rng</th><th>Dmg</th><th>Special</th></tr></thead>
<tbody>
<tr><td>Thau 5</td><td>Seith Curse</td><td>D1S1</td><td>3</td><td>5</td><td>-</td><td>MR+, Detect, NUW, Anon</td></tr>
<tr class="spell-desc"><td colspan="7">Seith is an ancient form of sorcery, reputedly invented by Angerboda. It has been practiced by females of the nation through the ages. Gygjor, vaetti hags and human Seithkonur all have some knowledge of the Seith, but it is the Seithkonur of Utgård that have mastered the art. Seith can be used to spell doom upon a distant target. When cast, a single enemy commander in a faraway province is cursed for the rest of his life. However, the price is high, and the Fates will keep the balance. Someone close to the caster will also suffer a curse.</td></tr>
</tbody></table>
```

## National Rituals: Nidavangr (age 2)

```{=html}
<table class="table spell-table">
<thead><tr><th>School</th><th>Ritual Name</th><th>Path</th><th>Cost</th><th>Rng</th><th>Dmg</th><th>Special</th></tr></thead>
<tbody>
<tr><td>Thau 5</td><td>Seith Curse</td><td>D1S1</td><td>3</td><td>5</td><td>-</td><td>MR+, Detect, NUW, Anon</td></tr>
<tr class="spell-desc"><td colspan="7">Seith is an ancient form of sorcery, reputedly invented by Angerboda. It has been practiced by females of the nation through the ages. Gygjor, vaetti hags and human Seithkonur all have some knowledge of the Seith, but it is the Seithkonur of Utgård that have mastered the art. Seith can be used to spell doom upon a distant target. When cast, a single enemy commander in a faraway province is cursed for the rest of his life. However, the price is high, and the Fates will keep the balance. Someone close to the caster will also suffer a curse.</td></tr>
</tbody></table>
```

## National Rituals: Oceania (age 2)

```{=html}
<table class="table spell-table">
<thead><tr><th>School</th><th>Ritual Name</th><th>Path</th><th>Cost</th><th>Rng</th><th>Dmg</th><th>Special</th></tr></thead>
<tbody>
<tr><td>Alt 0</td><td>Grow Fortress</td><td>N4</td><td>35</td><td>-</td><td>-</td><td></td></tr>
<tr class="spell-desc"><td colspan="7">This ritual forces nature to form a complete fortress in a matter of weeks, sturdy enough to rival stone walls. Defenders can stand on the walls and fire missiles from the parapets. This ritual can only be cast in forests or shallow seas, where nature has plenty of material to build from.</td></tr>
</tbody></table>
```

## National Rituals: Arcoscephale (age 3)

```{=html}
<table class="table spell-table">
<thead><tr><th>School</th><th>Ritual Name</th><th>Path</th><th>Cost</th><th>Rng</th><th>Dmg</th><th>Special</th></tr></thead>
<tbody>
<tr><td>Alt 3</td><td>From Death Comes Life</td><td>D1N1</td><td>3</td><td>-</td><td>-</td><td>NUW</td></tr>
<tr class="spell-desc"><td colspan="7">The Panageis uses sacred carcasses from a Megara Chasm to complete the cycle of death and rebirth and procure fertility in the province. The growth scale of the province is increased by two. The ritual lasts longer if more gems are used.</td></tr>
<tr><td>Conj 3</td><td>Curse Tablet</td><td>D1</td><td>3</td><td>2</td><td>-</td><td>MR+, Detect, Anon</td></tr>
<tr class="spell-desc"><td colspan="7">With the emergent interest in the fate of souls in Arcoscephale, necromantic practices have emerged. While most Orphic Mystics try to find the mysteries of a blessed afterlife, some less scrupulous individuals have used the new insights to command the newly dead. With this ritual the necromancer approaches the grave of a newly dead and places a tablet on it. The soul of the dead one is prevented from transmigrating or finding rest until it has performed the curse on the tablet. The spirit will travel to a distant province and curse a commander before finding final rest.</td></tr>
<tr><td>Conj 5</td><td>Monster Boar</td><td>N3</td><td>10</td><td>5</td><td>-</td><td>NUW, Anon</td></tr>
<tr class="spell-desc"><td colspan="7">The caster summons a monster boar and sends it to a distant province to ravage the land. The boar is a descendant of the monster boars sent by the Lady of the Hunt to ravage the farmlands of obnoxious peasants. The boar will cause unrest in the province until it is found and slain.</td></tr>
</tbody></table>
```

## National Rituals: Pangaea (age 3)

```{=html}
<table class="table spell-table">
<thead><tr><th>School</th><th>Ritual Name</th><th>Path</th><th>Cost</th><th>Rng</th><th>Dmg</th><th>Special</th></tr></thead>
<tbody>
<tr><td>Conj 5</td><td>Monster Boar</td><td>N3</td><td>10</td><td>5</td><td>-</td><td>NUW, Anon</td></tr>
<tr class="spell-desc"><td colspan="7">The caster summons a monster boar and sends it to a distant province to ravage the land. The boar is a descendant of the monster boars sent by the Lady of the Hunt to ravage the farmlands of obnoxious peasants. The boar will cause unrest in the province until it is found and slain.</td></tr>
<tr><td>Alt 5</td><td>Fort of the Ancients</td><td>N4</td><td>35</td><td>-</td><td>-</td><td></td></tr>
<tr class="spell-desc"><td colspan="7">In ancient times, Pangaea made its forts not from mud and mortar but bramble and birch. This ritual forces nature to form a complete fortress in a matter of weeks, sturdy enough to rival stone walls. The ritual can only be cast in forests or shallow seas, where an appropriate amount of vegetation can be found.</td></tr>
</tbody></table>
```

## National Rituals: Pythium (age 3)

```{=html}
<table class="table spell-table">
<thead><tr><th>School</th><th>Ritual Name</th><th>Path</th><th>Cost</th><th>Rng</th><th>Dmg</th><th>Special</th></tr></thead>
<tbody>
<tr><td>Ench 3</td><td>Katabasis</td><td>D1W1</td><td>8</td><td>-</td><td>-</td><td>UndIm, InanimIm, NUW</td></tr>
<tr class="spell-desc"><td colspan="7">A mystic of the Sacred River of Death and Rebirth descends into the underworld through the Sacred River and prepares a path for an eventual return from the underworld. If the Renatus or Renata is slain, he or she returns from the underworld to the province where the ritual was cast. They will be soaked in stygian waters and possibly gaining dark insights in the process. For the ritual to work, the province it was cast in must be in friendly hands when the mystic dies.</td></tr>
<tr><td>Ench 3</td><td>Epopteia</td><td>N1</td><td>12</td><td>-</td><td>-</td><td>NUW</td></tr>
<tr class="spell-desc"><td colspan="7">Mystics of the Great Mother gather in the spring and perform the Epopteia, Greater Mystery, in order to bless the land with one year of fertility. The Greater Mystery is a ceremony of a foreign faith and will reduce belief in the True God. Growth +2. Duration: until next spring. Dominion is reduced by 3 when the ritual is cast.</td></tr>
<tr><td>Thau 3</td><td>Taurobolium</td><td>N1F1</td><td>6</td><td>-</td><td>-</td><td>NUW</td></tr>
<tr class="spell-desc"><td colspan="7">The Heliodromus performs a ritual slaying of a sacred bull. The Heliodromus takes his place in a trench underneath a plate of copper pierced with holes. The sacred bull is slain by the participants and its blood pour down upon the Heliodromus. Baptized in blood the Heliodromus is purified and endowed with the power of the Solar Bull. For one year the reborn Heliodromus is worshiped by his fellows as an incarnate God. The Heliodromus receives increased magical understanding and false prophet status. There can only be one elevated Heliodromus. Grants fire magic bonus +2, nature magic bonus +1, heretic +3. Duration: 1 year.</td></tr>
</tbody></table>
```

## National Rituals: Marignon (age 3)

```{=html}
<table class="table spell-table">
<thead><tr><th>School</th><th>Ritual Name</th><th>Path</th><th>Cost</th><th>Rng</th><th>Dmg</th><th>Special</th></tr></thead>
<tbody>
<tr><td>Thau 4</td><td>Mirror Walk</td><td>G1S1</td><td>1</td><td>7</td><td>-</td><td></td></tr>
<tr class="spell-desc"><td colspan="7">With the help of two large flawless and perfectly aligned mirrors, the mirror mage can step into one mirror and then exit through the other regardless of the distance between. The mirror mages make sure that all laboratories are setup with this perfect mirror in order to make it possible for the mages to easily travel between the labs. The mirror walk ritual takes some time to perform, but it consumes very few magic resources.</td></tr>
</tbody></table>
```

## National Rituals: Abysia (age 3)

```{=html}
<table class="table spell-table">
<thead><tr><th>School</th><th>Ritual Name</th><th>Path</th><th>Cost</th><th>Rng</th><th>Dmg</th><th>Special</th></tr></thead>
<tbody>
<tr><td>Alt 6</td><td>Hellscape</td><td>F4</td><td>10</td><td>5</td><td>-</td><td>NUW, Anon</td></tr>
<tr class="spell-desc"><td colspan="7">The caster calls on the fires of Rhuax to curse a distant province with blistering heat. Smoke and wildfires will erupt as the very ground will burn with unnatural heat. The Hellscape will appear as an unnatural event, but those affected will not know who has cast the curse upon them. Heat Scale +3, Death Scale +1, Population -10%, Unrest +20.</td></tr>
<tr><td>Blood 3</td><td>Infernal Breeding</td><td>B2</td><td>25</td><td>-</td><td>-</td><td>NUW</td></tr>
<tr class="spell-desc"><td colspan="7">The Warlocks of Abysia have experimented with crossbreeding since they first discovered blood magic. Under the influence of infernal magic Abysians, humans and giants are crossbred with demons, salamanders and other beasts. In the early days most of the experiments were conducted on Abysians, but the wars with Hinnom made the blood of giants occasionally available. In later times humans and humanbreds have dominated the breeding stock and abysian crossbreds are rarer. Due to the creation process many Hell Spawn suffer from various afflictions and early aging.</td></tr>
</tbody></table>
```

## National Rituals: Ragha (age 3)

```{=html}
<table class="table spell-table">
<thead><tr><th>School</th><th>Ritual Name</th><th>Path</th><th>Cost</th><th>Rng</th><th>Dmg</th><th>Special</th></tr></thead>
<tbody>
<tr><td>Thau 7</td><td>Call of the Drugvant</td><td>D4F1</td><td>15</td><td>4</td><td>-</td><td>NUW, Anon</td></tr>
<tr class="spell-desc"><td colspan="7">The Drugvant are the People of the Lie, those under the influence of evil intentions. With this ritual the caster lets loose the will of the Destructive Spirit upon a remote land. Falsehood, wickedness and violence will spread in the province and in its wake Daevas will come. Unrest is greatly increased and the province is attacked by bandits and a host of Daevas.</td></tr>
</tbody></table>
```

## National Rituals: Caelum (age 3)

```{=html}
<table class="table spell-table">
<thead><tr><th>School</th><th>Ritual Name</th><th>Path</th><th>Cost</th><th>Rng</th><th>Dmg</th><th>Special</th></tr></thead>
<tbody>
<tr><td>Thau 7</td><td>Call of the Drugvant</td><td>D4F1</td><td>15</td><td>4</td><td>-</td><td>NUW, Anon</td></tr>
<tr class="spell-desc"><td colspan="7">The Drugvant are the People of the Lie, those under the influence of evil intentions. With this ritual the caster lets loose the will of the Destructive Spirit upon a remote land. Falsehood, wickedness and violence will spread in the province and in its wake Daevas will come. Unrest is greatly increased and the province is attacked by bandits and a host of Daevas.</td></tr>
</tbody></table>
```

## National Rituals: T'ien Ch'i (age 3)

```{=html}
<table class="table spell-table">
<thead><tr><th>School</th><th>Ritual Name</th><th>Path</th><th>Cost</th><th>Rng</th><th>Dmg</th><th>Special</th></tr></thead>
<tbody>
<tr><td>Alt 5</td><td>Internal Alchemy</td><td>W2S1</td><td>5</td><td>-</td><td>-</td><td>UndIm, InanimIm</td></tr>
<tr class="spell-desc"><td colspan="7">The mystics and hermits of T&#x27;ien Ch&#x27;i have always been obsessed with longevity. Internal Alchemy is a method to transmute the inner self instead of external substances. Meditation, severe asceticism and breathing techniques are used to access the inner cinnabar fields in an attempt to alter them. Often the alchemist feeds on cinnabar, transmuted quicksilver, the most highly regarded alchemical substance, during the process. The transformative nature of the cinnabar might also transmute the mind of the hermit. Age -15 years</td></tr>
</tbody></table>
```

## National Rituals: Bogarus (age 3)

```{=html}
<table class="table spell-table">
<thead><tr><th>School</th><th>Ritual Name</th><th>Path</th><th>Cost</th><th>Rng</th><th>Dmg</th><th>Special</th></tr></thead>
<tbody>
<tr><td>Conj 5</td><td>Send Lady Midday</td><td>A3D1</td><td>5</td><td>5</td><td>-</td><td>NUW, Anon</td></tr>
<tr class="spell-desc"><td colspan="7">The Lady Midday is a malign spirit of the noon. She appears as a young girl surrounded by whirling dust and armed with a scythe that stinks of disease. Sometimes she will stop people and ask them a question. Failure to answer results in her displeasure and she will use her scythe to disease or chop off the head of the victim. The caster of this ritual will contact the spirit and force it to appear in a suitable province where it will attack and try to slay a commander.</td></tr>
</tbody></table>
```

## National Rituals: Utgård (age 3)

```{=html}
<table class="table spell-table">
<thead><tr><th>School</th><th>Ritual Name</th><th>Path</th><th>Cost</th><th>Rng</th><th>Dmg</th><th>Special</th></tr></thead>
<tbody>
<tr><td>Thau 5</td><td>Seith Curse</td><td>D1S1</td><td>3</td><td>5</td><td>-</td><td>MR+, Detect, NUW, Anon</td></tr>
<tr class="spell-desc"><td colspan="7">Seith is an ancient form of sorcery, reputedly invented by Angerboda. It has been practiced by females of the nation through the ages. Gygjor, vaetti hags and human Seithkonur all have some knowledge of the Seith, but it is the Seithkonur of Utgård that have mastered the art. Seith can be used to spell doom upon a distant target. When cast, a single enemy commander in a faraway province is cursed for the rest of his life. However, the price is high, and the Fates will keep the balance. Someone close to the caster will also suffer a curse.</td></tr>
</tbody></table>
```

## National Rituals: Vaettiheim (age 3)

```{=html}
<table class="table spell-table">
<thead><tr><th>School</th><th>Ritual Name</th><th>Path</th><th>Cost</th><th>Rng</th><th>Dmg</th><th>Special</th></tr></thead>
<tbody>
<tr><td>Thau 5</td><td>Seith Curse</td><td>D1S1</td><td>3</td><td>5</td><td>-</td><td>MR+, Detect, NUW, Anon</td></tr>
<tr class="spell-desc"><td colspan="7">Seith is an ancient form of sorcery, reputedly invented by Angerboda. It has been practiced by females of the nation through the ages. Gygjor, vaetti hags and human Seithkonur all have some knowledge of the Seith, but it is the Seithkonur of Utgård that have mastered the art. Seith can be used to spell doom upon a distant target. When cast, a single enemy commander in a faraway province is cursed for the rest of his life. However, the price is high, and the Fates will keep the balance. Someone close to the caster will also suffer a curse.</td></tr>
</tbody></table>
```

## National Rituals: Atlantis (age 3)

```{=html}
<table class="table spell-table">
<thead><tr><th>School</th><th>Ritual Name</th><th>Path</th><th>Cost</th><th>Rng</th><th>Dmg</th><th>Special</th></tr></thead>
<tbody>
<tr><td>Ench 5</td><td>Send Tupilak</td><td>D3W1</td><td>5</td><td>5</td><td>-</td><td>NUW, Anon</td></tr>
<tr class="spell-desc"><td colspan="7">The Tupilak is an artificial animal made from various animal cadavers. It is able to take the appearance and attributes of any of its composite parts. Most Tupilaks are made from bears, ravens, seals and reindeer. This gives the Tupilak battle prowess and the ability of flight. After it has been created, it is given the task of hunting down and killing a specific enemy commander. Then the Tupilak will fly, run and swim across the world in order to find its prey and kill it.</td></tr>
</tbody></table>
```

## National Rituals: R'lyeh (age 3)

```{=html}
<table class="table spell-table">
<thead><tr><th>School</th><th>Ritual Name</th><th>Path</th><th>Cost</th><th>Rng</th><th>Dmg</th><th>Special</th></tr></thead>
<tbody>
<tr><td>Thau 6</td><td>Dreams of R&#x27;lyeh</td><td>S3G1</td><td>4</td><td>10</td><td>-</td><td>MR, Detect</td></tr>
<tr class="spell-desc"><td colspan="7">This spell can target the dreams of an enemy commander anywhere in the world. It will pull his dream through the Void Gate in R&#x27;lyeh and into the other world. Here the caster will manifest himself in the dream and kill the bewildered target. The spell does not work on mindless beings or those who never sleep.</td></tr>
</tbody></table>
```

